### ISSUE TITLE
method anyOne does not work correctly for ranges

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1003]
When running anyOne method on a range specified as the following:
(1..4).anyOne()
The last number included on the range is never chosen as a result. The distribution of the total amount of choices is given within the n-1 numbers of the range.

test "test_anyOne" {
    var cantidad = 0
	10000.times({if ((1..5).anyOne()==5)cantidad = cantidad +1})
	assert.notEquals(0,cantidad)
}

**Comment by matifreyre** [comment]
This isn't an error. The method anyOne doesn't mean to return a random
object in the collection, it only means that it has to be any object as
long as it is in the collection. It may as well return the first one always
and it would be correct.

**Comment by lspigariol** [comment]
lang.wlk:
```
/**
 * Answers a random integer contained in the range
 */		
method anyOne() native
```

anyOne() work randomly on other range elements

**Comment by javierfernandes** [comment]
I think that the range itself doesn't include the upper bound, right ?
Try something like

(0 -> 10).forEach { n => console.println(n) }

I think it will print 0,1, ... 9

(Just trying to remember how it was implemented :P)

**Comment by PalumboN** [comment]
> I think that the range itself doesn't include the upper bound, right ?

Nop, includes it

``` XTend
>>> (1..10).contains(10)
true
```

The implementation was wrong, I comment what in the PR https://github.com/uqbar-project/wollok/pull/1004

**Comment by matifreyre** [comment]
I find it plain wrong that the selected number is a random one. Why use
anyOne() for that when collections use it, as I said, to simply return an
object contained by it with no random logic? I would expect the same
behaviour for both ranges and collections. If we want something random, it
should be a different message.

**Comment by npasserini** [comment]
Traditionally anyOne does not return random objects. In fact, anyOne means
you do not care which object it returns... but when you want "random" you
have specific requirements, about every object being elegible and all of
them evenly elegible... so you DO care, it is not just anyOne.

But, at the end I do not care if we want "anyOne" to return random objects
or to keep traditional Smalltalk anyOne and create another "random"
message.

What is really important is that:
1) Every implementor of these messages should behave the same (whether all
random or none of them).
2) It should be clearly stated in the method comment.

**Comment by PalumboN** [comment]
Ok, but now List has a random implementation too:

```XTend
	/**
	 * Answers any element of this collection 
	 */
	override method anyOne() {
		if (self.isEmpty()) 
			throw new Exception("Illegal operation 'anyOne' on empty collection")
		else 
			return self.get(0.randomUpTo(self.size()))
	}
```

(And Set has a native implementation and returns `wrapped.head`).

Anyway, I don't understand why return an element with no-random-logic, but if you like we can have:

```XTend
class Collection {
	method anyOne() => self.toList().head()
	method random() => native
}
```

**Comment by matifreyre** [comment]
> Anyway, I don't understand why return an element with no-random-logic

I think Nico's answering that when he writes this:
> anyOne means you do not care which object it returns... but when you want "random" you
have specific requirements, about every object being elegible and all of them evenly elegible... so you DO care, it is not just anyOne

**Comment by PalumboN** [comment]
Yeah, I understood that. I didn't understand why don't use a random method (when exist) if I want an element and I don't care which.. Or why `anyOne()` should delegate in `head()` and not `random()`.

**Comment by matifreyre** [comment]
It's a term of not doing whatever is unnecessary. We could also calculate
how to send a rocket to the moon and then discard everything, but it would
be useless. Any random determination of an object is useless for the simple
purpose of answering "any object from the collection" (or range). I'd
rather have the simplest method possible, and then have a different one for
when I really need a random object.

**Comment by npasserini** [comment]
I do not really care if you prefer anyOne to return a random element.

I just stated that
- There are other contexts in which anyOne has already the behavior it has
in wollok, and people are used to it... so if you change it there might be
people that do not like it...
- We should be consistent... for example, having the set returning
"self.toList().head()" is not 'random', because if you call it several
times it will return always the same element (at least while you do not
change the set).

**Comment by lspigariol** [comment]
is an expresivity problem, where conflicts "common sense" vs conventions.

random is an evident term to refer "aleatorio"
first and head have direct sense, too
anyOne is more ambiguos, depend of contexts or points of view.
posibles meanings are debatables 
i think anyOne refer to "el que esta mas a mano", 
but accept anyother. only expect consistence.

but only expect c
i think anyOne  only return the element "más a mano" 

but, dont disagree with ramdom implementation in case

**Comment by lspigariol** [comment]
is an expresivity problem, where conflicts "common sense" vs conventions.

random is an evident term to refer "aleatorio"
first and head have direct sense, too
anyOne is more ambiguos, depend of contexts or points of view.
posibles meanings are debatables 
i think anyOne refer to "el que esta mas a mano", 
but accept anyother. only expect consistence.

**Comment by matifreyre** [comment]
Switching the discussion to its own issue (#1014), as the fix requested here is already implemented.
