### ISSUE TITLE
When I open a new wollok workspace it should start in the wollok perspective.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1005]
Is that possible? Did anyone try to do so?

**Comment by fdodino** [comment]
When does it happen to you?
I have launched a product built and it starts in Wollok perspective.

**Comment by npasserini** [comment]
Maybe I just tried from the development environment and that is what does not work?

**Comment by fdodino** [comment]
Indeed.
When you open Wollok from IDE also Splash is not shown, that is because wollok.product_product configuration doesn't run at all.
If you run a mvn clean install, and then in update site project, open your Wollok distribution product, that is the exact behavior of Wollok IDE for humans.

**Comment by npasserini** [comment]
Ok, let's close this then.
