### ISSUE TITLE
Problems with target platform.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1006]
I installed the latest Eclipse Neon and I get problems with target platform.
After trying the instructions in [Wollok developers page](https://github.com/uqbar-project/wollok/wiki/Development---Environment-Setup), error did not disappear. 

There is a conflict because it tries to load two different versions of plugin "org.eclipse.pde.feature.group" (3.12.0 and 3.12.1). 

I couldn't find exact explanation for the origin of those requirements, but I infer that one comes from my eclipse version, selected location in target platform is 
`<repository location="http://download.eclipse.org/eclipse/updates/4.6/"/>`

Which matches my eclipse Neon instalation:
Eclipse DSL Tools
Version: Neon Release (4.6.0)
Build id: 20160613-1800

But I find also another one which might be the origin of the problem: `<repository location="http://download.eclipse.org/releases/neon/"/>`

**Comment by javierfernandes** [comment]
Merged
