### ISSUE TITLE
Add random method to collections and ranges and change anyOne logic

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1014]
I think `anyOne()`'s current implementation (and doc) is wrong. I'd like to have anyOne meaning "any object in the collection" and with the simplest implementation possible, with no random logic.

I think that random logic is an additional requirement, as discussed in #1003, and so the message should be a different one. You are no longer saying "any object" here. @npasserini 's comment in that other issue is quite accurate in my opinion:

> anyOne means you do not care which object it returns... but when you want "random" you have specific requirements, about every object being elegible and all of them evenly elegible... so you DO care, it is not just anyOne

Some options for this new message could be:
- `random()`, but I'm not a fan of this one
- `randomOne()`, following `anyOne()`'s convention
- `randomElement()`, a little longer, but more expressive as well from my point of view

**Comment by fdodino** [comment]
@matifreyre I didn't follow you, do you want to add a new method randomElement() but also change current behavior of anyOne?

**Comment by npasserini** [comment]
There has been a long discussion about random a few months ago, I think we should recall that discussion. The most important is to pay attention that we keep the same message for all objects providing a random/randomElement.

I think random is good enough, randomElement is ok (yet longer). I do not like randomOne.

**Comment by matifreyre** [comment]
Exactly... I think our own code should serve as an example. If somebody
reads "anyOne" and looks at the code, he/she shouldn't find a random logic
in the code, because that is not "any one", it means "random one", which is
very different. In my opinion, the code for anyOne should be the simplest
possible. Random logic has unnecesary complexity, the user should
explicitly request for random logic by sending a different message.

**Comment by Juancete** [comment]
In Set, we have a native method that response with the first element. 
```xtend
	def anyOne() { 
		if(wrapped.isEmpty) 
			throw new WollokRuntimeException(NLS.bind(Messages.WollokInterpreter_illegalOperationEmptyCollection, "anyOne"))
		else
			wrapped.head
	}
```
@matifreyre do you think this must be the expected behavor for anyOne in List?

**Comment by matifreyre** [comment]
Yes, that seems to be OK for List too in my opinion.

**Comment by lspigariol** [comment]
a mi no me molesta que el anyOne sea aleatorio.
hay varios ejemplos hechos que ya lo usan, no se si es oportuno hacer un
cambio ahora.

**Comment by nicovio** [comment]
List has the methods first and head that response with the first element. Should we add another method that does the same?

**Comment by fdodino** [comment]
Yo no se, con el diario del lunes digo que no lo hemos necesitado en la materia y que si la colección tiene un anyOne() a vos no te debería importar cuál querés que te traiga, mientras sea un elemento de la colección. Yo voto por cerrar el issue.

**Comment by npasserini** [comment]
+1 a Fer

**Comment by matifreyre** [comment]
Mi opinión sigue igual que antes, me hace ruido que "anyOne" implique "random" y que para obtener un "random" tenga que usar "anyOne" (y más si ya está implementado el cambio), pero si soy el único tampoco es cuestión de ir contra todo el mundo por esto.

**Comment by matifreyre** [comment]
> List has the methods first and head that response with the first element. Should we add another method that does the same?

Yo lo haría para mantener un mismo tipo con Set (potencial polimorfismo). Creo que querés entender el mensaje adicional, por más que la implementación sea la misma (o que uno sólo delegue en el otro). Un Set no tiene por qué entender head o first, pero sí puede responder un anyOne.
Claro que esto aplica sólo si queda también random, que parece que va en camino de no pasar.

**Comment by fdodino** [comment]
Bueno, no hubo demasiada fuerza para modificar el comportamiento actual y queremos ponerle foco a muchas cosas el año que viene, en todo caso si tenés ganas @matifreyre podés reflotar el issue en el repo wollok-language. Por el momento quiero bajar la cantidad de issues dando vueltas y ver si podemos concentrarnos en ítems prioritarios, por eso cierro el ticket.
