### ISSUE TITLE
Doesn't check a repeated class name if you don't define a package

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok#1027]
If you do somethig like 

**>>>aFile.wlk**

```
class Bleh {
...
}
class Bleh {
...
}
```

Doesn't check a repeated class name. But if you do 

**>>>aFile.wlk** 

```
package aPackage {
   class Bleh {
   ...
   }
   class Bleh {
   ...
   }
}
```

Shows an error.

**Comment by Juancete** [comment]
Heee.... problems! 

I can run Xpect test in eclipse a file at once. I want to make a test and i found in DuplicatedChecksTestCase.wlk.xt.failing the right place. But is a .failing extencion. I guess it is to skip this test. I'm trying to do my test in a new file but doesn't like to Xpect. is it something about warnings?
@javierfernandes ?

**Comment by Juancete** [comment]
and I could run xpect test. :D

**Comment by javierfernandes** [comment]
Sorry I didn't get the issue.

Yes, I believe that the "failing" extension was to ignore them.

What is your issue ?

Beware that I think that those "failing" tests where bound to a different
java class (check on top of the test there's a SETUP "macro", where you
bind the file to the junit test).
You should use one that's not the same as those for failing but for the
ones that actually work :)

**Comment by Juancete** [comment]
It's a syntax error. In the .failing files the expectations are declared like 

`// XPECT errors -=>`

but is

`// XPECT errors -->`

And have the same setup i think 

`/* XPECT_SETUP org.uqbar.project.wollok.tests.xpect.WollokXPectTest END_SETUP */`

is that right?

**Comment by javierfernandes** [comment]
I'm not sure what they are for.

I've seen something similar before to assert for 1 or many expected errors,
like a list. But not that one "-=>"

**Comment by Juancete** [comment]
check [this file](https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DuplicatedChecksTestCase.wlk.xt.failing). 

For one or more expectations use this syntax:
`/* XPECT issues --- `

In this file i found the old wollok syntax like _new_ for a constructor. This is not updated. Is there a complete documentation for Xpect? i can't found anyone on the site.
