### ISSUE TITLE
Division of an integer by a float that returns a number too close to 0 raises an exception

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/wollok#1028]
For example:
>>> `0 / 100.0`
`wollok.lang.Exception: For input string: "0E+1"
    at wollok.lang.Integer./(other) [/lang.wlk:1027]`

>>> `1 / 100000000000.0`
`wollok.lang.Exception: For input string: "1E-11"
    at wollok.lang.Integer./(other) [/lang.wlk:1027]`

It seems to have something to do with numbers in scientific notation.

**Comment by fdodino** [comment]
See PR #1025
