### ISSUE TITLE
Expression "1 + if(1 == 2) 4" should fail

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1034]
We are adding `1 + somethingNotDefined` and that returns a valid result. Why? I find it a bit disturbing.

**Comment by matifreyre** [comment]
On the other hand:

```
>>> 1 * if(1 == 2) 2
null
```

**Comment by npasserini** [comment]
I think that
1) Only an if with else should be used as expression, we could validate it.
2) Once having done that, if the operand to +* is not a number it should be
an error... and allways the same.

2016-10-29 15:25 GMT+02:00 Matías Freyre <notifications@github.com>:

**Comment by fdodino** [comment]
Hi @matifreyre ,  I didn't understand the expression

```
1 + somethingNotDefined
```

But I made an extra validation here:

```
	method ifInsideExpressionWithoutElseShouldFailForBinaryRightOperation() {
		// XPECT errors --> "If used in an expression should have both if and else statement" at "1 == 2"
		return 1 * if(1 == 2) 2
	}
	
	method ifInsideExpressionWithoutElseShouldFailForReturn() {
		// XPECT errors --> "If used in an expression should have both if and else statement" at "1 == 2"
		return if(1 == 2) 2
	}
	
	method ifInsideExpressionWithoutElseShouldFailForBinaryLeftOperation() {
		// XPECT errors --> "If used in an expression should have both if and else statement" at "1 == 2"
		return (if(1 == 2) 2) + 3
	}
	
	method ifInsideExpressionWithoutElseShouldFailInAssignment() {
		// XPECT errors --> "If used in an expression should have both if and else statement" at "1 == 2"
		var failed = if(1 == 2) 2
		var ok = if (1 == 2) 2 else 3
		failed = ok
		return ok == 3
	}
```

I don't know which other cases do you have in mind...

**Comment by matifreyre** [comment]
Hi @fdodino !
My statement comes as an explanation for the title. The `if` fails and so it should be resolved to the `else` branch, but there is none... so, the result is something undefined.
Apart from those cases, I can only think of passing the expression as an argument to some method right now, but if any other cases comes to my mind then I'll add it here.
Chatting with @npasserini in the last meeting, he explained to me that this could be caught by the type system, as any `if` without `else` should type to void and therefore it would not be possible to use it as an expression. If I understand this correctly, this would catch all possible cases at once.

**Comment by fdodino** [comment]
Ok, I think it is still a good idea to add this validation, for the cases where you don't use a type system (possibly in initial stage).

Added this new test

`` xtend
	method addOneTo(value) {
		return 1 + value
	}

	method invokeAddOneTo() {
		// XPECT errors --> "If used in an expression should have both if and else statement" at "1 == 2"
		return self.addOneTo(if (1 == 2) 4)
	}
```

**Comment by npasserini** [comment]
I like this validation.

Thinking in the future, I am not sure which is the best strategy, whether having specific validations or let the type system do the job. 
On one hand, it is true what Mati says, if the type system determines that something is "void" (i.e. is a "statement" and not an "expression") it will forbid to use it in any place where an expression is expected. So it should cover all possible cases.
Also, I see a potential problem: it could be difficult to _prevent_ the type system from doing this kind of validations, i.e. if you add an additional validation, you will probably end up having two.

On the other hand, you just added a validation with a very nice, explicative and precise message... it might be difficult to have the type system doing so.

So, I am not sure... I think these are the kind of stuff we will be learning this year, once the type system starts being used for real.

What I do not understand is why you would not have the type system in the early stage... it is specifically designed for being used right in the very first program.

**Comment by fdodino** [comment]
Nevermind about activating type system, I thought it should appear after some practice like classes.

**Comment by matifreyre** [comment]
Regarding the message for the type system error, it could say something like "if statements without else cannot be considered valid expressions as they cannot always yield a value".

**Comment by fdodino** [comment]
Ok, upvote new message proposed by Mati since I have to touch in 3/4 places. Before I change it I want to be sure...

**Comment by npasserini** [comment]
I like it. Maybe add a hyphen in "if-statement" because otherwise it might
be read as "Si los statements sin else pueden ser considerados expresiones
válidas..."

2017-07-04 10:51 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Ok. Let's do it.
