### ISSUE TITLE
Better dialog balloon

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1038]
![ganjero_says](https://cloud.githubusercontent.com/assets/4098184/20034085/f07a5a1e-a390-11e6-87cc-5e022790607b.jpg)
- [x] Do it bigger, depending the text's large. At now exists one logic for that, but still is small.
- [x] Remove "ERROR: " string when Wollok Exceptions are caught  by the character. With the red color is enough.

![granjero_says_cut](https://cloud.githubusercontent.com/assets/4098184/20034109/6c8a3d7c-a391-11e6-81f5-2b9d89853d6d.jpg)
- [x] Should be nice detect when the visual is too close to the border of screen and draw the balloon in other direction

**Comment by PalumboN** [comment]
First problem solved:

![error_message](https://user-images.githubusercontent.com/4098184/34093233-e8bf28e4-e3a5-11e7-9295-a0dc1ce2df4d.gif)

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok/issues/1190

**Comment by fdodino** [comment]
Fixed "Should be nice detect when the visual is too close to the border of screen and draw the balloon in other direction"

![anim](https://user-images.githubusercontent.com/4549002/43814087-f502e4dc-9a9e-11e8-8177-3ee452659b79.gif)

I also detected a substring bug not showing character 46 :smile:

**Comment by npasserini** [comment]
👏

Il giorno mer 8 ago 2018 alle ore 00:07 Fernando Dodino <
notifications@github.com> ha scritto:
