### ISSUE TITLE
Problema al debuggear

### ISSUE THREAD

**Issue by agnmeinardo** [uqbar-project/wollok#1050]
Cuando intento de debuggear, me aparece el siguiente error: 
" "Iniciando testQuidditch.wtest" ha encontrado un problema. Could not connect to remote process. Could NOT connect to Wollok VM ! "
¿Qué puede ser?

**Comment by npasserini** [comment]
¿Pasa con todos los tests o sólo con ese?

2017-01-21 15:20 GMT+01:00 agnmeinardo <notifications@github.com>:

**Comment by agnmeinardo** [comment]
Sólo con este me pasa.

**Comment by npasserini** [comment]
En ese caso probablemente hay dos issues mezclados
1) Ese test tiene algún problema que no le permite arrancar
2) Wollok no informa bien el error.

¿Dónde puedo ver ese test para correrlo yo mismo?

2017-01-21 23:13 GMT+01:00 agnmeinardo <notifications@github.com>:

**Comment by agnmeinardo** [comment]
Cómo te lo puedo mandar? o por dónde?

**Comment by npasserini** [comment]
Si es un proyecto grande, lo más fácil es un repo git.

Otra opción es buscar un ejemplo lo más chiquito posible que permita
reproducir el problema, pero muchas veces en Wollok eso requiere dos
archivos, así que no es muy práctico.

2017-01-23 21:13 GMT+01:00 agnmeinardo <notifications@github.com>:

**Comment by agnmeinardo** [comment]
https://github.com/agnmeinardo/Quidditch

**Comment by agnmeinardo** [comment]
Perdón la demora

**Comment by npasserini** [comment]
¿Algún tip para poder importar el proyecto en wollok?

Me trae problemas que el código no esté en el root del repo y en cambio en
un subdirectorio... bah, debería andar y de hecho ya lo reporté (
https://github.com/uqbar-project/wollok/issues/1051) pero igual me parece
innecesario.

(Sólo un comentario al margen, puedo seguir igual.)

2017-01-27 12:25 GMT-03:00 agnmeinardo <notifications@github.com>:

**Comment by npasserini** [comment]
Bueno, ahí pude correr el test, pero no encuentro el problema, ¿tendrá que
ver con la estructura de directorios extraña?
El resultado de mi corrida es este:

[image: Images intégrées 1]

Otra opción es que sea un problema de versiones, yo estoy corriendo en
desarrollo contra dev.

Entonces, dos caminos se me ocurren:
1) Verificá tu estructura de directorios, si tenés bien importado el
proyecto o bien decime cómo importarlo yo para poder reproducir exactamente
tu situación.
2) Decime qué versión de Wollok estás usando así lo podemos testear ahí.

2017-01-30 19:54 GMT-03:00 Nicolas Passerini <npasserini@gmail.com>:

**Comment by agnmeinardo** [comment]
La versión es la 1.5.3

**Comment by npasserini** [comment]
Perdón, acabo de ver el título que dice "problema al debuggear". ¿Es que el
error se da sólo al 'debuggear' el test?

Igual me gustaría saber cómo está importado el proyecto en tu eclipse, para
terminar de entender tu configuración.

2017-01-31 11:04 GMT-03:00 agnmeinardo <notifications@github.com>:

**Comment by agnmeinardo** [comment]
Mirá, intenté de dos maneras. Primera: metí el proyecto en la carpeta de workspace, y luego importé el proyecto. Segunda: Lo tenía en el escritorio, y lo importé desde ahí. Ambas vías, me tira el mismo error. (Perdón la demora)
