### ISSUE TITLE
Can not select custom directory on creating Wollok project.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1051]
I am trying to create a new project from the code that is in a git repository (but no .project/.setting files). Also, the project is not in the root of the repository, but under a directory named 'Quidditch':
![image](https://cloud.githubusercontent.com/assets/4633913/22445173/8411f87e-e746-11e6-8fff-06a3f7759284.png)

I tried to create the project like this:
![image](https://cloud.githubusercontent.com/assets/4633913/22445212/ab8db85c-e746-11e6-9f2f-88a32ca36f6e.png)

The project is not created in the selected directory, but in the root of my workspace: 
![image](https://cloud.githubusercontent.com/assets/4633913/22445273/f7fd65c0-e746-11e6-9e72-f8452b0e87f2.png)

**Comment by tesonep** [comment]
Fixed in PR #1077

**Comment by npasserini** [comment]
:))))

2017-04-27 13:04 GMT-03:00 Pablo Tesone <notifications@github.com>:
