### ISSUE TITLE
Exponentiation should have higher precedence than multiplicative operations.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1052]
If you evaluate 

```program p {
	console.println(4 * 3 ** 2)
}
```

you will get 144 (=12^2) instead of 36(=4*9) as it should.

**Comment by juanbono** [comment]
Hi! Should I add a test to ensure that it works?

**Comment by lgassman** [comment]
I have this test red. I made pull from dev after hackaton and now too (june 9 2017)

	@Test
	def void exponentiationPrecedence() {
		'''
		assert.equals(24, 3 * 2 ** 3)
		assert.equals(36, 4.0 * 3 ** 2)
		assert.equals(5, 1 + 2 ** 2)
		'''.test
	}
org.uqbar.project.wollok.tests.interpreter.WollokComparisonFailure: Expected [24] but found [216]
	at wollok.lib.assert.equals(expected,actual).(classpath:/wollok/lib.wlk:88)
	at .(__synthetic0.wpgm:2)

**Comment by lgassman** [comment]
The problem was solved regenerating xtext artifacts from wollok.xtext file
