### ISSUE TITLE
Missing parenthesis on method definition causes undescriptive error

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1069]
![image](https://cloud.githubusercontent.com/assets/4633913/25305443/66db9364-2751-11e7-8e3f-00e5dfb7a624.png)

**Comment by fdodino** [comment]
What does method say?
method energia ... = 3?

**Comment by fdodino** [comment]
I could reproduce it:

```
method energia = 3
```

But, it is not easy to correct. WollokDslValidator is checking that all abstract methods are implemented, but WMethodDeclaration has no expression, nor an expression returned, and its not native

```
WMethodDeclaration:
	(overrides?='override')? 'method'
		name=WMethodName '(' (parameters+=WParameter (',' parameters+=WParameter)* )?')' 
		(native?='native')? 
		
		((expression=WBlockExpression) | (expressionReturns?='=' expression=WOrExpression))?
```

So energia is for Wollok an abstract method (expression is null and is not native):

```
	def static boolean isAbstract(WMethodDeclaration it) {
		expression == null && !native
	}
```

**Comment by fdodino** [comment]
In other words, writing

```
method energia = 3
```

is like writing

```
method energia
```

**Comment by tesonep** [comment]
The problem is previous, the parser cannot parse that "3" as a valid expression in that context. I cannot remember, but it is waiting for the return?

**Comment by tesonep** [comment]
The problem is that is missing the (), the correct way is 

`method energia() = 3`

**Comment by tesonep** [comment]
Not an issue, it is working
