### ISSUE TITLE
Error al copiar mensajes en el REPL

### ISSUE THREAD

**Issue by sergioloyola** [uqbar-project/wollok#1084]
Cuando abro el REPL de example.wlk y escribo el nombre del objeto ex. y luego copio y pego en el REPL el mensaje SayHI(), me da el siguiente error:
**ERROR: mismatched input '}' expecting RULE_ID (linea: 2)
ERROR: mismatched input '<EOF>' expecting '}' (linea: 2)
ERROR: El mensaje no existe o número incorrecto de argumentos para objeto (linea: 1)**

**Comment by fdodino** [comment]
@sergioloyola ¿podrías subir una imagen de cómo queda el REPL? Muchas gracias por subir el issue.
Fernando
