### ISSUE TITLE
 Wrong error message when  a test is defined into wlk file

### ISSUE THREAD

**Issue by lgassman** [uqbar-project/wollok#1089]
The error messaged displayed when it defines a test into a wlk file is:
"Clases y objetos se deben definir en archivos con extensión wtest" but must to say "Los tests se deben definir en archivos con extensión wtest" or similar

to reproduce error you must create a example.wlk with a test:
test "X" {
}

**Comment by juanbono** [comment]
Hi! Maybe this issue could be closed?
