### ISSUE TITLE
F3 on a constructor call should go to the constructor and not the class

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#109]
Currently navigating a constructor call only takes yo to the class, because the link is a crossref to a class.
The actual linking to a particular constructor is being done dynamically by the interpreter (although there are static checks doing the same linking process).

Anyway, to solve this we must customize 

```
org.uqbar.project.wollok.ui.editor.hyperlinking.WollokEObjectAtOffsetHelper
```

You can see for example how we are hyperlinking to methods that we can solve (methods to this), o super() calls.

We must do the same resolve the constructor, then create a link to that.
This must be done in case the linking object is a WClass ref used inside a constructor call.

**Comment by fdodino** [comment]
Hi @javierfernandes , this issue and #112 seem to have the same cause, does it?

**Comment by fdodino** [comment]
![anim](https://user-images.githubusercontent.com/4549002/30560742-35096c2c-9c8f-11e7-8b5a-ce5cc28517d5.gif)
