### ISSUE TITLE
Classes having same name can be created in the same, simple source file

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1099]
I suppose that having a source file having two classes with the same name should not be permitted. The attached source files generated no errors in ... version 1.5 (according to splash screen) or 1.4.3 (according to "ayuda -> acerca ...". Notice the presence of two classes named "PlagaPulgas".

I remark that no namespaces are explicitly defined in the source files (i.e. it is not the case that the classes belong to different packages, since there are no packages defined in the source file).

[plagas_plagas.wlk.txt](https://github.com/uqbar-project/wollok/files/1052025/plagas_plagas.wlk.txt)

**Comment by matifreyre** [comment]
Hi @clombardi !
This is not happening in Freire (I tested with your code). 
I'm closing it. Please re-open if you detect it again.
