### ISSUE TITLE
Discuss the possibility of mandatory explicit return instruction

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#11]
I think it is more clear for a beginner.

**Comment by npasserini** [comment]
Also, it would prevent the REPL to print non-interesting return values from "order methods" (i.e. where intention is to produce an effect rather than returning a alue).

I mean, if the method has no "return" then it has no return value, it will help both the repl and the type checker to be more helpful

**Comment by javierfernandes** [comment]
Two questions about "mandatory"

mandatory states for "to return you must write the return keyword" or "all methods must have a return value" ?

I don't remember if our "type system" has a notion of "void"

**Comment by npasserini** [comment]
> mandatory states for "to return you must write the return keyword" or "all
> methods must have a return value" ?
>
The first one: "to return you must write the return keyword"

The objective is to be able to differenciate:
a) "procedures" or "orders", which are interesting because of its (side)
effects and not by their return value (or do not have one).
b) "functions" or "questions", which are interesting because of its return
value and should (or must) not have side effect.


Another possibility is to introduce a new keyword, instead of using
"method" for both cases. That was my first idea.

But now I think that using the return keyword would do the trick and has
other advantages:
1) Explicit returns are more clear for beginners.
As much as I like implicit return values for my own programmres, I have to
admit that it confuses some people.

2) Explicit returns allow for more flow-control possibilities.
You can see that almost every language with implicit return values has also
the possibility of an explicit return instruction that allows to finish
current method.


The question is: Had we mandatory explicit returns for methods, should
blocks also have mandatory returns?
I do not know.

> I don't remember if our "type system" has a notion of "void"
>

Maybe not... we could add it.
Anyway I was thinking not to use the type system this semester.
