### ISSUE TITLE
Support message sending to closures

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1105]
Currently a message send coerces the type info to be a simple type.

```xtend
	/** 
	 * Register that a message has been sent to this type variable.
	 */
	def messageSend(String selector, List<TypeVariable> arguments, TypeVariable returnType) {
		// TODO Currently only simple types are supporting message sending, but closures also should.
		if (typeInfo == null) setTypeInfo(new SimpleTypeInfo()) 
		typeInfo.messages.add(new MessageSend(selector, arguments, returnType))
	}
```

**Comment by PalumboN** [comment]
Bueno, ahí tiré un PR sobre esto.

Creo que el problema principal está en el método que puso Nico en el issue, que [ahora quedaría así](https://github.com/uqbar-project/wollok/pull/1330/files#diff-315e04bf912d843f67a39112ec70c359).

Lo primero que hice fue "cachear" los mensajes cuando `typeInfo == null` y después los agregaba cuando se setteaba alguna. Eso funcionó para el caso que estaba viendo pero no para muchos otros, ya que hay casos donde se espera inferir el tipo de una variable a partir de los mensajes que recibe.

Así que me di cuenta que el `typeInfo` lo iba a tener que settear y tenía que diferenciar entre Closure o Simple (o agregar una tercera opción). Como lo único que tenía era el MessageSend tal vez una opción sea recorrer las clases y ver si se trata de un método de Closure o no, y eso me llevó a que solamente tenía que saber si se trataba de un método _apply_. Eso ahora está **hardcodeado** [acá](https://github.com/uqbar-project/wollok/pull/1330/files#diff-fe03fdad6f4dd6d15df0f5f5d170a9c3).

Esto implica que cualquier objeto que entienda `apply` sera tratado como Closure a nivel TS, que es mi duda principal por la que estoy escribiendo esto. Por ahora es el único método que define, así que serían 100% polimórficos. **¿Qué piensan ustedes?**

Después se podría *des*hardcodear el "apply" para que busque por los verdaderos métodos de Closure. No estoy seguro de cómo :P pero no debería ser complicado.

**Comment by PalumboN** [comment]
Closure ya es subtipo de Generic: https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ClosureType.xtend
Cierro este issue.
