### ISSUE TITLE
Add tests generating type errors for incompatibility between simple and closure types

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1106]
Look for two unimplemented methods in ClosureTypeInfo

```
	override addMinimalType(WollokType type) {
		throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}

	override setMaximalConcreteTypes(MaximalConcreteTypes maxTypes) {
		throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}
```

they should produce type system errors instead of whatever exception.

**Comment by fdodino** [comment]
@npasserini @PalumboN what about this?

**Comment by PalumboN** [comment]
Yo diría de ponerlo en Ready y aunque sea testear casos simples para sacar esos errores feos. Después se puede seguir iterando más en profundidad (o no).

**Comment by PalumboN** [comment]
Esto rompe todo el build del proyecto con StackOverflow: https://github.com/adrianyaniri/vendedores_2019s2/commit/b29e4bbbbd62dc9f999943bd9f59ce65260bb87b#diff-a5c1d8c5df21370fb40dc3b15dc5b5cfR12
