### ISSUE TITLE
[quickfix] create method on object from another file creates it in the import statement breaking the code

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#1110]
Checkout the capture.

Instead of creating it in the object declaration in another file it creates it in the import statement.
![wollok-createmethodbreakimport](https://user-images.githubusercontent.com/4428120/27509825-6a9d3ca8-58db-11e7-96b1-ed02af70b27d.gif)

**Comment by fdodino** [comment]
Hi , Javi!
Are you trying in dev branch or just generated product?
I made a test using development mode

![anim](https://user-images.githubusercontent.com/4549002/28115352-f4965c7a-66da-11e7-9309-0cc37bc9326e.gif)

I know indentation has to be enhanced, but it seems to work.

**Comment by javierfernandes** [comment]
Yeap, my mistake. I think that I was using an old wollok distribution.
Sorry

**Comment by fdodino** [comment]
Nevermind, it forced me to fix indentation.
:smile:

So, I'm doing this right now.
