### ISSUE TITLE
Handle the object `void` in the TypeSystem

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1114]
Each WKO defines its own type, with the same name, e.g. `console` has type `console`. But `void` object should not exist at language level and is only a implementation hack, as a place holder for the return value of methods that do not have a real return value (i.e. void medhods).

Therefore, void type has a specific representation `VoidType`. Maybe we should have special rules for unifying both ideas. 

But also I wonder if we could get rid of `void` object in wollok.lang, as it is not part of the language and should not referenced in code.

**Comment by npasserini** [comment]
I think this might be already solved. Any volunteer to validate it?

**Comment by npasserini** [comment]
@lspigariol ¿No tendrías ganas de agregar más tests sobre void?

**Comment by lspigariol** [comment]
​(recién ahora me siento con wollok y ya veo que lo cerraste!)​

2017-09-18 10:43 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by npasserini** [comment]
No hay problema, igual está bueno hacer tests de esto. Lo abrimos de nuevo!
