### ISSUE TITLE
Wrong description and action for quickfix for add constructor to WKO inherited from a class

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok#1117]
If you have a code like this 

```xtend
class Persona {
   var attribute

    constructor (_value) {
        attribute  =_value
    }
   method doSomething() {
       attribute += 1
   }
}

object pepe inherits Persona {
}
```
The text shown in the error is incorrect. It says _"No default constructor in super type Persona. You must explicitly call a constructor:..."_. The error should read _"WKO needs a constructor of the superclass Person"_. 

Also, the quick fix does not work because it is old. This worked with a **WClass** and inserted the constructor in the body of the subclass. The new quick fix has to add the constructor differently.

**Comment by fdodino** [comment]
@Juancete , since Validator-issues PR was merged, we are able to close this issue, aren't we?

**Comment by Juancete** [comment]
Yeap!
