### ISSUE TITLE
Wollok seems to lack a function to truncate numbers

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1118]
the expression
  17 / 5  
evaluates to 3.4 (at least in the REPL)
It would be nice to have a way to obtain the integer part.  I tried with trunc(), floor(), round(), round(0), nothing works.

**Comment by juanbono** [comment]
Hi! There is a method named roundUp().
You can use it like this:
```
 var x = 3.4
 var y = x.roundUp()
```

**Comment by clombardi** [comment]
Hi Juan, thanks for the prompt answer.
In my Wollok 1.5.0 installation, the number 3.4 does not understand the message roundUp(). I also tried with roundDown(), just in case.
In my opinion it is more relevant to have a way to truncate than to round up (besides that, the name roundUp is not too nice, it makes me remember about the Monsanto stuff).

**Comment by fdodino** [comment]
Hi @clombardi , there is a truncate() method , it was developed by @matifreyre 10 months ago. I'm not really sure, but I think 1.5.3 version should have it. 
Original issue: #995.
Abrazo!
