### ISSUE TITLE
copy-paste method name onto the REPL does not work

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1119]
Suppose we have the following class defined in a Wollok source file.

class Certificacion {
	var puntos
	var sobreProducto = false
	constructor(_p,_bool) {
		puntos = _p
		sobreProducto = _bool
	}
	method puntos() = puntos
	method sobreProducto() = sobreProducto
	method sobreNoProducto() = not self.sobreProducto()
}

I want to try the method puntos(). So I open a REPL on the source file, and create an instance like this
>>> var c = new Certificacion(50,true)
Then I type
>>> c.
and copy the text "puntos()" from the source file to the REPL, to form
>>> c.puntos()
If I build the expression like this, the following error pops-up
ERROR: mismatched input '}' expecting RULE_ID (linea: 2)
ERROR: mismatched input '<EOF>' expecting '}' (linea: 2)
If I type the same expression into the REPL, it works properly. The error occurs only if the method name is copied from the source file.

**Comment by fdodino** [comment]
Hi @clombardi , this issue has been already solved. 
Original issue: #1084
PR  merged in dev branch: #1104.
It will be available on friday in Wollok 1.6.0 Freire
Abrazo!
