### ISSUE TITLE
Static Diagram: Icon "Clean shape and size position" should be a rubber instead of a save button

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1134]
There was a misunderstanding, but clean shape and size position is confusing

![image](https://user-images.githubusercontent.com/4549002/28236162-f30888f8-68f4-11e7-95f5-29beffdd8d3d.png)

See Diskette png, it seems to be a "Save as..." button but it should be a rubber.

**Comment by Juancete** [comment]
It seems to be wrong the javadoc:
```xtext
/**
 * Exports diagram to .wsdi file
 */
class CleanShapePositionsAction extends Action {
.... 
}
```
It would be 
```xtext
/**
 *  Resets the layout and modifications made in the diagram.
 */
```
right?
Do you like something like this @fdodino ? 
![restore_welcome_Image](http://eclipse-icons.i24.cc/ovr16/restore_welcome.gif)

**Comment by fdodino** [comment]
:smile: Yeah!!

**Comment by fdodino** [comment]
And don't forget the icon, hahaha!

**Comment by Juancete** [comment]
Done!
