### ISSUE TITLE
WKO creation in REPL?

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1136]
It's possible to create anonymous objects with 1.6 release, however this is not working:

>>> object pepita {}
ERROR: extraneous input 'pepita' expecting '{' (line: 1)

Is this not supposed to be supported as well?

**Comment by fdodino** [comment]
Hi @mmatos ! 
But if you don't assign it to a reference it would be very uncomfortable to use. This works

```
>>> var four = object { method value() = 4 }
an Object[]
>>> four.value()
4
```

**Comment by fdodino** [comment]
This also works

```
>>> object { method value() = 4 }.value()
4
```

**Comment by fdodino** [comment]
Sorry, @mmatos , didn't understand you. Deleted all my previous messages.

**Comment by npasserini** [comment]
This is a bit tricky. On one side, object creation is not an expression, and the repl expects expressions, so to allow this we should allow one of:
a) wko declaration is an expresion and therefore is allowed in any context.
b) repl has a different syntax than the rest of wollok, and therefore it allows wkos along with normal wollok expressions.

None of these options seems nice, imho.

Currently there is a way to do what you want:
const pepita = object { ... }

I know we normally do not show anonymous objects, so this is not nice either.

Still, I think our problem is more profound, we have two ways of defining objects... shouldn't we unify? how?

**Comment by fdodino** [comment]
Closing since now we have a way to do it in REPL and in wlk file.
