### ISSUE TITLE
Static Diagram: problem when inheriting from a double-defined class

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1144]
See  this example

```xtend
import objects.Numerote

/** First Wollok example */
object wollok {
	var felicidad = 10
	method howAreYou() {
		return 1 / 0
	}
	method soFeli() {
		return felicidad > 0 
	}
}

class Numerote {
	method sosPar() {
		return true
	}
}

object cuatro inherits Numerote {
	const five = object {
		method value() = 5
	}
	method elFive() = five
			
}

```

**Comment by fdodino** [comment]
Well, problem is that validator should warn if you define a class that has already a definition in an import.

**Comment by fdodino** [comment]
Well, to my surprise static diagram helped me to realize I'm inheriting from imported superclass

![image](https://user-images.githubusercontent.com/4549002/28468046-320fcc2e-6e08-11e7-814f-075dc85cf50f.png)

In fact, adding an overriden method appears correctly

![image](https://user-images.githubusercontent.com/4549002/28468082-4ff7009a-6e08-11e7-9a28-82809ec6f19c.png)

So, I don't know if we should add a warning at least to avoid confusions to student (I see no good practice at all, that's why I believe in a warning message)

**Comment by npasserini** [comment]
I think it should be an error, you have two classes with the same name.

**Comment by npasserini** [comment]
+1

2017-09-04 21:47 GMT-03:00 Fernando Dodino <notifications@github.com>:
