### ISSUE TITLE
Type system: Error executing EValidator doesn't show stack trace

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1147]
This wlk definition

```
object pepita {
	var energia = 0
	
	method volar(kilometros) {
		energia = energia.toUpperCase()
	}
}
```

Leads to "Error executing EValidator"
But no stack trace is shown.
I put a "Show stopper" label, because this prevents knowing different type system errors. I have another validation error problems, but I can't determine whether they refer to same issue as this (and I think it is not worthy to open several issues for that).

**Comment by javierfernandes** [comment]
This also happens when using the "shortcut operators" like "-="

Example, this fails with the same error

```wollok
object link {
	var corazonesActuales = 3
	
	method recibirDanio(cuanto) {
		corazonesActuales -= cuanto
	}
}
```

While this works fine

```
/** First Wollok example */
object link {
	var corazonesActuales = 3
	
	method recibirDanio(cuanto) {
		corazonesActuales = corazonesActuales - cuanto
	}
}
```

I suspect it is the typesystem.
@npasserini ?
I can create a separated issue ?

**Comment by javierfernandes** [comment]
Confirmed. Disabling type system removes the error. I'll create a new one

**Comment by npasserini** [comment]
Thanks.

2017-07-26 14:01 GMT-03:00 Javier Fernandes <notifications@github.com>:

**Comment by fdodino** [comment]
Well, @npasserini , confirmed that in branch dev 1.6.4  the previously failing code

```scala
object link {
	var corazonesActuales = 3
	
	method recibirDanio(cuanto) {
		corazonesActuales -= cuanto
	}
}
```

now works.

Also, there is no longer a message with "Error executing EValidator", so I'll close this issue and go on with #1186.
