### ISSUE TITLE
Using a non-existing variable in a method with the same name as a constructor parameter doesn't show an error

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1149]
Something like this should show an error for using ```e``` in method setEnergia, but it doesn't.

```
class A {
	var energia

	constructor(e) { energia = e }
	method energia() = energia
	method setEnergia() { energia = e }
}
```

**Comment by fdodino** [comment]
Well , currently this is a Linker problem

**Comment by fdodino** [comment]
Hi @tesonep , any clue? I don't know why it works for methods but not for constructors.
Looked in WollokLinker, WollokDslScopeProvider and wollokDsl.xtext / mwe2 but no idea.

**Comment by fdodino** [comment]
It was a provider problem.

**Comment by fdodino** [comment]
Bueno, cuento cuál era el problema 

Wollok para poder resolver las referencias a cosas necesita saber dónde están las cosas, para poderlas alcanzar.
Eso es lo que se llama Scope.
En particular en Wollok tenemos el WollokDslScopeProvider, que es el que le provee el alcance de las referencias. Eso permite que cuando vos decís 

```javascript
class Ave {
    var energia = 0
    method volar() { energia += 10 }
}
```

dentro del alcance del método volar() vos puedas hacer referencia a energia. Pero también si pasás un parámetro...

```javascript
class Ave {
    var energia = 0
    method volar(tiempo) { energia += tiempo }
}
```

...tiempo es otra referencia que existe dentro de ese alcance.

El tema es que para poder encontrar las referencias, hay un WollokImportedNamespaceAwareLocalScopeProvider, que permite encontrar ponele dos wko en distintos archivos sin que se arme lío.

Eso te da un conjunto de elementos a los que podés acceder.
En el ejemplo de Ave, si el archivo se llama "ave.wlk", te da una lista de las referencias disponibles como

[ave.Ave, ave.Ave.energia, ave.Ave.volar.tiempo ]

Entonces si estás dentro del método volar(), podés llegar a la referencia a tiempo.
El problema es que cuando definís un constructor, no tiene nombre:

```javascript
class Ave {
    var energia = 0
    constructor(e) { energia = e }
    method volar(tiempo) { energia += tiempo }
}
```

Entonces en la lista de referencias que se arma, te queda:

[ave.Ave, ave.Ave.energia, ave.Ave**.e**, ave.Ave.volar.tiempo ]

Eso permitía que desde cualquier lugar de la clase vos le pudieras pegar a ese parámetro e.

La solución fue hacer que el constructor tuviera un *qualifiedName* propio, para que no se confundiera el scope provider:

En la clase WollokQualifiedNameProvider

```xtend
	def qualifiedName(WConstructor c) {
		val size = if (c.parameters !== null) c.parameters.size else 0
		QualifiedName.create(WollokConstants.CONSTRUCTOR + size)
	}
```

Y entonces quedan como referencias:

[ave.Ave, ave.Ave.energia, ave.Ave**.constructor1.e**, ave.Ave.volar.tiempo ]

Ahora sí, no se confunden las referencias.
