### ISSUE TITLE
Confusing message for using super constructor when superclass has none

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1150]
The following code highlights super() with a message that reads "Invalid super constructor call. It does not exist. Valid constructors are:"... followed by the quickfixes!
When the superclass doesn't have constructors at all, the message shouldn't include that "valid constructors are" part.

```
class A {
	var energia = 0

	method energia() = energia
	method energia(e) { energia = e }
}

class B inherits A {

	var sarasa	
	constructor(e) = super() {
		sarasa = e
	}
	
	method bla(algo) = algo + 1
}
```

**Comment by Juancete** [comment]
I may be a bit confused, but I think that should not be an error. Class A has a default constructor which is invoked from class B. Am i right? @fdodino @npasserini

**Comment by fdodino** [comment]
Yes, it should not be an error... We should take for granted default constructor...

**Comment by Juancete** [comment]
right!!!  I'm on this issue.

**Comment by fdodino** [comment]
:+1:

**Comment by Juancete** [comment]
I understand that the default constructor should inherited from "Object". Is it right?

From what I see there is a resolverConstructor method in WMethodContainerExtension File that is responsible for returning the constructor that resolves that class or super class. I was able to follow the calls to the code until I get to Object but I see that it does not have constructors. (wrong!!!! must be the default constructor!)

So.... where i can find the structure that builds the root object to add a default constructor?

**Comment by fdodino** [comment]
@Juancete, did you make a test for this issue? Could you push your branch so I can checkout it?
Maybe I can help you (most probably next monday)...

**Comment by Juancete** [comment]
Sorry for the delay @fdodino . The branch when i was working is this:
https://github.com/uqbar-project/wollok/tree/dev-1150-fix-delegate-constructor-to-super

**Comment by fdodino** [comment]
Well, I've read @matifreyre issue again and I agree we should change message validation.

> When the superclass doesn't have constructors at all, the message shouldn't include that "valid constructors are" part.

This is ok:

```xtend
			class SuperClass {
				var superX
				
				constructor() {
				}
				method getSuperX() { return superX }
				method setSuperX(value) { superX = value }
			}
			class SubClass inherits SuperClass { 
				var anotherVariable
				constructor(n) = super() {
					anotherVariable = n
				}
				method getAnotherVariable() = anotherVariable
			}
```

And this is also ok

```xtend
			class SuperClass {
				var superX
				
				method getSuperX() { return superX }
				method setSuperX(value) { superX = value }
			}
			class SubClass inherits SuperClass { 
				var anotherVariable
				constructor(n) {
					anotherVariable = n
				}
				method getAnotherVariable() = anotherVariable
			}
```

So we just have to change out validation message

**Comment by Juancete** [comment]
Ok, If you run:
```xtend
class A {
	var energia = 0

	method energia() = energia
	method energia(e) { energia = e }
}

class B inherits A {

	var sarasa
	constructor(value) = super(){
		sarasa = value		
	}
	method bla(algo) = algo + 1
}
```
The message will be _"Invalid super constructor call. **Default constructor is not overriden**."_ because default constructors exist in every class. 

If you do 
```xtend
class A {
	var energia = 0
      
	method energia() = energia
	method energia(e) { energia = e }
}

class B inherits A {

	var sarasa
	constructor(value) = super(5){
		sarasa = value		
	}
	method bla(algo) = algo + 1
}
```
The message will be _"Invalid super constructor call. **Superclass has no explicit constructors.**"_ because calls another constructor and super class have no constructors.

and if you do:
```xtend
class A {
	var energia = 0
        constructor(aValue,OtherValue){
        }
	method energia() = energia
	method energia(e) { energia = e }
}

class B inherits A {

	var sarasa
	constructor(value) = super(5){
		sarasa = value		
	}
	method bla(algo) = algo + 1
}
```
The message will be _"Invalid super constructor call. **It does not exist. Valid constructors are super(aValue,otherValue)**."_ because calls another constructor that not exist but have almos one to show. 

what do you think @matifreyre @fdodino ?

**Comment by matifreyre** [comment]
Just to stay tuned... the last one would be the current one, with the whole list of valid constructors from the superclass, right? If it's right, then 👍

**Comment by Juancete** [comment]
Yeap!
