### ISSUE TITLE
Implementation of WPosition

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1152]
Looking at impl of WPosition https://github.com/uqbar-project/wollok/blob/7b4589c239d0a9340e87dffda8072b2f5d73ef16/org.uqbar.project.wollok.lib/src/org/uqbar/project/wollok/lib/WPosition.xtend, I think that this is highly coupled to a Java/Xtend implementation.

I think we should change the implementation of this kind of objects, and have a common interface for interacting with its native counterparts, so that this code works on java/xtend/javascript/whatever without changes.

What do you think about this?

**Comment by npasserini** [comment]
@PalumboN

**Comment by PalumboN** [comment]
Yeah! 
I want to do a refactor in all WG design, moving all possible xtend code to wollok. This is a good start.

**Comment by npasserini** [comment]
Ojo, no es "mover todo el código posible de xtend a Wollok", sino definir
entre wollok y el lenguaje host (xtend en este caso) un contrato que sea
agnóstico de la tecnología del host. De forma que muchos hosts distintos
(javascript específicamente) puedan implementar ese contrato.

Supongo que mover muchas cosas a wollok reduce el códig xtend/host y eso
hace que el contrato sea más pequeño y por lo tanto más fácil de cumplir,
pero no necesariamente la relación es tan directa.

2017-09-05 0:32 GMT-03:00 Nahuel Palumbo <notifications@github.com>:

**Comment by PalumboN** [comment]
Agree 100%
