### ISSUE TITLE
Many exceptions in WNumber should be pure Wollok exceptions

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1153]
XTend exceptions normally indicate internal problems and they should not be found by students. In WNumber there are a few situations in which student errors could produce non-Wollok exceptions, we should correct

**Comment by fdodino** [comment]
I'll put this issue in "To Check" column since after last refactor for numbers I think there are no more such Xtend errors.

**Comment by fdodino** [comment]
Closing it.
