### ISSUE TITLE
Quick fix: Separate "Add new class" | "Add new inner class" for non-existing elements

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1159]
Now it is possible to add an inner class (in same file: test or wlk)
I think it would be nice to offer two options:

- add inner class: current behavior
- add new class : it would open "New Objects and classes"wizard

**Comment by lspigariol** [comment]
Me parece que agregar el concepto de inner/internal confunde.

Bastaria con dos items:
crear nueva clase
 - en este mismo archivo
 - en un nuevo archivo (con el wizard) 

tambien se podria agregar un "crearla en otro archivo existente" y dejar elegir, pero ya es demasiado. Que los casos rebuscados se hagan a mano.

**Comment by fdodino** [comment]
Je, vos decís algo como ésto?

![featurepepita](https://user-images.githubusercontent.com/4549002/29624063-93679096-87fe-11e7-9ad3-7bed79eb1d89.gif)

Por ahora puse "local" vs. "external", se puede mejorar la descripción.
Esto está en progreso, calculo que el viernes lo termino de pulir.
Como verás, cuando generás un archivo nuevo también te arma el import, y además te refresca el proyecto (compila de una).
El tema es que cuando lo agrego a un archivo existente, tengo que ver cómo hago para agregar el import en forma inteligente (porque si ya tenés un import example.* no hace falta, pero si tenés el import example.objeto1 tenés que hacerlo).

**Comment by lspigariol** [comment]
Siempre un paso adelante!

sí, imaginaba algo así.
Ahora que lo veo, tambien se me ocurre que el menu diga solo crear nueva
clase (u objeto) y en la otra ventana agregar la opción (seleccionada por
default) de crearla en el mismo archivo.

que haga tambien el import esta bueno!
(en mi caso, nunca muestro import example.objeto1, siempre con *, pero si
quedan los dos import, uno con * y otro con el objeto, anda igual)
