### ISSUE TITLE
Reification of Method lookup 

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok#1164]
There isn't an entity that handle the method lookup behavior. Now it's divided among several files. May be we can re-use code. For example the mechanism to find a constructor or method in a superclass.

**Comment by npasserini** [comment]
Sure, but kind of low priority. I think we need other refactors first.

**Comment by fdodino** [comment]
I believe this is also a stale issue, and since we are removing constructors for Wollok 2.0 version (and adding new tools for Wollok environment), closing it is ok.
