### ISSUE TITLE
Separate the validator from Xtext environment

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok#1165]
If we can separate the validator, we have the ability to check the code, raise exceptions and controlling warnings without the ide.

**Comment by fdodino** [comment]
It is a really wonderful idea. We will tackle this in TS for second semester of 2019, maybe, or 2020...

**Comment by fdodino** [comment]
Removing the Won't do since it is an interesting task to integrate it with VSC

**Comment by fdodino** [comment]
Cierro el issue porque lo vamos a abrir en wollok-ts (febrero o marzo 2020...) @nscarcella
