### ISSUE TITLE
Warning CONSTRUCTOR_IN_SUPER_TYPE

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1175]
Al correr tests, aparece warning

Warning: NLS unused message: WollokDslValidator_NO_DEFAULT_CONSTRUCTOR_IN_SUPER_TYPE in: org.uqbar.project.wollok.messages

@Juancete ¿es sobre lo que estuviste trabajando?

**Comment by Juancete** [comment]
Ese es el mensaje anterior que se evaluaba con el antiguo modo de trabajar con los constructores dodne se explicitaba que debía llamar al constructor de la super clase. Estaba eliminada la constante en el archivo inglés de la internacionalización pero no en español.
