### ISSUE TITLE
Comparar WKO con ==

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1176]
En wollok freire, ahora da error hacer
`variable == pepita`
siendo pepita un WKO.

Entiendo que es para evitar ifs, pero hay casos donde lo quiero usar en otros contextos, por ejemplo como retorno de un mensaje booleano.

**Comment by fdodino** [comment]
Estoy eliminando esta validación

```xtend
	@Check
	@DefaultSeverity(ERROR)
	@CheckGroup(WollokCheckGroup.POTENTIAL_PROGRAMMING_PROBLEM)
	def comparingEqualityOfWellKnownObject(WBinaryOperation op) {
		val comparisonOperands = #['==', '!=', '===', '!==']

		if (comparisonOperands.contains(op.feature)) {
			if (op.leftOperand.isWellKnownObject)
				report(WollokDslValidator_DO_NOT_COMPARE_FOR_EQUALITY_WKO, op, WBINARY_OPERATION__LEFT_OPERAND)
			if (op.rightOperand?.isWellKnownObject)
				report(WollokDslValidator_DO_NOT_COMPARE_FOR_EQUALITY_WKO, op, WBINARY_OPERATION__RIGHT_OPERAND)
		}
	}
```

Hasta que podamos hacer un mejor intento.

**Comment by clombardi** [comment]
Hola (mantengamos coherencia de lenguaje en un mismo thread).

Ayer charlamos sobre esto con Nico. En nuestra (con Leo Gassman) experiencia dando Objetos 1 en la UNQ, cuando un alumno hacía una comparación de igualdad con un WKO, le decía que estaba mal, y que resolviera el problema usando polimorfismo. No detecté ningún caso en donde una comparación de este estilo fuera conveniente. Me contó Nico que hay otros casos, posiblemente relacionados con Wollok-game, donde esto sí tiene sentido. Me gustaría conocerlos. Entonces por favor, Lucas o alguien que sepa, ponga un par de ejemplos donde uno aconsejaría, o aceptaría, una comparación de este estilo. Creo que como comentarios sobre este issue estaría OK.

¡Gracias! - Carlos

**Comment by fdodino** [comment]
Por el momento dejo el issue en la columna "Discuss", y borré el branch remoto, hasta tanto tengamos zanjada la resolución

**Comment by lspigariol** [comment]
hay muchos casos sencillos, por ejemplo metodos booleanos, donde obligar a
definir metodos polimorficos es complicarlo innecesariamente.
Si existe el método == ¿por qué permitir usarlo con literales y objetos
instanciados a partir de clases, e impedir usarlo con objetos definidos
como wko? esa inconsistencia no me parece buena.

el tema salio con un ejemplo de wollok game como podria haber salido con
cualquier otro.

un ejemplo:

object argentina {
}

object sanMartin {
var ubicacion = argentina
method viajar(destino){
ubicacion = destino
}
method enElPais() {
return ubicacion == argentina
}
}

así da error

es facilmente hackeable usando "argentina" o new Pais("argentina")

var arg = argentina
return ubicacion == arg

![ubicacion].contains(argentina)
y otras mas feas aún

la solucion polimorfica me obligaria a hacer un
return ubicacion.esArgentina()
y definirlo trivialmente en el wko argentina y en no sé cuantos/cuáles
otros objetos que podrian ser posibles ubicaciones.

Hay casos donde complejizar la solucion usando polimorfismo esta bueno para
ganar versatilidad, generalidad o probables cambios. Pero hay casos
sencillos donde no justifica.






2017-09-19 14:02 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by clombardi** [comment]
Hola Lucas, gracias por el comentario.

Imagino que estaba marcado como error para evitar que los estudiantes hagan cosas como
  if (ave == pepita) {
    // código que debería estar en pepita
  } else if (ave == juanita) {
    // código que debería estar en juanita
  } ... etc ...

que son los casos que vi en mi año dando Objetos 1 en la UNQ. 
Estoy de acuerdo en que, siendo fácilmente hackeable, correspondería más un warning que un error.

Respecto del ejemplo que das, me resulta sospechoso que argentina no tenga comportamiento. Parece un marker más que un objeto. También cabe la pregunta si la condición de "estar en el pais" va a ser satisfecha por exactamente una ubicación, de no ser así, correspondería algo como
  method enElPais() {
      return ubicacin.estaEnElPais()
  }

Esta nota es sólo para seguir pensando. A hoy, entiendo que esto no va a tirar ni warning ni error. En un estadío más avanzado del desarrollo de Wollok, podría aparecer un warning si es la condición de un if, o más cheto aún, solamente si hay un seudo-switch.

**Comment by fdodino** [comment]
Hola, preparando la clase de Tamagotchi, si modelamos con 3 wko los estados triste, contento y hambriento el test que pregunta si un tamagotchi está contento hace que yo defina un método

```javascript
method estaContento() = estado === contento
```

Ok, es un método que solo queremos para un test, podríamos preguntar directamente en el test si el estado es contento y ya, pero dado que ahora vi en el issue #1284 que hay warnings que  no lo son, quiero que pensemos muy bien los próximos validadores para estar seguros de lo que queremos (es decir, armar una especificación más formal).

**Comment by lspigariol** [comment]
si, un motivo más!

a proposito, por que usar === en vez de == ?
(en wollok aun no encontre un caso donde sea necesario usar === )

**Comment by fdodino** [comment]
no, es un tema que traigo con la nueva versión de xtend, debería ser ==
