### ISSUE TITLE
warning Esta variable solo se usa para retornarla

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1177]
hay veces donde da este warning y en realidad la variable se usa, por ejemplo para mandarle mensaje y retornar su resultado

ejemplo:

```
method nn() {
   const x = 1
   return x + 1  
}
```

**Comment by fdodino** [comment]
Sería bueno empezar a debatir por mail alguno de los issues @lspigariol @npasserini, creo que es importante retomar las discusiones...

**Comment by lspigariol** [comment]
puntualmente, el problema original no pasa más.  
(Ok con retomar discusiones varias...)

**Comment by fdodino** [comment]
Gracias por el update! Este issue no se me ocurrió probarlo. Lo cerramos.
