### ISSUE TITLE
Wollok Game: be able to configure a general background image

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1192]
Now you can add a background, but it is applied to each cell of Gameboard.
It would be nice 

- to maintain current behavior, so you can configure a background image for each cell
- or, apply a general background for Gameboard.

If you define a background image for a cell, it would override general background.

**Comment by PalumboN** [comment]
Nice! 
Now you configure the backgorund with `game.ground("image.jpg")` and this configure the image for each cell.
I'm thinking about how configure the background image for all gameboard. I have this options:
1. Having other method, as `game.boardGround("image.jpg")`, for that. With the your precedence.
2. Using the same method and choose if that is for cell/game background depending the image size: If it's bigger than cells is for gameboard background, else for cells.

I like the option 2 but i don't know if we want that kind of magic. What do you think?

Should be nice, in all cases, image size adapts to cell / game size.

**Comment by fdodino** [comment]
Je, I was thinking about a strategy...
:smile:

I agree with 2 if we are in a commercial language. But for an educational language, I think expressiveness is achieved better with 1 option.

I agree with you that "image size adapts to cell / game size".

**Comment by PalumboN** [comment]
@fdodino 
![peek 2018-03-12 00-55](https://user-images.githubusercontent.com/4098184/37265167-641e5a1a-2590-11e8-9014-a01e9d016404.gif)

**Comment by fdodino** [comment]
🥇 🏆 👍 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
