### ISSUE TITLE
Wollok Game: if you make Gameboard higher or wider, background image is partially applied to cells

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1193]
Steps to reproduce it:

```xtend
>>> game.height(8)
>>> game.width(8)
>>> game.start()
```

![image](https://user-images.githubusercontent.com/4549002/28868729-b468576c-7750-11e7-8b51-c50b632e7b1f.png)

**Comment by PalumboN** [comment]
We should lock the windows, no?

**Comment by PalumboN** [comment]
Ohh I misunderstood!
