### ISSUE TITLE
Issues with create method quickfix

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1196]
Say I have this code:

pepita.comerAlpiste(10)

The object pepita exists but not comerAlpiste, so I use the quick fix.

- if the object is defined like this:
object pepita {}
Nothing happens

- if the object is defined like this:
object pepita { } (note the space between the curly brackets)
The method is created below the object definition, outside of the brackets

- if it's defined like this:
object pepita {
}
The method is created, but the output does not compile for a completely different reason (instead of using a valid variable name for the parameter, it will say 10 leading to extraneous input error)
	method comerAlpiste(10) {
		//TODO: Autogenerated Code ! 
	}	

Also, while trying to create this issue it happened that I couldn't select the autogenerated code, because the editor went crazy and started modifying the code I was selecting. After playing around with it a bit, it stopped happening and I can no longer reproduce it, but maybe it's worth mentioning.

**Comment by fdodino** [comment]
I remember it happened once to me when I was developing this quickFix, but I could not reproduce it later. Lets give another try.

**Comment by fdodino** [comment]
Well, I added several tests (including these 3 situations). Now if you have

```xtend
object pepita {
}
```
And you call pepita.comerAlpiste(10) a new method like this will be generated:

```xtend
object pepita {
     method comerAlpiste(param1) {
           // Autogenerated code !
    }
}
```

Is it ok to you, @mmatos ?

**Comment by fdodino** [comment]
You can see the tests in MethodOnWKODoesntExistQuickFixTest and in ConstructorsQuickFixTest of last commit.

**Comment by mmatos** [comment]
Awesome, that should not lead to issues, thanks!

**Comment by fdodino** [comment]
![anim.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e99a932ec0cfeb9ffbb049a15ee4d6730472267a53a52e7687b570be107f075a094eac135d5816f5a89b37b4f46d2ede0356b49b381d66cc2f10abb2831abf04bd268c4c85b6bf8e49d2a5.gif)
