### ISSUE TITLE
Ocultar los mensajes de object

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1206]
Sobre todo en las primeras clases, que al desplegar el menu contextual de los mensajes disponibles en un wko  muestre tambien los mensajes de object, entorpece mas que ayudar. Despierta preguntas que desvian la atención y no hay como responder sin espoilear.

Con el mismo criterio de no mostrar object en el diagrama estatico, ni necesitar hacer inherits para heredar de object para no anticipar conceptos, seria mejor ocultarlos.
A lo sumo, permitir configurar para que un usuario avanzado lo habilite.

Aparte, excepto el == y el \=, el resto dificilmente se usa.

**Comment by lspigariol** [comment]
¿Es posible sugerir tambien los mensajes disponibles desde la consola?
¿Y los de los objetos literales?

**Comment by fdodino** [comment]
El autocompletado de la consola es muy difícil dada la tecnología en la que está implementada la consola.

**Comment by lspigariol** [comment]
Lo mas interesante era el issue original

**Comment by fdodino** [comment]
@lspigariol lo que se hizo fue ocultar los métodos privados que me parece una solución que ayuda bastante a despejar esos mensajes que nunca se usan.

Fíjate #1690 , para mí este issue estaría para cerrarlo

**Comment by lspigariol** [comment]
Genial, esto es mejor
