### ISSUE TITLE
Renaming a file breaks the runner

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok#1210]
If you change a file name, when you launch the application (I.e. REPL) wollok hangs "building" the project. You close the IDE and open again and the problem is solved. It's for a cache that is not updated?

**Comment by fdodino** [comment]
It happened to me recently, but I couldn't remember what I'd done. After a restart everything worked fine, so maybe it is a cache falling in a loop.

**Comment by fdodino** [comment]
I can't reproduce it in scopes-and-imports-issues, I will put this issuein To Check column

**Comment by fdodino** [comment]
Tested on 1.7.2 and it is happening

**Comment by lspigariol** [comment]
Me paso algo similar al copiar y pegar un archivo de un proyecto a otro.

**Comment by fdodino** [comment]
Encontré el origen del problema, y efectivamente son los synchronized que les puse a 

- WollokGlobalScopeProvider
- MapBasedWollokGlobalScopeCache

El tema es que no los puedo sacar a todos porque introduciría nuevamente problemas que teníamos todo el tiempo con el editor, así que voy a tunearlo finamente.
