### ISSUE TITLE
Incorrect "You should declare constructors before method" when declaring  a constructor in a "Mixin" !

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#1212]
This
```wollok
mixin M {
	constructor(pd) { }
	
	method a() {}
}
```

raises an error in "constructor" which says "You should declare constructors before methods", which is not the case.

If you change to class

```wollok
class M {
	constructor(pd) { }
	
	method a() {}
}
```

It then "compiles" files

**Comment by javierfernandes** [comment]
Just checked that mixins don't support constructors :P

http://www.wollok.org/en/lang-ref/#mixins

`it cannot define constructors (this might change in the future?)`

Ok, then the error should explicitely state that instead of the current error

**Comment by fdodino** [comment]
I had recently same weird error message for a wko

```scala
object example {
	var iable = 2
	constructor(mm) {}
```

So, +1

**Comment by javierfernandes** [comment]
Yeap, same case. Objects cannot have constructors.

**Comment by fdodino** [comment]
![issues1212.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e18789368790f8ddb8ed01e81fe086264c22703d46f96925d0b07fb9477d0359571fae150e5a12fcf9db2ea1e43521984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85b3bb8c4fc7e13e22e4829d02.png)
