### ISSUE TITLE
A const can be assigned twice in the constructor and fixtures

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1214]
The following definitions are considered valid, though a constant should not be assigned after it is initialized:

```javascript
class X {
	const e
	constructor(_e) {
		e = _e
		e = 2
	}
}

describe "group of tests" {
	const a
	
	fixture {
		 a = new Golondrina(10)
		 a = 8
	}
}
```

Trying to assign those variables in regular methods/tests is not considered valid, as expected.

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/30560916-bbacc314-9c8f-11e7-8500-cc419cddd921.png)
