### ISSUE TITLE
Quickfix to change const for var doesn't work

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1215]
Trying to assign a const within a regular method or test will lead to an error as expected, and proposes to change that variable to var as a quickfix, which makes sense.

However nothing happens if you use the quickfix.

**Comment by fdodino** [comment]
HI @mmatos , I could not reproduce it.
Can you post a way of how did you get into that situation?

![anim](https://user-images.githubusercontent.com/4549002/29488089-4fba17d2-84da-11e7-850c-eb6345291a44.gif)

**Comment by mmatos** [comment]
It looks like it only happens when the const reference is not initialized in the same line of it's declaration. I got into this situation declaring the const in a describe and initializing it in the fixture, and the same when initializing in a constructor.

**Comment by fdodino** [comment]
Ok, that was the problem.
Added some tests , and fixed null pointer exception.

**Comment by fdodino** [comment]
![anim.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e99a932ec0cfeb9ffbb049a15ee4d6730472267a53a52e7687b570be107f075a094eac135d5816f5a89b37b4f46d2ede0356b49b381d66cc2f10abb2831abf04bd268d4680bfba884bd2a5.gif)
