### ISSUE TITLE
If an import is missing in a wtest that is located in the same folder as the wlk file errors are shown only during execution

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1220]
I forgot to import from a wtest file the objects from wlk file that was in the same folder. Usages of those objects from the wtest files were not marked as errors, however when I tried to run that test file I got a bunch of errors like the following:

ERROR Couldn't resolve reference to Referenciable 'georginho'.

Apparently this only happens from a wtest file, because I tried removing an import from a wlk file that used an object from other wlk file that was in the same folder and that was marked as an error prior to the execution.

I tried moving the wtest file that was missing the import to a subfolder of where it was located, and only then I got the expected static errors.

**Comment by fdodino** [comment]
Hi @mmatos , could you upload the project into a public repo, so we can test it in another computer? Many thanks!

**Comment by fdodino** [comment]
I believe it was fixed today in local branch.
