### ISSUE TITLE
Reorganize menu 

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1227]
Wollok has a renaming feature (though buggy, see #1210). But it is very difficult to find.
First, it is nested in the menu below "refactoring" which is not a concept that beginners know.
Second, in spanish it is named "redenominar", it should be "renombrar".

I do not know if its better to just fix this particular issue or to review the whole menu, select the items that are really useful for beginners, organize them properly, and check the names and translations.

**Comment by fdodino** [comment]
Closing it since IDE related and found impossible to fix.
