### ISSUE TITLE
Confusing messages on different kinds of DNUs

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1228]
Currently in Wollok REPL you will get the same error in this two situations:
- if you mistype a message name.
- if you send the wrong number of arguments.

![image](https://user-images.githubusercontent.com/4633913/29596553-0eedc1d8-8794-11e7-9c1f-4874408808cf.png)

This is understandable because the signature of a wollok message consists of message name + argument count, but still, I think it might be confusing for students. So we should consider this two different kind of errors and provide different messages.

**Comment by lspigariol** [comment]
en la version en español:

>>> wollok.howAmI()
ERROR: El mensaje no existe o número incorrecto de argumentos para objeto (linea: 1)
>>> wollok.howAreYou("hi")
ERROR: El mensaje no existe o número incorrecto de argumentos para objeto (linea: 1)
>>> 

es mas expresivo alertando sobre los dos posibles problemas, pero sería mejor dos mensajes diferentes.

sin embargo, cuando se trata de un literal, el mensaje es diferente, y en ingles.
>>> 2.nada()
wollok.lang.MessageNotUnderstoodException: 2 does not understand nada()

**Comment by fdodino** [comment]
Related to #1195

**Comment by fdodino** [comment]
See this tests, is it ok the message? @lspigariol @npasserini 

```xtend
/* XPECT_SETUP org.uqbar.project.wollok.tests.xpect.WollokXPectTest END_SETUP */

class Persona {
	method blah() {
		pepita.foo()
		pepita.bar()
		
		// XPECT errors --> "pepita does not understand fooBar()" at "fooBar"
		pepita.fooBar()
		
		// XPECT errors --> "pepita does not understand fooBar(param1, param2)" at "fooBar"
		pepita.fooBar(2, "hola")
		
		// XPECT errors --> "pepita does not understand fooWithParam(), however a similar method exists: fooWithParam(p)" at "fooWithParam"
		pepita.fooWithParam()
		
		// XPECT errors --> "pepita does not understand fooWithParam(param1, param2, param3), however a similar method exists: fooWithParam(p)" at "fooWithParam"
		pepita.fooWithParam(new Date(), 2, 4)
	}
}

class B {
	var i = pepita.foo()
	// XPECT errors --> "pepita does not understand zoo()" at "zoo"
	var x = pepita.zoo()
	
	method a() = i + x
}


object pepita {
	method foo() = 23
	method bar() = self.foo()
	method fooWithParam(p) {
	}
}
```

**Comment by fdodino** [comment]
Also checking case typos

```
		// XPECT errors --> "pepita does not understand foO(), however a similar method exists: foo()" at "foO"
		pepita.foO()
```

Working on branch DNU-fixes

**Comment by npasserini** [comment]
This is great!

About the message.. I wonder if it is consistent with our normal speech.
When I say "pepita" understands a message I rarely say "volar with 1
argument", but instead I say "understands volar", without specifying
arguments.

So yet we fully agree in understanding volar/1 and volar/2 as different
messages, our normal speech does not emphasize it and informally kind of
implies the opposite. So, this might imply a decision:
a) should we consider that our speach  (or is it just mine?) is just wrong
and start being more precise?
b) or should we allow the other interpretation and provide error messages
that are more clear for that interpretation?

Going for b implies selecting a message like "message foo expects 2
arguments, you provided only one", without talking about understanding or
not.
For me it would be more natural to provide a message like this, what do you
think?
I would like the opinion of @clombardi here.

In any case, please consider the possibility that there more than two
messages with the same name and different arity... should we provide
messages that take this into account?


Finally, I understand that sometimes there is some gap between usual
language and "strict" language. Typical example is saying "send a message
to pepita" instead of "to the object referenced by variable/constant named
pepita". It would be to annoying to use the second form all the time, so we
allow the language gap.
Back in our current example, following the same strategy would imply that
we consider it as different messages, but allow that usual language
references messages by its name instead of being precise in referencing by
name + arity. So allow yet another language gap.
But then, I would be careful in using in the messages in the tool, a
language that has some differences with the language we use more frequently
in the classroom.

2017-08-26 13:36 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Hago un pequeño paréntesis a la pregunta de Nico para continuar el laburo sobre el PR
Sobre lo que dice @lspigariol :

sin embargo, cuando se trata de un literal, el mensaje es diferente, y en ingles.
```
2.nada()
wollok.lang.MessageNotUnderstoodException: 2 does not understand nada()
```

Esto se da porque el mensaje lo está generando WollokObject:

```
	/** @private */
	method messageNotUnderstood(name, parameters) {
		var message = if (name != "toString") 
					self.toString()
				 else 
				 	self.kindName()
		message += " does not understand " + name
		if (parameters.size() > 0)
			message += "(" + (0..(parameters.size()-1)).map { i => "p" + i }.join(',') + ")"
		else
			message += "()"
		throw new MessageNotUnderstoodException(message)
	}
```

Voy a tener que pasarlo a native para 

- que se adecue al idioma del entorno (i18n)
- pero además para verificar que no haya métodos "similares"

Por lo demás, lo que me molesta es que cuando vos mandás un mensaje a un wko, es el Validator el que chequea y tira un error, vs. el error con stack trace y todo que se genera cuando mandás un mensaje a un objeto de una clase. Ok, falta el type system para que estén a mano ambas validaciones, por eso por el momento lo dejo así.

**Comment by fdodino** [comment]
Related also with #1131

**Comment by clombardi** [comment]
Hi all,

I just react to the comment from Nico about the form of the message to be shown to the user.

We can assume that in most cases, objects/classes created by Wollok target users won't include mutiple methods having the same name, and differing only in the parameter count.

In such cases, I think that a message like
   Wrong argument count for message 'volar' sent to pepita: you should provide 1 argument, not 0.
would fit.
If the message is sent to an instance, there is no class/object having a fit method with the given parameter count, but there is/are some classes/objects with a method of the same name and different parameter count, this could be detected as well, with a message like
   Wrong argument count for message 'volar': you should provide 1 argument, not 0. 
   Note: this message should be sent only to a Golondrina/Paloma/Gorrion, or to pepita, pepon or pipa.

If there are competing methods with different parameter count, I suggest something like
   Wrong argument count for message 'volar' sent to pepita: you should provide either 1 or 2 arguments, not 0. 
   Note: are you sure that you want to include two versions of 'volar' in the definition of pepita?
For classes, we have two scenarios
1. there is no definition allowing different parameter count, but there are methods in non-competing (i.e. not related by inheritance) classes including definitions with different parameter count. Proposed message in this case:
   Wrong argument count for message 'volar' sent to pepita: you should provide either 1 or 2 arguments, not 0. 
   Note: with 1 argument, this message should be sent only to a Golondrina/Paloma/Gorrion, or to pepita, pepon or pipa. With 2 arguments, only to an AvionDeCarga.
If there are competing methods, the scenario gets more convoluted
   Wrong argument count for message 'volar' sent to pepita: you should provide either 1 or 2 arguments, not 0. 
   Note: with 1 argument, this message should be sent only to a Golondrina/Paloma/Gorrion, or to  pepon or pipa. With 2 arguments, only to an AvionDeCarga. In turn, pepita accepts 1 or 2 arguments (are you sure that you want to include two versions of 'volar' in the definition of pepita?).

Of course, I understand the potential complexity in doing the analysis. I could help with that, if you point me to the code in the Wollok implementation.

NB: with "Note" I mean extra information regarding the error message. I guess that could be a good idea to include this kind of guesses/insights into the message, to give further guidance to Wollok users.

**Comment by fdodino** [comment]
Ok, this led me to an intermediate solution

```
WollokDslValidator_METHOD_ON_WKO_DOESNT_EXIST = Wrong message {1} sent to {0}
WollokDslValidator_METHOD_ON_WKO_BAD_CALLED = Wrong argument count in message {1} sent to {0}, however similar definitions exist: {2}
```

Because achieving "either 1 or 2", "either 1, 3 or 4" and other possibilities was very uncomfortable adding also internationalization. I won't consider another objects of same type, at least, not for this original PR until type system is in production.

**Comment by clombardi** [comment]
Ok Fer, what the {2} would be in the latter message? 
And then, I imagine that this issue will be closed when you fix the problem leading to this discussion. Is there any possibility of keeping some of the texts (at least mine) open in a new issue to be handled later?

**Comment by fdodino** [comment]
Hi Nico, 
The {2} remained the same. There was also a subtle detail, when invoking a message with case differences (I realized I have to change the test with foO):

```xtend
class Persona {
	method blah() {
		pepita.foo()
		pepita.bar()
		
		// XPECT errors --> "Wrong message fooBar() sent to pepita" at "fooBar"
		pepita.fooBar()
		
		// XPECT errors --> "Wrong message fooBar(param1, param2) sent to pepita" at "fooBar"
		pepita.fooBar(2, "hola")
		
		// XPECT errors --> "Wrong argument count in message fooWithParam() sent to pepita, however similar definitions exist: fooWithParam(p)" at "fooWithParam"
		pepita.fooWithParam()
		
		// XPECT errors --> "Wrong argument count in message fooWithParam(param1, param2, param3) sent to pepita, however similar definitions exist: fooWithParam(p)" at "fooWithParam"
		pepita.fooWithParam(new Date(), 2, 4)

		// XPECT errors --> "Wrong argument count in message foO() sent to pepita, however similar definitions exist: foo()" at "foO"
		pepita.foO()
		
		// XPECT errors --> "Wrong argument count in message severalDef() sent to pepita, however similar definitions exist: severalDef(a), severalDef(a, b)" at "severalDef"
		pepita.severalDef()
		
		// XPECT errors --> "Wrong argument count in message severalDef(param1, param2, param3, param4) sent to pepita, however similar definitions exist: severalDef(a), severalDef(a, b)" at "severalDef"
		pepita.severalDef(1, 2, 3, 4)		
	}
}

class B {
	var i = pepita.foo()
	// XPECT errors --> "Wrong message zoo() sent to pepita" at "zoo"
	var x = pepita.zoo()
	
	method a() = i + x
}


object pepita {
	method foo() = 23
	method bar() = self.foo()
	method fooWithParam(p) {
	}
	method severalDef(a) { return a + 1 }
	method severalDef(a, b) = a + b
}
```

And for the second question, I opened a PR and assigned you as a reviewer, so we can discuss this further until there is a common agreement. Meanwhile I will work in another branch, so we don't take premature decisions.
