### ISSUE TITLE
REPL continues to run after program has been modified

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1229]
If you have a program running in the REPL and you modify it, the REPL continues running the old program. 

I would like to give a try to update the program in execution, maybe it is easier than it appears at first sight. But still, if that is not possible, we should take some action when the running program is modified. Otherwise, programmers tend to get confused because they can't see any behavior change after program modifications.

Two simple actions, we should either
a. Stop de REPL, or
b. If we allow to continue running, at least add some kind of visual clue about running an obsolete program: change a color or icon, display a warning, etc.

**Comment by lspigariol** [comment]
prefiero b)
a veces pasa que cuando se está haciendo la modificación, uno quiere volver a ver que es lo hacia antes.

**Comment by fdodino** [comment]
+1 and agree with b) option, it seems to be not so hard to achieve

**Comment by matifreyre** [comment]
Why not ask the user? "Hey! You changed the source file with a REPL running. What ya wanna do?" and then, if he/she continues with the running REPL, then add that proposed visual clue.
Many text editors do something like that when they don't lock the open files and something else changes them.

**Comment by fdodino** [comment]
Popups are not my friends. I hate them. I think to have a silent indicator is preferable.

**Comment by fdodino** [comment]
Something like this:

![anim](https://user-images.githubusercontent.com/4549002/30977887-53bc2584-a44f-11e7-97ad-9765e6fa4116.gif)

:smile:
