### ISSUE TITLE
WKO instanciados

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1231]
Ya se hablo del tema, pero para reflotarlo y pasar en limpio propuesta

Permitir pode hacer esto fuera de la definicion de objects y class
`object pepita = new Golondrina() `
y que sea equivalente a cualquier otro WKO

recuerdo que hasta ahí había acuerdo.
Lo que habia diferentes miradas es sobre:

1) Con la sintaxis anterior permitir tambien cosas como 
`object pi = 3.14`
`object entrenador = pepita.entrenador()`
o cualquier otra cosa que tambien sea valida en la inicializacion de variables de los wko, clases, etc.

2) Ser mas restrictivo y agregar un nuevo término 
`object pepita instanceOf Golondrina() `
y de esta manera permitir solamente instanciar.

Prefiero la 1), me resulta las simple y potente.

**Comment by matifreyre** [comment]
Creo que #1241 sería un caso concreto de esto un poco más interesante.

**Comment by lspigariol** [comment]
Con las excepciones, veo que tambien es otro caso de aplicacion.
hay ejemplos donde definimos una subclase (pero podria ser un objeto) de Exception sólo para tener un id cacheable, pero que no agrega comportamiento y la herencia pierde sentido.

ver tambien #1205 donde hay propuesta de manejo de excepciones sin herencia

**Comment by fdodino** [comment]
La sintaxis que vamos a tomar es

```js
const pi = 3.1416
const pepita = new Golondrina()
```

Y deberíamos tirar error si un objeto dice heredar de una clase y no agrega comportamiento ni estado.
