### ISSUE TITLE
Should a test send at least one message to assert?

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1235]
See this 'test'

```xtend
test "no pruebo nada" {
	1 + 1
}
```

Test runs fine.
But I think there should be at least one message sent to assert wko. 
It should be a warning issue.
I'm not sure, because that will lead to a warning if you design your own assert object.
What do you think @npasserini @tesonep @lspigariol ?

**Comment by npasserini** [comment]
Yes
