### ISSUE TITLE
const attributes should be initialized in ALL constructors

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1239]
This code fails because the constant is never assigned:
```Wollok
class Golondrina {
	const energia
	
	method energia() = energia
}
```

And that is ok. 
This code should fails too:
```Wollok
class Golondrina {
	const energia
	
	constructor() { }
	
	constructor(_energia) { energia = _energia}
	
	method energia() = energia
}
```
But compiles :(

**Comment by fdodino** [comment]
![issue1239](https://user-images.githubusercontent.com/4549002/30561033-21474316-9c90-11e7-9f0d-f03fd57fa71d.png)
