### ISSUE TITLE
no me funciona wollok

### ISSUE THREAD

**Issue by paniaton** [uqbar-project/wollok#1242]
estoy teniendo un problema a penas abro el programa, con 2 errores que me inutilizan las funciones
version de wollok 1.6.2 64bits
version de java : 1.8 64 bits
ambos intaladores bajados de los links recomendados: wollok-win32.win32.x86_64 y jdk-8u144-windows-x64
![error wollok](https://user-images.githubusercontent.com/26838158/29995863-03c73602-8fca-11e7-916d-cc6205ab18d6.png)

**Comment by fdodino** [comment]
Hola @paniaton, estas son advertencias, no errores. Podés trabajar normalmente con el entorno. Ya hay abierto un issue: #676, así que cerraremos éste. Saludos y suerte
Fernando
