### ISSUE TITLE
Code formatter should maintain line breaks after if-expression

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1243]
Currently this method:

	method comprar(cosa){
		var monto=cosa.precio()
		cantComida+=if(cosa.esComida())1 else 0
		cantElectrodomestico+=if(cosa.esElectrodomestico())1 else 0
		self.gastar(monto)
		totalCompras+=monto
		estaEquipado=cosa.esElectrodomestico()
	}

is reformatted as 

	method comprar(cosa) {
		var monto = cosa.precio()
		cantComida += if (cosa.esComida()) 1 else 0 cantElectrodomestico += if
		(cosa.esElectrodomestico()) 1 else 0 self.gastar(monto)
		totalCompras += monto estaEquipado = cosa.esElectrodomestico()
	}

Which is not nice.
Probably we are just incorrectly removing some line breaks, apparently after if expressions.

**Comment by fdodino** [comment]
Formatter has several issues, including #702 for if situations.
Unfortunately it was not easy to solve, because optional { } make it difficult to parse.
But I think if we change a little xtext definition I could be easier to solve.

**Comment by fdodino** [comment]
Closing since it is duplicated.
