### ISSUE TITLE
Syntatic sugar: add with operator

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1244]
After solving a TP, I found myself needing a builder. I decided to explain it

https://github.com/fdodino/scripts-clase/blob/master/PDP/objetos/Clases-constructores-builders-herencia-clase5.md

but I feel uncomfortable with that kind of solution, because student has to instantiate objects in a fixture:

1. Using an empty default constructor and setting each variable one by one.
2.Or just create a 5/6 parameter constructor, so he can't have default values without  creating 3 kind of different constructors.
3. And then, "final" solution is a builder.

I think an intermediate solution between 2 and 3 could be to develop a with operator, like Xtend has...

``` xtend
const presentacion = new Presentacion() => {
      agregarCantante(lucia)
      lugar(lunaPark)
}
```

**Comment by npasserini** [comment]
The problem with this is that it breaks the object.message() syntax. If we are allowing implicit receivers we should do it all over the program. Otherwise, we should insert a pseudo variable (such as "it") and change the previous code to make "it" the receiver of the messages.

**Comment by lspigariol** [comment]
no entendia bien el issue, pero la respuesta me desoriento...

la idea es [ 2,3,4] + 5 == [2,3,4,5] ?
o al estilo haskell 2:[3,4,5] = [2,3,4,5] ?

2017-09-04 21:01 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by fdodino** [comment]
No, la idea mía era usar un operador que se llama with, que lo tenía Visual Basic, Javascript hasta la 1.5 y Xtend, que te permite mandar varios mensajes al mismo objeto como el ejemplo de arriba. El sentido es que así en el fixture vos podés inicializar muchas referencias de un objeto sin estar repitiendo el objeto receptor y tampoco definiendo un constructor con 128412 parámetros. En xtend esto se logra:

```xtend
new Factura() => [
     total(100)
     agregarItem(2, queso)
     agregarItem(4, bondiola)
     cliente(cacho)
]
```

Nico dice con cierta razón que eso viola el contrato objeto.mensaje(parámetros) que por otra parte estamos tratando de validar con un mensaje lindo en otro issue.

Ok, cierro  el issue porque además es un poco un bardo lograrlo y me voy a arreglar generando como paso intermedio que el mismo objeto tenga un setter que devuelva el objeto  receptor, como en Smalltalk. De esa manera armo el message chain y listo.
