### ISSUE TITLE
Test expecting exception with wrong message fails red instead of yellow.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1245]
![image](https://user-images.githubusercontent.com/4633913/30032874-8a38950a-916e-11e7-8ca5-dace38025e2f.png)

**Comment by lspigariol** [comment]
a proposito de colores, el iconito de falla en la lista de tests, podria
ser tambien amarillo en vez de azul

2017-09-04 12:43 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/30559793-3b96d230-9c8c-11e7-8151-f37564ae9aba.png)
