### ISSUE TITLE
Quickfix for constructor creation

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1247]
Currently, if you write something like:  new Caballero(10,true)  and there is no custom constructor defined, the following error appears: "Wrong number of arguments. Should be new Caballero"

It would be nice to have a quickfix to create the constructor stub with the correct amount of arguments (without calling super or anything). I guess this has the complication that the constructor needs to be declared before methods, but that would also help to not make mistakes when writing it manually.

**Comment by fdodino** [comment]
+1!

**Comment by fdodino** [comment]
![anim](https://user-images.githubusercontent.com/4549002/32463278-17092ee4-c31b-11e7-9283-11b2502f4cce.gif)

Added an "adjust parameter" option.
