### ISSUE TITLE
"Cannot resolve import model.musicos.*" error shows when it should be valid for projects with more than one folder

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1253]
I created a project with the following structure:

src
   /model
   /test

In test folder there are some .wtest files and in model folder there's a .wlk file named musicos and the aim is to be able to import the objects and classes from the test folder using `import model.musicos.*`.

For some reason in some projects that were created with this same structure the error "Cannot resolve import model.musicos.*" shows up and it doesn't look like a cache issue because switching from one workspace to the other, as suggested in other issue does not make the error go away.

I don't have this problem with the project that I created from my machine, but the ones that I cloned from github that were a copy of my own project for the students do have this issue.

**Comment by JuanFdS** [comment]
Creating a `WOLLOK.ROOT` file with `wollokRoot` as its content in src fixes this problem.
