### ISSUE TITLE
Improve error message when incorrectly initializing attributes

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1254]
A student did something like the following:

```
object ble {
        var x
	var y = 8 * x.m
	method x(anX) {
		x= anX
	}
	method y() {
		return y
	}
}
```

This of course is incorrect because m is missing parenthesis and also the whole thing should be in method y and not have var y at all. However the error she got was: "no viable alternative at input 'method'" and method was underlined, when the error was in x.m so she didn't understand what was the problem.

It would be great if the error was marked where the error is actually caused with a message like "Missing parenthesis for message send".

Regarding the initialization, this would also lead to an issue in runtime as the x will not be initialized. So that's something else that can be marked as an error, independently of whether or not you think this kind of initialization should be valid instead of not having that variable at all.

**Comment by npasserini** [comment]
This error is not related to attribute initialization but to incorrect
syntax "x.m".
I think it is probably already reported.

2017-09-12 16:39 GMT-03:00 Mariana <notifications@github.com>:

**Comment by fdodino** [comment]
Related to #1216

**Comment by fdodino** [comment]
As already reported, closing it.
