### ISSUE TITLE
"Error executing EValidator" on correct project, led to actual errors not being marked

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1256]
I was working in class about inheritance with a project that had no particular complexity. At some point (sorry I cannot state exactly how this started happening), when I tried to run the test cases that we had already, it started saying if I wanted to run them anyway though there were errors, I clicked ok and the tests ran as expected.

Since I was in the middle of the class, I couldn't stop to analyze what that error was. The file that was marked as with errors was the wtest file that I was executing, but no lines were marked when looking at it in the editor. Closing and reopening Wollok didn't make it go away.

The Problems tab said "Error executing EValidator" and clicking on it took me to the first test declaration in my describe, which I had just been able to run without problems (21 occurrences of that same error that took me to the same place).

The main issue here was that for my class I was counting on the errors being shown when introducing abstract classes, but apparently that error prevented other errors from being displayed so I was not able to show the error "Class Guardian cannot be instantiated because it has abstract methods: coeficienteDeVelocidad() (required by Jugador)" unless I tried to run it so it would crash on runtime. 

I can see that error now after being able to get rid of the EValidator problem (I cut that first test case and copied it again to make it go away). 

Note that I don't have any Wollok project specific settings.

**Comment by mmatos** [comment]
Now I'm seeing another strange behavior related to this same thing:

I have the following code in a wlk file:
```
object ron inherits Guardian(10, 4, saetaDeFuego) {
	method decirUnChiste() = "Knock knock"
}

class Guardian inherits Jugador {
	var nivelDeReflejo = 20
	
	method concentrarse(){
		nivelDeReflejo += 10
	}
	method nivelDeReflejos() = nivelDeReflejo
	override method habilidad() = skills + nivelDeReflejo
	
	override method coeficienteDeVelocidad() = 2
}
```
Where Jugador is an abstract class with an abstract method named coeficienteDeVelocidad(), defined in the same file. And I also have a few test cases that use the following `new Guardian(100, 40, saetaDeFuego)` (that constructor is inherited from Jugador).

If I comment out the method coeficienteDeVelocidad in Guardian and save, only one error shows up in the Problems tab: "You must implement all inherited abstract methods: Jugador.coeficienteDeVelocidad()" leading to ron object. However the test file is not marked with errors in the Package Explorer, and nothing shows in the Problems tab for it, though the error is there in the editor: "Class Guardian cannot be instantiated because it has abstract methods: coeficienteDeVelocidad() (required by Jugador)".

If I also comment out the definition of ron WKO and save, the following errors are shown in the Problems tab for the test file:
- Error executing EValidator 
      2 occurrences in the test file, I cannot make it go away with cut/paste
- Wrong number of arguments. Should be new Cazador(unasSkills,unPeso,unaEscoba,unaPunteria)
     3 occurrences in the test file, one in each line where I do `new Guardian(100, 40, saetaDeFuego)` 

Cazador is another class that inherits from Jugador, no relation with Guardian which was what I was using there.

Those same errors remain if I uncomment the overrided abstract method, but if I then uncomment the ron WKO, they all go away (????).

**Comment by fdodino** [comment]
Verifyied against Wollok 1.6.7. Closing.
