### ISSUE TITLE
Randomly Wollok hangs in editor while building workspace

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1264]
I think it could be Wollok scope system but a profiling must be executed.
Users must quit IDE and start it again to make it work.

**Comment by tesonep** [comment]
Hi Fer, I am coming back from holidays.... do you have any idea how to provoke it? Or a workspace that is failing or something?

**Comment by fdodino** [comment]
Great!! Welcome back!

It is not easy to reproduce it. Sometimes it happened me when I did a rename, sometimes changing an import, but yesterday it happened me doing a "new  Doctor".

I would try to add and delete import lines repeatedly.

And unfortunately I can't give you a workspace because when you startup again everything works fine.
I suspect that could be creating a scope, it enters in an infinite loop.

**Comment by fdodino** [comment]
Well, it does happen in 1.6.3 when you rename a wlk but it has no effect on performance. You see a permanent loop "Building workspace". So I changed severity to minor.

**Comment by fdodino** [comment]
Recently I came up with this error again. Downloaded VisualVM, and problem seems to be here:

```xtend
	override synchronized IScope getScope(IScope parent, Resource context, boolean ignoreCase, EClass type,
		Predicate<IEObjectDescription> filter) {
			var explicitImportedObjects = context.importedObjects
			if (filter !== null)
				explicitImportedObjects = explicitImportedObjects.filter(filter)
			val defaultScope = super.getScope(parent, context, ignoreCase, type, filter)
			new SimpleScope(defaultScope, explicitImportedObjects)
	}
```

**Comment by fdodino** [comment]
Yes, main problem is a file corrupted. Today I'm facing the same problem, hanging in this line:

```javascript`
class WollokLibExtensions {

	/**
	 * loads the objects without cache
	 */
	static def load(URI uri, Resource resource, Manager manager) {
		var newResource = resource.resourceSet.getResource(uri, true)
``` 

which seems fine to me.

**Comment by fdodino** [comment]
More details: 

```xtend
public class XtextResourceSet extends ResourceSetImpl {

    @Override
	public Resource getResource(URI uri, boolean loadOnDemand) {
```

hangs when calling

```
	    if (loadOnDemand)
	    {
	      resource = demandCreateResource(uri);
	      if (resource == null) {
	        throw new RuntimeException("Cannot create a resource for '" + uri + "'; a registered resource factory is needed");
	      }

	      demandLoadHelper(resource);
```

demandLoadHelper is hanging.
If you call in WollokLibExtensions

```xtend
var newResource = resource.resourceSet.getResource(uri, false)
```

Eclipse is back to life. But you see errors in synchronization. Google didn't help.

**Comment by npasserini** [comment]
Several students report this and in some cases it has been close from show stopper for a machine-based exam. It happened 3 or more times in the same machine during exam.

![image](https://user-images.githubusercontent.com/4633913/45590523-6599e580-b910-11e8-9470-eb790a7c4121.png)
