### ISSUE TITLE
Los comentarios en list/collection/set deberían aclarar cuando son inválidos para colección vacía.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1267]
Algunos métodos de colecciones no se pueden usar con colecciones vacías y tiran errores. En otros lugares, eso está documentado, se aclara que tira error en ese caso, pero por ejemplo en #max no está esa aclaración. Deberíamos agregarla.

**Comment by fdodino** [comment]
Already done. Closing it.
