### ISSUE TITLE
"MultiOpAssignments" shouldn't be parsed as BinaryOperations

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1270]
Currently Wollok parser handles `a += b` as a special case for a (binary operation such as `a + b`).
I think it would be better to treat it as something more similar to an assignment, because they are not "expresions" in wollok. 

On the other hand, this implementation might be more flexible if in a future we change our mind and want more things to be expressions. Maybe @javierfernandes has something to say about this.

Also I do not like the name "MultiOpAssignment", maybe because I do not get the meaning of it. Another possible name could be "CompoundAssignment".

**Comment by lspigariol** [comment]
​Desde otro punto de vista, me cuesta darle un nombre que me deje conforme
cuando lo explico en clase
Lo mas ​probable es que diga que es un "sugar sintax" de un mensaje y una
asignación, pero es cierto que estructuralmente responde a la logica de un
mensaje binario.

Durante un buen tiempo uso el x = x + algo, y luego, cuando estan mas
cancheros les muestro el x += algo

lo que me disparo este tema (y que lo relacione con algo que estaba
pensando dias atras con wollok game, de alguna forma grafica estandarizada
de representar variables numericas que se incrementan/decrementan) es sobre
la posibilidad de incluir una clase de objetos que representen
"acumuladores".

Por ejemplo, en pepita decimos que cuando come su energia se incrementa en
cierta cantidad

por qué no escribirlo así:

method comer(alpiste) {
 energia.inc(alpiste)

}



class Acumulador {
var valor
constructor(v) {
valor = v
}

method inc(numero) {
valor += numero
}
method dec(numero) {
valor -= numero
}

method sig(){self.inc(1)}
method ant(){self.dec(1)}
//method newInstance() = #

}


2017-09-20 0:20 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by lspigariol** [comment]
uy! se mando antes de tiempo...

me faltaba completar el ejemplo

object pepita {

var energia = #100
// el # como literal para acumuladores.

method energia() = energia.value()

Lo único feo que le veo es tener que agregarle un mensaje value() para
obtener el valor, aunque si se hiciera completamente polimorfico de los
numeros, se acotaría bastante la necesidad de usarlo.

Tambien, puede haber una clase de acumuladores con maximos y minimos, que
es algo frecuente en nuestros ejemplos.

estuve viendo que la idea ya se le ocurrio a otra gente, bajo el nombre de
mutable numbers

¿En qué lugar está entre ser una genial idea o una completa estupidez?



2017-09-27 14:11 GMT-03:00 Lucas Spigariol <lspigariol@gmail.com>:

**Comment by fdodino** [comment]
Bueno, al final hay otro issue para eliminar estos "MultiOpAssignments", así que cierro este ticket.
