### ISSUE TITLE
wrong warnings in test when creating an empty object at the top of a file

### ISSUE THREAD

**Issue by dadais216** [uqbar-project/wollok#1276]
If I use an empty object in my main file I get the warning 'message doesn't exist or wrong number of arguments' in all methods of my test file (even the ones that have nothing to do with that object)

this is what I mean with 'empty object' : 

`
object empty{ }
`
I get the same thing if I separate the brackets.

The tests work fine, and the empty object is usable.
The warnings vanish If I move the declaration of the empty object to the bottom of the file

Here is an example: [https://github.com/dadais216/wollok-warning-empty-objects/tree/master/src](url)

**Comment by fdodino** [comment]
I don't know which behavior caused this error, but in an installation pointing to dev this works fine:

![issue1276-dadais.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e187893687d2fbd8bff247a559f19d3a046b313916ac217586f76ae5002e545c5818f9170a594cadfbdd7da3e03c70d8590cbfd83c4d68d47f40f2ecdd42e64bef62994597b7bb804dc5e83b26e78c884d3e1e041f9bb2.png)

So I will put this in a To Check column for further  tests when we deploy 1.6.3 version.
Thanks in advance @dadais.

**Comment by fdodino** [comment]
Another evidence more realistic:

![anim](https://user-images.githubusercontent.com/4549002/30790638-6a72b082-a183-11e7-98e0-7d6d97e22ebd.gif)

**Comment by fdodino** [comment]
Closed.
