### ISSUE TITLE
Problems when creating a new wollok test

### ISSUE THREAD

**Issue by LihueMahmoud** [uqbar-project/wollok#1278]
When I click on the src folder -> new wollok test, and I hit play or try to save it, it displays this window:
![image](https://user-images.githubusercontent.com/21241162/30880009-96431b5c-a2d7-11e7-996d-86a0a0e7f0ca.png)
When I click ok, it seems like it still evaluates them because this appears on green:
![image](https://user-images.githubusercontent.com/21241162/30880022-9dd05560-a2d7-11e7-8ee4-56863777ec88.png)
However, when I try to close eclipse, it won't let me because it says that I can't close it without saving the changes first, which I can't do
To solve this I went to windows -> preferences -> searched for "encoding" and changed cp1252 for UTF-8
![image](https://user-images.githubusercontent.com/21241162/30880027-a5eb4a8e-a2d7-11e7-9557-178ff6767db1.png)
![image](https://user-images.githubusercontent.com/21241162/30880034-ad83e8a0-a2d7-11e7-9768-4a1141f6bee4.png)

**Comment by fdodino** [comment]
Ok, maybe we should stick UTF-8 preference in wollok.ini, as we did for showing lines.
This is default on Linux and Mac, but not for Windows and causes many ugly character conversions when changing from Cp1252 to UTF-8.
