### ISSUE TITLE
Recomendación errónea en constructor respecto a las variables

### ISSUE THREAD

**Issue by sanuzzi** [uqbar-project/wollok#1284]
La advertencia se muestra acá:

![image](https://user-images.githubusercontent.com/1631264/31262459-746f06ec-aa31-11e7-9979-d569fc38d6e4.png)

El warning dice:

![image](https://user-images.githubusercontent.com/1631264/31262419-29d0d5d4-aa31-11e7-99ee-738ff68a82a9.png)

Y esto es erróneo. Si tenemos una referencia **variable**, es recomendable que exista un **setter** y usarlo desde todos los puntos donde queramos alterarla (incluso en el constructor).

De esta forma, si el día de mañana queremos una validación para que el valor sea consistente (limitándolo en un rango, lanzando excepciones, o lo que queramos), simplemente lo agregamos en el setter y todo el código queda consistente.

Si bien en Wollok es algo engorroso escribir getters y setters en comparación a algunos otros lenguajes, sigue siendo recomendable, y el IDE no debería forzarnos a dejarlos de lado.

Esto sucede desde que actualicé a la versión 1.6.3.

**Comment by fdodino** [comment]
Hoy caí en la misma trampa, y no es fácil detectar si una referencia quedó correctamente inicializada. Al menos hay que elaborar un poco más esa validación para evitar que en este constructor me diga que "estado" no está siendo inicializada (lo cual es un error)

```
class Tamagotchi {

	var estado
	var felicidad = 0
	
	constructor() {
		self.ponerseContento()
	}
	
	method comer() {
		estado.comer()		
	}	

	method ponerseMasFeliz(cuanto) {
		felicidad += cuanto
	}
	
	method felicidad() = felicidad
	
	method ponerseContento() {
		estado = new Contento(self)
	}	
}
```
