### ISSUE TITLE
No reconoce la redefinición de un método abstracto en una subclase

### ISSUE THREAD

**Issue by natoszme** [uqbar-project/wollok#1294]
O al menos no inmediatamente.

Al agregar el método abstracto en la superclase y en las subclases y modificar lo que correspondía en los tests me tiraba (en los tests) que las subclases no implementaban el método abstracto cuando en realidad si lo hacían. Adjunto algunas capturas para que se vea mejor!

![1](https://user-images.githubusercontent.com/14940818/31800903-bd983390-b51a-11e7-8e42-8c9ccc4e4c91.jpg)
![4](https://user-images.githubusercontent.com/14940818/31800904-bdb81eb2-b51a-11e7-95c0-46ee73a4fb73.jpg)
![2](https://user-images.githubusercontent.com/14940818/31800905-bddb9982-b51a-11e7-95e2-e897a3cff972.jpg)
![3](https://user-images.githubusercontent.com/14940818/31800906-bdfeceb6-b51a-11e7-9f7a-709c1c6641d6.jpg)

Al eliminar los errores de la vista Problemas (click derecho, Suprimir) los tests no corrían, así que probé cerrando el IDE y al volverlo a abrir todo estaba en orden.

**Comment by fdodino** [comment]
¡hola!  ¿podrías confirmarme qué versión de Wollok estás usando? en el menú Acerca de | Wollok o bien en Ayuda | Software instalado

**Comment by natoszme** [comment]
@fdodino 1.6.3!

**Comment by fdodino** [comment]
¡gracias!

**Comment by fdodino** [comment]
@tesonep Creo que hay algún temita todavía con la cache que provee las definiciones de los objetos, también parece pasar con los constructores cuando hay una jerarquía que se modifica.

**Comment by tesonep** [comment]
@fdodino Esto tiene que ver con un "feature" de xtext que hace que no agregue o remueva los errores que se producen en otro archivo más que el que se está modificando. Lo que no pude reproducir es que los tests dejen de correr, ya que al correrlos se vuelve a leer todo el código, por lo que no debería haber problemas.

Estoy viendo como hacer para que procese todos los errores de todos los archivos, pero esto puede tener una penalidad en performance, ya que para eso debe correr el validator sobre todos los archivos (aunque... ahora tengo la teoría de que lo hace igual).
