### ISSUE TITLE
"XtextReconcilerJob" ha encontrado un problema. 

### ISSUE THREAD

**Issue by GuillermoSBR** [uqbar-project/wollok#1295]
Cuando creo un nuevo test sale este error cada vez que escribo o borro un caracter en el describe del mismo. 
![1ae4a1f89f978b305d3b544bc353d245](https://user-images.githubusercontent.com/22582075/31866927-aeaf4d66-b75c-11e7-99cc-ddc0461452d9.png)

**Comment by fdodino** [comment]
Hola , para poder reproducir el problema necesitaría que nos pases un repositorio con el proyecto completo, muchas gracias!

**Comment by fdodino** [comment]
Cerramos el incidente. Podemos reabrirlo cuando haya más información.
