### ISSUE TITLE
Wollok Game: add Ticker for timing

### ISSUE THREAD

**Issue by BrianCraig** [uqbar-project/wollok#1296]
Hi!

I was trying to use wollok game but, i feel the necesity for using a ticker system, for doing something each frame. I was thinking on trying to do a pong example for learning the library, but i don't know how to manage to move the ball consistently without relying on user input binds.

A simple interface that could resolve this would be:
`object game {
  method onTick(aBlock)
}`
and when the game is running (between start and end messages), the game would apply the block given each frame.

What do you think of this?

Brian.

**Comment by PalumboN** [comment]
Hola Brian!

Gracias por el aporte. Sí, ya hay varios pidiendo este feature y seguramente lo agreguemos en la próxima versión.

Más allá de eso: ¿Para qué necesitás ese método? ¿Qué estás queriendo hacer?
Tal vez podamos buscar un workaround mientras.

**Comment by fdodino** [comment]
Bueno, agregué un método nuevo onTick(milliseconds, action), que te permite correr un bloque cada n milisegundos. Se agrega como listener del board, así que podés tener la cantidad de "ticks"que quieras a distintos intervalos. Les dejo una demo
![anim.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e99a932ec0cfeb9ffbb049a15ee4d6730472267a53a52e7687b570be107f075a094eac135d5816f5a89b37b4f46d2ede0356b49b381d66cc2f10a5b2831abc02bc278d4887bfb5824cd2a5.gif)

**Comment by fdodino** [comment]
Incluso le agregué un control de errores para que si dentro del bloque ocurre un error lo avise alguno de los componentes del juego:

![image](https://user-images.githubusercontent.com/4549002/43803796-331bdf8c-9a70-11e8-87c7-05a4ec313e85.png)

**Comment by npasserini** [comment]
Muy bueno!

Il giorno mar 7 ago 2018 alle ore 18:32 Fernando Dodino <
notifications@github.com> ha scritto:
