### ISSUE TITLE
Cambiar void[] doesNotUnderstand por "te olvidaste un return"

### ISSUE THREAD

**Issue by gabriell24** [uqbar-project/wollok#1298]
Cuando tenès una variable que no tiene un tipo inferido y le mandàs un mensaje, que en tiempo de ejecución resuelve bien pero no tiene return como deberìa, dice void no entiende un mensaje...

**Comment by fdodino** [comment]
hola @gabriel24, ¿podrías pasarnos un ejemplo concreto para poderlo incorporar a los tests? Un repo con el ejemplo o bien el código para poderlo reproducir y corregirlo.
Muchas gracias.

**Comment by gabriell24** [comment]
Hola Fernando, te comento que el issue lo subió un docente.
Te dejo el repo donde se puede ver: https://github.com/gabriell24/EjemploAusenciaReturn.git
Saludos!

**Comment by fdodino** [comment]
¡Muchas gracias Gabriel!
Acabo de subirlo a https://github.com/wollok/issue1298 donde lo vamos a revisar (de acá al próximo cuatrimestre).

**Comment by fdodino** [comment]
Esto funciona si trabajamos con wko (hay un validator).

Marcar el error "te olvidaste un return" no es 100% exacto, lo que voy a hacer es cambiar el mensaje de error del validator e incorporarlo a una clase:

![issue1298.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e187893687d2fbd6b1fd0fe64de29b234324676b5ee17e25d6b42eba447957570e4cf8175d0944fcab8c2cf4bf6d62964e49bc8f3900299f7744eeaa880dbe06b0218e4d84b3bb824dc6ed3a23e099c2.png)
