### ISSUE TITLE
It would be nice to put the focus on the REPL when it starts.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#13]

**Comment by npasserini** [comment]
Che, esto a mí no me anda, ¿cómo lo puedo verificar?

**Comment by tesonep** [comment]
Que buena pregunta, deberia estar andando. En master o en dev lo probaste?


On Sun, Aug 9, 2015 at 6:04 PM, Nico Passerini <notifications@github.com>
wrote:

> Che, esto a mí no me anda, ¿cómo lo puedo verificar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uqbar-project/wollok/issues/13#issuecomment-129240324>
> .
>



-- 
Pablo Tesone.
tesonep@gmail.com

**Comment by npasserini** [comment]
En dev.

**Comment by javierfernandes** [comment]
Creo que a mí tampoco.
