### ISSUE TITLE
Problemas en el debugger

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1300]
Tratando de debuggear un test que fallaba, ni bien entra en el breakpoint tira
![image](https://user-images.githubusercontent.com/715971/32118570-8614352c-bb28-11e7-832a-175d76ad979e.png)

Lo cual parece que puede ignorarse y seguir avanzando.

Luego, si le llegás a hacer un into a un método de assert, saltan estos otros problemas:

![image](https://user-images.githubusercontent.com/715971/32118711-101dde76-bb29-11e7-9e38-c1a37cb00a42.png)

**Comment by fdodino** [comment]
El debugger no está funcionando. 
Hay que conseguir un sponsor para que tome el tema. Por el momento con @npasserini coincidimos en que no forma parte del roadmap del 2018.

**Comment by fdodino** [comment]
Ya que hay abiertos muchos otros issues sobre el debugger, cierro éste con la esperanza de algún día retomarlo
