### ISSUE TITLE
Should num.div(0) fail?

### ISSUE THREAD

**Issue by marcodicro** [uqbar-project/wollok#1304]
I was trying this in the REPL with some students

>>> 0.div(0)
0
>>> 2.div(0)
2147483647
>>> 1.div(0)
2147483647
>>> 3.div(0)
2147483647
>>> 4.div(0)
2147483647

Is this the normal behavior? Because we were waiting for an exception.

Thanks!

**Comment by fdodino** [comment]
This can be done when developing unification between Decimal and Integer into Number.
