### ISSUE TITLE
Mutating a position does not move a visual object

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1307]
If an object knows its position and this position is mutated, the visual representation does not update. 
Example:
```
object pepita { 
  const position = new Position(2,3)
  method moveUp() { position.moveUp(1) }
}
```

**Comment by PalumboN** [comment]
Are you adding to the game with `game.addVisual(pepita)`?

It's working for me!

**Comment by npasserini** [comment]
I thought this was the bug you talked about in the class. Probably I
misunderstood.

2017-11-14 10:35 GMT-03:00 Nahuel Palumbo <notifications@github.com>:

**Comment by PalumboN** [comment]
Ahahhh capaz que fue cuando WG se tildó desde el REPL: ya había un issue con eso que lo estuvieron resolviendo Fer y alguien más. 
Lograron solucionar algo, pero al parecer hay casos en los que aún se tilda.

**Comment by PalumboN** [comment]
Ok, this still happens using wollok game from REPL. 
You can prove executing `pepita.moveUp()` many times until the program broke and the REPL doesn't respond.
I suspect it's a concurrency common problem en Wollok Game, we should continue investigating.

**Comment by PalumboN** [comment]
Here other program from UTN students with the same problem when adds new objects on gameboard: https://github.com/matigiorda/TaTeTiWollokGame

**Comment by fdodino** [comment]
I tested (a lot) and I didn't experience this problem. I'll close this issue until it happens again.
