### ISSUE TITLE
The collition block could receive old/new positions of the collitioner object

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1308]
By receiving positions, the collitionee object can implement "go back" features more easily and avoid objects like "ArbustoIzquierda", "ArbustoDerecha", ext as in farmville.

**Comment by PalumboN** [comment]
Yes, I was thinking that we can add a `direction` element. So any object can go back / forward. 

Something like this is implemented here: https://github.com/wollok/sokoban-game.

**Comment by PalumboN** [comment]
Or we can have inmutable positions that knows its previous state https://github.com/uqbar-project/wollok/issues/1318

**Comment by fdodino** [comment]
Related to #1318

**Comment by fdodino** [comment]
Proposals for new Wollok Game TS maybe?

**Comment by PalumboN** [comment]
El saber la posición anterior es algo que ahora se no se está guardando en ningún lado. Faltaría una propuesta para ver cómo manejar esto.

#### Habría que ver si queremos resolver este issue o buscar un propuesta para manejar "objetos bloqueadores" como las paredes, desde el propio game, ó si es algo interesante para que resuelvan los estudiantes mismos.

Cierro esto por ahora.
