### ISSUE TITLE
Apply empty closure return null

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1317]
```xtend
>>> {}.apply()
null
>>> { pepita.vola() }.apply()
>>> 
```

**Comment by PalumboN** [comment]
Related to https://github.com/uqbar-project/wollok/issues/845

**Comment by fdodino** [comment]
I added an if, so if return value is null nothing is printed.
I think there are very few examples where this happened.
For a complete solution, we must implement "Nothing wko" previously discussed. 

See @PalumboN @npasserini 

![anim](https://user-images.githubusercontent.com/4549002/37174752-4771e748-22f6-11e8-85d2-f07cde213c50.gif)

**Comment by fdodino** [comment]
Changed implementation in PR for closures, so a null in REPL console is still printed.
