### ISSUE TITLE
assert.equals hell

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1321]
This year one student make a test like this:
```xtend
test "testX" {
	assert.equals(obj.mensajeBooleano())
}
```
That **always runs green** even when mensajeBooleano was false.

Of course, the problem is that he was using `assert.equals` instead of `assert.that`. And that happens because exist `assert.equals(obj)` (from object) and `assert.equals(obj1, obj2)` (for testing).

Maybe we can override `assert.equals(obj)` (from object) with an exception for avoid this kind of problems.

**Comment by PalumboN** [comment]
Related with https://github.com/uqbar-project/wollok/issues/1235
It's other (better) option!

**Comment by javierfernandes** [comment]
This should also raise a validator error (warning)

```
assert.equals(obj.mensajeBooleano())
```

Because you are generating a value that is not being used / assigned.
`Object.equals(o)` is a method that returns a value, and here no one is using it.

Instead `assert.equals(a, b)` should be void, because it throws exception.

That difference should at least give a clue that the guy is using the incorrect method.

**Comment by PalumboN** [comment]
Yes, with the TS should be easy detect that cases (when the returned value is not used). 
I wanted to think a help for this particular case, but maybe with the TS (and the Fer's issue) we are ok.

**Comment by faloi** [comment]
+1 para esto (y gracias GitHub related issues por la sugerencia).

Me acaba de pasar en la corrección de un parcial. ¿Alguna chance de que sea solucionado?

**Comment by fdodino** [comment]
sí, estamos retomando los issues @faloi, recientemente, pongo el issue como major para que tenga prioridad ya que es fácil manquearla y es fácil solucionarlo.

**Comment by faloi** [comment]
Crease o no, hoy volví a encontrar este error en una entrega de TP. Qué bueno que la próxima ya lo va a atajar Travis. :smile:
