### ISSUE TITLE
REPL doesn't work on MacOS HighSierra

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#1324]
# Environment:
JDK: 1.8.0_20
MacOS High Sierra: 10.13.2
Wollok Freire 1.6

# Steps

* Download latest wollok package for MacOS (1.6 Freire)
* Open a terminal and run  `Wollok.app/Contents/MacOS/wollok`
* "New Wollok Project", give it a name.
* Open the autogenerated wlk file
* Right-click "Run as.. Launch with RPL"

You will see that the console is blank and when you type characters are not visibles.
If you switch the console to show the "underlying java process" you will see there wollok's output. 

![image](https://user-images.githubusercontent.com/4428120/34613190-a76d97ee-f20b-11e7-8829-0c091efa4f45.png)

In the background there are SWT errors

**Comment by cervecero** [comment]
Hi, I got same issue. 

**Environment:**
JDK: 1.8.0_172
MacOS High Sierra: 10.13.4
Wollok Freire 1.6

Is there any workaround to fix this?

**Comment by npasserini** [comment]
I think that updating to the last Wollok 1.6.5 should solve this, please
let me know.

2018-05-22 18:54 GMT-03:00 Fede <notifications@github.com>:

**Comment by cervecero** [comment]
Hi Nico, I've just download wollok from http://www.wollok.org/instalacion/ and its version is 1.6 Freire.  Where I can find the last release of Wollok?.

**Comment by sanuzzi** [comment]
A mí me anda la consola pero no se me ve. Como si el texto tuviese color blanco.

![image](https://user-images.githubusercontent.com/1631264/43038496-fd18ec50-8cef-11e8-8b36-0a8e35604b51.png)

![image](https://user-images.githubusercontent.com/1631264/43038500-14b2b7e2-8cf0-11e8-8d79-3ec0bdaea24a.png)

Es urgente este tema, sin esto se van a dificultar mucho las primeras clases

**Comment by npasserini** [comment]
@Fernando Dodino <fernando.dodino@gmail.com> recuerdo que estuvimos
hablando de este tema, pero no veo que esté reportado como solucionado.
¿Será que está solucionado en dev-1.6 o nunca lo hicimos?

Il giorno sab 21 lug 2018 alle ore 14:12 sanuzzi <notifications@github.com>
ha scritto:

**Comment by fdodino** [comment]
No @npasserini , eso nunca lo solucionamos, es difícil porque no tengo una mac para probarlo, hay una clase que se encarga de los caracteres de escape para cada sistema operativo, habría que ver si alguno de los que tiene mac se copa para verlo.

**Comment by npasserini** [comment]
Vamos a pedirle ayuda a @Débora Fortini <deborafortini@gmail.com>

Il giorno mer 25 lug 2018 alle ore 07:21 Fernando Dodino <
notifications@github.com> ha scritto:

**Comment by fdodino** [comment]
Dale, si le instalás el ambiente de desarrollo Wollok nos juntamos un día y lo vemos.

**Comment by fdodino** [comment]
El error viene de la mano de [este otro issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525465). Es un poco críptico ObjectiveC, pero ahora entendí que es un DNU (Does not understand), ya que no existe el método attachment para la clase SWTTextAttachmentCell.

Una de las clases de SWT que usa el SWTTextAttachmentCell es TextLayout y tiene [este fix](https://bugs.eclipse.org/bugs/attachment.cgi?id=162103).

El problema puntual en Wollok se da en esta línea de la clase WollokAnsiColorLineStyleListener:

```xtend
	def void addRange(List<StyleRange> ranges, int start, int length, StyleRange defStyle, boolean isCode) {
            ...
            // FIXME: MAC // puede ser esto lo que reviente
            if (showEscapeCodes || isOsMac)
                range.font = new Font(null, "Monospaced", 6, SWT.NORMAL)
            else
                range.metrics = new GlyphMetrics(0, 0, 0)
            // fin FIXME
        }
        ....
    }
```

En particular estoy casi seguro de que la línea range.metrics es la que termina causando el error, no tengo una Mac para cerrarlo pero estoy armando un branch para probarlo mañana en la máquina de Deby. 

Sí hemos visto que si en la clase WollokReplConsolePageParticipant eliminamos este listener:

```xtend
	override init(IPageBookViewPage page, IConsole console) {
		this.page = page
		if (page.control instanceof StyledText) {
            viewer = page.control as StyledText
            
            #[ new WollokAnsiColorLineStyleListener, // este listener
            	new WollokCodeHighLightLineStyleListener, new WollokStyleRangeListener(viewer)
            ].forEach[
            	viewer.addLineStyleListener(it)
            	listeners += it	
            ]
        }
```

la consola vuelve a funcionar, aunque con los caracteres de escape feos, que hay que inhabilitar en la clase WollokLauncher:

```xtend
	override doSomething(WFile parsed, Injector injector, File mainFile, WollokLauncherParameters parameters) {
		try {
			val interpreter = injector.getInstance(WollokInterpreter)
			val debugger = createDebugger(interpreter, parameters)
			interpreter.setDebugger(debugger)

			log.debug("Interpreting: " + mainFile.absolutePath)
			interpreter.interpret(parsed)
	
			if (parameters.hasRepl) {
				val formatter = if (parameters.noAnsiFormat) new RegularReplOutputFormatter else new AnsiColoredReplOutputFormatter
				// FIXME: Issue #
				// TODO 1: Preguntar si es MAC
				// TODO 2: Pasarlo a una configuración de Wollok
				// val formatter = new RegularReplOutputFormatter
				new WollokRepl(this, injector, interpreter, mainFile, parsed, formatter).startRepl
			}
```

Pero no hace falta usar el RegularReplOutputFormatter (que perdería los colores para lo que retorna la consola: errores, strings, números y mensajes de bienvenidas, solo se colorearía lo que escribe el usuario), basta con hacer la prueba de no llamar a Glyphmetrics por el momento.

**Comment by fdodino** [comment]
@dfortini @npasserini dejé un branch para probar: fix-#1324-repl-console-mac

Revisando un poco más la documentación efectivamente StyleRange hereda de TextStyle que justamente tiene un TextLayout que es el que está causando este problema. Otra opción a futuro sería subir la versión de SWT, pero faltando tan poco para que arranque el cuatrimestre me parece muy arriesgado ir por esa opción.
