### ISSUE TITLE
Autocomplete should consider properties too

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1325]
If you define a wko and want to use autocomplete, properties don't appear in autocomplete window:

![ezgif com-optimize](https://user-images.githubusercontent.com/4549002/35351936-399de532-0121-11e8-8d9d-06380885776e.gif)

**Comment by fdodino** [comment]
![anim](https://user-images.githubusercontent.com/4549002/44054084-05064018-9f18-11e8-9a1f-c86ed08c0666.gif)

**Comment by PalumboN** [comment]
Puede que esto se haya roto en la nueva versión?
![Peek 2019-08-01 06-03](https://user-images.githubusercontent.com/4098184/62280382-2b4f0f00-b422-11e9-827b-ae9abac176eb.gif)

 https://github.com/uqbar-project/wollok/issues/1561

**Comment by fdodino** [comment]
Técnicamente es otro issue :smile: , funciona si el type system no está activado, pero cuando el type system está activado no reconoce las properties...

**Comment by fdodino** [comment]
Ahí le metí un hackazo, no me gusta mucho el código pero técnicamente estamos tomando variable declarations en lugar de method declarations, así que por ahora está bien... hay que tratar de armar los tests como dice el #1561 porque es difícil saber si anda bien con el TS, sin el TS, con literales, con variables, con self, pegándole a una expresión, etc.

Esta noche creo el PR.

**Comment by fdodino** [comment]
Aaaaaaaagh

**Comment by fdodino** [comment]
El aggggh de recién fue la bronca de no haberlo testeado con el type system activado. En ese caso, no funciona el autocomplete de un `const property` (sí el `var property`). Así que lo vuelvo a abrir y en la semana lo veré... :angry:

**Comment by npasserini** [comment]
@fdodino Veo este issue abierto pero asociado a un milestone viejo. Me das una mano para confirmar si está resuelto o no?

**Comment by fdodino** [comment]
Sí, confirmo que está en producción. Se cierra!
