### ISSUE TITLE
Detect wrong uses of conditionals and issue warning.

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#133]
if(cond)
return true 
else return false

should raise a warning, or even an error if a flag is set in configuration (strict mode or something like that)

**Comment by javierfernandes** [comment]
<img width="242" alt="screen shot 2015-07-06 at 09 12 31" src="https://cloud.githubusercontent.com/assets/4428120/8521919/426df91e-23bf-11e5-9598-95866221a7e5.png">
