### ISSUE TITLE
Change times method in Number to use a closure with one argument.

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1344]
Now it is optional, but it should enforce one argument (a Number).
This requires special treatment for closures, since defining

```
	Number >> "times" === #[closure(#[Number], Any)] => Void;
```

in WollokCoreTypeDeclarations breaks this test:

```xtend
        // XPECT methodType at m27 --> (Number) => Void
	method m27(a) {
		var b = 0
		a.times({ i => b = i })
	}
```
_numbers.wlk.xt_

(instead of  Number type for first argument, it points to Any)

That is because parameters in closure doesn't match. If you leave declaration empty:

```
	Number >> "times" === #[closure(#[], Any)] => Void;
```

it works because parameters are empty and you don't really compare argument types of closure.

**Comment by PalumboN** [comment]
Esto ya está implementado en dev:
https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.lib/src/wollok/lang.wlk#L1763

https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/NumberTypeDeclarations.xtend#L41

Cierro el issue
