### ISSUE TITLE
OpenConstructor inference strategy

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1346]
When a constructor call is found in the code, it should be processed in a similar way as it is done for methods. We need a new strategy for that.

**Comment by fdodino** [comment]
Related test:

```xtend
	// XPECT methodType at m2 --> (Number) => Date
	method m2(day) = new Date(day, day, 2018)
```
_dates.wlk.xt_

OpenConstructor inference strategy should notice this definition

```xtend
		Date.constructor(Number, Number, Number)
```

leads us to pass this expectation.
