### ISSUE TITLE
Assignments, postfix operations and variable declarations return assigned value

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1354]
Since it is a void operation, it shouldn't return the assigned value.

Problem is in interpreter

```xtend
def dispatch WollokObject evaluate(WAssignment a) {
	val newValue = a.value.eval
	interpreter.currentContext.setReference(a.feature.ref.name, newValue)
	newValue
}
```

Also for WPostfixOperation and WVariableDeclaration...

**Comment by lspigariol** [comment]
Entiendo que el objetivo es no poder hacer cosas como por ejemplo 
p = x++

lo que vi que pasa es esto (copio secuencia del REPL)

>>> var x = 0
>>> var p = x++
>>> p
>>> p++
wollok.lang.Exception: El mensaje "self" no retorna ningún valor (quizás te falte un return en el método)
   at wollok.lang.Object.messageNotUnderstood(messageName,parameters) (classpath:/wollok/lang.wlk:213)
>>> p + 1
wollok.lang.Exception: El mensaje "p" no retorna ningún valor (quizás te falte un return en el método)
>>> 

Algo similar ocurre con 
>>> p = (x = x + 1)

y con 
>>> (x = 1) > 5
wollok.lang.Exception: El mensaje "(x = 1)" no retorna ningún valor (quizás te falte un return en el método)

**Comment by fdodino** [comment]
Verifyied agains Wollok 1.6.7
Closing
