### ISSUE TITLE
Javascript Prototype

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#136]
- https://github.com/zaach/jison
- http://pegjs.org
- https://github.com/antlr/antlr4-javascript

**Comment by fdodino** [comment]
Pablo today found:
http://www.eclipse.org/Xtext/documentation/330_web_support.html

**Comment by flbulgarelli** [comment]
Hi!

I recommend using the technology @AlvarezAriel developed for gobstones web: https://github.com/gobstones/gobstones-web. 

It has native integration with ACE, and it will have native integration with some aspects of mumuki. Actually, the gobstones and mumuki team are integrated by the same people. 

I actually started a wollok propotype in it a month ago. It will be nice if wollok project uses the same stack.

**Comment by npasserini** [comment]
@javierfernandes @nscarcella @nnydjesus Does this issue make sense?

**Comment by fdodino** [comment]
Closing this issue since we already have Ronny & NicoS approaches.
