### ISSUE TITLE
Renames

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1364]
ClassBasedWollokType => ClassType
ObjectBasedWollokType => ObjectType

**Comment by npasserini** [comment]
@fdodino @PalumboN Do you agree with this change?

**Comment by fdodino** [comment]
Ok for me (I'm still a newbie but it sounds a better name)

**Comment by PalumboN** [comment]
:+1:

**Comment by fdodino** [comment]
We now have ObjectLiteralWollokType and NamedObjectWollokType, maybe we can rename it to ClassWollokType instead of ClassType. Do you agree @npasserini ?

**Comment by npasserini** [comment]
What if we instead remove the Wollok from the other two?


Il giorno gio 19 lug 2018 alle ore 12:31 Fernando Dodino <
notifications@github.com> ha scritto:

**Comment by npasserini** [comment]
Great. But don't do it right now because it will be a nightmare to merge.

Il giorno gio 19 lug 2018 alle ore 14:28 Fernando Dodino <
notifications@github.com> ha scritto:

**Comment by fdodino** [comment]
relax, I'm struggling with #1264 right now
