### ISSUE TITLE
Casos de mensaje a null para los que el reporte de errores actual es subóptimo

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1366]
En este programa, el reporte de error que obtenemos
```
>>> "hola".equalsIgnoreCase(null)
wollok.lang.Exception: Reference aString is not initialized
   at wollok.lang.String.equalsIgnoreCase(aString) (classpath:/wollok/lang.wlk:1387)
>>> 
```
El alumno puede decir ¿de dónde sale aString? 
Una opción es usar un mensaje un poco más abstracto, teniendo en cuenta que el receptor podría ser un parámetro y entonces la falta de inicialización está en otro lado. O podría ser el resultado de un envío de mensaje y lo mismo. 
Otra es hacer que el código del core que necesita cosas no-nulas, las chequee y las reporte claramente. Creo que ya hay varios lugares donde se hace eso.

**Comment by fdodino** [comment]
+1 a que el código core chequee los parámetros cuando no pueden ser nulos o deban ser de algún tipo

**Comment by fdodino** [comment]
Hay que buscar todos los lugares donde vamos a utilizar al parámetro y mandarle un mensaje, y previamente hacer el chequeo (podríamos tener un mensaje en Object en lugar del nativo aunque eso no lo haga i18n)

**Comment by fdodino** [comment]
Esto es lo que relevé

String
======
X equalsIgnoreCase
<=
>=
X charAt
<
>
split(null)
take(null)
drop(null)

Object
======
>>> pepita.resolve(null)
wollok.lang.Exception: Couldn't resolve reference to

Collection
==========
max(null)
maxIfEmpty(null, null)
min(null)
minIfEmpty(null, null)
addAll(null)
removeAll(null)
forEach(null)
any(null)
all(null)

findOrElse ==> es nativo arreglar
count(null)
sum(null)
map(null)
flatMap(null)
filter(null)
sortBy ==> nativo arreglar

Set
===
join ==> nativo arreglar
equals ==> nativo arreglar

List
====
get ==> nativo arreglar
sublist(null, null)
take(null)
drop(null)
join ==> nativo arreglar
equals ==> nativo arreglar

Number
======
..null
limitBetween(null, null)
rem(null)

Boolean
=======
b.and(null) tira error
b.or(null) tira error "true does not understand null"

Range
=====
step ==> no permitir null
forEach ==> tira error wollok.lang.Exception: null nativo arreglar
map ==> wollok.lang.Exception: Unhandled parameter types: [null]
flatMap ==> wollok.lang.Exception: Unhandled parameter types: [null]
fold ==> wollok.lang.Exception: Unhandled parameter types: [null]
any, all y filter lo mismo
   TODO SE ARREGLA si asList() tira error
   Pero vuelve a tirar Reference closure is not initialized ==> arreglar Collection

assert
======
that(null)
notThat(null)
throwsException => agregar
throwsExceptionLike
throwsExceptionWithMessage
throwsExceptionWithType
throwsExceptionByComparing

StringPrinter
=============
println

Faltaría ver Game, Mirror y VM

**Comment by fdodino** [comment]
En todos esos casos 

- en Wollok hay que verificar el parámetro con un método checkNotNull que recibe el parámetro a chequear y el mensaje donde estamos
- en Java tenemos un checkNotNull en AbstractJavaWrapper, no tenemos una jerarquía única para objetos nativos pero puede ir a parar a un extension method

Intenté cambiar el mensaje de error del intérprete mostrando el mensaje en lugar del nombre del parámetro pero eso no cubre el issue bien, porque si estás en un método interno te muestra que el "+" no entiende null y vos estás mandando otro mensaje...
