### ISSUE TITLE
Capturar errores del intérprete al ejecutar programas o en la consola REPL

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1379]
A partir de la versión 1.6.5, los tests atrapan errores del intérprete y muestran el mensaje de error evitando el stack trace completo que se imprimía antes en el label del mensaje de error.

Falta hacer eso para los mensajes de error del intérprete (WollokInterpreterError.originalCause) en programas y consola REPL:

(repasando el issue #690)
![error690.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46ed86882c90d5f0dfabf301b44fff9e2c4533317346f67e23d2e52db9402d590e5d1afa440e5f44aefc8e79afe72e6c981e5ab38532022d8c6853beb2901eb60bbb25894c87b2bd8e4cc2e83921f5c6.png)

**Comment by Juancete** [comment]
Estoy trabajando en el Issue para la consola en primer lugar, logré reutilizar el código de WollokExceptionUtils utilzado para los test. El problema es que solo puedo arrojar el error del interpreter, pero cuando intento arrojar el archivo y línea me arroja del syntetic file que utiliza el REPL, al igual que su nro de línea. 

Veo que originalCause  da un Throwable, cosa que no tiene ni línea ni URL, es correcto? 

![screenshot from 2018-09-03 14-57-38](https://user-images.githubusercontent.com/1617224/45000448-583d3c80-af9b-11e8-95d9-6664fd2b2c77.png)

Por ahora estoy buscando como llegar al lugar donde tratar el problema para el Wollok Program. Si alguien tiene algún tipo donde encontrarlo es bienvenido.

**Comment by Juancete** [comment]
Bueno, terminé encontrando que hay una clase WollokInterpreterConsole en project.wollok. El tema es que tengo que utilizar la lógica que se creó para los test y se encuentra en otro proyecto. 
![screenshot from 2018-09-03 22-28-11](https://user-images.githubusercontent.com/1617224/45005321-0e6b4b00-afc9-11e8-8ea3-ebe95379966d.png)
Ahora el problema es que no tiene sentido importar desde el manifest wollok.launcher, sino que la lógica que se creó para los test (WollokExceptionUtils), no debería encontrarse el project.wollok? de hecho que diferencia hay con WollokExceptionExtensions de project wollok @fdodino ?

**Comment by fdodino** [comment]
Hay un WollokExceptionExtensions en el proyecto Wollok, ése podés utilizar. Por otra parte me llama la atención que no tengas el stack trace filtrado, que debería recuperarte la info que estás buscando. En WollokRepl lo tenés:

```xtend
	def dispatch void handleException(Throwable e) {
		println(e.stackTraceAsString.errorStyle)
	}

	def dispatch void handleException(WollokProgramExceptionWrapper e) {
		// Wollok-level user exception
		println((e.exceptionClassName + ": " + e.wollokMessage).errorStyle)
		val errorLine = e.wollokException
			.convertStackTrace
			.toList
			.map [ stackDTO | stackDTO.toLinkForConsole ]
			.join(System.lineSeparator)
		
		if (errorLine !== null && !errorLine.equals("")) {
			printlnIdent(errorLine.errorStyle)
		}
	}

	def dispatch void handleException(WollokInterpreterException e) {
		if (e.lineNumber > numberOfLinesBefore) {
			printlnIdent('''«WVM_ERROR» («e.lineNumber - numberOfLinesBefore»): «e.nodeText»:'''.errorStyle)
		}

		if (e.cause !== null) {
			indent
			handleException(e.cause)
		}
	}
```
