### ISSUE TITLE
Mensaje put en Dictionary retorna null

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1385]
y lo muestra en el Repl

**Comment by fdodino** [comment]
De paso, cambié el toString() para que se muestren los valores
![dictionary1385.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46ec9d99378b8ca78efba612f705a5d665043761260ea62864c7b96aea172856090a18fe47500e46a8af8c7da6b66e758d0e02bcc3714d36976345f3e5db55ea43a82a994e82bcbd8f4ec4e93b20e78e8b4b361d1755.png)

**Comment by npasserini** [comment]
Me gusta lo del toString.
Me pregunto si no podríamos
a) pensar en un literal de diccionario
b) más allá de que implementemos ese literal ahora o no, hacer que el toString devuelva lo mismo que el literal.

**Comment by lspigariol** [comment]
+1 a buscar un literal
%[ ] 
&[ ]
$[ ]

De paso, seria practico generalizar y que los sets sean  #[ ]  (o que conviva con el actual)
(Los rangos, o eventuales futuros iterables tambien podrian tener un chirimbolo antes del [ ] )
