### ISSUE TITLE
Tab order in "new object/class" pop-up window

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1390]
I guess that the popup order is not correct in the window that pop-ups when choosing to add a source file (Ctrl-N from the package explorer), and then (in Spanish) "Objetos y clases Wollok".
The tab order is 
  1. Object/class selection
  2. Folder
  3. File name
  4. Object/class name
I guess that Object/class selection should go after Folder, to mantain coherence with the up/down order of the control in the popup.

**Comment by lspigariol** [comment]
hice un comentario al respecto en #1394 

ademas, es sutil, pero se podria cambiar el titulo de la ventana por uno mas generico. (codigo wollok o algo así) 
de hecho, se pueden definir tambien mixins
cuando se trabaja solo con objetos, todo lo que diga "clases" no ayuda.

**Comment by fdodino** [comment]
Lo pongo en la columna 'Discuss" para ver cómo rearmamos los wizards New...

**Comment by fdodino** [comment]
En un cónclave definimos:

- reemplazar "New objects and classes" por "New Wollok File" | "Nuevo archivo de Wollok"
- reemplazar radio button por un combo, y que el default sea Object (luego Class y agregamos mixin)
