### ISSUE TITLE
Do not include package name when choosing a class from the typing assistant

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1391]
Let us suppose that I am writing a Wollok test file to test the class Vaca, which is included in the animales.wlk file.
At the beginning of the test file, I include the "import" directive.
import animales.*

Then, I want to create an instance of the Vaca (in fact animales.Vaca) class. I type
     const aurora = new Vac
and then I press Ctrl-Space. The first option in the popup frame that appears is "Vaca - animales.Vaca", as expected. When I choose that option, the source line turns into
     const aurora = new animales.Vaca
That is, the name of the package is included, even when I explicitly included the import directive before starting to type the tests.
 
I guess that at least in that case, the (redundant) package name should not be included.
Moreover, it would be nice that if the import directive is not present, Wollok could at least give the user the possibility of either add the import directive or prepend the class name with the package name. I guess that Eclipse for Java Developers just includes the import directive.

**Comment by fdodino** [comment]
Closing since #1417 has a better explanation.
