### ISSUE TITLE
Al crear un archivo con el asistente, puede hacerlo desde un source folder o desde un proyecto

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1393]
En sí ese comportamiento es correcto, pero al haber un source folder en el proyecto, eso termina generando este tipo de proyectos:

![image](https://user-images.githubusercontent.com/4549002/39066901-1fb16dd6-44ad-11e8-86cb-a94980b5ac46.png)

Los archivos wlk funcionan en el REPL y probé también un test aislado, pero cuando uno quiere hacer imports la cosa se complica. Hemos hablado con @npasserini respecto a eliminar la carpeta source folder, pero por el momento yo preferiría que el asistente de Wollok hiciera lo mismo que el de Eclipse para Java, que si te parás en el proyecto te lo quiera guardar en el primer source folder que exista.

De esa manera evitamos que los alumnos generen una estructura que después cause problemas en su uso.

**Comment by lspigariol** [comment]
Lo puse en el otro issue, por mi ok con que no este la carpeta src.
