### ISSUE TITLE
Remove initialize from Date

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1395]
Date class has an initialize method that makes Dates mutable and I think it is not necessary.

Currently it is only used for the constructor
```
	/**
	 * Constructor: you should pass the day, month and year (integer values only).
	 */
	constructor(_day, _month, _year) { self.initialize(_day, _month, _year) }
```

Is it possible to remove it and make the constructor native instead of the initialize method?

**Comment by lspigariol** [comment]
si, me parece mas consistente que las fechas no sean mutables. 
si se quisieran fechas (numeros u otros tipos) mutables, se podrian agregar otras clases nuevas

**Comment by fdodino** [comment]
Me lo había anotado para hacer pero eso requiere un refactor de Date, lo que no es tan sencillo. Esto ocurre porque la clase Date no tiene como variables el día, mes y año, habría que generarlas y después todas las operaciones nativas deberían utilizar esos valores. Lo dejo para más adelante.
