### ISSUE TITLE
SCM for packaging and publish Sublime extensions

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#140]
https://github.com/uqbar-project/wollok-sublime

We need to research if there's some kind of conventions for packaging all the different sublime extensions for wollok: sintax, completion, checker.

**Comment by javierfernandes** [comment]
@tesonep & @npasserini   this is marked as "ready"
what does that means ?

I haven't noticed this and followed Sublime Package Manager instructions to publish a new package as stated here https://packagecontrol.io/docs/submitting_a_package

I've create a PR here
https://github.com/wbond/package_control_channel/pull/4622

Waiting to hear from them

**Comment by npasserini** [comment]
I think it is marked as ready just because it was selected to the next
release.

**Comment by fdodino** [comment]
Closing it . We'll have to rethink for next generation IDE (and maybe @npasserini already has a syntax coloring for VSC, maybe we just need to publish it somewhere in the site)
