### ISSUE TITLE
Wollok permite crear archivos con ñ

### ISSUE THREAD

**Issue by javiemgz** [uqbar-project/wollok#1400]
![error](https://user-images.githubusercontent.com/37852313/39388496-a163636a-4a80-11e8-8138-ab4e86ce7348.PNG)

**Comment by npasserini** [comment]
No deberían poder crearse archivos con ñ.

**Comment by fdodino** [comment]
Es relativamente fácil de lograr, hay un método dialogChanged en la clase AbstractNewWollokFileWizardPage de la que heredan todos los wizards New Test, New Describe, New Program y New Objects and Classes. 
Habría que eliminar todos los caracteres que no sean ASCII.
