### ISSUE TITLE
¿Validación innecesaria?

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1405]
Laburando con #1402 encontré este método en WMethodContainerExtensions que me parece que hace validaciones de más que confunden un poco. 

```
	// all calls to 'this' are valid in mixins
	//	def static dispatch boolean isValidCall(WMixin it, WMemberFeatureCall call) { true }
	def static boolean isValidCall(WMethodContainer c, WMemberFeatureCall call) {
		c.matchesProperty(call.feature, call.memberCallArguments.size) 
			|| c.allMethods.exists[isValidMessage(call)] 
			|| (c.parent !== null && !c.hasCyclicHierarchy && c.parent.isValidCall(call))
	}
```

La condición tiene 3 partes, en la segunda se chequea `allMethods` que incluye los heredados. En la siguiente se busca en el padre, lo cual es innecesario dado el chequeo anterior y probablemente incorrecto ya que no está teniendo encuenta mixins.

@fdodino algún motivo para no volar eso?

**Comment by fdodino** [comment]
@npasserini , paso en limpio lo que hablamos el sábado. No estoy seguro de haber escrito la validación entera, sí recuerdo el hasCyclicHierarchy que evitaba entrar en loop (por ahí la validación original tenía lo mismo menos el hasCyclicHierarchy). Yo probaría volar la tercera validación y correr los tests, dado que cosas como
 
```xtend
class A inherits B
class B inherits A

class C inherits C
```

ya tienen tests propios.

**Comment by fdodino** [comment]
Deberíamos volar la tercera parte y correr los tests.

**Comment by fdodino** [comment]
@npasserini , update: saqué la tercera validación y dieron error dos tests de wko que usan properties heredadas de una clase. Claro, si bien se valida allMethods en toda la jerarquía, no pasa eso con las properties. Voy a ver si lo refactorizo.
