### ISSUE TITLE
scope problem on "new" call with named paremeters: Duplicated name

### ISSUE THREAD

**Issue by lgassman** [uqbar-project/wollok#1407]
Using same name for variable produce a validation error on IDE. 
In this case I have an instance variable named 'golosina' in GolosinaBaniada class.
I want to make a test variable with same name, but I have 'Duplicated name' error.
 
```
describe "test de golosina baniada"{

	var golosina = new GolosinaBaniada(golosina=new Oblea())
...
```

**Comment by fdodino** [comment]
Maybe we did something in Wollok 1.6.7, but it works now.

![image](https://user-images.githubusercontent.com/4549002/43854551-935d6c5e-9b19-11e8-8b65-13668a439df9.png)

Closing until it appears again.

**Comment by npasserini** [comment]
Deberíamos probar en otros contextos además del describe.
Esto podría tener que ver con otra cosa que yo marqué hace un tiempo y es
que el initializer "define" una nueva variable, según la implementación
actual.
Si bien funciona, es un detalle de implementación que podría tener
consecuencias, como en este caso.

Il giorno mer 8 ago 2018 alle ore 14:45 Fernando Dodino <
notifications@github.com> ha scritto:
