### ISSUE TITLE
wollok IDE hangs when it's create a Class starting with a name of existent class 

### ISSUE THREAD

**Issue by lgassman** [uqbar-project/wollok#1408]
create a clase 'Bombon', use it.
After that, in the same wlk file, create a class 'BombonDuro'. 
May be you must to wait a moment between 'n' and 'D'. 
The IDE rebuild the project, and hangs it.

**Comment by fdodino** [comment]
Hi @lgassman !

Tested on Wollok 1.6.7 recent version and it works!

![anim](https://user-images.githubusercontent.com/4549002/43744676-77b6cff4-99b1-11e8-899f-3e8232947ea4.gif)

Maybe it is the new builder. Closing this issue (if it appears again we can reopen it)
