### ISSUE TITLE
Properties are not working with native implementations

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1411]
Now game object has native getters and setters implementations:
```js
game {
	method title(title) native
	method title() native
	
	method width(width) native
	method width() native

	method height(height) native
	method height() native
}
```
I tried to change them to properties but it's not working:
```js
game {
	var property title
	var property width
	var property height
}
```
And with `native` keyword throw errors

**Comment by fdodino** [comment]
Mmmm... if method is native then it can't be marked as a property. I'll put in Discuss list.

**Comment by fdodino** [comment]
Hola @PalumboN , qué opinión tenés después de un tiempo?
No termino de comprar la idea de tener property native, porque me parecen conceptos contrapuestos, pero espero tus palabras...

**Comment by PalumboN** [comment]
Yo te ayudo
