### ISSUE TITLE
Error when trying to install wollok plugin in eclipse because dependencies are broken

### ISSUE THREAD

**Issue by cervecero** [uqbar-project/wollok#1413]
**Environment:**
JDK: 1.8.0_172
MacOS High Sierra: 10.13.4
Wollok Freire 1.6

I was trying to install latest stable release of wollok but I couldn't do it, because dependencies are broken.

After downloading plugin from  http://update.uqbar.org/wollok/stable, Eclipse shows me the following error:

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: Wollok Language Feature 1.6.6 (org.uqbar.project.wollok.sdk.feature.group 1.6.6)
>   Missing requirement: Wollok's XSemantics TypeSystem 1.6.6 (org.uqbar.project.wollok.typeSystem.xsemantics 1.6.6) requires 'bundle it.xsemantics.runtime 1.11.0' but it could not be found
>   Cannot satisfy dependency:
>     From: Wollok Language Feature 1.6.6 (org.uqbar.project.wollok.sdk.feature.group 1.6.6)
>     To: org.uqbar.project.wollok.typeSystem.xsemantics [1.6.6]

![screen shot 2018-05-22 at 19 39 19](https://user-images.githubusercontent.com/2037497/40393985-eb403276-5df7-11e8-9178-c062af738e80.png)

**Comment by fdodino** [comment]
hola, estás tratando de correr un update de una versión anterior? Lamentablemente los repositorios cambiaron, así que no funciona pasar de una versión anterior de 1.6.6 a 1.6.6. Hoy acabo de instalar la versión 1.6.7 como update de la 1.6.6 en Linux y Windows y funciona correctamente, veremos hoy en la máquina de @dfortini que tiene Mac si funciona. Gracias igualmente por reportarlo!

**Comment by fdodino** [comment]
Confirmado, la versión 1.6.7 se puede instalar correctamente en Mac, Linux y Windows. Cerramos el issue.
