### ISSUE TITLE
Error de wollok al imprimir  error en los test

### ISSUE THREAD

**Issue by alexanderCifuentes** [uqbar-project/wollok#1414]
Estoy corriendo un test sobre colecciones, al ejecutarlo  wollock no me muestra el error que tengo si no que explota y lanza un StackOverFlow. Exception, el problema del test ya lo solucionamos , el problema es que  esperaba un set y el test devuelve una lista...

envío código de implementación y test

[Codigo del test e implementacion.zip](https://github.com/uqbar-project/wollok/files/2070218/Codigo.del.test.e.implementacion.zip)

**Comment by fdodino** [comment]
Gracias Alexander!

Teníamos reportado el issue #1401, que estamos por subir a la próxima versión de Wollok.
Confirmamos que resolviendo ese issue también estamos resolviendo éste:

![image](https://user-images.githubusercontent.com/4549002/43957864-c2ffba18-9c7f-11e8-8190-560342673050.png)

Cerramos este incidente, y te agradezco por colaborar con el proyecto. Un abrazo!
