### ISSUE TITLE
Superfluous "import" clause when writing class/object names through content assist

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1417]
Let us consider a file `uniforme.wlk` that defines a class `Uniforme`, and the following code in a different file

```
import uniforme.*

class Taller {
    method crearUniforme() { return new Unif }	
}
```

if I press Ctrl-Space after the word `Unif`, the IDE shows the option  **Uniforme - uniforme.Uniforme**. 
If I select that options, then the text `uniforme.Uniforme` is inserted into the edition:
```
import uniforme.*

class Taller {
    method crearUniforme() { return new uniforme.Uniforme }	
}
```

where the package name in the `new` expression is superfluous, given the presence of the `import` clause at the beginning of the file. IMHO, the IDE should insert just `Uniforme`, resulting in
```
import uniforme.*

class Taller {
    method crearUniforme() { return new Uniforme }	
}
```

**Comment by clombardi** [comment]
Alas, I just realized that I already reported this issue. Namely: this issue duplicates #1391 . Sorry.

**Comment by fdodino** [comment]
![anim](https://user-images.githubusercontent.com/4549002/44045947-81983658-9f00-11e8-8213-2abf8c11d297.gif)

**Comment by fdodino** [comment]
@clombardi I realized that it could be nice to also add some parentheses (you can continue from this point)
