### ISSUE TITLE
Wrong tab ordering in new object/class file popup

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1418]
The tab order in this popup window

![image](https://user-images.githubusercontent.com/5519535/42351610-503048c2-808c-11e8-9b05-a63f7bc4b710.png)

behaves as follows: 

- **Back** button 
- **Finish** button
- **Cancel** button
- the text "This wizard creates a new wollok file for the definition of objects and classes" (strange!)
- the **Object** / **Class** radio selector
- container
- file name
- object / class name

IMHO it should behave this way instead:
- container
- file name
- the **Object** / **Class** radio selector
- object / class name
- **Back** button 
- **Finish** button
- **Cancel** button

**Comment by clombardi** [comment]
Alas, I just realized that I already reported this issue. Namely, this issue duplicates #1390 . Sorry I am

**Comment by fdodino** [comment]
No problem, I think this issue has a clear resolution, while #1390 needs further discussions.
