### ISSUE TITLE
Content assist does not work properly until a char is typed

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1420]
Suppose I am typing a class as follows
![image](https://user-images.githubusercontent.com/5519535/42376278-f3091084-80f4-11e8-9e03-8ca27597e688.png)
When I press Ctrl-Enter in this situation, I would expect to obtain `isBuene` as the first option in the content assist popup. Alas, this is not the case:
![image](https://user-images.githubusercontent.com/5519535/42376353-4201f8a4-80f5-11e8-9b4e-abebf7ec3914.png)
The desired behavior occurs only if I type an additional character "towards" the desired option, in this case a `u`, *after* having pressed Ctrl-Enter:
![image](https://user-images.githubusercontent.com/5519535/42376436-85eb9386-80f5-11e8-92d5-40854b676e57.png)

**Comment by fdodino** [comment]
When Type System is ready, we should address all autocomplete issues.

**Comment by clombardi** [comment]
Amen
