### ISSUE TITLE
warnings when a project includes multiple source folders

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1431]
I created a project in which 
- I deleted the `/src` folder
- I created two source folders, `/etapa1/src` and `/etapa2/src`, with separated output folders (namely, `/etapa1/bin` and `/etapa2/bin`).

The project seems to work:
- I can run the REPL on a source file, and
- I created a test that uses the objects defined in another file, and this test runs soundly

This project is available [as a GitHub repo](https://github.com/clombardi/multipepita). Checkout the branch `twosrcfolders`.

The only problems I am aware of are three warnings that appear in the "Problems" view, relative to the build.properties file, line 1, with "Plug-in Problem"  as type. The warning texts are:
- etapa1/src/ is missing from source.. 
- etapa2/src/ is missing from source.. 
- The folder "src/" does not exist in the workspace

**Comment by fdodino** [comment]
This is an Eclipse warning, the way of repairing it is changing `build.properties` Eclipse file. I removed intentionally `src` folder and configured build path to use `etapa1` and `etapa2` as source folders. Then:

![issue1431](https://user-images.githubusercontent.com/4549002/69860237-8c71dc80-1274-11ea-8e4c-8416e17594bd.gif)

Closing this issue.
