### ISSUE TITLE
two consoles for each REPL, just one terminates on "quit" 

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1433]
If I launch a REPL on a file, and later I click the "Display selected console"  option at the right of the console pane, there are **two** options, not just the REPL I just opened. Namely:

![image](https://user-images.githubusercontent.com/5519535/43265360-e3c20d5e-90be-11e8-817d-7e6059b24e9e.png)

If I choose the option indicated as [Wollok program], I get an awful text in the console pane:.

![image](https://user-images.githubusercontent.com/5519535/43265461-2cbf6a42-90bf-11e8-954c-846925e63121.png)

Then I go back to the option indicated as REPL, and I type `quit`. The console does not disappear. By clicking again "Display selected console", I discover that the console marked as `<terminated>` is that indicated as [Wollok program]:

![image](https://user-images.githubusercontent.com/5519535/43265572-80743e38-90bf-11e8-9f3c-44e8b8abc8f9.png)

The REPL gets frozen. Even if I click the red "Stop"  image, I cannot get rid of this REPL console. If I open again the same source file as REPL, the former run still appears in the "Display selected console" list

![image](https://user-images.githubusercontent.com/5519535/43265733-ffb3625a-90bf-11e8-8aae-5a34d5b00780.png)

If I select the former run, I can see it as a "dead" REPL.

![image](https://user-images.githubusercontent.com/5519535/43265777-2259247a-90c0-11e8-90f7-fcda44c9893f.png)

The only way I found to get rid of "dead" REPLs is by closing and reopening Wollok. I guess that a workspace change could also do the trick; I did not tested this alternative.

**Comment by fdodino** [comment]
I think we can avoid this behavior by removing drop down button from Console (RemoveWizardsAtStartup)

**Comment by clombardi** [comment]
In such a case, we accept that there cannot be more than one REPL active at a given time. Am I understanding correctly? In such a case, what should be the expected behavior when I type "quit" on a REPL?

**Comment by fdodino** [comment]
Yes, there is only one instance of Wollok REPL Console. In fact, WollokLaunchDelegate does this:

```xtend
	override launch(ILaunchConfiguration configuration, String mode, ILaunch launch, IProgressMonitor monitor) throws CoreException {
		if (mode.isDebug && configuration.getAttribute(ATTR_REFRESH_SCOPE, null as String) !== null) {
			DebugPlugin.getDefault.addDebugEventListener(createListener(configuration))
		}
		var config = configuration.configureLaunchSettings(mode)
		super.launch(config, mode, launch, monitor)
		
		if (configuration.hasRepl) {
			val consoleManager = ConsolePlugin.getDefault().consoleManager
			var console = consoleManager.consoles.findFirst[ name == WollokReplConsole.consoleName ] as WollokReplConsole
			if (console === null) {
				console = new WollokReplConsole
				consoleManager.addConsoles(#[console])
			}
			console.startForProcess(launch.processes.get(0))
		}
```

So I'll check what is happening with dead windows.

If you type "quit", I think there is some output missing there, this obviously is confusing. Moreover, you still see red button active (but console is dead). Maybe some listeners are not notified. I'll check that.

**Comment by fdodino** [comment]
Bueno, paso  en limpio: la consola tiene otro nombre  "Wollok REPL Console: example.wlk" por lo tanto nunca encuentra la otra instancia y está creando la consola de cero todas las veces. El tema es que cuando llamás a super.launch(...) te crea otra consola: ProcessConsole, y por eso se activa el combo de consolas. Ese ProcessConsole es útil cuando tenés un programa, o cuando corrés los tests y querés imprimir console.prinltn... por eso no podemos sacarlo. Pero sí podemos eliminar la consola de Java cuando corra el REPL, entonces lo que hice fue eliminar todas las consolas anteriores únicamente cuando corras el REPL (hoy no solo te lo pisa sino que aparecen los caracteres feos). Y te queda así:

![anim](https://user-images.githubusercontent.com/4549002/44094284-24323d7c-9fac-11e8-8e66-547fe5c34aa1.gif)

@npasserini @tesonep se los cuento por si ven algo raro:

```xtend
if (configuration.hasRepl) {
			val consoleManager = ConsolePlugin.getDefault().consoleManager
			consoleManager.removeConsoles(consoleManager.consoles)
			val console = new WollokReplConsole
			consoleManager.addConsoles(#[console])
			console.startForProcess(launch.processes.get(0))
		}
```

**Comment by fdodino** [comment]
Ah, y por supuesto si tipeás "quit" y volvés a iniciar la consola ya no tenés más consolas muertas...

**Comment by npasserini** [comment]
:+1:

**Comment by fdodino** [comment]
Tratando de encontrarle una vuelta al tema del comando "quit" que propone la consola y que nunca usé, no descubrí todavía por qué cuando corrés "quit" algún listener desactiva todos los comandos. Más allá de que puedo seguir tratando de descubrir qué pasa, me parece que a esta altura sería mejor que no exista ese comando **quit**. Es decir, si lo querés detener, hacelo visualmente, sin escribir nada y si no que quede ahí hasta que quieras ejecutar algo (ya sea esa consola o una nueva). 

Qué opinan?

**Comment by npasserini** [comment]
En principio suena bien la idea, pero ojo que ese quit entiendo yo que
apunta también a ejecutar ese mismo REPL por línea de comando, donde no
tenés un botón para irte.
No sé, tal vez la forma de irse es ctrl+c como pasa en node, sólo digo que
tengamos en cuenta ese caso también, dado que es algo a lo que estaríamos
apuntando en el futuro no tan lejano.

**Comment by npasserini** [comment]
Si mantuviéramos el quit, sería bueno hacerlo más visible, onda grisar la
consola o algo así, porque realmente no se ve.
Si el botón elimina la consola no hace falta... en caso contrario también
vale lo del grisadito.
Es un chiche, y no sé qué tan difícil es, pero si se pudiera creo que
mejoraría la UX.

**Comment by npasserini** [comment]
Jajajaja, ok.

**Comment by fdodino** [comment]
Bueno, al final me inspiré con lo que me dijiste de la pantalla gris y creo que le encontré una vuelta de tuerca. Medio fea mi solución porque en todos los listeners estoy verificando si la consola está corriendo y si detecta que no está corriendo grisa el fondo. No pude hacer que sincronice el botón (se ve habilitado) pero entiendo que visualmente se ve el fondo gris y eso ya ayuda, además le escribo un mensaje de despedida que ayuda a que aparezca el fondo gris (hay algunas ocasiones en las que no sale, pero no me preocupa porque el fondo gris se activa en cuanto te parás con el mouse, o cuando querés escribir cualquier tecla).

![anim](https://user-images.githubusercontent.com/4549002/44623207-3955f080-a89f-11e8-8895-c886eb16e242.gif)

No es perfecto (habría que refactorizarla cuando armemos una versión de Wollok web o javascriptera), pero algo es algo @clombardi @npasserini

**Comment by npasserini** [comment]
Magia!
