### ISSUE TITLE
Type error warning in wrong line

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1440]
This code has a type problem in line `empl.hola()`, nevertheless the warning appears in the previous line:

```Wollok
class Empleado{
	var property categoria = cadete
}

object cadete {
}

object jefe {
	method m(empl){
		empl.categoria()
		empl.hola()
	}
}
```

![seleccion_564](https://user-images.githubusercontent.com/5421992/43679363-4e9175ce-97fa-11e8-8fc6-ea68d08ef33a.png)

**Comment by npasserini** [comment]
Fixed in https://github.com/uqbar-project/wollok/pull/1454/commits/e362292161a484c686ccf35f0c429a1dcb8fac91#diff-4b70e0b1eab67967ad404aa4f812c172R37
