### ISSUE TITLE
Type system doesn't detect when no existent type matches the expected usage

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1441]
This code has a type problem in line `empl.chau()`, nevertheless **no warning appears**

```Wollok
class Empleado{
	var property categoria = 0
}
object jefe {
	method m(empl){
		empl.categoria()
		empl.chau()
	}
}
```
![seleccion_566](https://user-images.githubusercontent.com/5421992/43679420-2dc64332-97fb-11e8-969e-bb55b1c29e38.png)

**Comment by lspigariol** [comment]
No necesariamente el problema esta ahí.
En este caso, me parece bien que al tipo de empl no lo infiera como
empleado.
Pero tampoco está bueno que lo infiera como any, que entiendo es lo que
estaría diciendo actualmente. Lo que esperaría es todo lo contrario, un
"not any" o similar, que me de idea que no existe ningún tipo con ese
conjunto de mensajes.

si nos ponemos exquisitos, el TS podría orientar diciendo cual(es) es el
tipo mas genérico posible por el lado de categoria() y cual(es) por chau().
Si a la variable empl se la usara muchas veces en el mismo metodo, estimo
que si bien es posible no debe ser para nada trivial detectar el uso
extraño frente al uso habitual.

En este caso particular, el warning más evidente es que no existe método
chau() en ningún objeto.

**Comment by npasserini** [comment]
>
> El any lo querria interpretar como que seguro puede ser cualquier cosa, ya
> que no se hace nada en especial con eso. Sería poco usado en ejemplos
> completos, pero tiene sentido durante el proceso de desarrollo.
> Un "not any" sería como "no hay tipo existente para esto". En un ejercicio
> terminado claramente es un error, durante el desarrollo puede que sea un
> error o tal vez sea sólo que faltan definir objetos/clases.
>
 Entiendo lo del not any, sólo que
a. EL ts no puede saber si es un ejercicio terminado o no, entonces, o
siempre contestamos "not any" o siempre "error", no veo como discernir
ambos casos.
b. Un detalle, es que "not any" no me suena a buen inglés... supongo que lo
correcto sería "None" (o tal vez "Nothing", que ya está propuesto para otra
cosa). No sé si None será claro para los chicos. (Not Any tampoco me parece
mucho más claro.)

> No se si se puede diferenciar cuando el TS no pudo completar su analisis o
> hubo algun inconveniente por el que no se puede inferir, en ese caso
> esperaría algo estilo "undefined".
>
No entiendo bien la diferencia entre estos dos casos.
