### ISSUE TITLE
When typing block variable, it should also type the collection

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1442]
This types variable `emp` as `Empleado`.

```javascript
class Empleado{
	var property categoria = 0
}
object jefe {
	var empleados = []
	method algunoConCategoria(cat){
		return empleados.any{emp => emp.categoria() == cat}
	}
}
```

![seleccion_567](https://user-images.githubusercontent.com/5421992/43679581-80ad2550-97fd-11e8-8893-e3eb607e32fd.png)

Should type list as `List<Empleado>`

**Comment by npasserini** [comment]
Fixed by #1458
