### ISSUE TITLE
En ocasiones desaparece el icono de ejecutar en la barra de tareas

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1470]
Sucede mientras se esta editando un archivo. Se arregla cuando se elige el archivo desde el explorador. Solo lo vi luego de hacer un cambio de workspace. (no lo pude reproducir en el workspace original) 

![image](https://user-images.githubusercontent.com/11738011/44155122-c92c0778-a082-11e8-971b-07166082af40.png)

**Comment by fdodino** [comment]
Sí, en la toolbar desaparece cuando te parás sobre el editor. Si querés verlo tenés que pararte sobre el package explorer (Explorador de paquetes).

**Comment by lspigariol** [comment]
si, eso es lo que pasa, pero no es práctico. En las las versiones
anteriores no sucedía.
Se cambió a propósito o es un bug?

**Comment by fdodino** [comment]
El cambio se originó para ocultar otras opciones como el debugger que no están listos todavía

**Comment by npasserini** [comment]
¿Pero no se puede ocultar sólo el debugger y no el run?
Además de la molestia (pequeña, ponele) de tener que hacer un click extra
para correr algo, pasa que los chicos ven sólo el botón de correr sin
archivo y lo presionan. Entonces abre el REPL pero no están sus objetos.
Ese me parece un issue importante.

Por otro lado, yo en linux veo el botón siempre, n'importe quoi.

**Comment by fdodino** [comment]
Yo en Linux lo veo siempre que no me pare en el editor, ahí desaparece la toolbar, que corresponde a:

The active contribution item identifier:
org.eclipse.debug.internal.ui.actions.RunDropDownAction
Action set identifier:
org.eclipse.debug.ui.launchActionSet

Eso lo podés ver levantando el IDE de desarrollo, haciendo Alt + Shift + F2 y haciendo click sobre el elemento de la toolbar.

**Comment by npasserini** [comment]
Yo lo veo siempre, no importa qué haga. Creo que ese comportamiento está
bien, no veo qué aporta borrarlo.
El debugger es al revés, dado que no le estamos dando bola, lo sacaraía
siempre, no importa qué hagamos.

**Comment by npasserini** [comment]
Ejemplo de consultas que recibimos:
[image: image.png]

Y la solución:
[image: image.png]

Y lo que pasa es que los chicos apretan ese botón porque es el único que
ven, es bastante misguiding.

**Comment by fdodino** [comment]
Ahí estuve jugando un poco, logré reflotar el menú desde el Editor pero también se ve el Debugger

![anim](https://user-images.githubusercontent.com/4549002/44492595-7e79e880-a63b-11e8-8174-cc3d9cb40450.gif)

Esto se da como efecto colateral de querer ocultar los menúes de debugger. Voy a jugar un rato más a ver qué consigo.

**Comment by fdodino** [comment]
Ah, y lo molesto de este issue es que tenés que generar el producto para ver cómo se ve (no es lo mismo si lo levantás desde Desarrollo)

**Comment by npasserini** [comment]
Gracias por ocuparte de esto.

**Comment by fdodino** [comment]
Ahi logré que se vea el Run pero además que si querés correr el Debug te avise que no está disponible (muestra un cartel), eso es mejor porque no se rompe todo. Voy a ver si logro que no se muestre el dropdown toolbar del debug, es muy intrincado pero le estoy encontrando la vuelta.

**Comment by fdodino** [comment]
Demo del producto final:

![anim](https://user-images.githubusercontent.com/4549002/44623262-3d364280-a8a0-11e8-9d44-c4474c96df3f.gif)

**Comment by npasserini** [comment]
Gracias Fer.

**Comment by lspigariol** [comment]
bien ahí!
para mí ya es suficiente. (Me va a ahorrar varias explicaciones, incluso a
los ayudantes)
