### ISSUE TITLE
TS: Mejorar mensaje de error cuando un objeto no entiende un mensaje

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1472]

**Comment by fdodino** [comment]
Habilité el Type System para el ejemplo de Empanadas Giménez y me encantó definitivamente que el Type System se de cuenta de que hay un mensaje que no está implementado en los posibles objetos receptores:

![issueTS.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e187893687b79acda5fd53b652fa912a5265296b51f6782783e62ebd1423005d0b18a917585f16f9fedb22f7a42062c80d55b98e30063e937f03a6aa8318b500bf238f4c80b4ba894dc4ed3537aa.png)

El tema para mejorar es que incluya también a gimenez que no lo entiende también. Si gimenez lo entiende que no aparezca.

Pero me sorprendió muy gratamente.

**Comment by npasserini** [comment]
Parece relacionado a #1507

**Comment by fdodino** [comment]
Yafu...
