### ISSUE TITLE
onTick - Way to remove it

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1475]
game.onTick is useful, is declarative, and elegantly solves a common problem.

Yet however I'd like a way to stop the event from firing. For example, if one uses the onTick to move an "enemy", I'd like the event to stop happening when the enemy is hit.

I'd like to be able to "tag" that onTick, 

```Wollok
game.onTick(2000, "enemyMoving", { /*movement magic*/} )
```

In order to be able to remove event:

```Wollok
game.removeTickEvent("enemyMoving")
```

But it's just an idea. Opinions?

**Comment by fdodino** [comment]
Something like this @asanzo @npasserini ?

![anim](https://user-images.githubusercontent.com/4549002/45453758-1eb1b300-b6b8-11e8-9a7f-a6d1fb0ee302.gif)

**Comment by asanzo** [comment]
HAHAHHAHA I love it. ¡¡ Amazing !!

Can we overload the onTick method in order to be backward-compatible and in order to mantain the simple version?

**Comment by fdodino** [comment]
I would rather not doing this, since some tick listeners would remain without a name

**Comment by asanzo** [comment]
Ok!

What about putting a nice error "deprecated - use the other" on the old method?

Perhaps you can also send me to fry churros.

**Comment by fdodino** [comment]
haha, I love you Alf!
Lets see what @npasserini thinks about this

PS: Why are we talking in english?

**Comment by npasserini** [comment]
Creo que el onTick todavía no se usó tanto y podemos volarlo de una. Pero
si Alf dice que ya lo están usando tampoco me parece grave dejarlo como
deprecado hasta fin de año.
En ese caso, yo propongo lo mismo que para imagen/posición, que sólo figure
en la documentación el método que queremos dejar.

**Comment by asanzo** [comment]
Ahhhg buscar era tanto más inteligente.

Busqué en la orga Wollok, ningún onTick. Conozco dos proyectos con onTick con toda la furia. 

Estoy de acuerdo con la justificación de Dodine para deprecarlo, y ahora que hice la búsqueda y Nico contó cómo se hicieron otras deprecadas, me quedo más tranquilo. 

Ambas soluciones me parecen bien :) Y tengo una ligera preferencia por la de sacar el método.

 Perdón por el ruido.

Abz

**Comment by lspigariol** [comment]
+1 a sacar métodos que (casi) no se usan, antes que se usen mas
