### ISSUE TITLE
Se borran las marcas de error en el editor al grabar

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1477]
Marcas de error en el editor se ven (en rojo y con la leyenda al pasar el cursor) cuando se  esta editando, pero al grabar o cuando se abre un archivo, no se muestran (se ve el icono grisado y no aparecen en la barra de desplazamiento)

**Comment by npasserini** [comment]
Sí, yo también lo noté. Anoche hablábamos con @Fernando Dodino
<fernando.dodino@gmail.com> de esto.

**Comment by npasserini** [comment]
Igual no pasa siempre. Por ejemplo:

[image: image.png]

Se reporta bien. Habría que ver si podemos encontrar cuál es el patrón que
permite reproducir el problema.

**Comment by fdodino** [comment]
Hace un mes me pasaba esto mismo cuando estaba cerrando el Builder, y el tema pasa porque una vez que ponés las anotaciones de error en el editor, corre algún proceso posterior de validación que hace que Eclipse te lo marque con gris porque entiende que el error que vos reportaste puede haber sido solucionado.

Lo que hay que mirar son los eventos que disparan el validator, y el listener que escucha la activación del editor (si mal no recuerdo estaba en WollokActivator de wollok.ui). Lo ideal sería lanzar un error, atraparlo en un try/catch que loguee tanto en el evento activate como en el WollokChecker que llama a los validator extensions, para ver quién lanza en qué momento la validación de nuevo y deja en gris las marcas del editor.

**Comment by fdodino** [comment]
relacionado con #1444

**Comment by fdodino** [comment]
Bueno, de casualidad @npasserini encontré el problema que ocurre cuando importás un proyecto desde otro directorio que no sea tu workspace de trabajo. Por eso estuve tratando de reproducirlo sin éxito. Cuando quise levantar un proyecto desde otro lugar, ahí empecé a tener el tema de que las marcas quedaban desactualizadas, en la clase WollokActivator de wollok.ui:

```xtend
	override partActivated(IWorkbenchPart editor) {
		if (editor instanceof WollokTextEditor) {
			Thread.sleep(300) // fixes synchronization problem
			val wollokTextEditor = editor as WollokTextEditor
			if (wollokTextEditor.resource === null) return;
			val activeEditorURI = activeURI.toString.replaceAll(workspaceURI, " ").trim
			val issues = mapIssues.get(activeEditorURI) ?: #[]
```

workspaceURI no es útil en ese caso porque el path absoluto hace que no encuentre ningún issue y devuelva lista vacía. Entonces las marcas que tenían errores en el editor se deprecan.

Ya logré utilizar el path relativo de cada archivo, me falta revisar el tema de los imports.
