### ISSUE TITLE
Dificultades para inferir en el TS

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1478]
Reporte de cosas que el TS no infiere bien

el siguiente ejemplo es breve y se le dificulta inferir como numericos los siguientes mensajes polimorficos (en realidad en neutro podria inferir any)

object neutro {
	method cuantoVaria(molestia) {
		return molestia 
	}
}
object derecha {
	method cuantoVaria(molestia) {
		return molestia * 2
	}
}	

object izquierda {
	method cuantoVaria(molestia){
		return molestia - 4
    }
  }

object republicano {
	method cuantoVaria(molestia){
		return 34
    }

ejemplo completo en
https://github.com/wollok/EjemploUniversidadGobierno.git

**Comment by npasserini** [comment]
¿A qué te referís con "no infiere bien"? ¿Qué tipo infiere? ¿Qué esperarías
vos?

**Comment by npasserini** [comment]
Yo lo veo todo lógico lo que infiere:

[image: image.png]

**Comment by lspigariol** [comment]
no veo la imagen, pero lo volví a probar lo mismo reiniciando el ambiente y ahora infirió number como esperaba, en vez de any.

Pero vi dos cosas nuevas:

cuando inicializo la variable
var property orientacion = neutro
infiere como tipo neutro

cuando no la inicializo
var property orientacion
infiere todas las posibilidades (neutro, derecha, izquierda, republicano)

y pasa algo similar con el setter
method aprenderAReclamar(nuevaMedida){
		medidaFavorita = nuevaMedida
	}

si en el codigo no lo uso, infiere que puede ser cualquiera de las alternativas (paro, marcha, clase)

pero si en algun lado del codigo aparece
self.aprenderAReclamar(marcha)
al parametro lo infiere solo como marcha.

**Comment by fdodino** [comment]
Lo acabo de probar

![image](https://user-images.githubusercontent.com/4549002/57198767-224ac080-6f4d-11e9-8360-84ac26fb6946.png)

y para mí efectivamente falta que infiera molestia como Number en derecha o izquierda.
Si lo cambiás a 2 * molestia ahí sí entiende que devuelve un Number, y recibe un Number.

Lo dejo en el Ready to Develop.

**Comment by PalumboN** [comment]
Esto ya estaría solucionado en https://github.com/uqbar-project/wollok/pull/1889, pero queda el inconveniente con la inferencia de la `property` inicializada: `orientacion = neutro`. 
Related: https://github.com/uqbar-project/wollok/issues/1891
