### ISSUE TITLE
Check lines which don't produce any effect

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#148]
For example:

```
object blah {
    method b() {
        var a = 0

        a - 10
    }
}
```

Here "a - 10" has no sense.
It doesn't produce any effect.

**Comment by fdodino** [comment]
It works now

![image](https://cloud.githubusercontent.com/assets/4549002/23961000/4f52bf92-0988-11e7-8a2c-c9fc03d58570.png)
