### ISSUE TITLE
Traducir métodos de game al inglés

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1483]
posicion debería ser position
imagen debería ser image

**Comment by fdodino** [comment]
existen ambos métodos, posicion() y position(), imagen() e image()

**Comment by npasserini** [comment]
¿Y por qué no dejamos sólo los de inglés?
O al menos migrar los ejemplos a usar inglés... todo wollok desde las
keywords hasta la api están en inglés.

**Comment by clombardi** [comment]
+1 a lo que propone el maese Passerini

**Comment by fdodino** [comment]
ok, no me opongo. :smile:
