### ISSUE TITLE
Mensaje de error poco claro al usar una asignación dentro de if

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1486]
Un alumno me manda esto. Si bien es un error del programador (usa una asignación dentro del if, en lugar de una comparación) creo que deberíamos mejorar el reporte de error.

![image](https://user-images.githubusercontent.com/4633913/45041614-2087d080-b03f-11e8-9375-e318093d5864.png)

![image](https://user-images.githubusercontent.com/4633913/45041623-254c8480-b03f-11e8-966f-1d110f1c58d8.png)

**Comment by fdodino** [comment]
hay una validación dentro de WIfExpression que el contenido de la expresión debe ser booleana, debe haberse escapado la WAssignment supongo.
