### ISSUE TITLE
Errors in return as an argument - pepita.eat(return 4)

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1491]
## First problem

This code shows this error:  "Debe retornar un valor en todas las posibles ramas de la ejecución". But the description of the error is incorrect.  It should be something like "there is code that will never be executed"

```Wollok
object foo {
	 method bar(){
	 	pepita.eat(return 4)
	 }
}
```

## Second problem

This error appears in the "Problems" view but not in the editor.

## Third problem

A similar code doesn't show any error:

```Wollok
object foo {
	 method bar(){
	 	return 3.min(return 4)
	 }
}
```

**Comment by fdodino** [comment]
hi @asanzo , could you check if new version 1.7.1 fixed second problem? First adn third problem should be still there...

**Comment by fdodino** [comment]
Issue #1383 is related to this

**Comment by asanzo** [comment]
Checked, the second problem is solved. That is to say, now it **does** appear in the editor

![seleccion_836](https://user-images.githubusercontent.com/5421992/45633022-1faa6200-ba75-11e8-9361-0f89c4f49f01.png)

![seleccion_837](https://user-images.githubusercontent.com/5421992/45633050-30f36e80-ba75-11e8-97ce-b839a484486a.png)

Great, Fer!!!

**Comment by fdodino** [comment]
:smile:

**Comment by fdodino** [comment]
@asanzo, developing validator & quickFix also
![anim.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e99a932ec0cfeb9ffbb049a15ee4d6730472267a53a52e7687b570be107f075a094eac135d5816f5a89b37b4f46d2ede0356b49b381d66cc2f10a5b2831abc08bc24824881b0b48e49d2a5.gif)

**Comment by asanzo** [comment]
Absolute magic. :+1:  :clap: :clap: :clap:
