### ISSUE TITLE
Error al instalar Wollok.

### ISSUE THREAD

**Issue by nfleitas** [uqbar-project/wollok#1492]
Me sale un error al momento de instalar Wollok en OSX. Imagen: https://ibb.co/m8mjKp

**Comment by fdodino** [comment]
Hola @nfleitas , fijate que en
http://www.wollok.org/instalacion/
dice cómo solucionar este tema que es propio de OSX:

___

# Problema con App Translocation (Mac)

En la versión 10.12 de OS X se introdujo un sistema de seguridad llamado Gatekeeper. Este sistema tiene como objetivo evitar la ejecución de programas de forma no deseada. Por lo tanto los programas no ejecutan si son ejecutados o descomprimidos en la carpeta Download o donde los guarda el browser. Para poder ejecutarlo es solamente necesario mover la aplicación a otra carpeta, todo haciendolo desde Finder. De esta manera Wollok va a funcionar correctamente.

**Comment by fdodino** [comment]
Por favor avisanos si lo pudiste instalar siguiendo esos pasos. Muchas gracias! Fernando

**Comment by nfleitas** [comment]
Resuelto. Gracias!

**Comment by mesaglio** [comment]
Tengo el mismo problema pero no se puede ejecutar. Movi el archivo descargado de Descargas -> Aplicaciones, y tampoco abrio 
<img width="594" alt="Captura de pantalla 2019-03-11 a la(s) 01 38 41" src="https://user-images.githubusercontent.com/29051129/54100715-b7db3100-439e-11e9-8eee-c34bcceebe78.png">
