### ISSUE TITLE
Impedir referencias con null

### ISSUE THREAD

**Issue by sanuzzi** [uqbar-project/wollok#1501]
Al poner una property constante, wollok sugiere ponerle un valor inicial. Sería bueno que eso no suceda, y en cambio, que obligue a usar sí o sí el _constructor con parámetros nombrados_. Que no pueda quedar en null, pero que la validación sea al construirlo.

También, para las variables, pienso que sería bueno lo mismo: Que no permita que estén asignadas a null. Si hay variables sin inicializar, que se obligue a usar constructor con args nombrados.

Hay muy pocos casos en donde nos hace sentido que una referencia tenga null, y en general se puede zafar cómodos modelando de otras formas.

Obligar a **inicializar todo junto** es mucho mejor que ir armando el objeto de a partes, rellenando los huecos de null que queden. Es más claro, disminuye la mutabilidad, y esta práctica facilita la concurrencia.

¿Qué opinan?

También, de yapa, sería bueno un "validate", "initialize", o algo similar. Que se encargue de hacer validaciones extra. Por ejemplo, al crear un triángulo, lanzar excepción si 2 lados suman menos que un tercero.

**Comment by fdodino** [comment]
yo separaría este issue en dos, porque si no es difícil atacarlo de una.

1) validar en las llamadas al constructor es algo que @npasserini pidió hace un tiempo y este issue vendría bien para formalizarlo.

2) también @npasserini me habló de un initialiize() o validate(), a mí no me termina de cerrar, porque en general no suele aparecer, y para los casos que vos decís están los constructores, y hay otra idea que son las invariantes que me parece más copada. Pero lo metería en otro issue.

**Comment by npasserini** [comment]
Ok. Otro detalle es que no se pueden evitar del todo las referencias a
null. Pero la idea es que si querés eso tenés que indicarlo explícitamente.
O sea, en los poquísimos casos en los que uno necesita una variable
inicializada en null tiene que escribir:

var pepe = null

Más discutible es si sería válido
const pepe = null

A priori no parece tener mucho sentido, pero eventualmente uno podría
overridear el null en el constructor, aunque es un patrón medio raro.

**Comment by fdodino** [comment]
sí, las llamadas al constructor es utilizar una expresión new Saraza( ... ) donde en ... están los parámetros nombrados. Esa es la expresión correcta.

Dado que en #1519 ya estamos resolviendo este tema, yo voy a cerrar este issue y en todo caso abramos otro issue que quede en "Discuss" sobre agregar un método initialize o similar.

**Comment by sanuzzi** [comment]
@fdodino veo que se cerró para usar el otro issue para el punto 1.
Lo de initialize/validate/invariantes, ¿Quedó en algún lado?

@lspigariol lo de "constructor con parámetros/argumentos nombrados" [lo saqué de Groovy](http://groovy-lang.org/objectorientation.html#_named_argument_constructor), que ya tiene la idea hace mucho. En definitiva, es un constructor, solo que no hace falta codificar cada detalle.

En cuanto a esto:

> Si hay variables sin inicializar, que se obligue a usar constructor con args nombrados.

Tal cual lo que dijiste en respuesta, me refería al caso en donde no se le envían parámetros. Ahí te deja pasar que queden muchas cosas en null, y es medio extraño eso.

**Comment by fdodino** [comment]
@sanuzzi , en [este documento](https://docs.google.com/document/d/16kKi_HgpA5GsmxreKU-CiUgou47lUHHV0t40ayZVdrY/edit#) está la especificación de constructores y en particular en la página 13 hay un comentario de NicoS y Lucas al respecto. Pero no tenemos una especificación formal todavía, estaría bueno tratar de vender el feature más allá de que exista un method initialize() que corra siempre. En qué casos serviría que hoy no se pueda resolver mediante constructores?

**Comment by sanuzzi** [comment]
Lo que necesito se resuelve muy bien con los constructores de antes. Pero si la idea es dejar de usarlos, no se me ocurre cómo se podría hacer con los constructores de parámetros nombrados.

Volviendo al ejemplo del triángulo: Quiero usar un constructor nombrado mandando los 3 lados. Los 3 deben ser positivos, y la suma de cada par de lados debe ser mayor a la del tercero. Si no, excepción.

En un constructor de los de antes, iba perfecto. Con los de ahora, entiendo que no se puede redefinir el comportamiento, ¿Verdad? Si se pudiera hacer eso no creo que haga falta un validate/initialize, pero no me imagino bien cómo quedaría.

**Comment by javierfernandes** [comment]
Dispersando un poco: eso suena a un caso “de libro” para modelar como
invariantes. Habia una spec de pre+post condiciones e invariantes con una
implementación y todo en un branch “vanguardista” de wollok

**Comment by npasserini** [comment]
UOOOOOOO... Sí!

**Comment by fdodino** [comment]
Totalmente, creo que podemos abrir un issue en Discuss y definir si lo metemos en el roadmap 2019
