### ISSUE TITLE
new Exception(message = "Saraza") se rompe

### ISSUE THREAD

**Issue by sanuzzi** [uqbar-project/wollok#1502]
Al hacer esto:
throw new Exception(message = "Saraza")

Wollok se rompe diciendo:
[ERROR] C:\Users\Sanuzzi\Desktop\wollok\workspace\Conejos\src\example.wlk:76:1602 ERROR Debe proveer un valor inicial a las siguientes referencias: cause 

Sería bueno que ande con constructor de parámetros nombrados, así explicamos una sola forma de construir a los objetos.

Quizá la causa pueda tener por defecto un objeto que no continúe el stacktrace.

**Comment by fdodino** [comment]
@npasserini , creo que podemos por defecto setear cause = null (a futuro nothing) y con eso se resolvería, es verdad que no siempre tenemos una causa para generar

**Comment by npasserini** [comment]
Excelente

**Comment by lspigariol** [comment]
El mensaje también podría ser opcional. A veces el nombre de la excepción
es suficientemente expresivo

**Comment by npasserini** [comment]
Pero ese es el constructor de exception, no tiene nombre la excepción.

**Comment by npasserini** [comment]
Lucas, ¿esto lo reabriste intencionalmente?

Si lo estás testeando en tu versión de producción 1.7.1, obvio que no funciona porque no hubo un release en el medio. 

Si lo querés probar deberías bajarte la vesión de desarrollo. Ya está mergeado así que podés bajar los productos de http://download.uqbar.org/wollok/products/dev/

Si no, esperar a que se libere 1.7.2, lo que va a ocurrir en unos días.

**Comment by lspigariol** [comment]
fue adrede, tarde, pero solo para explicar lo que quería decir con "A veces el nombre de la excepción
es suficientemente expresivo".

Una de las alternativas es simples es hacer  
class NoHaySaldo inherits Exception { }

 y luego hacer new NoHaySaldo( ) sin un mensaje. 

aunque lo que tambien suelo hacer es directamente un objeto
object noHaySaldo inherits Exception { } con lo que ni siquiera es necesario el new.

En ambos casos me parecen mas robusto que testear o capturar usando el string de mensaje.

**Comment by npasserini** [comment]
En líneas generales estoy de acuerdo que es más robusto. De hecho esto de
las excepciones es un punto para mí flojo de wollok y no hemos tenido
tiempo de pulirlo como a mí me gustaría.

Por otro lado, gran parte de esos mecanismos están puestos para evitar
hablar de clases, en momentos donde los chicos no saben aún clases. Y una
de las cosas dudosas es justamente que la sintaxis de catch permite
escribir un nombre de clase, atrapar en función de la clase. Algo que no
pasa en ningún otro lugar del lenguaje, o sea ahí hay escondido un instance
of que normalmente no permitimos.

Pero bueno, el tema es que usar objeto no me queda claro que esté bien,
porque una excepción tiene estado, específicamente un stack trace, entonces
no se pueden reutilizar así nomás.
¿Cómo queda el stack trace cuando usás object en lugar de class?

Lo otro imagino que es posible, pero para eso deberíamos hacer que el
mensaje default se pueda inferir a partir del nombre de la clase o algo
así, porque si no no sé cómo queda el output de la consola o similar cuando
se lanza esa excepción.

**Comment by npasserini** [comment]
Para aclarar lo último: creo que no es consistente que haya excepciones sin
mensaje. En todo caso lo que puede pasar es que yo no tenga que pasarle un
mensaje porque lo calcula solo.

**Comment by lspigariol** [comment]
estuve probando con un nuevo ejemplo en https://github.com/wollok/EjemploExcepciones.git

1) haciendo object ... inhertis Exception:
- el testeo se puede hacer sencillamente con throwExceptionLike y el wko
- el stack trace funciona bien
- en consola, el mensaje de error muestra el nombre del objeto excepcion y : null
- no se puede capturar (en el catch da un error que espera una clase) 

2) haciendo class ... inherits
- el testeo hay que hacerlo con throwExceptionLike (o ...type), instanciando.
- el stack trace funciona bien
- consola idem
- se puede capturar con el nombre de la clase.

Lo que me pasó este tiempo dando clase con las excepciones es:
Nunca mostre el catch.
Lanzar una excepcion con el objeto error, antes de dar clases, lo usé sin problemas.
Lanzar una excepcion  de la clase Exception con diversos strings, lo mostre muy rápidamente y no lo recomendé.
Lanzar excepciones con subclases ( o subobjetos) de Exception, es lo que planteo como mejor alternativa.
Nunca se me planteo el caso que necesite que existan a la vez dos excepciones, por lo que con wko me fue suficiente. (No se si tiene sentido en la vida real que convivan excepciones, o que se las quiera conservar una vez capturadas o algun motivo por el cual la excepcion no pueda ser singleton )
Con el esfuerzo que hacemos en expresividad del codigo, y pensando en la excepcion para el programador mas que para el usario, el mensaje me parecio generalmente redudante, 
De todas maneras, usar herencia para no agregar comportamiento me parece un poco desafortunado. 
Cuando en wollok tengamos la posibilidad de definir objetos instanciados globales, los usaria tambine para las excepciones. Me parece un buen caso donde me interesa identificar un objeto entre otros, pero sin requerir comportamiento diferenciado

De todas maneras, lo que alguna vez propuese y me parece mas didactico es mantener el esquema wollokero de **1 Concepto = 1 Palabra** , o sea reificar el concepto y agregar exception como palabra reservada (aun siendo sugar syntax de una instanciacion/herencia que exista por detras)

forma basica
exception pasaronCosas {}

con mensaje/causa
exception pasaronCosas("un mensaje", unaCausa) { }

con comportamiento/estado adicional
exception pasaronCosas("un mensaje", unaCausa) { 
var algo
method algo(){}
}

**Comment by npasserini** [comment]
De acuerdo.
