### ISSUE TITLE
Error extraño del type system

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1507]
Esto no tiene sentido

![image](https://user-images.githubusercontent.com/4633913/45854652-93bd6200-bd22-11e8-8fbc-d98b8440f90b.png)

El programa completo en https://github.com/obj1unq-2018s2/pepita-game-atupilojon

**Comment by PalumboN** [comment]
Esto ya estaría solucionado en https://github.com/uqbar-project/wollok/pull/1889, pero hay otro inconveniente con este método: 
```
	method levantarComida(alimento) {
		if (comida != null) {
			game.addVisualIn(comida, posicion.up(1))
		}
		comida = alimento
	}
```
Que infiere como `levantarComida(alimento: Object)` porque infiere que comida es Object por el `!=`. Related: https://github.com/uqbar-project/wollok/issues/1578
