### ISSUE TITLE
Error al tipar IfExpression

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1508]
![image](https://user-images.githubusercontent.com/4633913/45855096-e730af80-bd24-11e8-8ef9-9effca41e01f.png)

Ejemplo completo en https://github.com/obj1unq-2018s2/pepita-game-atupilojon

**Comment by PalumboN** [comment]
Creo que el problema es el `null`.

![screenshot from 2018-10-07 20-31-24](https://user-images.githubusercontent.com/4098184/46581749-70a7e780-ca70-11e8-9681-4eb8ea2d7f19.png)
