### ISSUE TITLE
Agregar copyWithout a colecciones

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1518]
Al margen de que habilitemos el if + == por identidad, creo que este código sigue siendo feo
```
		var cultivosARegar = posicion.allElements()
			.filter { obj => !(self == obj) }
```
y se podría mejorar con un copyWithout.

De la mano podría haber un copyWith, que devuelva una colección nueva + el elemento agregado.

**Comment by lspigariol** [comment]
me gusta que haya metodos para esto y se amplie la bilioteca. 
me quedan dudas sobre que se llame "copy", me parece que puede confundir (los que no dice copy tienen efecto?

lo mejor que se me ocurre, aunque tampoco estoy plenamente convencido  es without y with a secas

otra es seguir la logica del sort/sorted y apuntar a un added removed, pero no me suena del todo bien (de paso, recuerdo que habia un issue sobre hacer un sort con un bloque de un argumento, que era una buena idea y no sé en qué estado quedó)
