### ISSUE TITLE
Non-initialized constants show an error

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1519]
```scala
class Something {
    const property aValue
}
```
This code shows an error on the const definition due to not being initialized. When direct initialization is used, this should not be a problem, like in:
```scala
new Something(aValue = 100)
```
The error should only be displayed on a piece of code that instantiates a Something without assigning a value to ```aValue```, like in ```new Something()```, otherwise you are always forced to define constructors to get rid of this error when you cannot define a default value for the constant.

**Comment by fdodino** [comment]
I agree. 

I think we should leave the "constant not initialized" error only if there are constructor definitions. Otherwise , we should check against each initialization:

```js
class Something {
    const property aValue
    var anotherValue
}

new Something() // throws an error
new Something(anotherValue = 2) // throws an error, aValue not initialized
new Something(aValue = 3)  // throws an error, anotherValue not initialized
new Something(anotherValue = 2, aValue = 3) // OK
```

What do you think @npasserini?

**Comment by matifreyre** [comment]
Duplicated? 
#1501 seems to be closely related, if not the exact same thing (the proposed solution of "impeding null references" differs from this one of just moving the validation to the actual creation of the object, but the issue is essentially the same).
I don't agree to forcing the use of direct initialization... I can survive without that as long as a constructor is defined and used. I think the idea behind that phrase is the same as the one proposed here, just check the creation of the object, but it can be either direct initialization or a constructor.
Neither I agree to not allowing null references, but I can agree to not allowing a default null value by omission and instead force an initialization of a null reference by any explicit way possible (default value on declaration, direct initialization or constructor).

**Comment by lspigariol** [comment]
cambio a idioma argento.

desde que tenemos inicializacion directa, es imposible que la deteccion de un warning o error en la declaración de una variable sea certero, aun teniendo constructores. Solo en el new se lo puede detectar, o en el constructor.

Mas que marcar el problema como si fuera de la variable, (que no es asignada/inicializada) el problema es del constructor o del new, que no está haciendo buen uso de las variables (o constantes).  

Asumiendo que es una buena practica que siempre quede todo bien inicializado al instanciar, (o explicitamente inicializado con null) cuando eso no sucede, basta que sea un warning (o un error que permite ejecutar igual)

**Comment by fdodino** [comment]
No entendí muy bien lo que dijo Mati.
Mi propuesta es:

- si la clase tiene constructores, entonces esos constructores tienen que asegurar que todas las variables estén inicializadas con valores por defecto (null es válido)
- si la clase no tiene constructores, si hacés new Clase() o new Clase(... con parámetros nombrados ...) debe chequear que la instancia tenga todas las variables con valores inicializados (null es válido). El problema no se va a detectar en la variable (no desde que haga el cambio), sino en el new que se haga.

**Comment by matifreyre** [comment]
Perfetto

**Comment by npasserini** [comment]
> No entendí muy bien lo que dijo Mati.
> Mi propuesta es:
> 
> * si la clase tiene constructores, entonces esos constructores tienen que asegurar que todas las variables estén inicializadas con valores por defecto (null es válido)
> * si la clase no tiene constructores, si hacés new Clase() o new Clase(... con parámetros nombrados ...) debe chequear que la instancia tenga todas las variables con valores inicializados (null es válido). El problema no se va a detectar en la variable (no desde que haga el cambio), sino en el new que se haga.

Un detalle acá es que la validación no cambia mucho si hay o no hay constructores. Quiero decir, aunque la clase tenga constructores yo puedo usar inicialización directa, entonces esas validaciones siguen siendo necesarias. ¿No?

**Comment by fdodino** [comment]
Sí, eso no cambió. Solo se relaja la validación si no hay constructores.
