### ISSUE TITLE
Better organization of wollok-test project

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#152]
```
class CamionReutilizable extends 
    var destinos = #[]

    new(cargaMaximaPosible) = super(cargaMaximaPosible)
}
```

Después hay un par de métodos que están tratando de alterar parámetros. Me refiero a referencias.
Creo que antes no estaba el check en las operaciones tipo "-=, +=, *=" etc.
Y lo agregué.
Y en algún momento habíamos definido que los parámetros era "final". Con lo cual ahora sí checkea

​
Eso pasa en un par de lugares.

Otra cosa que ví de los ejercicios es que tienen varios warnings de variables que no se usan o nunca se asignan.
Por lo que ví parecen válidos los checkeos.

Otro error que ví es este

```
class Bulto {
    var cantidadCajas
    var pesoCaja
    var pesoEstructura
    var contenido

    new(unaCantidadCajas, pesoCadaCaja, pesoEstructuraMadera, contenidoCaja) {
        cantidadCajas - unaCantidadCajas    ///// ACA
        pesoCaja = pesoCadaCaja
        pesoEstructura = pesoEstructuraMadera
        contenido = contenidoCaja
    }
}
```

Parece un typo. En lugar de asignar la variable hace una resta que se pierde en la nada.
Voy a crear un issue para que el checker se de cuenta de eso y tire un error.
Sería algo equivalente a java cuando te dice que no produce ningún efecto.

Esto también se ve sospechoso

```
pedido -= pedido - transporte.capacidad()
```

**Comment by fdodino** [comment]
@npasserini maybe we can enhance the description of this issue (or change the title :))

**Comment by fdodino** [comment]
@npasserini  yo cerraría este issue y abriría otro con lo que estuviste contando la otra vuelta, no debería haber un método con varias líneas donde antes de la última línea haya mensajes que no tengan efecto.

**Comment by fdodino** [comment]
Stale issue. Closing it. :)
