### ISSUE TITLE
Local declaration in a describe method shows error for duplicated name with a local declaration of a test

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1520]
The following piece of code shows an error within method ```camionCon(coso)``` on the declaration of ```const camion``` saying that the variable name is duplicated. When I remove all tests that declare a local ```const camion``` or change the constant name, the error dissapears. The error only shows up in the method's declaration, not in the tests'.

```scala
describe "Carga de camiones" {
	const aceite = new Liquido(contenido = "aceite", densidad = 0.8)
	const bidonDeAceite = new Bidon(liquido = aceite, capacidad = 200)
	const cajaDeTornillos = new Caja(contenido = "tornillos", peso = 12)
	const bultoDeTornillos = 
		new Bulto(caja = cajaDeTornillos, cantidadCajas = 50, pesoPallet = 70)

	method camion(unEstado) = new Camion(pesoMaximo = 200, estado = unEstado)
	method camionCon(coso) { 
		const camion = self.camion(disponible)			/* <---------- */
		camion.cargar(coso)
		return camion
	}
	/* ....... */
	test "Intentar cargar un camión en exceso no afecta al camión" {
		const camion = new Camion(pesoMaximo = 150)		/* <---------- */
		camion.cargar(bidonDeAceite) // Pesa 200, no se puede cargar
		assert.equals(0, camion.cantidadDeCosos())
	}
```

**Comment by fdodino** [comment]
It took me almost two hours, but I could figure out 

- scopes had to be defined better (defined, as @npasserini pointed out some time ago)
- and duplicate variable validation, too

![image](https://user-images.githubusercontent.com/4549002/46708088-5f4b1080-cc13-11e8-9d29-b77c46afc9d0.png)

I'll add some new tests tomorrow before generating a PR.
