### ISSUE TITLE
Repeated validation preferences with the same description

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1521]
"No Effectless Expressions in Sequence" is there twice in a row:

![image](https://user-images.githubusercontent.com/10454118/46259748-ac144600-c4b3-11e8-9e72-b57add8a5b8b.png)

**Comment by matifreyre** [comment]
Y sigue siguiendo...

![image](https://user-images.githubusercontent.com/10454118/46259871-f2b67000-c4b4-11e8-92af-6829ff41b7fe.png)

**Comment by fdodino** [comment]
Since we are focusing in new tools, closing this issue
