### ISSUE TITLE
bug de wollok en linux o error mio ?

### ISSUE THREAD

**Issue by ma77hews** [uqbar-project/wollok#1522]
a la hora de ejecutar alguno de los proyectos wollok se queda freezeado ejecutando algo que parece nunca terminar...
![error wollok](https://user-images.githubusercontent.com/22912470/46263166-07f5c380-c4e2-11e8-88d2-1f903ab1dbe8.png)
uso linux mint y la ultima version disponible de wollok
tengo todo actualizado y no puedo usar el programa alguno tiene una solucion ? 
desde ya muchas gracias

**Comment by fdodino** [comment]
hola @ma77hews, 
          es un problema conocido (#1264). Recientemente hemos sacado una versión de prueba, que podés descargar de
http://download.uqbar.org/wollok/products/dev/
(en tu caso te bajarías la versión de Linux 32 ó 64 bits). No hace falta que pises tu instalación existente, simplemente la descomprimís de un directorio y levantás tu entorno importando los proyectos con los que estabas trabajando. Nos gustaría saber si se soluciona el inconveniente, que es un deadlock cuando varios procesos intentan acceder al mismo recurso (algún archivo wlk de tu proyecto).
Por cualquiera de los dos resultados te agradecería si nos escribieras en este mismo issue, para poderlo seguir.
Saludos y suerte
Fernando

**Comment by ma77hews** [comment]
Hola @fdodino muchas gracias por tu respuesta segun lei el caso #1264 y me parece interesante saber que ya pudieron identificar el problema.
hoy mismo pruebo la solucion y vuelvo a publicar 
si sirve de algo te comento que el error unicamente ocurre cuando intento ejecutar un programa luego de un pull

**Comment by ma77hews** [comment]
actualizacion de estado: 
descargue y descomprimi el archivo wollok
hasta el momento no presento ningun problema pude hacer todo sin que se cuelgue ni nada 😁

**Comment by fdodino** [comment]
gracias @ma77hews ! cualquier cosa avisanos!

atención @npasserini ...

**Comment by fdodino** [comment]
Cerramos por el momento el incidente, gracias por colaborar!
