### ISSUE TITLE
evitar advertencia de redondeos al usar bibliotecas estandar

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1528]
Me paso al usar anyone(), que muestra por consola los redondeos que hace internamente el método. No es grave, pero queda desprolijo.

**Comment by npasserini** [comment]
Sí, creo que habría que repasar este tema. Me parece que hay más lugares
donde recibimos esos errores de redondeo que no deberían estar.
De hecho no estoy seguro de querer ese error de redondeo ahora.

**Comment by fdodino** [comment]
+1

Hoy hablamos en lo de Nico de sacarlos, es algo sencillo de hacer así que le subo la prioridad.

**Comment by isaiaslafon** [comment]
Hi, recently a student send and Email, about console warning: 
   **ADVERTENCIA: El valor 3.6496675816995863 se ha truncado a 3.64967
   3.64967**
 When asking anyOne() to a list. 
 I notice even a **roundUp(0)** when I use **0.randomUpTo(aMax)** wollok console return same warning type.
 But when doing a anyOne() to a Range instance this doesn't happen.

**Comment by fdodino** [comment]
El cartel no aparecerá más en Wollok Hipatia. Ya está sacado en dev, podés probarlo en tu entorno de desarrollo o apuntando a dev.
