### ISSUE TITLE
TS Confunde tipos 

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1530]
Vi varios comportamientos extraños en este ejercicio.

![image](https://user-images.githubusercontent.com/11738011/46689455-42441c80-cbd6-11e8-93ae-5400cb9cafe2.png)

la cantidad de parametros es correcta. 

despues, (tambien se puede ver en el esquema de la imagen) infiere a mensajeros como Paquetes.

En otra parte, aparece
![image](https://user-images.githubusercontent.com/11738011/46690044-baf7a880-cbd7-11e8-99b1-d1d4e65de7b0.png)
y en esa variable nunca hay un camion. 

Tal vez tenga que ver que hay un metodo peso() que los mensajeros y camiones entienden, pese a no ser tratados polimorficamente. 

este es el repo con la solucion https://github.com/wollok/polimorfismoColeccionesMensajerosDePelicula.git

(no se si tiene algo que ver, pero con este ejercicio me volvio el problema de "hibernando" y "construyendo le espacio de trabajo". Estoy con la version dev. Despues de cerrar y abrir proyectos, reiniciar wollok, activar o desactivar el TS parece haber vuelto a la normalidad...)

**Comment by PalumboN** [comment]
Luego de https://github.com/uqbar-project/wollok/pull/1593 este repo tipea todo correctamente ;)
