### ISSUE TITLE
super() call should navigate to the super method

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#154]
Check this screenshot

![screen shot 2015-06-30 at 16 57 55](https://cloud.githubusercontent.com/assets/4428120/8440648/e699676e-1f49-11e5-889f-f0a04967c801.png)

While one can navigate with the arrow on the left, hitting F3 or CTRL/CMD + click won't get you anywhere.

**Comment by npasserini** [comment]
Why could not this be included in https://github.com/uqbar-project/wollok/milestones/Wollok%20v1.3.1

**Comment by javierfernandes** [comment]
Yes just that i fixed it will working on mixins. I need to also fix it in
1.3. I cannot merge due to other changes

**Comment by javierfernandes** [comment]
Actually this is already working in 1.3
I cannot find an failing example. So closing it.
