### ISSUE TITLE
Questionable error message and quickfix when creating an object of a class that is not declared

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1544]
This code used to work before Exceptions were changed to accept named parameters: `new BusinessException("hola")`.

Now it is underlined with the message: "Wrong number of arguments. Should be new null()" which doesn't seem correct. And the quickfix Adjust parameters in constructor call changes `new BusinessException("hola")` for `new null()`, that's obviously incorrect.

**Comment by mmatos** [comment]
I just realized that BusinessException did not exist. I'm not closing but renaming the issue since it still seems confusing.

**Comment by fdodino** [comment]
Oh, it happened to me once but I could not reproduce it. Good work @mmatos !

**Comment by fdodino** [comment]
It happened once to me but I could not reproduce it, nice work @mmatos!

**Comment by npasserini** [comment]
Me gusta que Maiu dice que es un mensaje "cuestionable". Decilo Maiu, está mal!
