### ISSUE TITLE
Allow to copy the output of a test

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1545]
It would be very useful to be able to copy the stacktrace of a test failure / error. Currently students can only share this information to ask for help by taking a screenshot of the test runner.

**Comment by fdodino** [comment]
Ver si se puede agregar un botón para copiar el contenido del stack trace (hay algo hecho en la consola REPL).

**Comment by fdodino** [comment]
https://stackoverflow.com/questions/33175024/how-to-make-the-text-in-an-swt-link-widget-selectable

**Comment by fdodino** [comment]
@mmatos Link control is not selectable, althought we now have a copy button :smile: 

![WollokCopyOutputTest](https://user-images.githubusercontent.com/4549002/58704683-38e50b80-8383-11e9-9050-6758d35346c5.gif)
