### ISSUE TITLE
Tests incompletos dan errores que confunden

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1551]
Acabo de ver dos situaciones en las que los errores de Wollok confundieron a un alumno:
1) Un describe vacío (o con una declaración de variable, pero sin tests) da un error de sintaxis.
2) Un test sin asserts lo mismo.

En general, creo que sería interesante pensar qué hacer con los programas incompletos, yo estoy escribiendo, todavía no terminé y esto da error. Que me dé un error mientras estoy escribiendo puede ser confuso, normalmente en una aplicación, al completar un formulario, uno evita que eso pase... acá el principio idealmente es el mismo, claro que es más difícil y no sé cómo se hace, pero lo dejo para pensar. No sé si se puede dilatar la validación un poco, o hacerla al grabar en lugar de mientras edito. 

A falta de una solución más creativa propongo tomar dos acciones:
a) Bajarles el grado de prioridad a warning, el rojo debería reservarse a los programas que no funcionan y estos programas funcionan, tal vez podría fallar en runtime un describe vacío, en js pasa (con jest).
b) Asegurar errores descriptivos, en particular cambiar la sintaxis para que acepte el describe vacío y dejarle esa tarea al validador.

**Comment by lspigariol** [comment]
+1 al item a)
Hay numerosos ejemplos del mismo estilo. Tenemos pendiente la discusion de
categorizar warnings

**Comment by fdodino** [comment]
Me sumo si quieren ir por el a), pero yo me animaría a pensar que no es un tema general, vos notaste que es algo que pasa seguido con los que arrancan? Cómo respondió el pibe cuando le dijiste que tiene que escribir un assert o un test para que no falle?

**Comment by fdodino** [comment]
Bueno, a detalles implementativos, bajamos el grado a warning (en connivencia con lo que planteó hoy Nico en su casa, solo dejar como errores las cosas bloqueantes)

**Comment by fdodino** [comment]
@PalumboN @npasserini, me gustaría que alguna de las veces que nos juntemos lo definamos entre los 3 los grados de error/warning  de cada validator (podría ser con @lspigariol también)

**Comment by fdodino** [comment]
Este cuatrimestre ya se bajó el nivel de severidad a warning, cierro el issue.
