### ISSUE TITLE
En el REPL se puede inicializar dos veces una constante

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1557]

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/60406083-8de68e00-9b8a-11e9-8af7-b138bcc07c26.png)

**Comment by npasserini** [comment]
Es discutible, no me parece grave. Tal vez nos cagaría si intentáramos
convertir esto en un test más cheto. No me jode si lo restringimos pero no
me parece prioritario.

**Comment by fdodino** [comment]
Si bien es cómodo alguien avanzado, a mí me parece que es confuso para el estudiante que dentro del editor no se pueda pero dentro de la consola sí. Incluso es poco consistente la idea de hacer

```wollok
const a = 1
a++               // no te deja
const a = 4   // pero acá te deja redefinirlo
```

**Comment by npasserini** [comment]
Ok.

**Comment by lspigariol** [comment]
comentario sutil

en la consola, lo que sucede no es que deje inicializar dos veces una
constante.
Sino que permite volver a declarar cualquier referencia (variable o
constante) ya declarada antes, de manera que la nueva declaracion sustituye
la anterior.

Lo que pasa es que en la consola no ves lo que hiciste mucho antes.
Pero si molesta, se podria limitar con un error tipo "La referencia ya fue
declarada anteriormente, use otro identificador"

**Comment by fdodino** [comment]
Hoy me di cuenta de que hay situaciones en las que se comportaba feo:

- `const a = algoRaro.probar()` si tiraba error la variable te quedaba inusable, tiraba error a y tratar de definirla no te dejaba porque ya la había agregado
- después intenté catchear el error y ahí sí funcionaba ok, pero si querías hacer `const a = 3 y después a = algoConError`, eso tiraba error y te eliminaba a de la lista de variables del REPL!!
- también se visualizaba mal las referencias sin inicializar
- y lo peor es que en el intérprete no chequea reasignaciones de un const. Es solo el validator el que las corre, y encima ahora tira warning en lugar de error.

Por todo lo dicho antes, me parece que no vale la pena invertir tiempo ahora, voy a cerrar el issue y en otro momento lo volvemos a discutir. A mí me parece que sería bueno definir un comportamiento consistente, porque si no es como el chiste de la diferencia entre la teoría y la práctica.
