### ISSUE TITLE
REPL doesn't show "" for Strings in collection

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1563]
The representation string for these cases are the same
```scala
>>> [1,2,3]
[1, 2, 3]
>>> ["1","2","3"]
[1, 2, 3]
>>> ["1, 2, 3"]
[1, 2, 3]

>>> #{1,2,3}
#{1, 2, 3}
>>> #{"1","2","3"}
#{1, 2, 3}
```

When Strings and Numbers have different string representations:
```scala
>>> 1
1
>>> "1"
"1"
```

**Comment by fdodino** [comment]
Nico proponía pasar a nativos los toString() sin decir `override`.
Fer propone ver si con agregar las `"` en String tenemos lo que queremos.
