### ISSUE TITLE
Wollok no toma en cuenta al definir un método abstracto que una property la pueda redefinir

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1564]

**Comment by fdodino** [comment]
Me pasó que al refactorizar un TP de Wollok Game tenía algo como

```xtend
class Arma {
    method bla() {
       const artefacto = self.artefacto()
       ...
   }

   method artefacto()
}

class EspadaVisual inherits Arma {
      const property artefacto = new Espada()
}

class Espada {}
```

Wollok te marca que no podés instanciar una clase EspadaVisual porque no implementa el método abstracto artefacto.

**Comment by fdodino** [comment]
Jajaja, pero no lo resolví, solamente lo detecté.

**Comment by matifreyre** [comment]
Ah... decía "Ready"... esos labels confunden, debería ser "Ready for
development". Entonces es un "a mí también me pasó".

**Comment by npasserini** [comment]
No es mala idea cambiarlo, pero ojo chequear que no se rompa el waffle (y
taiga?)

**Comment by npasserini** [comment]
@JavierGelatti Esto ya se puede cerrar, no?

**Comment by npasserini** [comment]
@JavierGelatti @fdodino Ping.
