### ISSUE TITLE
[TS] Ave does not understand vola()

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1569]
This program:
```scala
class Ave {
	var property energia
		
	method come() {
		energia += 3
	}
}

class Golondrina inherits Ave {
	
	method vola() {
		energia -= 10 
	}
	
}

object entrenador {
	method alimentar(ave) {
		ave.come()
	}
	
	method queVuele(golondrina) {
		golondrina.vola()
		self.alimentar(golondrina)
	}
}

object wollok {
	method testEntrenador() {
		entrenador.alimentar(new Ave())
	}
}
```
Shows these errors:
```
Ave does not understand vola()
Type system: expected <<Ave>> but found <<Ave>>
```
It's trying to infer `entrenador.queVuele :: (Ave) => Void`.
I suspect that something is wrong with MinType inference, because all errors disappear when you add a call to the method with a Golondrina: `entrenador.queVuele(new Golondrina())`

**Comment by npasserini** [comment]
Los errores del tipo
```Type system: expected <<Ave>> but found <<Ave>>```
ya están solucionados en https://github.com/uqbar-project/wollok/tree/fix-%231425-map-method
Espero mergear eso pronto.

**Comment by PalumboN** [comment]
Y el error
```
Ave does not understand vola()
```
Se debería arreglar con https://github.com/uqbar-project/wollok/issues/1587
