### ISSUE TITLE
¿Cómo tipar los objetos que están en una celda de game?

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1586]
El siguiente programa da error (tomado de https://github.com/wollok/sokobanGame):

```	method validarLugarLibre(direccion) {
		const posAlLado = direccion.posicionDeAlLado(posicion) 
		var lugarLibre = game.getObjectsIn(posAlLado)
			.all{ obj => obj.puedePisarte(self) } 
		
		if (!lugarLibre) 
			throw new Exception("Algo traba la caja.")
	}
```

El tema es que getObjectsIn es un método genérico que devuelve List<Any> entonces no hay forma de hacer nada con los objetos recibidos que no de un error de tipos.

La forma tradicional que yo veo en lenguajes pasa por:
- A la Java permitir un casteo, el programador especifica el tipo.
- Más moderno, indicar al linter que ignore esa línea.

Una idea que me gustaría experimentar es tener una anotación de tipo especial para eso, que indique que puede ser cualquier cosa, que no sabemos qué es y que le dé la derecha al programador.

En este caso podría funcionar que ese método tuviera un generic "global" y calcular cuál es el tipo posta en función de usos que tengan los métodos que agregan cosas al tablero. Pero eso sólo funcionaría si todos los objetos en el tablero son polimórficos, así que me parece que no alcanza.

**Comment by PalumboN** [comment]
> En este caso podría funcionar que ese método tuviera un generic "global" y calcular cuál es el tipo posta en función de usos que tengan los métodos que agregan cosas al tablero.

Siiiii yo quería algo así :+1: 

> Pero eso sólo funcionaría si todos los objetos en el tablero son polimórficos, así que me parece que no alcanza.

No, en realidad todos los que estén en esa celda deberían ser polimórficos. O sea, yo esperaría que cada llamada de `game.getObjectsIn(pos)` devolviera un _List de cosas particulares que se infieren por el uso_, que no tienen por qué ser todos del mismo tipo.
Y no me calentaría si el programador la manquea en la construcción del juego y termina llegando un objeto que no cumpla con la interfaz que se infiere, en el peor de los casos fallará en ejecución con un MDU (o hasta se  podría lanzar un error de tipos en ejecución, como si fuera un error de casteo). Pero por lo menos podemos checkear que existe un tipo consistente con los mensajes que se les manda.

**Comment by PalumboN** [comment]
Lo mismo pasa con:
```xtend
		Position >> "allElements" === #[] => List.of(Any)
		game >> "whenCollideDo" === #[Any, closure(#[Any], Void)] => Void
		game >> "getObjectsIn" === #[Position] => List.of(Any)
		game >> "colliders" === #[Any] => List.of(Any)
```
