### ISSUE TITLE
El código del método tiene que tener preponderancia para calcular tipos sobre sus usos

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1587]
Este método no tipa por #1586.
Sin embargo el mensaje que relaciona `unElemento` con la celda de game no está aquí sino en otro lado, este método sí se puede tipar, el error no debería aparecer acá.

(Ver ejemplo completo en https://github.com/wollok/sokobanGame)

```
	method empuja(unElemento) {
		try
			unElemento.movete(direccion)
		catch e {
			self.retrocede()
		}
	}
```

**Comment by npasserini** [comment]
El error se reproduce o no dependiendo del orden en el que se analizan los archivos del proyecto.

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok/issues/1526
