### ISSUE TITLE
Detect assignment to same variable as error

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#160]
```
routeHandler = routeHandler
```

**Comment by npasserini** [comment]
Does not seem to work in v1.1

**Comment by javierfernandes** [comment]
Works for me in dev (1.2)
<img width="110" alt="screen shot 2015-09-18 at 09 03 59" src="https://cloud.githubusercontent.com/assets/4428120/9958846/3e2996c4-5de4-11e5-8625-bce98e839597.png">
