### ISSUE TITLE
How to create Wollok Splash Screen

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1601]
Should be great add those instructions to wiki: https://github.com/uqbar-project/wollok/wiki/Deploying-Wollok

**Comment by fdodino** [comment]
Sure! I'll add it to the wiki from a previous mail.

**Comment by fdodino** [comment]
By the way @PalumboN @npasserini 
![hypatia3](https://user-images.githubusercontent.com/4549002/54156098-45149900-4424-11e9-932e-5ea3da529bea.png)
, here's my gift (a jpg, and not a gif :smile:)

**Comment by fdodino** [comment]
New wiki page added:

https://github.com/uqbar-project/wollok/wiki/Splash-screen

I'm also creating a new PR, but locally I can't build with maven.

**Comment by PalumboN** [comment]
Thanks @fdodino !!! :dancer:
