### ISSUE TITLE
Type System not working in v1.7.3

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1604]
I downloaded Wollok for Linux-64.
Create a new project.
Activate Type System.
And everything is typed as `Any` :(

**Comment by npasserini** [comment]
Creando proyectos simples, encuentro que el TS funciona correctamente. Creo que se está mambeando con algún caso no considerado. En particular encontré este problema en https://github.com/wollok/multipepita/tree/alternativa

![Screenshot from 2019-03-20 09-45-11](https://user-images.githubusercontent.com/4633913/54685401-77de2180-4af5-11e9-8c6c-0d7fec1d68b1.png)

@lspigariol @PalumboN 
¿Alguien de los que reportó tener este problema ve un error parecido?
Como para quedarnos tranquilos de que en todos los casos el problema viene por acá.
Y de paso si me pueden marcar en qué proyectos les pasa podemos tratar de sacar qué tienen en común.

Una cosa notable es que al agregar multipepita al workspace se rompen incluso proyectos que andan bien si cerrás el proyecto problemático.

Una sospecha es que multipepita tiene definidos objetos con el mismo nombre en diferentes archivos (lo que está bien, pero tal vez el TS no lo está soportando adecuadamente). Si encuentran proyectos problemáticos porfa fíjense si tienen esa característica.

**Comment by lspigariol** [comment]
bien!
cerré los 4 o 5 proyectos que tenía abiertos, dejé solo un hola mundo, y
funciona correctamente el TS.
voy a buscar a ver qué es lo que lo altera y aviso

**Comment by lspigariol** [comment]
encontré una pista, que puede ser  detonante de la falla: los archivos de
test.

hice tambien la siguiente prueba:
un proyecto con solo un archivo wlk, funciona bien.
cuando agrego un archivo de test, se tilda. Si elimino el archivo vuelve a
funcionar

al abrir proyectos que tienen tests, generalmente falla, pero en algunos
casos funciona bien y no logro encontrar un patron
por ejemplo, en un proyecto que ya tiene test, creo un nuevo arvhivo de
test, y sigue funcionando bien
