### ISSUE TITLE
Errors should not prevent Wollok programs from running!

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1606]
El otro día me pasó que Wollok me volvió loco con sus restricciones a lo que se puede hacer y lo que no. No es que estén mal las validaciones, son perfectas, pero es un impedimento grande para el docente no poder correr los programas con errores.

Por ejemplo este programa

method estaFeliz() { if (energia > 50) return true }
Me gustaría poder correrlo, mostrarles qué pasa cuando intento usarlo.
Pero no puedo, sólo me da error.

Lo mismo si quiero jugar con los booleanos y hacer true && false en el repl, no me deja.
Es muy frustrante.

Propongo que 
1) Siempre se pueda ejecutar un programa no importa los errores que tenga (o lo más parecido a eso posible).
2) Cualquier programa que "anda" no puede estar marcado como error, deben ser warnings.

**Comment by lspigariol** [comment]
Estoy de acuerdo.

Ya lo hablamos algunas veces y debe estar escrito en algun doc o mail.
Coincido en que hay que advertir, pero sin impedir la ejecución.
Si hilamos más fino, podriamos tener una categorización de warnings para
diferenciar este tipo de situaciones de las del ts y otras

**Comment by fdodino** [comment]
De acuerdo a lo que hablamos con @PalumboN @npasserini
Errores de linker, parser, debería marcar la unidad (no todo el proyecto).
Después, algunas validaciones tiene sentido marcarlas como error (hay que consensuar la categoría).
El resto, debería ser warning.
Otra opción es impedir la ejecución de un método, en lugar de esa unidad de código.

**Comment by npasserini** [comment]
Decisiones
a) Sólo se considera error lo que es "bloqueante", es decir, 100% de seguridad de que al ejecutarlo no va a andar.
b) Errores bloquean la ejecución, pero sólo a nivel "unidad", es decir un test o un método.

Acciones:
1) REPL tiene que considerar la configuración de error-warning.
2) Revisar las configuraciones de todos los validadores y garantizar que sólo está marcado como error lo que sea bloqueante (según decisión a).
3)  Tests y métodos no deberían ejecutarse si tienen errores (see #1626).

**Comment by lspigariol** [comment]
me parece genial el avance
