### ISSUE TITLE
Más usos para el diagrama dinámico

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1610]
Me gustaría poder ver el estado del diagrama dinámico en más situaciones... claro, lo ideal sería un debugger, pero me pregunto si hay alguna versión intermedia antes de ir por eso.

Por ejemplo abrir el estado al finalizar un fixture o en el momento que falla un test. 
Si me dejan fumar quiero poder ir para atrás y para adelante :)

**Comment by fdodino** [comment]
Definitivamente queremos eso, pero me parece que hay que suspenderlo para la próxima versión.

**Comment by fdodino** [comment]
Refloto esto para jugar un poco y tenerlo después de un test o de un programa...
