### ISSUE TITLE
Consume 1gb de RAM cuando ejecuta el Repl

### ISSUE THREAD

**Issue by Maruu32** [uqbar-project/wollok#1618]
![image](https://user-images.githubusercontent.com/9415724/55038819-d6793300-5000-11e9-9e1e-e271a8bbc652.png)

**Comment by PalumboN** [comment]
Al parecer el problema está al mandar a ejecutar es REPL (flechita verde) muchas veces sin pararlo antes (botón rojo)

**Comment by fdodino** [comment]
Hay que matar el proceso Repl cuando se inicie el nuevo repl.

**Comment by fdodino** [comment]
![issue1618](https://user-images.githubusercontent.com/4549002/60402669-1d7b4500-9b69-11e9-8328-c108831b403d.gif)

Testeado en Win10
