### ISSUE TITLE
Cuando pruebo mi codigo en el REPL a veces falla

### ISSUE THREAD

**Issue by Maruu32** [uqbar-project/wollok#1619]
![image](https://user-images.githubusercontent.com/9415724/55040671-21e30f80-5008-11e9-9305-c0595d578fc5.png)
Cuando dejas el cursor directamente a la izquierda del paréntesis ")" y apretas intro tira el primer error de la imagen.

**Comment by Maruu32** [comment]
Estoy usando wollok 7.1.4 en windows 10. 
Quiero aclarar que esta bien escrita la primer linea pero al apretar el intro evidentemente primero ejecuta un enter como lo conocemos en un editor de texto y después ejecuta, por eso se ve el salto de linea.

**Comment by 51lv3str1** [comment]
me parece notable que en la imagen se nota que en la primera ocasión , se ve que se produce un salto de linea y afecta el resultado, pero en la segunda ejecución no y falla también peroooo en la tercera ejecución... funciona.

**Comment by fdodino** [comment]
Cerramos el issue hasta tanto podamos replicarlo
