### ISSUE TITLE
Error de TS en el metodo max()

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1621]
en esta linea

`return empleados.max({e=>e.cuantasDonas()}) `

da el error

`Sistema de tipos: se esperaba <<(Date|Number|String)>> pero se encontró <<Number>>`

cuantasDonas() es polimorfico y en todos los casos devuelve Number

El codigo funciona correctamente

![image](https://user-images.githubusercontent.com/11738011/55369887-d4b2e200-54ce-11e9-8ade-67732f210984.png)

https://github.com/wollok/Ejemplo-Colecciones-Simpsons

**Comment by fdodino** [comment]
Hay que arreglar `max` junto con otros métodos de collection.
Ver collections.wlk.xt
