### ISSUE TITLE
Wollok game necesita OpenGL 2.0 o superior

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1622]
Hay que tener en cuenta esto para cuando se use en clase. Estaría bueno documentarlo en algún lado.

**Comment by fdodino** [comment]
Sí, la respuesta es https://www.wollok.org/documentacion/conceptos/ dentro de WollokGame

**Comment by fdodino** [comment]
@lspigariol te copás a agregarlo en el sitio?

**Comment by lspigariol** [comment]
Bien...
Y alguna orientación para el que no tenga esa versión?

**Comment by fdodino** [comment]
Buscando links encontré [éste](https://community.khronos.org/t/where-to-download-opengl-2-0/23758/3) cuya respuesta de ZbuffeR me llevó a 

https://www.khronos.org/opengl/wiki/Getting_Started

que te dice cómo instalarlo.
