### ISSUE TITLE
Objetos duplicados en el Intérprete

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1624]
Ejemplo:
![Peek 2019-04-13 14-42](https://user-images.githubusercontent.com/4098184/56086356-aec10200-5e2b-11e9-942f-7daf36dec97a.gif)

Falta discutir qué medida tomar al respecto (que puede ser que quede así).
**Solución:** evitar que el intérprete duplique el 2 si ya lo encontró.

**Comment by fdodino** [comment]
Bingo!
Encontré el tema

![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d196abdd1606700156ee30f)

Esto empezó a pasar cuando unificamos números. El error está en el intérprete

**Comment by fdodino** [comment]
![issue1624](https://user-images.githubusercontent.com/4549002/60408431-34379100-9b95-11e9-90f4-dbed42cca22c.gif)

**Comment by npasserini** [comment]
¡Qué grosso Fer!

Igual yo insisto que los criterios de identidad son conceptuales y no
físicos. Que yo diga que hay un único 1 no necesariamente significa que el
intérprete funcione de esa manera, que haya una única representación del 1
en memoria. Sólo significa que el sistema se compora "como si" eso pasara.

No me parece mal si el arreglo se hace a nivel intérprete, salvo por algún
concern a nivel performance, ¿en cada cuenta estamos buscando si el mismo
número está en algún lugar de la memoria? ¿eso no es destructivo a nivel
performance? ¿si lo hacemos a nivel diagrama no es más liviana la solución?

**Comment by fdodino** [comment]
La verdad es que no hay mucha diferencia a nivel performance, habría que hacer una prueba con 1.000 ó 10.000 números, pero mi percepción es que es mejor tener una cache de objetos antes que tener que instanciarlos n veces (debería ser mejor solución en términos de rendimiento). Porque la búsqueda es con un mapa, anda bastante bien.

Y de paso... es más fácil para el diagrama no tener que simular la identidad de dos objetos, lo único que tuve que tocar en algún momento son las referencias circulares.

**Comment by npasserini** [comment]
Sí, 100% de acuerdo, sólo quería dejar picando la idea. No vi el PR
todavía, espero ponerme esta noche pero supongo que lo mejor es avanzar con
esta estrategia y eventualmente si hay un problema de performance ya nos
vamos a dar cuenta.

**Comment by fdodino** [comment]
:+1: 

En algún momento tengo pendiente sentarme con vos a revisar el intérprete
