### ISSUE TITLE
El Diagrama dinámico no se limpia al iniciar un REPL

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1625]
![Peek 2019-04-13 14-43](https://user-images.githubusercontent.com/4098184/56086395-eb412d80-5e2c-11e9-9635-3cf3f41fba3f.gif)
Eso hace que a veces, cuando se van haciendo cambios a un ejercicio por ejemplo, hayan dudas sobre el estado actual (en realidad inicial, porque después se actualiza) de los objetos.
Tal vez estaría bueno limpiar el diagrama cuando se inicia (o mate) el REPL.

**Comment by fdodino** [comment]
WollokRepl.startRepl() line 57.
We should add a new `initialize()` method for WollokInterpreter, delegating to each listener (WollokDynamicDiagram...)
