### ISSUE TITLE
Tests con nombre duplicados NO corren

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1626]

**Comment by fdodino** [comment]
Related to #1629, so what to do when you have two tests with the same name

textX -> Ok
testX -> Running

**Comment by fdodino** [comment]
@PalumboN , Wollok le avisa con errores que los tests están duplicados, cuando los querés ejecutar te avisa que hay errores nuevamente, la forma de identificar unívocamente entre ambas VM (la que interpreta los tests y la que muestra los resultados) es por el nombre, entonces la VM que muestra no tiene forma de saber si es el primer o el segundo test, por eso se pisa el resultado del primer test con el segundo:

![issue1626](https://user-images.githubusercontent.com/4549002/69860941-048cd200-1276-11ea-94cb-f8ac0d46d08d.gif)

Me parece que es una solución _good enough_ y dado que estamos buscando mejorar las herramientas de wollok-ts, yo cerraría el ticket si me lo permitís :stuck_out_tongue:

**Comment by PalumboN** [comment]
:ok_hand:

**Comment by npasserini** [comment]
Y pero hace flata identificarlo por nombre? Por qué no le ponemos un id
autonumérico y listo?

**Comment by fdodino** [comment]
Con el tema de tener varios describes en el mismo archivo no es tan simple, tendríamos que buscar un id de cada describe e internamente un id por cada test. A mí particularmente me parece que es un cambio que no trae beneficios para un estudiante y trae como consecuencias un costo demasiado alto de desarrollar (hay que cambiar toda la estructura con la que pasamos info entre ambas VM). Más si no tiene sentido definir dos tests con la misma descripción y están saltando validadores para que no lo haga.

**Comment by npasserini** [comment]
El id del test incluye el del describe que lo contiene? Porque si no lo
incluye entonces me parece una situación batante posible de ocurrir/tener
sentido.

**Comment by fdodino** [comment]
Sí, lo tiene y es una de las pruebas que hicimos: vos podés definir dos tests con igual descripción en distintos describes y no se confunden

**Comment by npasserini** [comment]
Ok
