### ISSUE TITLE
Workspace Initial Build no avanza (Workspace corrupto?)

### ISSUE THREAD

**Issue by leodelgadodev** [uqbar-project/wollok#1628]
Ocurrió al intentar hacer el primer Commit & Push del primer ejercicio usando github. Apareció este mensaje con la barra que nunca más avanzó. Los archivos no pudieron pushearse adecuadamente al repo. Aún intentando cancelar el mensaje siguió apareciendo. No pude hacer más nada porque cualquier acción (guardar un archivo, importar, exportar, ejecutar un test, etc.) la bloqueaba hasta completar Workspace Initial Build (que nunca iba a pasar), es el caso de la segunda foto.

La solución fue borrar el workspace y crear uno nuevo. Acá dejo el workspace corrupto: 
https://www.mediafire.com/file/198yx466dt2qimr/workspace_viejo.zip/file

![15-04-2019-18:45-29s-1920x1080](https://user-images.githubusercontent.com/46352908/56462566-ade41f00-639b-11e9-8c5f-c4bfff134a18.png)

![15-04-2019-18:44-58s-1920x1080](https://user-images.githubusercontent.com/46352908/56462569-bd636800-639b-11e9-8bd2-2c56d3634dbe.png)

**Comment by fdodino** [comment]
Muchas gracias! Estaremos viendo el issue y te avisaremos por acá cualquier novedad.

**Comment by fdodino** [comment]
IMPORTANTE: Probar de sacar las dependencias entre archivos wlk

Concretamente

```java
import wollok.vm.*
```

en lib.

**Comment by fdodino** [comment]
Bueno @leodelgadodev, me bajé tu workspace y el problema es que efectivamente no tiene la estructura de proyecto que Wollok necesita (falta un .project). Pero no se cuelga independientemente de las mejoras que introduje, porque se ve que al ejecutarlo desde cero no pasa. Voy a cerrar el issue ya que tenemos el #1210 que puede reproducir el incidente.
