### ISSUE TITLE
Git plug Git Plug at window close after adding files to commit

### ISSUE THREAD

**Issue by isaiaslafon** [uqbar-project/wollok#1631]
When ussing the **Git plug** in (Wollok version **1.7.6**) after add files to commit but not commiting, when **closing** the **Git windows** get an **Error at reopen**, when is commented in the right window of the commit it get the error at close. 
 This error stop continue working, if you try to do anything the error reapear. Hav eto close Wollok and re-run.

**WOLLOK VERSION:**   1.7.6
**SO:**    WIndows 7 x64 SP1
**JAVA JDK:**   8 Update 201
**WOLLOK FOLDER LOCATION:** C:\Wollok\
**HARDWARE:**  Intel I3 2350M  2x 4GB of RAM

![error git 1 before commit and push](https://user-images.githubusercontent.com/49459637/56960519-7f96da00-6b27-11e9-9bab-f65d4c69c6f9.png)
![error git 2 after close and repopen git window (sometime crash at close if it commented](https://user-images.githubusercontent.com/49459637/56960517-7f96da00-6b27-11e9-9d69-e60ad5e717ec.png)

![error wollok git tab close and reopen without commit and push](https://user-images.githubusercontent.com/49459637/56960520-7f96da00-6b27-11e9-8f5f-aa06c3165a0c.png)

**Comment by fdodino** [comment]
@PalumboN, podrías clonar el issue para Lucas? Gracias!

**Comment by PalumboN** [comment]
Done!

**Comment by isaiaslafon** [comment]
Son unos Cracks!!! Vamo' Wollok Team!
