### ISSUE TITLE
Property is never assigned

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1634]
Actualmente está marcando atributos que nunca se asignan para las properties:
![Peek 2019-05-04 17-00](https://user-images.githubusercontent.com/4098184/57184201-3ed3f380-6e8e-11e9-91ff-9e3146dd7c4c.gif)

Pero no tiene en cuenta que se puede hacer desde el setter (como está pasando acá).

Creo que lo más fácil es sacar esa validación cuando el atributo es property, y en otra iteración validar que se esté llamando al setter (usando el TS).

**Comment by fdodino** [comment]
Cambiar el mensaje a "Variable could be never assigned."
