### ISSUE TITLE
Game: los errores aparecen como mensaje del último visual agregado

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok#1658]
No importa qué objeto arroje el error, el diálogo siempre aparece en el último visual que se haya agregado.

![image](https://user-images.githubusercontent.com/1585835/58638310-e34d2800-82ca-11e9-9367-0fe524ed353c.png)

En este ejemplo, el error lo tira el comedero con este método:
```wollok
method validarRacionesSuficientes() {
	if (raciones == 0) { 
		self.error("No tengo más comida")
	}
}
```

Pero se ve en la vaca, porque se agrega última:

```wollok
const elComedero = new ComederoNormal()
game.addVisual(elComedero)

var animalActual = new Vaca()
game.addVisual(animalActual)
```

Si invierto los llamados a `addVisual`, todos los errores aparecen en el comedero.

**Comment by PalumboN** [comment]
Existe `game.errorReporter(visual)` que sirve para eso (creo). El ~~problema~~ feature es que ese objeto va a reportar todos los errores.
Me gustaría tener algo más inteligente. Además de loggear el error por consola que ahora no se hace y estaría bueno (no recuerdo si ya hay un issue sobre esto).

**Comment by faloi** [comment]
Sí, lo vi, pero no me sirve: lo que a mí me gustaría que pase es que el
mismo objeto que tiró el error sea el que muestre el mensajito.

Me parece que ese comportamiento es el más razonable para usar como
default. De hecho, fue un estudiante que acababa de aprender cómo tirar
errores el que se extrañó por la forma en que funciona ahora.

**Comment by npasserini** [comment]
Coincido en que estaría bueno, peeeeero, está lejos de ser fácil. No sólo
de implementar sino incluso de definir "qué objeto tiró el error". Por
ejemplo:
-  si pepita quiere comer manzana y le manda un mensaje a la manzana que no
entiende, ¿quién tiró el error? (ambos objetos visuales)
- ahora si pepita le manda un mensaje a la manzana, que la manzana sí
entiende, pero le manda un parámetro erróneo y entonces es la manzana la
que le manda un mensaje que no entiende a un objeto no visual, ponele un
número, ¿dónde queremos ver el error?
- y eso se complica más si la excepción ocurre dentro de un bloque, porque
tenés un stack trace más grande dentro, que el usuario no ve.

Imagino que una primera aproximación es pensar si, ante un DNU, ¿quién es
el objeto que tira el error? ¿el que manda el mensaje o el que lo recibe?
No estoy seguro de qué es mejor, ¿qué opinan?

Luego está el tema de considerar los objetos no visuales imagino que ahí
uno querría burbujear hasta encontrar un objeto visual, ahí entran los
problemas de implementación.

Tendríamos que armar una especificación tratando de tener en cuenta todos
los casos posibles. Y sospecho que es posible que haya que toquetear el
intérprete para implementarlo, no lo vas a poder hacer en el módulo de
game. Tal vez vale la pena juntarse un día a pensarlo bien.

**Comment by PalumboN** [comment]
Ok, yo tengo esta opinión:

Si hay un error de programación (como MNU) no estoy seguro si quiero que lo
diga un objeto del tablero... Tengo mis dudas.

Por lo gral (de lo juegos que hago) cuando quiero que un objeto hable es
porque estoy tirando una excepción de mi dominio, que lanzo yo.

Entonces, no se podría tener una WollokGameException que reciba el objeto
visual por parámetro?

De cualquier forma, creo que cualquier tipo de excepción debería ser
logeada en la consola.

**Comment by faloi** [comment]
Yo coincido con Nahue, los errores que me gustaría que se vean en el juego son los que lanzo adrede en mi dominio. En nuestro curso, eso lo hacemos exclusivamente con `self.error`, no usamos `throw`.

Si `self.error` (o un método nuevo) tirara un tipo de excepción que luego se atrapara en WG para mostrar un mensajito, eso sería todo lo que pretendo. Sobre las otras excepciones no sé... que se logueen me parece bien, incluso creo que me parecería bien que el juego crashee y se cierre.

**Comment by lspigariol** [comment]
simplemente recuerdo las ideas de incluir una sintaxis especifica para
excepciones, tal vez sea un camino para resolver también esto.

**Comment by npasserini** [comment]
Mmm... pero hacer que self.error tire algo específico de game no me cierra,
está acoplando cosas medio raras.
A lo mejor se podría hacer game.error(...).

La opción que propone Nahuel me parece conceptualmente limpia, pero tiene
el problema que no se puede aplicar antes de ver clases y wollok game a mí
me gustaría poder introducirlo antes que clases.

Lo de la sintaxis específica que propone Lucas, es algo para pensar con más
tiempo, a mí personalmente me parece que el camino va medio en la dirección
opuesta, creo que lo especial del manejo de excepciones debe estar en el
manejo de flujo throw/catch y no en el objeto throwable, entonces agregar
una sintaxis específica creo que no ataca el punto central de donde
queremos ir. Pero bueno, es un tema largo y da para charlar un montón... en
todo caso no veo bien cómo afectaría acá.

**Comment by faloi** [comment]
Yo no proponía modificar `self.error` para que tire un error de Game. Lo que digo es que, tal vez, el error que arroja ese método podría ser considerado "de dominio", y por defecto atrapado por Game.

Buceando un poco en el código de Wollok, veo que `error` tiene esta definición:
```wlk
method error(message) {
  throw new Exception(message)
}
```

Mi propuesta sería modificar eso para que tire una excepción "de usuario" que luego sería atrapada por Game. No sé cómo afectará eso al código de Wollok ni tampoco sé cómo enseñan excepciones en otros cursos, hablo siempre desde la propia experiencia.

Lo de `game.error` no me agrada mucho, pero no me molestaría tener que hacerlo para salir del paso.

**Comment by npasserini** [comment]
No está mal la idea.

**Comment by PalumboN** [comment]
Me parece bien. Entonces pasando un poco en limpio y pensando en la implementación:

- Hacer que `self.error` tire una `DomainException`. También le agregaría un "owner" (no sé si es el término que quiere) que sería el objeto que lanza la excepción (self).
- WollokGame debería atrapar todas estas excepciones y
  - Si tienen owner y está en el tablero -> hacer que ese objeto diga el error.
  - Sino, queremos que siga con la lógica actual?? A mi no sé si me convence mucho el `errorReporter` pero no jodería dejar eso como está, por las dudas
- Además debería loggear el error por consola.

Algo que me quedó picando:
El resto de las excepciones que NO son de dominio, las debería atrapar igual o hacer que se rompa todo? Yo estaría tentado a hacer que se rompa todo, pero no sé si eso va a interferir en la forma que se desarrollan los juegos: yo veo que los estudiantes al principio tienen un montón de errores, de cosas del juego que todavía no encararon, pero quieren probar otras cosas. No me gustaría interrumpir eso... 
Tal vez sea mejor dejar eso como está: que no rompa todo, lo diga el _error reporter_ y (lo nuevo) se loguee por consola.

**Comment by npasserini** [comment]
El jue., 6 de jun. de 2019 a la(s) 10:11, Nahuel Palumbo (
notifications@github.com) escribió:

> Me parece bien. Entonces pasando un poco en limpio y pensando en la
> implementación:
>
>    - Hacer que self.error tire una DomainException. También le agregaría
>    un "owner" (no sé si es el término que quiere) que sería el objeto que
>    lanza la excepción (self).
>
> Me parece perfecto.

>
>    - WollokGame debería atrapar todas estas excepciones y
>       - Si tienen owner y está en el tablero -> hacer que ese objeto diga
>       el error.
>       - Sino, queremos que siga con la lógica actual?? A mi no sé si me
>       convence mucho el errorReporter pero no jodería dejar eso como
>       está, por las dudas
>
> Después de usarlo un tiempo, me parece que el error reporter no funciona
bien. Suele confundir a los chicos.
Se me ocurre que deberíamos tener una forma de reportar un error que no
esté asociada a ningún objeto. El mecanismo sería parecido pero mostraría
el error en un lugar "neutral".

Por otro lado, tal vez la confusión se mitigue fuerte haciendo lo que ya
estamos proponiendo cambiar, así que podríamos dejar esta parte como está y
ver si funciona mejor... pero bueno, depende de cuánto trabajo sea, si no
es mucho trabajo yo lo cambiaría y ya.

>
>    - Además debería loggear el error por consola.
>
> No estoy 100% seguor pero yo creo que no loggiearía los self.error por
consola, lo estás tirando vos el error, no lo veo necesario.

> Algo que me quedó picando:
> El resto de las excepciones que NO son de dominio, las debería atrapar
> igual o hacer que se rompa todo? Yo estaría tentado a hacer que se rompa
> todo, pero no sé si eso va a interferir en la forma que se desarrollan los
> juegos: yo veo que los estudiantes al principio tienen un montón de
> errores, de cosas del juego que todavía no encararon, pero quieren probar
> otras cosas. No me gustaría interrumpir eso...
> Tal vez sea mejor dejar eso como está: que no rompa todo, lo diga el *error
> reporter* y (lo nuevo) se loguee por consola.
>
> —
>
 Yo no rompería todo, las atraparía igual, pero habría que informarlas
mejor. Lo fácil es
- Informar en el tablero en un formato aprecido al que propuse para los
self.error sobre objetos no visuales
- Informar ahora sí en la consola con un stack trace.

La difícil pero muy cheta es parar la ejecución en ese punto para poder ver
el diagrama... no sé si eso es fácil.

**Comment by fdodino** [comment]
+1, suena toda una especificación para un Wollok gamer 😀

**Comment by faloi** [comment]
¿Cómo quedó esto al final? ¿Si llamo a `self.error` se lanza la excepción correcta?

**Comment by PalumboN** [comment]
Sí! Se implementó como habíamos hablado: lanza una DomainException y en WG el mensaje lo dice `self`

**Comment by faloi** [comment]
😍
¿Qué versión deberíamos usar para que esto ocurra?

**Comment by PalumboN** [comment]
1.8.4 ;)
