### ISSUE TITLE
StackOverflow con constantes globales en tests con describe

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1659]
Tengo este código:
```Wollok
object wollok {
	method numero() = numeroLoco
	
}

const numeroLoco = 87
```

Y este test:
```Wollok
describe "Tests" {
	test "Numero loco es 87" {
		assert.equals(87, numeroLoco)
	}
}
```

Falla con `StackOverflowException`

---------------

Aclaro que esto solo pasa cuando:
- El test está dentro de un describe
- Y se accede directamente a la constante

Sospecho que puede ser porque lo busca como atributo del describe (ya que teniendo el test solo anda bien).

**Comment by fdodino** [comment]
Sospecho que puede tener que ver con el SuiteBuilder:

```js
	def build() {
		// Suite -> suite wko  
		val suiteObject = new WollokObject(interpreter, suite)
		// Declaring suite variables as suite wko instance variables
		suite.members.forEach [ member |
			suiteObject.addMember(member)
		]
		if (suite.fixture !== null) {
			suite.fixture.elements.forEach [ element |
				interpreter.performOnStack(test, suiteObject, [| interpreter.eval(element) ])
			]
		}		
```

Concretamente, me parece que en esta línea

```js
				interpreter.performOnStack(test, suiteObject, [| interpreter.eval(element) ])
```

debería apuntar al suite y no al test como primer parámetro

**Comment by fdodino** [comment]
No, no es eso. :)

**Comment by fdodino** [comment]
El tema está acá:

```js
	def dispatch WollokObject evaluate(WVariableDeclaration it) {
		interpreter.currentContext.addReference(variable.variableName, right?.eval)
		WollokDSK.getVoid(interpreter as WollokInterpreter, it)
	}
```

**Comment by fdodino** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5cf2a77915f663000f4eebf6)

@PalumboN, @npasserini.
La solución fue detectar que la declaración de una variable puede ser global ahora:

```js
	def dispatch WollokObject evaluate(WVariableDeclaration it) {
		if (it.declaringContext === null) {
			interpreter.currentContext.addGlobalReference(variable.variableName, right?.eval)
		} else {
			interpreter.currentContext.addReference(variable.variableName, right?.eval)
		}
		WollokDSK.getVoid(interpreter as WollokInterpreter, it)
	}
```

Ese if me costó 4 horas, je. Pero me queda la duda ya que no estuve en la implementación, de si está ok eso, no terminé de entender cómo funciona en los programas y en los objetos (justo los dos casos de prueba que ya estaban definidos en `GlobalConstantsTestCase`)

**Comment by PalumboN** [comment]
Je, creo que este método te puede servir para ese if: https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend#L162

De paso miraría dónde se usa (seguramente haya un if similar a este) y si tiene sentido abstraerlo o no.

Sino tirá el PR y lo vemos :)

**Comment by fdodino** [comment]
Buen dato!

El _isGlobal_ se usa para asegurar la inicialización de las variables de un method container, para mostrar el fqn de wko (y ahora de constantes)... y ahora lo pondré también para hacer este chequeo. Hay otros chequeos que hace el validator, pero no el intérprete. Así que lo que hice fue agregar dentro del method dispatch la WVariableDeclaration:

```js
	def static dispatch boolean isGlobal(WVariableDeclaration it) {
		declaringContext === null
	}
	def static dispatch boolean isGlobal(WVariable it) {
		//eContainer instanceof WVariableDeclaration && eContainer.eContainer instanceof WFile
		declaringContext === null
	}
	def static dispatch boolean isGlobal(WNamedObject it) { true }
	def static dispatch boolean isGlobal(WParameter it) { false }
```

También me gusta más pensar en el declaringContext (lo usé en muchos lugares: validators, quick fixes, diagrama dinámico) y no en ser tan específico del container del container porque cualquier cambio que hacés en la gramática te deja mal parado.

>Sino tirá el PR y lo vemos :)
Obvio, estoy metiendo varios features de testing... :smile:

**Comment by fdodino** [comment]
Bueno, salió con algunos toques pero la idea general fue esa.
