### ISSUE TITLE
Reporter más verboso para los tests

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok#1660]
Cuando se corren los tests desde el https://github.com/uqbar-project/wollok-cli, estaría bueno que el output sea un poco más verboso.

Como ejemplo, va una parte de la salida de _rspec_ para Yanapiri:

```
Yanapiri::Bot
  #commit!
    should have author "Yanapiri <bot@yanapiri.org>" (FAILED - 1)
  #preparar_correccion!
    cuando no hay cambios
    cuando hay cambios
      sin proyecto Wollok
        should have branch "base"
        should have remote branch "base"
        should have branch "entrega"
        should have remote branch "entrega"
      con proyecto Wollok
        con transformación
        sin transformación
          should not include "<name>camion-transporte-warmichina</name>"
      con corrección ya preparada
        should have last commit message "Merge branch 'master' into entrega"
        should include commit with message "Creado solution.txt"
      con proyecto Wollok ya corregido
        should include "<name>camion-transporte-warmichina</name>"
  #aplanar_commits!
    should eq 1
    should eq ["master", "prueba"]
    should eq ["master"]
    should have branch "master"
    should have author "Yanapiri Bot <bot@yanapiri.org>"

Failures:

  1) Yanapiri::Bot#commit! should have author "Yanapiri <bot@yanapiri.org>"
     Failure/Error: it { expect(commits.last).to have_author 'Yanapiri <bot@yanapiri.org>' }
       expected #<Git::Object::Commit:0x000055958f0d5f50 @base=#<Git::Base:0x000055958f05e5e0 @logger=nil, @working_d...ail="federico.aloi@gmail.com", @date=2019-06-02 15:37:19 -0300>, @message="Un, dos, tres, probando"> to have author "Yanapiri <bot@yanapiri.org>"
     # ./spec/bot_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 5.11 seconds (files took 0.46619 seconds to load)
43 examples, 1 failure

Failed examples:

rspec ./spec/bot_spec.rb:17 # Yanapiri::Bot#commit! should have author "Yanapiri <bot@yanapiri.org>"
```

**Comment by fdodino** [comment]
Me gustaría que agreguemos acá una propuesta de ese output: sería similar al que provee el Stack trace del IDE? 
Y en el  ejemplo no estoy seguro qué output te da wollok y cual yanapiri, sería bueno arreglar entre nosotros para que quede claro esa diferencia.

**Comment by faloi** [comment]
La salida que pongo de ejemplo es de [rspec](https://rspec.info/), uno de los frameworks que hay para testear código Ruby - que sea de Yanapiri es anecdótico, es porque lo tenía a mano.

A mí me gustaría un output de ese estilo, donde se ven todos los tests que corrió y se indica si falló alguno: `should have author "Yanapiri <bot@yanapiri.org>" (FAILED - 1)`. Además, fijate que al final te agrega un resumen, porque si tenés muchos tests la línea que muestra el FAILED se te pierde.

**Comment by faloi** [comment]
Te quise grabar un GIF pero GitHub no me lo sube... mirá cómo se ve un output de un proyecto Ruby cuando falla: https://travis-ci.org/uqbar-project/yanapiri/builds/542502801

No se sí taaaan así pero algo intermedio que sea mejor que lo de ahora. Lo que se ve ahora es:
* nada, si pasan los tests;
* el error y el stack trace si falla algún test.

También sería bueno que se corran todos los tests, independientemente de si alguno(s) falla(n)....

**Comment by npasserini** [comment]
¿Y no muestra data detallada del test que falló, onda un stack trace?
Yo creo que un CI debería tirar ese detalle, odio cuando el CI falla y no
me dice por qué.

**Comment by fdodino** [comment]
Tira muy poca data, de eso doy fe porque solo aparece una línea que dice [ERROR].
Yo creo que debe ser un tema de configuración de log4j o algo así , por eso en principio trataría de mostrar el mismo stack trace que lo que te da el IDE.

**Comment by faloi** [comment]
Un ejemplo de algunos que fallan:

* [Error de sintaxis en el archivo de test](https://travis-ci.com/obj1-unahur-2019s1/huerta-de-toni-kevinmatias120/builds/113321213). (ok, se entiende)
* [Error de compilación](https://travis-ci.com/obj1-unahur-2019s1/huerta-de-toni-fabiola37/builds/114022679). (ok, se entiende)
* [Assertion failure](https://travis-ci.com/obj1-unahur-2019s1/huerta-de-toni-AgustinZucchi/builds/114022623). (no se sabe qué test falló)

Copio output abajo:
```
Ejecutando tests...
   ==>  ./src/Huerta.wtest
wollok.lib.AssertionException: Expected [430] but found [280]
	at org.uqbar.project.wollok.launch.tests.WollokExceptionUtils._generateAssertionError(WollokExceptionUtils.java:48)
	at org.uqbar.project.wollok.launch.tests.WollokExceptionUtils.generateAssertionError(WollokExceptionUtils.java:75)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.handleExceptionInTest(WollokLauncherInterpreterEvaluator.java:206)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:193)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:273)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:281)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:145)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.access$0(WollokLauncherInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator$3.apply(WollokLauncherInterpreterEvaluator.java:146)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator$3.apply(WollokLauncherInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.threads.WThread.performOnStack(WThread.java:62)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:362)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evalInSuite(WollokLauncherInterpreterEvaluator.java:149)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator$1.apply(WollokLauncherInterpreterEvaluator.java:93)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator$1.apply(WollokLauncherInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:102)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:269)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:178)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:104)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:78)
	at org.uqbar.project.wollok.launch.WollokChecker.launch(WollokChecker.java:161)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:90)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:43)
ERROR en el archivo ./src/Huerta.wtest. Por favor verifique que funcione correctamente.
```

**Comment by npasserini** [comment]
Sí, claramente ese stack trace no tiene sentido, creo que eso no está en
discusión.

En los casos que wollok se rompe en runtime, lo que debería aparecer es el
stack trace de Wollok, entiendo que es lo que dice Fer, es lo que pasa en
el IDE.

En los casos que falla un assertion... no sé si ese stack trace de wollok
es muy útil, creo que podríamos obviarlo. Es más interseante poner el diff
entre expected/actual y en todo caso la línea del test, no más que eso.

Los errores de sintaxis (o errores estáticos en general) no sé si tenemos
algo piola.

**Comment by faloi** [comment]
Ahí pude subirlo, vean el output de rspec a modo de ejemplo de una salida que a mí me gusta:

![Peek 2019-06-06 19-29](https://user-images.githubusercontent.com/1585835/59152679-8dd9ef00-8a1f-11e9-988f-ff9cde0b9dc8.gif)

**Comment by fdodino** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d00736e85316f000fa416d6)

Bueno, le falta todavía mucho más cariño @faloi, @npasserini @PalumboN, pero al menos aparecen los colorcitos y se vislumbra el stack trace (me faltó el mensaje de error, je)

**Comment by faloi** [comment]
:smiley:

**Comment by npasserini** [comment]
Excelente, excelente!

**Comment by fdodino** [comment]
Update: ![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d018f55f9378c000f0ee4fb)

Logré que Wollok haga exit 1 si falla alguno de los tests solo cuando lo ejecutás en Consola. No fue fácil porque tuve que saltar del WollokChecker > WollokLauncher - > al WollokInterpreter -> al WollokInterpreterEvaluator -> al WollokTestReporter y a la implementación concreta. Entonces tiro una excepción y hago que le llegue al WollokLauncher desenredando algunos cables que se estrangulan solos (el mecanismo de excepciones de Java con sus bemoles sigue siendo más cómodo que cascadear el call & return)

Voy a estar emprolijando un poco pero va a salir una nueva versión de wollok-cli con este toque y los jars que están en el branch `fix-tests`.

**Comment by faloi** [comment]
Muy bueno che. Y lograste también que se ejecute la suite completa aunque falle algún test (¿o quizás eso ya estaba y era que el output no lo mostraba?).

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/59399578-e59f8f80-8d6a-11e9-99c7-2b393d1dce23.png)

Sí, corren los suites (aclarando cuál es). Si un test falla los otros siguen corriendo, el exit 1 lo tira el Reporter de consola cuando terminan de ejecutar todos (sabe cuántos fallaron o tiraron error).

El error que se comía la consola era de wollok-cli porque lo grababa en un archivo result que usaba para parsear si había algún "ERROR". Eso funcionaba bien pero estaba muy acoplado por un lado y por otro no te permitía poner colores (con el comando `tee` lo podía mostrar por consola). Esto anda mucho mejor porque le pone colores y onda, aunque ahora tengo que arreglar los sanity tests, porque aparentemente un archivo wlk que no compila no está tirando un exit 1. Por eso le pedí a Nico que mergeara un PR que hizo él que sospecho hace lo que yo quiero.

**Comment by fdodino** [comment]
Pst, pst @faloi

https://travis-ci.org/wollok/introPepita/builds/545483985

Falta ajustar algunos detalles pero tenemos la versión deployada de wollok-cli 2.0

**Comment by faloi** [comment]
De lujo. Me quedan dos dudas:
* si hay varios archivos de test, ¿cómo se ve la salida?
* ¿sería posible agregar al final un resumen de la ejecución? Por ejemplo, algo así:
```
Finished in 5.11 seconds (files took 0.46619 seconds to load)
43 examples, 1 failure

Failed examples:

rspec ./spec/bot_spec.rb:17 # Yanapiri::Bot#commit! should have author "Yanapiri <bot@yanapiri.org>"
```

**Comment by fdodino** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02d585b042e2000faf9579)

Así se ve cuando tenés más de un test. Pero ojo al piojo, si falla alguno de los tests se corta:

![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02d5f285316f000fa44d9b)

Y sí, tenía en mente agregar un resumen final.

**Comment by faloi** [comment]
Ojo, lo del resumen lo pido porque intuyo que tal vez no te cueste tanto ahora y que luego te mate el context switch. Lo que hay ya está excelente, haber pasado de:

![image](https://user-images.githubusercontent.com/1585835/59472884-65366880-8e16-11e9-8df1-f0f1dc15dacf.png)


...a esto...

![image](https://user-images.githubusercontent.com/1585835/59472860-50f26b80-8e16-11e9-95e2-254f34ef8a81.png)


...no tiene precio.

**Comment by fdodino** [comment]
:)

Gracias!

Y sí, ahora me di cuenta de que no es complicado dejar que corran todos los tests y fallar al final, todavía tengo 1h 50' mientras los chicos de UNSAM siguen haciendo el parcial.

**Comment by faloi** [comment]
> mientras los chicos de UNSAM siguen haciendo el parcial.

Lo bueno es que lo vas a poder corregir vía GitHub, con colores y ejecución en la nube. :computer: :cloud:

**Comment by fdodino** [comment]
jajaja, en UNSAM no doy Wollok, doy todas las materias que le siguen...

**Comment by fdodino** [comment]
Bueno, ya le puse que corra todos los tests y falle si alguno falló:
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02de48b042e2000faf9613)

porque me lo pediste un montón de veces (?) y bueh...

**Comment by fdodino** [comment]
Y... se ve nomás la cantidad de tests, errores y fallas

![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02e472b042e2000faf9655)

**Comment by fdodino** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02efe7b21c58000ff9245b)

Ahí sí, sale 1 failure (sin la s), la cantidad de errores, el stack trace limpito, y de paso mejoré el stack trace filtrándolo de movida (algo que tenía que hacer hace rato). Sale deploy nuevo de wollok-cli....

![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d02f04fb21c58000ff9245e)

**Comment by npasserini** [comment]
Un detalle, es que estaría bueno evitar los stack traces que arrancan en
lang o lib.wlk.
O sea si la excepción es que dividí por 0 sería ideal que eso muestre el
lugar donde está el "x / 0" y no dentro de las clases del wdk.

(Ojo no sé si es para este ticket, sólo vi luz y opiné.)

**Comment by fdodino** [comment]
No hay problema, el momento para meter toquecitos-que-siempre-me-parecieron-piolas-hacer-pero-paja-de-abrir-un-issue es éste, tengo la mano caliente y lo hago cuando vuelva de la corrección de UNSAM (semana que viene seguro).

**Comment by fdodino** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d08e9b04858360015b0dee3)

Listo. Solo aparece en el stack trace código que escribió el alumno.

**Comment by npasserini** [comment]
Ahora sí tenemos todo lo que quieren las wachas.

**Comment by fdodino** [comment]
Le voy a meter algunos chiches más y ya lo largo al PR. wollok-cli ya tiene estos cambios para tirar en Travis, fíjense que incluso tiene un README.md nuevito: https://github.com/uqbar-project.wollok-cli
