### ISSUE TITLE
Game se cuelga al lanzar error con más de un salto de línea

### ISSUE THREAD

**Issue by LeaTex** [uqbar-project/wollok#1663]
Cuando se lanza una excepción en un Game, si el mensaje a mostrar tiene más de un salto de línea (`\n`), la ventana del juego queda colgada, los elementos dejan de responder, y la ventana ni siquiera se puede cerrar.

Código de pruebas:
```
import wollok.game.*

object wollok {
	var property position = game.origin()
}

program prueba {
	game.title("Prueba error")
	game.width(5)
	game.height(5)
	game.addVisual(wollok)
	keyboard.h().onPressDo { error.throwWithMessage("ayuda \n funcionando") }
	keyboard.e().onPressDo { game.error("ayuda \n que \n falla!!") }
	game.start()
}
```
Ocurre tanto con `error.throwWithMessage()` como con `anObject.error()`

**Comment by fdodino** [comment]
El problema estaba en Window de wollok.game, hay un while del que no logra salir cuando al aumentar el ancho nunca
puede disminuir el height:

```xtend
		while (glyphLayout.height > 29 {
			glyphLayout.reset
			plusWidth += 10
			this.setText(newText, baseWidth + plusWidth, color)
		}
```

Agregamos una condición: cuando el alto no cambia, detenemos el while.
