### ISSUE TITLE
la pagina de novedades no se carga al inicio

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1672]
desde la pagina de bienvenida al abrir wollok por primera vez, el link de novedades falla

**Comment by fdodino** [comment]
@lspigariol sería bueno si tirás la URL a la que está tratando de ir... o qué es lo que falla (un screenshot)

**Comment by lspigariol** [comment]
no se ve el link, pero los que fallan son
-novedades
-tutoriales

[image: image.png]

**Comment by fdodino** [comment]
ah, la página apunta a https://www.wollok.org/welcome/root.html
y https://www.wollok.org/en/welcome/root.html

Así que paso el issue a wollok-site: https://github.com/uqbar-project/wollok-site/issues/19 y cierro éste
