### ISSUE TITLE
advierte erroneamente sobre asignar la variable a si misma en parametros nombrados

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1673]
funciona bien si se hace
`new Algo( nombre = nombre) 
`

pero si se provoca un error en otro lado, por ejemplo
`new Algo( nombre = nombre, 18)
`
ademas del nuevo error del segundo parametro, advierte "no se puede asignar la variable a si misma"

**Comment by fdodino** [comment]
Lo muevo a Won't DO ya que vamos a deprecar los constructores

**Comment by fdodino** [comment]
Cierro el issue a la espera de eliminar los constructores para el 2020
