### ISSUE TITLE
Cambiar algunos toString de lang

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1692]
- **Date**: 
```wollok
>>> new Date(16,7,2019)
a Date[day = 16, month = 7, year = 2019]
```
Podría ser `16/7/2019` o `16-7-2019` o alguna otra?.

- **Pair**: 
```wollok
>>> 1->2
a Pair[x=1, y=2]
```
Qué les parece `(1 -> 2)`?
(No sé si me gustan los nombres de los atributos. No podría ser `key value` o `fst snd`?)

Actualmente las posiciones de WG tienen una implementación propia:
```wollok
>>> game.at(1,2)
(1,2)
```

**Comment by PalumboN** [comment]
@isaiaslafon si estabas buscando algún issue fácil para empezar este parece piola :+1:

**Comment by fdodino** [comment]
+1, definamos un formato de fecha así ya queda. A mí me gustaría más con /, pero si acordamos uno me da igual... En Date incluso hay un shortDescription implementado, fíjate Isa.

**Comment by npasserini** [comment]
¿No debería estar internacionalizado?

**Comment by fdodino** [comment]
+1 a hacerlo, no está hecho

**Comment by lspigariol** [comment]
para las fechas, prefiero el 16/07/2019
(hay que tener en cuenta que el aspecto va a ser el mismo que un string
pero por otra parte, me parece que algo que ayuda es que la representacion
de "entrada" sea lo mas parecida posible a la de "salida"
en las fechas, sin constructores, va a haber que hacer
new Date(day = 16, month=7, year = 2019)

para mantener el estilo y facilitar la instanciación en algunos contextos,
estaria bueno tener un metodo tipo
"16/07/2019".toDate()


de los pares, me quede pensando en lo que hablabamos el otro dia de pares y
posiciones.
yo decia que eran cosas diferentes, porque habia metodos que solo tenian
sentido en posiciones por ser numericos, tipo distance() left() right()
pensandolo mejor, se podria unificar y que lance excepcion si no es
numérico, como sucede con algunos metodos numericos. habria que ver que
consecuencias tiene para WGame.

en todo caso, la representacion podria ser la misma (3,4) (3,"hola") estilo
tuplas de haskell
y siguiendo la logica de la equivalencia entrada/salida, lo ideal seria que
se puedan construir tambien con (3,4) en vez de 3->4
(Dicho sea de paso, no es muy intuitiva usar una flecha para armar un par,
pero tal vez sea mucho quilombo hacer ese cambio)
por lo pronto, que los pares se muestren como se instancian, como decia
nahue, pero sin los ( )

>>> 1->21 -> 2

desvirtúo un poco... pero viendo tambien como se muestran los strings ¿no
seria mejor que siempre se muestren entre " ", para diferenciarse de otras
expresiones de diferente tipo con igual representación ?

**Comment by isaiaslafon** [comment]
Concuerdo con Nico que deberíamos internacionalizar la fecha, al menos para mostrar, o poner 2 métodos toString, uno internacional (el toString) y otro que se le agregue el formato tipo: date.toString("dd-mm-yyyy") y distintos formatos. Para ingresar como se nombran los argumentos/parámetros no requiere un orden específico.
 Sobre los pares me parece más amigable (2,3), pero también tenemos que ir acostumbrándonos los estudiantes a maneras distintas a las preconcebidas.
 Estaría bueno el .toDate(), pero quizás se podría poner una variante con "string".toDate("stringFormat")

**Comment by fdodino** [comment]
Yo no veo que necesitemos el toDate desde String, ni el date.toString("dd-mm-yyyy"), al menos por ahora. Acá me pongo medio celoso como Nico de no agregar métodos hasta que no los necesite, y me parece que mientras nosotros no pidamos esas cosas la interfaz de Date tiene lo que necesita un curso de POO.

Por otra parte, lo que sí creo que hay que hacer es reemplazar el método `toSmartString(booleano)` por un **native** en Java que considere el [Locale actual](https://stackoverflow.com/questions/35581921/localdate-format-with-locale).

**Comment by isaiaslafon** [comment]
Creo que cualquiera "/" o "-" estaría bien. Acá es más común usar "/" pero si no va a ser necesario por el momento el "aString".toDate() es más o menos lo mismo.
> +1, definamos un formato de fecha así ya queda. A mí me gustaría más con /, pero si acordamos uno me da igual... En Date incluso hay un shortDescription implementado, fíjate Isa.

**Comment by isaiaslafon** [comment]
Consultas:
¿El método shortDescription() de la clase Date deberia ser lo que responde toString()?
o deberian directamente llamar de WClass Date y cambiarlo ahí?
en java existen los metodos: toLocaleDateString()  "21/7/2019"
y toDateString()  "Sun Jul 21 2019"
pero esta clase Date guardan también el tiempo.

**Comment by fdodino** [comment]
Lo que yo haría es

En **la implementación de la clase Date de Wollok**

- el método toString que siga delegando a toSmartString(false)
- el método toSmartString que delegue a shortDescription sin importar si el parámetro es true o false
- shortDescription cambiarlo a un método nativo

toSmartString se usa por ejemplo para mostrar objetos dentro de una lista.
shortDescription lo usa por ejemplo el diagrama de clases

En Java/Xtend hay que

- definir el shortDescription en base al método que vos encontraste, usando getWrapped como valor (el Date interno) pero sin considerar la hora (cosa que entiendo nunca debería pasar)

**Comment by fdodino** [comment]
Dónde dije que shortDescription lo usa el diagrama de clases quise decir el dinámico

**Comment by ldevoto** [comment]
Buenas! 
Creé un [PR](https://github.com/uqbar-project/wollok/pull/1715) para el toString del Date y necesito una mano del que pueda 😄

**Comment by fdodino** [comment]
jajaja, dale, yo mañana a la noche me siento a verlo y te cuento...
Abrazo!!!!

**Comment by fdodino** [comment]
Released in 1.8.1 version!

**Comment by isaiaslafon** [comment]
Hi, I was testing Date Class. In the Dynamic Diagram show the date as "m/d/yyyy". I'm going to check the code in dev branch to see if It's use locale Date format or how is implemented. 
 Is fixed the issue that I test the other day of returning null when using methos like .pludDays(aNumber)  and similar.
  Sorry to be absent until today. I get sick and I couldn't go to the hackaton.

**Comment by isaiaslafon** [comment]
I check, and I can't find what make it show like that in the dynamic diagram ("m/d/yyyy"), but in the REPL show it correctly ("d/m/yyyy"), I think both use the shortDescription method, and this use the Locale Default, but I don't understand why Dynamic Diagram use a different Locale than REPL.

**Comment by npasserini** [comment]
Reabro este issue para que revisemos si está todo bien.

**Comment by npasserini** [comment]
Lo agrego al nuevo milestone para que lo revisemos y cerremos si correspondiere.

**Comment by fdodino** [comment]
Bueno, estamos siguiendo el issue en wollok-language, creo con seguridad que podemos cerrar este issue (ya que buscamos que el toString sea simple, aun tenemos que resolver el tema de los dates internacionalizados, pero el issue original está resuelto)
