### ISSUE TITLE
Range calcula mal su size

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1693]
Hay una propuesta en https://github.com/uqbar-project/wollok/pull/1668#discussion_r300215971

**Comment by PalumboN** [comment]
Ese comentario ya está implementado y mergeado :)

https://github.com/uqbar-project/wollok/blob/a3f6b1f708b751ccac7d208e9809e1e73507514d/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RangeTestCase.xtend#L69-L89

Creo que faltaría probar [este otro](https://github.com/uqbar-project/wollok/pull/1668#discussion_r303943455).

**Comment by npasserini** [comment]
Ah sí? Pensé que se había caído del PR. Lo cierro entonces. Ya creé otro issue relativo al otro comentario.
