### ISSUE TITLE
Imports in REPL are not correctly highlighted.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1707]
We should look in WollokCodeHighLightLineStyleListener

**Comment by fdodino** [comment]
```
resource program repl {
            import comidas.*
}
[XtextSyntaxDiagnostic: null:2 mismatched input 'import' expecting '}']
resource.syntax errors [org.eclipse.xtext.nodemodel.impl.LeafNodeWithSyntaxError@51406cdd]

```

Concatena el import dentro de program...

**Comment by fdodino** [comment]
Aaaah, casi lo tengo @npasserini !!

![image](https://user-images.githubusercontent.com/4549002/62008922-f2b3ea80-b12e-11e9-9dcd-c485a4ebf40b.png)

Mañana a la noche lo sigo...

**Comment by fdodino** [comment]
No pude con mi genio...

![importReplHighlight](https://user-images.githubusercontent.com/4549002/62016059-4140a380-b186-11e9-97f3-1f2ce5b4adac.gif)

Simplifiqué el algoritmo: me parece al cuete mandar a parsear por segunda vez solo para tener el highlight, quedó solamente el parseo que hace el REPL original (el que vos cambiaste). Entonces lo que hago es agregar un solo rango de estilos a mano, que incluye desde donde arranca hasta donde termina el import.

**Comment by npasserini** [comment]
Jajajaja, qué grande!!!!
