### ISSUE TITLE
Core objects should not appear in dynamic diagram

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1710]
Roots of the diagram should always be references defined by the user, such as:
- WKOs
- global consts
- REPL consts and vars

Core objects can only appear in diagram when referenced by a chain starting in one of those roots.

**Comment by fdodino** [comment]
Also, date object should have a different implementation. Since we are showing "01/07/2019", it's not worthy to show also its variables.

**Comment by fdodino** [comment]
Buenas...

![image](https://user-images.githubusercontent.com/4549002/62089915-3c8cf580-b241-11e9-8c85-401999185f58.png)

Detectar el tipo de variable no es tan simple, al menos dentro del intérprete una vez que se crearon los objetos. Pero creo que llegué a una solución lo suficientemente piola. Lo que hice fue lo siguiente:

- detecté que todas las variables root de los wko serían los `pepita.pepita` o bien `wollok.game.game`, `wollok.lib.console`, `wollok.lib.assert`, etc. A esos los estoy filtrando desde el intérprete. Pero si vos definís un `const a = game` sí aparece porque el nombre de la variable no arranca con `wollok.game`. Eso se genera como un método `isCustom()`. Hay una validación adicional que creo no hace falta, lo voy a chequear bien... (estoy pidiendo que sea wko para filtrarlo, porque tenía miedo de no mostrar números o strings, pero eso no va a pasar)
- algunos objetos como el Date no van a mostrar las variables (es al cuete), así que armé un método que te dice si hay que mostrar variables o no y ahí se filtran
- y de yapa, hoy si vos tenés más de una variable apuntando al mismo objeto no se estaba mostrando, metí un algoritmo para que muestre todos los nombres de referencias
