### ISSUE TITLE
Codigo base de la creacion de un archivo de test

### ISSUE THREAD

**Issue by Guusy** [uqbar-project/wollok#1717]
Cuando desde el IDE, creamos un nuevo archivo de test wollok, la estructura que nos genera es la siguiente :

![Captura de pantalla de 2019-07-28 19-51-41](https://user-images.githubusercontent.com/23525653/62016734-2bcd7880-b18a-11e9-95bb-c9d1e50a0bfe.png)

Les parece que tambien inicie con un describe ?

```js
describe "Tests de Pepita" {
    test "un test de pepita" {
    	assert.that(true)
    }
}
```

Tambien por lo que acabo de probar no podemos tener `describe` nesteados, no estaria bueno que puedan tener varios contextos en los test? de esta manera se podria aclarar bien didacticamente las partes de un test `precondiciones, operacion y postcondiciones`

**Comment by npasserini** [comment]
Con respecto a lo primero, yo prefiero que se mantenga simple. La idea de
Wollok es poder introducir los conceptos de a uno, entonces en un primer
paso ese archivo tiene lo mínimo que necesita un estudiante para poder
hacer un test y permite que el describe se introduzca luego, cuando el
docente vea que empieza a ser necesario.

Si le cambiara algo a ese archivo, me gustaría cambiar el assert, usando
equals que me parece lo más natural al comenzar, creo que siempre damos
assert.equals antes que assert.that. Podría decir `assert.equals(2, 1+1)`.

Si no me equivoco, hay otra opcion que crea un `describe` directamente. O
si estoy confundiéndome, tal vez eso sí se pueda agregar.

Con respecto a los describes anidados, me parece razonable. También me
gustaría poder tener más de un describe en un mismo archivo a top level (o
sea sin anidamiento)

**Comment by fdodino** [comment]
+1 a que existe un archivo de test y otro de describe, separados, y ése te crea el describe.
Y +1 a que se puedan anidar...

**Comment by Guusy** [comment]
Les parece dividir este issue en 2 ? 

- Que los describes se puedan anidar
- Modificar el `assert.that` por `assert.equals`

@npasserini @fdodino

**Comment by fdodino** [comment]
+1!

Modificar el código inicial que use  `assert.equals` :100:

**Comment by lspigariol** [comment]
Así como esta ahora es suficiente y es simple.
Todo bien con los cambios, pero no sé si justifica el esfuerzo

**Comment by fdodino** [comment]
Cierro este ticket que quedó duplicado
