### ISSUE TITLE
Separación de los archivos del lenguaje

### ISSUE THREAD

**Issue by Guusy** [uqbar-project/wollok#1718]
Hoy en dia tenemos todo el lenguaje en un file llamado `lang.wlk`, me parece que seria  mas dev friendly separarlos en files, para que sea mucho mas fácil la lectura de los mismos.

Entiendo que hoy capaz es un cambio grande, pero capaz en las proximas clases/objetos wollok que agreguemos, generarlo en un file aparte y que se requieran en el `lang.wlk`

**Comment by fdodino** [comment]
Voy a dejar por escrito lo que contaba en la reunión:

- la estrategia de tener muchos archivos separados complejiza la biblioteca base de Wollok
- no estoy seguro de cuántos alumnos abren el archivo y miran la biblioteca
- cuando actualizamos un archivo el editor y el builder compiten por el highlight y por mostrar errores y eso trajo primero problemas de concurrencia (saltaban popups muy molestos en las primeras versiones, hasta el 2017) y luego deadlocks (todavía hoy tenemos que ver si lo solucionamos)

Por eso mi warning es que es un feature que para mí tiene muy baja prioridad, comparado con tener un debugger, o que el diagrama de clases incorpore el concepto de interfaz ad-hoc para unión de tipos estructurales, o tener un editor web, wollok-game en el browser o bien una consola con autocomplete.

**Comment by lspigariol** [comment]
+1 a dejarlo todo junto.
En lo personal, me resulta más cómodo verlo en un archivo.

**Comment by fdodino** [comment]
Ahora que empezamos la unificación con wollok-ts, que solo tenía 2 archivos, creo que prefiero cerrar el ticket y en todo caso discutirlo como issue para el repo wollok-language
