### ISSUE TITLE
Cambiar codigo inicial de los archivos de  test

### ISSUE THREAD

**Issue by Guusy** [uqbar-project/wollok#1719]
Segun lo hablado en #1717 

![Captura de pantalla de 2019-07-28 19-51-41](https://user-images.githubusercontent.com/23525653/62016734-2bcd7880-b18a-11e9-95bb-c9d1e50a0bfe.png)

Podriamos cambiar el `assert.that` que ponemos al crear un archivo de test, por `assert.equals` ya que en las clases se estila enseñar el `equals` antes que el `that`.

**Comment by lspigariol** [comment]
Depende, a veces se explica primero uno u otro. El that es más facil de ver

**Comment by Guusy** [comment]
@lspigariol 
`assert.that` seria un equivalente a hacer un assert de true ?

**Comment by npasserini** [comment]
Sí.

**Comment by fdodino** [comment]
Lo cierro, si hay interés lo reflotamos.
