### ISSUE TITLE
Describes anidados

### ISSUE THREAD

**Issue by Guusy** [uqbar-project/wollok#1720]
Segun lo hablado en #1717 

Estaria buena la posibilidad de nestear los `describe` en los test

**Comment by fdodino** [comment]
Esto requiere cambiar la gramática y modificar el intérprete para reutilizar contextos. No es un ticket simple, pero es un feature lindo...

**Comment by npasserini** [comment]
Yo empezaría por permitir más de un describe en el mismo archivo, sin
anidamiento. También es un cambio gramatical, pero muy simple.

**Comment by fdodino** [comment]
+1 aunque no se si no armar un issue aparte para poder cerrar cada iteración

**Comment by npasserini** [comment]
Ok.

**Comment by fdodino** [comment]
Creado el #1734

**Comment by fdodino** [comment]
Bueno, ahora que lo pienso bien, no se si quiero tener múltiples describes anidados.
De hecho estoy pensando en trabajar con objetos factories, o en todo caso con tener múltiples describes en el mismo archivo evitaría tener fixtures con 12 atributos de los cuales 6 se usan en unos tests y otros 6 en los demás, encima penalizando la performance. Además es un feature que complica la detección de errores en los tests, y que me parece demasiado para un curso inicial de objetos. Yo lo frenaría en pos de otras funcionalidades que sí serían más provechosas.

**Comment by npasserini** [comment]
Yo con tener dos describes en un mismo archivo me conformo. La anidación es
lujo.

**Comment by lspigariol** [comment]
+1
