### ISSUE TITLE
Validación correcta en los describes vacios

### ISSUE THREAD

**Issue by Guusy** [uqbar-project/wollok#1721]
Hoy en dia cuando tenemos un describe vacio nos figura el siguiente error:

![image](https://user-images.githubusercontent.com/23525653/62094407-67804500-b253-11e9-8910-d87604ccb6d5.png)

En el error dice `No debe escribir código dentro del describe, utilice el fixture para inicializar los tests`

No seria mejor tener un mejor mensaje de este estilo ? `Los describes no deben estar vacios` 
Este mensaje estaria bueno que sea de tipo `WARN` o `ERROR` ?

**Comment by lspigariol** [comment]
+1 al mensaje nuevo y debería ser warning

**Comment by fdodino** [comment]
hola @Guusy, la clase que hace esto es `WollokSyntaxErrorMessageProvider.xtend`, es un poco áspera porque todavía no tenemos las construcciones sintácticas del lenguaje, sino algo mucho más primitivo porque estamos a nivel parser: nodos, tokens, y esas cosas.

Como dijo NicoP en la hackaton, la solución pasaría por relajar la sintaxis de `WollokDsl.xtext`, poner un `*` en lugar de un `+` en WSuite, de manera de aceptar un describe vacío, y agregar una validación en el `WollokDslValidator` que detecte que no tiene expresiones (`expressions.isEmpty` o algo similar). De esta manera estás más seguro de no recibir un error del parser de este estilo. Podés jugar si te animás y te voy guiando...

**Comment by Guusy** [comment]
Buenas buenas @fdodino , estuve avanzando con este issue y ya resolvi la validación sin problemas :rocket: 

Lo que sucede ahora es este [test](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/parser/ConstructorParserTest.xtend#L35) sobre los constructores dentro de los describe, falla.
y [este](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/parser/TestParserTest.xtend#L86) otro tambien, que habla del codigo dentro de los describes.

Asumo que pasa esto ya que decidimos hacer mas flexible el parser, y ya no se pasa mas por [este](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/parser/WollokSyntaxErrorMessageProvider.xtend#L126) file que handleaba los errores.

Lo que se me ocurre a mi es agregar estas 2 cosas como validaciones o tal vez si ves un modo de modificar el parser para que esto siga chequeándose ahi, joya !

Hago este comentario para no mandarme a codear algo que capaz se puede solucionar de otra manera :smile:

**Comment by fdodino** [comment]
Hola @Guusy , está perfecto, la idea es exactamente ésa:

- relajar la regla del Parser
- eliminar [las líneas que intenta mejorar el mensaje del parser](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/parser/WollokSyntaxErrorMessageProvider.xtend#L126)
- agregar validaciones (WollokDslValidator) considerando que un WSuite no debe tener WExpressions sueltas, esto significa que no sean hijas del WSuite que estás validando. Sí está bien que haya WExpression dentro de un WTest que está en un WSuite, y también están perfectos WExpression dentro de un WAssignment:

```wollok
describe "saldos de cuenta" {
    const cuenta = new Cuenta() 
    const otraCuenta = ... // si acá querés usar una WExpression está bien
    cuenta.retirar(20) // es incorrecto

    test "puedo retirar una cifra mayor al saldo" {
          cuenta.retirar(20)  // es correcto
    }
}
```

- Probar con un if (que es otra WExpression, un WIfExpression)
- Habría que ver qué otras construcciones fallidas podría tener un describe: una clase? como para ver qué dice el parser y cómo puede atajar el validador estas líneas

Me encantó el PR, está muy bueno!

**Comment by npasserini** [comment]
Yo pienso que relajar demasiado la regla del parser puede ser un poco
complejo, obliga a atajar demasiadas cosas a mano.

Creo que en el estado actual la sintaxis es bastante razonable:

WSuite:
'describe' name=STRING
'{'
(members+=WVariableDeclaration ';'?)*
(fixture=WFixture)?
(members+=WMethodDeclaration ';'?)*
(tests+=WTest)+
(tests+=WTest)*
'}'
;
O sea, acepta sólo declaraciones de variables, luego fixtures, luego
métodos y finalmente tests.
Es posible que si ponés alguna otra expresión te va a decir que se esperaba
un fixture... no sé si querés relajar la gramática aún más para manejar
esos casos.

**Comment by Guusy** [comment]
@npasserini  acabo de tratar de modficar el Wsuite de la manera que comentaste : 
```
WSuite:
'describe' name=STRING
'{'
(members+=WVariableDeclaration ';'?)*
(fixture=WFixture)?
(members+=WMethodDeclaration ';'?)*
(tests+=WTest)+
(tests+=WTest)*
'}'
;
```

Y estalla todo por los aires, creo que no se puede hacer esto : 

```
(tests+=WTest)+
(tests+=WTest)*
```

Entonces te parece que no relajemos la gramatica y manejemos este error de describe vacio a nivel parser ?

**Comment by npasserini** [comment]
Uh, perdón, fue una confusión, eso era copypaste (mal hecho) de lo que ya
hiciste... nada, yo decía exactamente lo mismo que estás diciendo, no
cambiar la gramática, que está perfecta como está en tu PR.
