### ISSUE TITLE
Quick Fix - agregar import de un elemento no existente

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1726]
Ejemplo:

![QuickFix-Import](https://user-images.githubusercontent.com/4549002/62336790-567c4180-b4a8-11e9-9606-a139eeddedab.gif)

Habría que buscar los archivos de un proyecto, foldearle los nombres de los elementos (wko, clases, referencias globales) y si alguno matchea ese nombre agregar como primera opción `Import <<nombre del archivo>>`

**Comment by nicovio** [comment]
buenas, no encontre un ícono de import para poner...

por ahora vengo usando el de JDT Icons (también probé con otro que encontre por ahí).

¿Me tiran un centriño? @fdodino @asanzo

**Comment by fdodino** [comment]
Groso!!
Lo que yo usaría es:

![package](https://user-images.githubusercontent.com/4549002/65811235-aebf7f00-e18b-11e9-8db8-e06b84586b52.png)

para importarlo tipo `archivo.*` incluyendo todo lo que tiene el paquete. El ícono está en "wollok/org.uqbar.project.wollok.ui/icons/package.png" (wollok es el directorio raíz, buscalo en tu proyecto).

Otra opción, que se puede hacer es:

- si es un objeto: wollok/org.uqbar.project.wollok.ui/icons/wollok-icon-object_16.png
- si es una clase: /wollok/org.uqbar.project.wollok.ui/icons/wollok-icon-class_16.png

![wollok-icon-class_16](https://user-images.githubusercontent.com/4549002/65811219-7c158680-e18b-11e9-98d5-4af95da13032.png)
![wollok-icon-object_16](https://user-images.githubusercontent.com/4549002/65811221-80da3a80-e18b-11e9-936f-ff3484a14653.png)

Para importarlo individualmente.

Es decir, el quick fix podría sugerir ambas opciones...

**Comment by asanzo** [comment]
¿Y por qué no el ícono de wollok, el mismo de los archivos?

![Selección_999(388)](https://user-images.githubusercontent.com/5421992/65980118-e6108300-e44c-11e9-86de-c2baaa6c9293.png)

La mayoría de las veces uno hace import wollok.*, y por ahí corresponde. 

Bah, podrían estar los 2 fixes: "agregar import de la clase/objeto" (con el ícono de la clase ú objeto), y sino "agregar import nombreArchivo.*" (con el ícono de un archivo).

Abz!

**Comment by nicovio** [comment]
![fix-1726](https://user-images.githubusercontent.com/26492157/65994145-0a7a5880-e469-11e9-962b-b6e9c79c97e0.gif)

**Comment by fdodino** [comment]
:clap: :1st_place_medal: #ViottiImprescindible #ElMejorEquipoDeLosUltimos5Cuatris #SacaDelMedioEclipse

**Comment by asanzo** [comment]
Pah qué máquina!!!!

**Comment by npasserini** [comment]
IM PRE SIO NAN TE ! ! !

**Comment by fdodino** [comment]
Y lo mejor, es que puede estar en el próximo deploy, no @nicovio ?

**Comment by nicovio** [comment]
Si... en un rato mando PR así lo pueden revisar
