### ISSUE TITLE
Caso en el que el TS infiere any

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1735]
En uno de los métodos, infiere any

https://github.com/wollok/EjercicioIntegradorPresidentesArgentinos.git

```wollok

class Presidente {
	
	method imagenPositiva() 
		= actos.sum{a=> a.impacto()} * self.porcentajeMuerte()
	
```

**Comment by PalumboN** [comment]
Me lo acabo de bajar en la versión 1.8.5 e infiere todo. Lo único raro que encontré es que ese método que comentás infiiere: `Method imagenPositiva() → (Date|Number|String)`. Lo cual debería ser solo Number, pero es un error menor.

@lspigariol podés confirmar si esto está arreglado?

**Comment by lspigariol** [comment]
efectivamente, ya no da any, sino los tres tipos. Es raro. Una pista: comentando el método desde donde se llama a `imagenPositiva()`, infiere bien.

**Comment by PalumboN** [comment]
Esto ya estaría solucionado en https://github.com/uqbar-project/wollok/pull/1889, pero hay otro inconveniente con las `property` en un test. 
Related: https://github.com/uqbar-project/wollok/issues/1891
