### ISSUE TITLE
Simplificar los juegos

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1736]
Luego de un cuatrimestre donde muchos estudiantes estuvieron haciendo juegos, estuve recopilando comentarios que salieron entre los docentes y tengo ganas de:

- [x] Agregar un método `onCollideDo(visual, action)` similar a `whenCollideDo(visual, action)` pero que el bloque se ejecuta **solo la primera vez** mientras los objetos estén colisionando (y no todo el tiempo, como el que está ahora).

- [x] Agregar un método `schedule(milliseconds, action)` similar a `onTick(milliseconds, name, action)` pero que se ejecuta **una sola vez**.

**Comment by PalumboN** [comment]
@npasserini @clombardi @faloi

**Comment by PalumboN** [comment]
- Otra cosa que fue duda general en los cursos es el hecho de que la configuración de colisiones para un objeto se "borra" cuando sacás dicho objeto del tablero. Creo que no quiero eso.

**Comment by faloi** [comment]
La primera me parece una gran sugerencia, nosotros habíamos sugerido el hack de mover a uno de los dos visuales luego de la colisión, pero mucho mejor no tener que hacerlo. 

Ahora no recuerdo otros comentarios, pero voy a tratar de hacer memoria.

**Comment by npasserini** [comment]
-

   Agregar un método onCollideDo(visual, action) similar a
whenCollideDo(visual,
   action) pero que el bloque se ejecuta *solo la primera vez* mientras los
   objetos estén colisionando (y no todo el tiempo, como el que está ahora).

Sí

   -

   Agregar un método schedule(milliseconds, action) similar a
onTick(milliseconds,
   name, action) pero que se ejecuta *una sola vez*.

Sí

   -

   Otra cosa que fue duda general en los cursos es el hecho de que la
   configuración de colisiones para un objeto se "borra" cuando sacás dicho
   objeto del tablero. Creo que no quiero eso.

Sí, cambiémoslo
