### ISSUE TITLE
No poder poner 2 veces el mismo objeto en Game

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1737]
Actualmente te deja poner **el mismo objeto** más de una vez en el tablero (incluso en posiciones distintas).
![image](https://user-images.githubusercontent.com/4098184/63214795-2f9e4c00-c0f3-11e9-85a9-da7bde669a43.png)

**Comment by PalumboN** [comment]
@lspigariol @npasserini al final en que quedó esto? Recuerdo que alguien comentó algo que me hizo dudar de esto.

**Comment by PalumboN** [comment]
@clombardi @faloi

**Comment by npasserini** [comment]
Yo por mí lo volaría. Pero si hay otros profes que lo quieren usar,
podríamos al menos tirar un warning al hacerlo.
Para bonus de chetez un warning que se pueda configurar para apagarlo.

**Comment by nscarcella** [comment]
Yo quiero hablar con cada profe que quiere usarlo y tratar de convencerlo de que no es una buena idea. Sería más fácil ordenarse el cronograma (para que no aparezca hasta ver clases) que explicar el mambo que puede causar con temas como identidad, encapsulamiento o estado interno.

**Comment by PalumboN** [comment]
Sí, yo entiendo las razones por las cuales parece ser una mala idea, de hecho estaba convencido de que lo quería. Pero me hicieron dudar 2 cosas:
- Que eso limite _mucho_ los juegos que se pueden hacer sin clases. Por ejemplo, para armar una pared o plataforma hay que poner muchos objetos "iguales" (muchas veces stateless). Esto afecta el poder modelar esos juegos solo con wko.
- Si didácticamente lo queremos. Ahora con lo que decís tengo ganas de hacer un juego poniendo muchas veces un objeto con estado, ver qué pasa y cómo surge la necesidad de _instanciación_ a partir de eso :P

**Comment by nscarcella** [comment]
Es que para mi postergar mucho la aparición de clases es un vicio que traemos de cuando pasar a usar clases requería un cambio de herramienta y era a todo o nada. Hoy por hoy la necesidad de usar clases puede aparecer antes si uno no fuerza a que no sea así y es mucho menos traumático.

Yo diría que las ganas de hacer un juego con muchos objetos parecidos es un gran punto de entrada a las clases. Inventar una mecánica para simular que un objeto está en muchos lugares que se va a romper en el momento en el que le pongas estado o le definas el método position me parece contraproducente.

En todo caso, si posta posta posta querés esto para poner objetos que no sirven más que para estar ahí, pongamos un método drawImage(image, position) que instancie un objeto bobo por atrás o algo así.

Lo que digo es que estaría bueno no meter ruido en conceptos que después se hacen más complejos si hay que empezar a explicar la implementación de game para que se entienda la diferencia.

**Comment by faloi** [comment]
+1 a no permitirlo. Usá clases o creá 20 objetos y date cuenta de que te falta una herramienta (las clases).

**Comment by lspigariol** [comment]
me quede pensando despues de lo que hablamos el sabado y estoy de acuerdo
en quitarlo, sin warning ni nada.

me convence la idea que es un buen argumento para explicar clases, mas allá
que sea mas pronto o mas tarde, que es otra discusión.
(si se lo quiere hacer de todas maneras, hay manera de lograrlo con objetos
anónimos y un foreach)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
