### ISSUE TITLE
Definición de una constante por fuera de un container me pide que inicie en minúscula

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1739]
![image](https://user-images.githubusercontent.com/4549002/63225084-13f27e80-c1a3-11e9-8af9-ac357949926d.png)

Quería definir una constante y me pide que inicie con minúscula. Yo creo que podríamos relajar esta validación si estás definiendo una referencia por fuera de un method container (clase, objeto, mixin)

**Comment by fdodino** [comment]
Es fácil de implementar, si tengo el ok lo tiro a los muchachetes de UNSAM, @npasserini @PalumboN @lspigariol @nscarcella ?

**Comment by npasserini** [comment]
Pero por qué ese cambio?
Esa formato de nombre no se usa en ningún lado en wollok. Además las consts
están pensadas justamente para reemplazar a los wkos al migrar a clases
entonces yo quiero cambiar `object pepita` por `const pepita`.

**Comment by fdodino** [comment]
yo no quiero exigir mayúscula o minúscula, lo quiero dejar libre, porque un const puede servir para pasar de wko a clase pero también para externalizar una constante como en este caso. 

> Ese formato de nombre no se usa en ningún lado en wollok.
yo uso las mayúsculas en Java y en Typescript/JS, y supongo que lo traigo de C, y solo para estas constantes, una variable en minúscula me hace pensar en una referencia propia de una clase.

Si al resto no le convence tampoco cierro el ticket, es una sutileza, pero me gustaría ver qué opinan.

**Comment by lspigariol** [comment]
¿por que querrías tener diferentes validaciones de mayuscula/nuuna
cosntante

**Comment by lspigariol** [comment]
auch! se mando antes de tiempo....

lo que no entiendo es por que querrías tener diferentes validaciones de
mayuscula/minuscula dependiendo del alcance de la referencia.

si por algun motivo resulta mas comodo usar mayusculas en los
identificadores o esta bueno que cada uno elija su estilo, que se permita
en todos lados y listo.

**Comment by npasserini** [comment]
Mientras me permita mutar `object pepita` => `const pepita`, me da lo mismo.
Coincido en que ese formato es común en la industria.

**Comment by fdodino** [comment]
no se si @nicovio está trabajando en esto, pero creo que hay cosas más interesantes para laburar, puedo vivir poniéndole la minúscula, así que cierro el ticket.

**Comment by nicovio** [comment]
este ya está... si queres abrimos y tiro PR.

**Comment by fdodino** [comment]
hablémoslo esta noche. Viotti, usted es un héroe.
