### ISSUE TITLE
Optimización de "mismo nombre distinta aridad" termina no tirando MessageNotUnderstoodException?

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1742]
Los siguientes tests en los que un objeto no entiende un mensaje tiran Exception en lugar de MessageNotUnderstoodException. En el caso general anda, sospecho que se relaciona con la optimización del mensaje de mensaje de error que intenta hacer notar que hay otro mensaje con distinta aridad.

```
	test "closures wrong arguments"{
		assert.throwsExceptionWithType(new MessageNotUnderstoodException(""), { { a => a + 2 }.apply(1, 2) })
	}
	
	test "closures wrong arguments 2"{
		assert.throwsExceptionWithType(new MessageNotUnderstoodException(""),{ { a => a + 2 }.apply() })
	}
```

**Comment by fdodino** [comment]
Estos tests se pasaron a wollok-language:
https://github.com/uqbar-project/wollok-language/blob/231907fa91d0b017813d0f304bf7e08da938413f/test/sanity/basics/closures/closures.wtest#L69

Cierro el issue, en todo caso tenemos que hablar de la internacionalización de mensajes en wollok-language
