### ISSUE TITLE
withoutDuplicates de List no respeta el orden.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1743]
```
	test "without duplicates" {
		// TODO No respeta el orden
//		assert.equals([1, 3, 1, 5, 1, 3, 2, 5].withoutDuplicates(), [1, 3, 5, 2])
//		assert.equals([1, 3, 5, 2].withoutDuplicates(), [1, 3, 5, 2])
	}	
	```

**Comment by lspigariol** [comment]
la logica actual debe ser
"si el elemento vuelve a aparecer mas adelante en la lista original, no lo
agrego a la nueva lista"

podria ser
"si al elemento ya lo agregue en la nueva lista, no lo agrego nuevamente"
