### ISSUE TITLE
[Type System] Problema al inicializar una lista y al agregar elementos por afuera

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1745]
En este ejemplo

```wollok
class Casa {
	const habitaciones = [new Cocina()]
	method agregarHabitacion(habitacion) { habitaciones.add(habitacion)}
}

class Cocina{
	
}

class Banio {
	
}

class UsoLaCasa {
	method prueba() {
		const casa = new Casa()
		casa.agregarHabitacion(new Banio())
	}
}
```

El type system me dice `Type system: expected <<Banio>> but found <<Cocina>>` .
Se arregla eliminando la inicialización de habitaciones. Me pasa también si lo hago con parámetros nominales en un test:

```wollok
const casa = new Casa(habitaciones = [new Cocina()])
```

**Comment by lspigariol** [comment]
Tengo un caso similar que vi el otro día...
Tambien noto que la inicialización de variables acota el rango de tipos posibles de una variable al tipo del valor inicial. 

tengo un ejemplo (está en la documentación de conceptos)

el tipo de mascota se infiere como `Ave|Superman`
![ts2](https://user-images.githubusercontent.com/11738011/63432435-86f43300-c3f7-11e9-85a6-970574e0b185.JPG)

al inicializarla con pepita, pasa ser sólo `Ave`
![ts3](https://user-images.githubusercontent.com/11738011/63432492-a8551f00-c3f7-11e9-9ca7-5d43f848368b.JPG)

Hay otros comportamientos que me llamaron la atencion, que en algun momento como que agrega mas tipos posible y en una corrida posterior del TS se da cuenta que algo no va y lo arregla.

por ejemplo
si agrego un `mascota + 1`, infiere `Ave|Number|Superman`
![ts4](https://user-images.githubusercontent.com/11738011/63432625-db97ae00-c3f7-11e9-85d5-1807f5adbaca.JPG)

y no sé bien qué hice (o deshice), pero me en un momento agrego una subclase:  `Ave|AveQueNada|Superman`
![ts1](https://user-images.githubusercontent.com/11738011/63432860-637db800-c3f8-11e9-9a0c-ae4401a202cc.JPG)
