### ISSUE TITLE
Impedir al game acceder directamente a atributos de objetos visuales

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1746]
obligar a que en los objetos visuales `image ` deba ser un método (o property) y no simplemente un atributo.
(similar con position, en los casos que corresponda, eventualmente tambien un getter) 

ayuda a que los estudiantes entiendan que es parte del comportamiento que requiere un objeto para ser mostrado y que game no hace magia oscura, sino que simplemente le envia mensajes.

(adicionalmente, sospecho que la existencia de un metodo ayudaría al TS)

**Comment by npasserini** [comment]
+1
