### ISSUE TITLE
El TS ignora properties heredadas

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1748]
se define una propiedad en la superclase,  se infiere correctamente el tipo, pero al usarse advierte que una de las subclases no tiene el metodo (el de la propiedad)

https://github.com/wollok/examenTareas.git

(en el mismo repo hay una caso donde tambien da un warning por la falta de un metodo en la superclase (que se la usa como abstracta, pero no tiene ningun metodo abstracto) que esta definido en todas las subclases, lo mismo que #1566

**Comment by npasserini** [comment]
En estos casos sería piola si pudiéramos tener el ejemplo mínimo, cosa de
poder incluirlo en un test.

**Comment by lspigariol** [comment]
copio el caso mínimo, donde logre reproducir un error no igual, pero similar.
Lo curioso, es que el warning de a property fecha desaparece si se quita el metodo montoTotal(), pero infiere fechaInicio(), como tipo Tarea|Tarea.

Tambien se ve en el ejemplo el otro tema de la clase abstracta: warning porque tarea no entiende el mensaje monto( )

```
class Proyecto {
	const tareas = [ ]

	method fechaInicio() = 
		tareas.min{ tarea => tarea.fecha() }
	
	method montoTareas() = 
		tareas.sum{ tarea => tarea.monto() }
}

class Tarea {
	var property fecha = new Date()
	
}

class TareaProduccion inherits Tarea {
	method monto() = 10
}

class TareaRecaudacion inherits Tarea {
	method monto() = 50
}

class TareaReunion inherits Tarea {
	method monto() = 0
}
```
