### ISSUE TITLE
No infiere bien constantes globales

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1751]
infiere el tipo de paredPiedra como Pared
infiere el tipo de paredes como List<Pared> 
pero  de toda maneras advierte que falta informacion de tipos en paredPiedra

```
object casa{
	var property paredes = [paredPiedra]
	method tiene(material){
		paredes.any{p=>p.material() == material}
	}
}

class Pared {
	var property material  
}

const paredPiedra = new Pared(material = "piedra")
```

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok/issues/1724

**Comment by PalumboN** [comment]
Esto es por el orden de las cosas. Se debería agregar las constantes globales como global en el TS: https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend#L85
