### ISSUE TITLE
El mensaje minusDays( ) retorna un objeto Date con problemitas

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1752]
`new Date().minusDays(1).year() `

retorna null 

idem con month() y day()

**Comment by nscarcella** [comment]
Quien sea que arregle esto estaría muy bueno que se asegure de que haya un sanity test y, si no, lo agregue ;)

**Comment by fdodino** [comment]
Sí, sería bueno hacer un circuito completo

- hacer el test por ahora en wollok-xtext
- arreglarlo
- hacer el sanity test en ... (?) dónde era?

**Comment by nscarcella** [comment]
@fdodino [https://github.com/uqbar-project/wollok-sanity-tests](https://github.com/uqbar-project/wollok-sanity-tests)

**Comment by fdodino** [comment]
gracias NicoS!!!

**Comment by fdodino** [comment]
Ahí lo estuve viendo, bien ahí @lspigariol detectando un problemón!!

![image](https://user-images.githubusercontent.com/4549002/63562400-da6b9b80-c533-11e9-9798-2c7172df711d.png)

El tema para @alete89 @maurocasciati @nicovio que lo estuvieron viendo es efectivamente cuando hacemos una operación que devuelve un Date, si bien seteábamos `wrapped` como variable interna de WDate (lo cual hace que el toString se vea perfecto, como todo lo nativo), no se actualizaban las referencias del objeto Date de Wollok, entonces:

- todo lo nativo funciona perfecto
- todo lo de Wollok tiene referencias day, month, year en `null`

La solución fue redefinir el `setWrapped` de WDate para que actualice las referencias del objeto Wollok.

Agregué unos tests en Wollok Xtext, ahora me fijo de agregarlo en los sanity tests.

**Comment by fdodino** [comment]
@nscarcella , soy un salame, agregué los tests en el proyecto de sanity y no me di cuenta que pusheé a master. Puedo deshacerlo y armamos un PR, avisame cómo preferís seguir.

**Comment by nscarcella** [comment]
Nah, yo digo que todo lo que sea de esta versión lo agreguemos sin pedir permiso. Cuando pasemos a trabajar en la próxima, tagueamos esta y así podemos congelar la versión a la que se compromete la implementación.

**Comment by nscarcella** [comment]
Además le tengo fe a que en wollok-ts pasen

**Comment by nscarcella** [comment]
Confirmado que en wollok-ts pasan.

**Comment by fdodino** [comment]
Mamita querida!! Este equipo está ma-ni-ja!!!
