### ISSUE TITLE
Cuando ejecuto algún test aparece en consola "Warning: NLS unused message: WollokLauncherOptions_OBJECT_DIAGRAM_PORT in: org.uqbar.project.wollok.launch.messages"

### ISSUE THREAD

**Issue by Nykros** [uqbar-project/wollok#1762]
Alguna idea?
Corriendo Wollok 1.8.4 (recientemente actualizado desde la misma IDE) sobre Windows 10.
El test corre correctamente, pero ese warning popula la consola.

**Comment by fdodino** [comment]
Hola @Nykros , vas a poder trabajar normalmente, solo que está faltando traducir ese string para castellano. En la próxima versión estará resuelto. Gracias por avisar.

**Comment by fdodino** [comment]
Por favor @Nykros no cierres el issue porque todavía no está desarrollado, si no lo vamos a perder de vista.
