### ISSUE TITLE
Usos de tests en el type system

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1770]
Visto en clase que con el programa de el bolichito, aparentemente al ejecutar los test crea un problema (o mensaje de advertencia) con el sistema de tipos. Dejo URL de mi repo para poder revisarlo: https://github.com/obj1unq/2019s2-gustos-debug-matiasnfuentes

**Comment by PalumboN** [comment]
Esto se comenzó a trabajar en https://github.com/uqbar-project/wollok/tree/fix-%231770
