### ISSUE TITLE
Inconsistencias en list.asSet()

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1771]
Tengo este código del REPL:
```Wollok
>>> var set = #{}
>>> set.add("Hola")
>>> set.add("Hola")
>>> set.add("Hola")
>>> set.size()
1 // -> Solo lo agrega una vez
>>> var list = []
>>> list.add("Hola")
>>> list.add("Hola")
>>> list.add("Hola")
>>> list.size()
3 // -> Lo agrega n veces
>>> list.asSet().size()
3 // -> Tengo un set con 3 elementos iguales (!!)
```
Con este diagrama:
![set_vs_list](https://user-images.githubusercontent.com/4098184/64480293-93b8ab00-d19b-11e9-8e91-4d337915df1b.png)

Y acá veo / pregunto:
1. Una inconsistencia en el `asSet()` de la lista, dejando los 3 objetos que no me dejaba agregar de una.
2. ¿El set trabaja con identidad o igualdad? ¿Está bien eso?
3. ¿2 strings con el mismo valor ahora son iguales, pero no idénticos? ¿Eso está bien?

**Comment by nicovio** [comment]
Hola Nahuel, creo que yo me la mande acá #1749 poniendole native a `asSet()` y haciendo que devuelva `wrapped.toSet`, porque el `equals` de `WollokObject` compara por identidad. Ya me pongo a ver como solucionarlo!

**Comment by nicovio** [comment]
Se me ocurre que `asSet()` vuelva a ser como antes (y al hacer `unaLista.asSet()` no se preserve el orden) y que `withoutDuplicates()` no use `asSet()`.

¿Qué opinan? @fdodino @PalumboN  @npasserini.

**Comment by npasserini** [comment]
El orden de `unaLista.asSet()` no debería preocuparnos, no tiene sentido
pensarlo: el resultado es un set y no tiene orden.

Tenemos que asegurar que en todos los casos se utilice el mismo criterio de
"igualdad" que yo entiendo debería estar dado por el "equals" de los
objetos.

Es decir, dados dos objetos a y b cualesquiera Si (a = b)

#{a, b}.size() == 1
#{a, b} == #{a} == #{b}

var set = new Set()
set.add(a)
set.add(b)
set.size() == 1
set == #{a} == #{b}

[a,b].asSet().size() == 1
[a,b].withoutDuplicates().size() == 1

Idealmente el diagrama de objetos debería mostrar sólo uno de los dos, pero
esto podría ser un ticket aparte.
En particular debemos testearlos con strings, por ejemplo a = "hola" y b =
"ho" + "la".

Pero no estaría mal hacer la misma prueba con:

   - números: a = 2, b = 1+1
   - fechas
   - booleanos
   - listas (o sea un conjunto que contiene listas)
   - conjuntos (o sea un conjunto que contiene conjuntos)
   - dictionary
   - pair
   - position
   - user defined objects que implementan el equals
   - colecciones con objetos mezclados!!!

Si alguno de los casos más raros se complica, podemos abrir un ticket
aparte y solucionar los más comunes.

--------------------------------
Segunda parte, si a != b

#{a, b}.size() == 2

var set = new Set()
set.add(a)
set.add(b)
set.size() == 2

[a,b].asSet().size() == 2
[a,b].withoutDuplicates().size() == 2
[a,b].withoutDuplicates() == [a,b]

El diagrama de objetos debe mostrar a y b como objetos distintos.
Ejemplos:

   - a= true, b=false,
   - a=1, b=2
   - a="hola" b="Hola"
   - fechas
   - pares
   - positions
   - listas, conjuntos y dictionaries
   - keys (de keyboard)
   - dos wkos cualesquiera
   - colecciones con objetos mezclados!!!

**Comment by nicovio** [comment]
Bueno, en los commits 4b3382872d3a1c3ed8d9dace65f1e2ba439ab37b y 9a6885efb106f407853aad38790e47a204caf6ff agregué tests a ListTest y SetTest teniendo de guía el comentario de @npasserini. Habría que ver si están bien y/o si faltan.
