### ISSUE TITLE
Objetos sin atributos se imprimen con []

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1772]
Ahora cuando imprimimos un objeto sin atributos en la consola se imprimen con un `[]` al final:
```Wollok
>>> nido
nido[nivel=null, position=a Position[x=7, y=8]]
>>> jaula
jaula[]
```

El otro día, en la clase de colecciones, a un estudiante esto le parecía **confuso**.

- ¿Podríamos sacar los corchetes cuando el objeto no tiene atributos?
- El otro día @npasserini sugería la idea de sacar los atributos **siempre** del `toString()`. Yo creo que ahora que tenemos el diagrama dinámico para ver el estado interno de los objetos ya no sería necesario este feature => VOT_SI.

**Comment by fdodino** [comment]
+1 a lo primero,
respecto a lo segundo, a priori estoy de acuerdo, me gustaría ver qué efecto tiene en las herramientas que todavía no tienen incorporado el diagrama dinámico (ej: tests, cuando tira el error del assert, para mí cuando tenés dos objetos que difieren en un elemento dentro de una colección, es imposible detectarlo, no sirve para mucho el toString, pero querría tomarme un tiempo para analizar casos)

**Comment by npasserini** [comment]
Yo estaría tentado a decir que los estudiantes rara vez entienden esos
strings que tiramos. Imagino que las veces que eso sirvió para detectar
errores fue más bien de la mano de un docente. Pero puede ser una idea
sesgada... si quieren nos tomamos el tiempo para decidirlo y lo medimos.

A lo mejor obligarlos a usar el toString para resolver esos problemas, y
reforzar su uso puede ayudar a entender mejor la relación entre el objeto y
su representación textual, que es un problema que yo veo con bastante
frecuencia.

Para hacer esto, además habría que tener claro los distintos usos de
toString/printString y la mar en coche, para garantizar las consistencias
en todos los casos.

En resumen me parece un cambio medio delicado que no lo haría a las
apuradas, pero me parece interesante.

**Comment by fdodino** [comment]
Bueno, acabo de pushear el fix al primer punto. Respecto al segundo, dejémoslo macerar un poco, en otros lugares como el stack trace aparecen ciertos atributos, a mí no me convence mucho la utilidad para poder entender el origen de un error (eventualmente podría servir), me gustaría darle una vuelta de rosca y abrir otro issue para eso, si les parece.

**Comment by fdodino** [comment]
A partir de una consulta en la lista wollok-dev, quizás sí esté bueno repensar el toString (simplificarlo y buscar herramientas alternativas para debuggear)

**Comment by npasserini** [comment]
Yo diría que demos este issue por cerrado y abro uno nuevo para discutir en
profundidad nuestros usos de string/to string y demás.

**Comment by fdodino** [comment]
Finalmente como vamos a cambiar la implementación de toString, dejamos sin efecto este issue.
