### ISSUE TITLE
Dónde encuentro el CHANGELOG?

### ISSUE THREAD

**Issue by Nykros** [uqbar-project/wollok#1778]
Buenas tardes, quería saber si llevan un CHANGELOG para saber las novedades y problemas arreglados entre una versión y otra.

**Comment by npasserini** [comment]
Cada versión liberada tiene un milestone asociado, entrando a la página
github del milestone podés ver los cambios asociados. Por ejemplo acá está
el de v.1.8.5 que acabo de liberar
https://github.com/uqbar-project/wollok/milestone/30?closed=1

**Comment by Nykros** [comment]
Eso no es un CHANGELOG.
Si hubiera un CHANGELOG podria hacer un Ctrl-F y buscar "error.throwWithMessage" y encontrar cuando fue deprecado, removido y por lo que fue reemplazado sin tener que molestarles.

https://keepachangelog.com

**Comment by npasserini** [comment]
Es totalmente cierto lo que decís, y es algo que internamente venimos
discutiendo sobre cómo mejorar. Más ahora que tenemos varias versiones del
lenguaje que deben manternerse sincronizadas y esto es un inconveniente.

Igualmente, cualquier consulta que quieras hacer, para nada es molestia.

Me parece interesante la propuesta de change log que mandaste, espero que
podamos tenerla en marcha a la brevedad.
