### ISSUE TITLE
REPL should give better visual indication of whether it is running or finalized.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#178]
Currently the user does not know if the repl is running or not.
Also it would be nice to know which program is running.

**Comment by npasserini** [comment]
Also it would be nice to put the focus in the repl when the program starts.

**Comment by fdodino** [comment]
I think first issue is ready.
Pending issue is second requirement (to know which program is running, or neither of them if you are running REPL without a file)

**Comment by fdodino** [comment]
Closing this issue.
Please @npasserini add a new issue for pending issue : to know which program is running, or neither of them if you are running REPL without a file.
