### ISSUE TITLE
Reemplazar WOLLOK.ROOT por un package.json

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1781]
El package.json sería un archivo que tenga de entrada la versión de wollok que usa y además sirve para lo que hoy se usa el wollok root.

A futuro puede tener más fields.
Seguiría el estandar de package.json existente.

**Comment by fdodino** [comment]
Por lo pronto, estamos de acuerdo en la reunión de hoy en agregar la versión de Wollok en el proyecto, para que pueda ubicarse el runner fácilmente.

**Comment by fdodino** [comment]
https://docs.npmjs.com/cli/v6/configuring-npm/package-json
