### ISSUE TITLE
reemplazo de error.throwWithMessage

### ISSUE THREAD

**Issue by Nykros** [uqbar-project/wollok#1782]
Tengo código antiguo que utiliza el objeto error para lanzar excepciones. Supongo lo han eliminado en las nuevas versiones. Cual es el método recomendado actualmente?

![Captura](https://user-images.githubusercontent.com/15970152/64580658-77fd0280-d35d-11e9-8d17-a7b6d784bb25.JPG)

**Comment by PalumboN** [comment]
`self.error("...")`

**Comment by Nykros** [comment]
Gracias!
