### ISSUE TITLE
Expected [#{"dos", "uno"}] but found [#{"uno", "dos", "dos"}] 

### ISSUE THREAD

**Issue by Nykros** [uqbar-project/wollok#1783]
Tengo código antiguo y me fallan varios test. Pude aislar la causa al uso del método abstracto asSet() que todavía aparece en la documentación, pero me parece que está roto.

```
test "assert.equals sobre conjuntos funciona"{
	const conj1 = #{"uno","dos","dos"}
	const conj2 = #{"dos","uno"}
	
	assert.equals(conj1,conj2)
}

test "asSet() falla"{
	const lista = ["uno","dos","dos"]
	const conj = lista.asSet()
	
	assert.equals(#{"uno","dos"},conj)
}
```

**Comment by nicovio** [comment]
Si se resuelve #1771 se resuelve este y viceversa.

**Comment by mmatos** [comment]
Vine a reportar lo mismo, al parecer es el asSet() con strings (se está fijando en identidad en vez de igualdad?):

```Wollok
>>> ["hola", "hola"].asSet()
#{"hola", "hola"}
>>> [1, 2, 2, 4].asSet()
#{1, 2, 4}
>>> #{"hola", "hola"}
#{"hola"}
```

**Comment by npasserini** [comment]
Esto ya debería estar solucionado en dev. Tenemos que hacer un release.

**Comment by fdodino** [comment]
Confirmado que en dev ya está solucionado.

**Comment by fdodino** [comment]
Acabo de testearlo en producción, cierro el issue
