### ISSUE TITLE
En ocasión de una nueva versión disponible, la entrada de menu "Help -> Check for Updates" no acusa la existencia de esta.

### ISSUE THREAD

**Issue by jcfstabile** [uqbar-project/wollok#1785]
Acostumbro a hibernar y restaurar la maquina en lugar de apagar y encenderla. Cuando en esta dinámica me encuentra con wollok corriendo y en este periodo se encuentra disponible una actualización, al pretender que la entrada de menú _Help -> Check for Updates_ me indique su existencia para proceder a actualizar el entorno, esta indica que no hay actualizaciones disponibles. 
En esta circunstancia al cerrar el entorno y volver a iniciarlo, sí se me informa  automáticamente que hay una actualización disponible.
Cabe aclarar que no recuerdo haber usado la entrada de menú para verificar después de reiniciar el entorno.

**Comment by asanzo** [comment]
Hola, @jcfstabile ! ¿Puede ser que te esté pasando lo que me pasaba a mí? Por ahí ya tenés la última versión. Ver #1860

**Comment by jcfstabile** [comment]
Hola @asanzo. No lo creo. Fíjate que cuando cerraba el entorno y volvía a iniciarlo, sí acusaba al inicio que había una nueva versión disponible.

**Comment by fdodino** [comment]
Hmmm.... no tenemos mucho control sobre el Check for Updates, y en particular no tenemos forma de replicar este comportamiento fácilmente. Lo movemos a "Rainy day fund", pero si al reiniciar el entorno te avisa creo que al menos tenemos un _workaround_. La verdadera prueba de fuego hay que hacerla instalando un Eclipse de Java y teniéndolo abierto para ver si ocurre lo mismo.

**Comment by fdodino** [comment]
Acabo de generar un release de Wollok y en dos máquinas diferentes en Linux me saltó el Check for Updates. Al no poder reproducirlo y existiendo un _workaround_ para esta situación puntual, cierro el ticket.
