### ISSUE TITLE
String asList()

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1787]
It would be great to be able to have filter, map, etc. for Strings. The easiest way to do this is to have a message that returns a list of all the one-character-strings in the original String.

The following should pass:

```Wollok
assert.equals(["h","e","l","l","o"],"hello".asList())
assert.equals(["h"],"h".asList())
assert.equals([],"".asList())
```

**Comment by alete89** [comment]
This should be probably closed because already can be achieved with `string.split("")` as for https://github.com/uqbar-project/wollok-language/pull/24

**Comment by npasserini** [comment]
+1

**Comment by asanzo** [comment]
It is not the same to navigate String's messages in the IDE and quickly finding asList or something simmilar.

My original chain of thought was:

"Hey, i want to transform every character"
"Ok, I need map."
"Geez, Strings don't understand map like lists"
"Ooohhh here is an asList, problem solved"

Which is a bit different from having split there.

.......


Howeeeeeever, after mapping one would have to join them, so the problem is still there.

Let's close this and spend time in juicier things. 

Thks

**Comment by npasserini** [comment]
La verdad me dejaste pensando con esto, tiene sentido.

El problema es que Wollok no tiene el concepto de caracter, eso es lo que
complica ver al string como lista, porque es una lista... de qué?
Y una cosa simpática es que la operación inversa al split se llama join con
lo cual vos podrías hacer unString.split("").map(lalala).join() y tiene una
simetría que me parece piola... al menos para el que entiende inglés.

El problema del map sobre unString.split("") es que sigue siendo una lista
de strings, ergo, no hay operaciones tipo "el caracter siguiente". Así que
no sé qué tan útil es mientras no metamos el concepto de caracter.
Tal vez estaría bueno ver ejemplos concretos de cosas que quisiste hacer.

Otra cosa interesante es mirar cómo se maneja esto en JS que tampoco tiene
caracteres.

**Comment by lspigariol** [comment]
Se me ocurren dos alternativas, pero que van en direcciones opuestas.
Una tiende a ver los strings como listas (de strings de un elemento) como lo asume el asList. En esa dirección se le podria agregar comportamiento polimorfico a las listas (dias tras subi un issue con alguna idea similar #1826 para los diccionarios). El issue #1871 va en ese sentido también.

La otra es diferenciarlos aún más, considerando que es más una coincidencia de nombres que un uso polimórfico. Hay una discusión en wollok dev "acerca del supuesto polimorfismo del +" que entre otras cosas propone que la concatenación de strings sea diferente a la de colecciones e incluso distinta de los numeros, (que no sea con +). Se relaciona con #1202. Aparte, creo que ayudaría al Type System, por ejemplo en casos como #1862

**Comment by asanzo** [comment]
Yo tengo una tercera propuesta que es agregar los Char, pero no sé si me quiero meter en eso.

Yo me estaría también bajando de este issue, hay que pensar más y por un tiempo largo no voy a tener ese resto. Gracias y perdón por joder.

**Comment by npasserini** [comment]
Voto cerrar esto y concentrarse en que ande bien el `split`, como dijo Ale
Dini.

**Comment by alete89** [comment]
Ok, cerrado al menos hasta que querramos profundizar la discusión. Ya está el fix del split en wollok-language. https://github.com/uqbar-project/wollok-language/pull/24
