### ISSUE TITLE
String split doesn't work for given strings longer than one char

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1788]
I would expect this:

```Wollok
>>> "kamehameha".split("me")
["ka","ha","ha"]
```

Rather than this:
```Wollok
>>> "kamehameha".split("me")
[]
```

(which is what is happening now)

**Comment by nicovio** [comment]
Se me ocurre solucionarlo con recursión. Otra opción es pasar `split` a nativo y usar el `split`de `String` de Java. ¿Qué opinan?

**Comment by nicovio** [comment]
¿Que estaria bueno que devuelva en estos casos? :

`"kamehamehaaaaa".split("a")`

`"kamehamehaaaaadefinitivo".split("a")`

**Comment by npasserini** [comment]
Ahora que tenemos dos implementaciones de Wollok, pasar a nativo es una
paja porque hay que mantenerlo en dos lugares a la vez. Si no tenemos un
motivo duro para hacerlo, yo diría que lo evitemos.


> "kamehamehaaaaa".split("a")
>
[ "k", "meh", "meh", "", "", "", "" ]

Parece medio rario el resultado pero si pensás por ejemplo en un csv y
hacés row.split(",") tenés muchas comas seguidas significa muchas columnas
vacías que se van a traducir en strings vacíos.

> "kamehamehaaaaadefinitivo".split("a")
>
[ "k", "meh", "meh", "", "", "", "", "definitivo" ]

O algo así.

**Comment by asanzo** [comment]
La justificación del csv me gusta.  O sea, esto también cambiaría la respuesta de nico. Creo que lo más saludable sería una lógica como:

> El parámetro de split es un separador. Consideramos que la lista resultante debe tener tantos elementos como separadores + 1

Entonces:

```Wollok
>>> "kamehameha".split("kamehameha")
["",""]
```

¿O así?

```Wollok
>>> "kamehameha".split("kamehameha")
[""]
```

**Comment by nicovio** [comment]
Perdón si me pongo pesado, pero prefiero quedar un poco mal y sacarme la duda jaja. 

esto: `"kamehamehaaaaa".split("a")`

deberia devolver: 

[ "k", "meh", "meh", "", "", "", "" ] (con 4 strings vacíos)

ó

[ "k", "meh", "meh", "", "", "", "","" ] (con 5 strings vacíos)

Mi confusión es porque tiene cinco "a" al final.

**Comment by asanzo** [comment]
Acabo de modificar mi comment anterior q se mandó solo. Con eso respondo.

**Comment by nicovio** [comment]
Perfecto, estoy de acuerdo con todo.

**Comment by nicovio** [comment]
method split(expression) {
		self.checkNotNull(expression, "split")
		if (expression.isEmpty()) {
			if (self.isEmpty()) return [] else return [ self ]
		}
		try {
			const expressionIndex = self.indexOf(expression)
			const remainingString = self.substring(expressionIndex + expression.size())
			return [ self.take(expressionIndex) ] + remainingString.split(expression)
		} catch e {
			return [ self ]
		}
	}

Esta es la solución recursiva que pensé

**Comment by npasserini** [comment]
Yo creo que con los temas de performance que hemos venido teniendo, estaría
tentado de ser precavido y hacer una versión iterativa en lugar de
recursiva, no creo que agregue gran complejidad.

Otra cosa dudosa es el catch sin indicar qué excepción esperamos atrapar,
eso no podemos hacer, es fuente de errores futuros.

**Comment by nicovio** [comment]
Si, olvidate... por eso borre el comentario.

**Comment by nicovio** [comment]
method split(expression) {
		self.checkNotNull(expression, "split")
		if (expression.equals("")) return [ self ]
		const result = []
		var me = self
		(0 .. self.size() - 1).forEach{ i =>
			if (me.contains(expression)) {
				const indexOfExpression = me.indexOf(expression)
				result.add(me.substring(0, indexOfExpression))
				me = me.substring(indexOfExpression + expression.size())
			} else return 0
		}
		result.add(me)
		return result
	}

pensé esta solución. ¿Alguna idea para mejorarlo?

o si se les ocurre otra forma de encararlo...

**Comment by npasserini** [comment]
Yo creería que el if inicial no es necesario, no?
Pero lo que más me preocupa es el return 0.
Creo que necesitás un while que no hay y entonces la única opción es
hacerlo recursivo.


split(e) {
  if (self.contains(e)) {
    const indexOfExpression = me.indexOf(expression)
    return [self.substring(0,index)] + me.substring(index +
e.size()).split(e)
  else {
    return [self]
  }
}

Qué te parece?

**Comment by nicovio** [comment]
Me gusta, el problema es que tiene muy mala performance.

**Comment by npasserini** [comment]
Perdón, sí, yo quería una iterativa, pero no se me ocurre.
Creo que lo del return 0 no camina.

Probaste el tema de performance?
Si no en un rato armo otra propuesta superadora.

**Comment by PalumboN** [comment]
Y este? 
```Wollok
	method split(string, expression) {
		if (string == expression) return []
		if (expression == "") return [string]
		const result = []
		const me = string
		const size = me.size()
		var start = -expression.size()
		(0 .. size).forEach{ i =>
			if (me.takeRight(size - i).startsWith(expression) or i == size) {
				result.add(me.take(i).takeRight(i - start - expression.size()))
				start = i
			}
		}		
		return result
	}
```

Salió medio a los bifes...

**Comment by npasserini** [comment]
Creo que no está bien, dame un minuto.

**Comment by npasserini** [comment]
Efectivamente


describe "string search" {
method split(string, expression) {
if (string == expression) return []
if (expression == "") return [string]

const result = []
const me = string
const size = me.size()
var start = -expression.size()
(0 .. size).forEach{ i =>
if (me.takeRight(size - i).startsWith(expression) or i == size) {
result.add(me.take(i).takeRight(i - start - expression.size()))
start = i
}
}

return result
}

test "basic" {
assert.equals(["a","b"], self.split("a,b", ","))
}

test "hdp" {
assert.equals([""], self.split("aaaa", "aa"))
}
}

**Comment by nicovio** [comment]
Aclaro que en solución que comente se puede sacar el `else return 0` y da el mismo resultado. 

Lo puse como para que "salga" del `forEach`, pero es medio turbio

**Comment by npasserini** [comment]
Bueno, yo armé algo. Lo copio abajo.
Veran que los casos borde son distintos a los que planteó Alf. Yo parto de
pensar este que me parece el más "realista":

assert.equals(["", "", ""], self.split(",,", ","))

Imagino un archivo separado por comas, un poco desvirtuado, campos vacíos
=> dos comas son tres campos.
Eso me lleva a pensar otros casos borde:
assert.equals(["h", "o", "l", "a"], self.split("hola", ""))
assert.equals(["", ""], self.split("hola", "hola"))

Que se deducen más o menos de lo anterior. ¿Qué les parece?

----------------------------------------------------------------------
describe "string search" {
method split(text, pattern) {
const result = []
const totalSize = text.size()
const patternSize = pattern.size()
var previous = 0
const last = (totalSize - patternSize).max(0)
(0 .. totalSize).forEach { current =>
if (current >= previous) {
if (current > last) {
result.add(text.substring(previous, totalSize))
previous = totalSize + 1
} else {
if (text.substring(current, current + patternSize) == pattern
and current + patternSize > 0
) {
result.add(text.substring(previous, current))
previous = current + patternSize
}
}
}
}

return result
}

test "basic" {
assert.equals(["a", "b", "c"], self.split("a,b,c", ","))
}

test "compound pattern" {
assert.equals(["a", "b", "c"], self.split("a=>b=>c", "=>"))
}

test "empty csv" {
assert.equals(["", "", ""], self.split(",,", ","))
}

test "hdp" {
assert.equals(["", "", ""], self.split("aaaa", "aa"))
}

test "empty pattern" {
assert.equals(["h", "o", "l", "a"], self.split("hola", ""))
}

test "pattern = text" {
assert.equals(["", ""], self.split("hola", "hola"))
}
}

**Comment by nicovio** [comment]
Estoy de acuerdo. 

Dejo una nueva versión del que había pensado (teniendo en cuenta el comentario anterior).

El return 0 no solo estaba mal sino que era al pedo!
	
	method split(text, expression) {
		text.checkNotNull(expression, "split")
		const result = []
		var me = text
		const size = text.size() - 1
		const expressionSize = expression.size()
		if (expression.equals("")) {
			(0 .. size).forEach{ i =>
				if (i != size) result.add(me.charAt(i)) else me = me.charAt(i)
			}
		} else {
			(0 .. size).forEach{ i =>
				if (me.contains(expression)) {
					var indexOfExpression = me.indexOf(expression)
					result.add(me.substring(0, indexOfExpression))
					me = me.substring(indexOfExpression + expressionSize)
				}
			}
		}
		result.add(me)
		return result
	}

**Comment by npasserini** [comment]
Me parece perfecto, porfa chequealo con los tests que pasé. Estaría bueno
que opine Alfredo sobre mi propuesta de casos borde.

**Comment by nicovio** [comment]
Ahí ví como andaba en esos casos. Dejo imagen:

![casos-split](https://user-images.githubusercontent.com/26492157/65656461-54d98080-dff6-11e9-819e-8c90eb4d3304.PNG)

Otros casos podrían ser:

`assert.equals(["hola"], self.split("hola", "sarasa"))
`

`assert.equals([], self.split("", ""))
`

**Comment by npasserini** [comment]
Banco

**Comment by fdodino** [comment]
@nicovio @npasserini @PalumboN @asanzo éste es un lindo ticket para que NicoV conozca wollok-language, habría que agregarlo en el changelog, abrir un PR en wollok-language y después ver si hacemos el toque, en principio en paralelo, pero eso podría cambiar en las próximas semanas, qué les parece?

**Comment by asanzo** [comment]
Respecto de los casos bordes definidos, ok ,estoy de acuerdo. Me hace un poco de ruido el separador `""`. La semántica es "si no hay separador sólo separá todas las letras" ¿verdad?

Ok con todo el resto.

**Comment by lspigariol** [comment]
lo estuve viendo dias atras, la nueva versión es mucho mas consistente. +1

solo respecto de lo último, lo entiendo como que entre cada elemento y su
siguiente, hay un "" como separador

**Comment by npasserini** [comment]
Sí, eso que dijo Lucas.
