### ISSUE TITLE
Información confusa cuando hay un error en wollok-cli

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1792]
Corrí mal wollok-cli y me dio un error muy confuso:
![image](https://user-images.githubusercontent.com/4633913/64910721-0243be80-d6f0-11e9-94af-6eb5dc7bfa66.png)

Después de debuggear un poco llego a este cambio:
![image](https://user-images.githubusercontent.com/4633913/64910898-d0cbf280-d6f1-11e9-90b8-09faadad73a9.png)

Revertirlo me permitió entender qué era lo que estaba pasando, en el log original no estaba la información. Propongo dos action items:
1) Considerar explícitamente el caso de no recibir ningún archivo y manejar ese problema antes de llegar a este punto.
2) En los casos que llegue a producirse un error no manejado, usar `log.error(mensaje, throwable" y dejar que el mecanismo de logging maneje el error, creo que va a ser más claro.

**Comment by npasserini** [comment]
Si estamos de acuerdo en la solución propuesta tal vez convenga partirlo porque el punto 2 es trivial y el 1 no.

**Comment by fdodino** [comment]
La razón por la que puse ese println a mano es porque haciendo pruebas me fallaba la consola y no veía el error, quizás porque estaba usando el reporter para wollok-cli desde la UI. Ok con revertir el cambio entonces, y lo voy a probar con el modo desarrollo.

**Comment by fdodino** [comment]
Después de la migración a 1.9.2 / 2.0.0 hagamos la prueba, entiendo que esto ya está solucionado.

**Comment by fdodino** [comment]
Agregué un fix en wollok-cli, porque 2. ya estaba hecho pero 1. no enganchaba bien cuando tenías wollok-cli en el PATH (te tomaba los tests de sanity checks de wollok-cli como archivos existentes en el `find` y pasaba la validación de que hubiera al menos un archivo `.wtest`). Ya está oficialmente en Wollok Ingalls.
