### ISSUE TITLE
Indentar constantes globales

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1794]
Si le paso el formatter a este código:
```Wollok
const a = new Sobreviviente()
const b = new Sobreviviente()
```

Me lo deja:
```Wollok
const a = new Sobreviviente()const b = new Sobreviviente()
```

:disappointed:

**Comment by npasserini** [comment]
Me gustaría tomar este issue así aprendo a usar el formatter. 
@fdodino me das una mano?

**Comment by fdodino** [comment]
Buenísimo, sí.
Tenés que toquetear `WollokDslFormatter`, armando un método dispatch

```wollok
def dispatch void format(??????, extension IFormattableDocument document) {
```

Reemplazando `????` por la construcción del AST que corresponda, el tema es engancharlo tanto en los tests como en los programas y las definiciones wlk.

El prepend, append, etc. está bastante piola...
Avisame si te trabás.

**Comment by fdodino** [comment]
Bueno, estuve jugando un poco y el método que tendrías que tocar es

```xtend
def dispatch void format(WFile file, extension IFormattableDocument document) {
```

Ahí se llama al main, a los tests, o a los suite, etc. 

Otra ayuda: `AbstractWollokFormatterTestCase` tiene esta definición

```xtend
	def assertFormatting(String program, String expected) {
		//program.parse.eContents.show(1)
		Assert.assertEquals(expected,
        program.parse.serialize(SaveOptions.newBuilder.format().getOptions()))		
	}
```

La primera línea la podés descomentar y te muestra el AST tal cual lo procesa el formatter.

**Comment by fdodino** [comment]
Bueno, antes de que me olvide ahí subí el fix.

**Comment by npasserini** [comment]
Ok, gracias.
