### ISSUE TITLE
Cambiar los [ ] al fallar un assert

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1797]
En la última clase de UNSAM, al menos 2 estudiantes no entendían un mensaje de error como el sisguiente:
![image](https://user-images.githubusercontent.com/4098184/64914555-e0b3f880-d72a-11e9-9617-45d1506f183a.png)
porque el mensaje confunde cuando falla el objeto con una lista de un elemento :(

Podríamos cambiar esos `[ ]` por otra cosa? Como _nada_ o `< >` o `| |`?

**Comment by npasserini** [comment]
:+1:

Usar <> podría tener sentido, creo que es un símbolo que no estamos usando
para nada más.
Lo de poner nada es tentador, pero no sé si la ausencia de limitador no
puede prestarse a confusión también.

**Comment by fdodino** [comment]
Me parece bien como propuesta intermedia, lo que quiero hacer es que el assertion error devuelva dos grafos igualito como ya lo tiene el diagrama dinámico y la vista del test rubner haga un diff visual como el git diff

**Comment by fdodino** [comment]
Cerramos este issue para seguirlo en el #1822

**Comment by fdodino** [comment]
Se cerró el issue pero en realidad estaba confundiendo assert vs. toString. Lo reabrí.
