### ISSUE TITLE
REPL does not support running files with "-" in its name.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#180]
Create any program in a file named foo-bar.wlk and run it in the REPL.
If you rename it to foo_bar.wlk it will work.

**Comment by tesonep** [comment]
because foo_bar is a valid identifier and foo-bar not, each file describes a package. So it has to have a valid package name,

**Comment by npasserini** [comment]
Right, I've noticed that. So I changed all tests names. I close this.
