### ISSUE TITLE
El test runner desde cli debería correr todos los tests y no parar en el primer error.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1801]
Entiendo que si falla un test sigue corriendo los demás tests en ese archivo, pero no sigue con los demás archivos.

Se puede probar provocando una falla en sanity tests.

**Comment by fdodino** [comment]
Esto ocurre al correr muchos archivos, en la clase `WollokLauncher`

```xtend
override doSomething(List<String> fileNames, Injector injector, WollokLauncherParameters parameters) {
		try {
			val interpreter = injector.getInstance(WollokInterpreter)
			createDebugger(interpreter, parameters)
			val filesToParse = fileNames.map [ wollokFile |
				new File(wollokFile)
			]

			interpreter.interpret(filesToParse.parse(parameters), parameters.folder)
			System.exit(0)
		} catch (Exception e) {
			System.exit(-1)
		}
		
	}
```

Debería quedar igual que `override doSomething(WFile parsed, Injector injector, File mainFile, WollokLauncherParameters parameters) {`

**Comment by fdodino** [comment]
Un efecto adicional es que este código no está devolviendo un exit code inválido al wollok-cli, provocando falsos positivos. El método `override doSomething(WFile parsed, Injector injector, File mainFile, WollokLauncherParameters parameters)` lo maneja adecuadamente (habría que extraer el método del catch).
