### ISSUE TITLE
¿Se rompió el asSet con strings?

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok#1803]
Esto obtengo en una consola sin proyecto:

```wlk
>>> ["frutilla", "frutilla", "chocolate"].asSet()
#{"frutilla", "frutilla", "chocolate"}
```

![image](https://user-images.githubusercontent.com/1585835/64987287-432e0580-d89f-11e9-9ef0-6392903a6585.png)

Estoy usando Wollok 1.8.5.

**Comment by faloi** [comment]
Investigando con @gonzager, descubrimos que los strings se están comparando por identidad y no por igualdad.

**Comment by npasserini** [comment]
Es un poco más complejo que eso.
Miren https://github.com/uqbar-project/wollok/pull/1786

**Comment by fdodino** [comment]
Ya lo estamos viendo con los chicos, hay un PR en marcha.
Cerramos este issue?
