### ISSUE TITLE
Deja inicializar objetos con referencias const sin pasar al constructor

### ISSUE THREAD

**Issue by mnmallea** [uqbar-project/wollok#1808]
Teniendo esto:
```
class Viaje {
	const property origen
	const property destino
	const property medioDeTransporte
}
```
Al usarlo en el REPL y hacer un `new Viaje()` sin argumentos todos quedan en null y deja instanciar al objeto.
Al pasar un sólo argumento rompe.
![image](https://user-images.githubusercontent.com/28768483/65391974-07cf8300-dd46-11e9-92db-43ab0613852d.png)

Entiendo que el comportamiento esperado sería que rompa también en el primer caso. :thinking:

**Comment by PalumboN** [comment]
Hola, esto pasa por el conflicto de constructores vs inicialización nombrada. En el primer caso no dice nada porque piensa que se va a ejecutar un constructor, en el segundo ya es obvio que queremos inicializar los atributos, así que corre la validación.

Ahora que deprecamos los constructores se podría checkear siempre esto, no?

**Comment by npasserini** [comment]
+1 Deberíamos validar eso.

Si querés, mientras no estén borrados los constructores se puede agregar un
if al respecto en la validación, no debería ser mucho trabajo. Pero es una
sutileza, les queda poco tiempo.

**Comment by PalumboN** [comment]
Hago un BUMP de esto, me gustaría tenerlo para la próxima versión. Ya van varias las veces que me juega una mala pasada en la clase de clases.
Qué opinás @fdodino ?

**Comment by fdodino** [comment]
+1 a tenerlo, es un issue importante y no debería ser tan difícil de validar.

**Comment by fdodino** [comment]
@PalumboN , hoy me hice un tiempo y estuve viendo esto: la regla requiere algunos toques:

1) si tenés un método `initialize` como Date, no hay que correr la validación
2) si tenés un constructor vacío, tampoco, porque el constructor se valida (te obliga a inicializar referencias const)

**Comment by fdodino** [comment]
Bueno, y ahí pusheé una posible solución. Me molestó un poco no poder meterlo en wollok-language porque corre sin validaciones... pero bueno, es mejor que nada. Y lo otro que me molesta es que AppVeyor no puede encontrar el repo p2 de Babel, pero Travis lo debe tener cacheado.
