### ISSUE TITLE
Validator: agregar validación de referencias var que podrían ser const

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1809]
## Issue original

Me gustaría que el validador detectara las referencias `var` que podrían ser `const` (WARNING). 

- lo más fácil: hacerlo con variables locales
- cuando haya variables de instancia properties, no hay que hacer nada (no podemos saber si alguien las modifica siendo `var property`)
- el caso que me interesa ilustrar

En este ejemplo:

```ẁollok
object camion {
	var property cosas = []
	var pesoTotal = 1000
	
	method cargar(unaCosa) {
		cosas.add(unaCosa)
		// agregar lógica para el bonus. 
	}
	method descargar(unaCosa) { cosas.remove(unaCosa) }
	method pesoTotal() = pesoTotal + self.pesoDeCarga()
	method pesoDeCarga() = cosas.sum {cosa => cosa.peso() }
	method excedidoDePeso() = self.pesoTotal() > 1500
	method objetosPeligrosos(nivel){
		return cosas.filter({ cosa => cosa.peligrosidad() > nivel })
	}
	method cosaMasPesada() = cosas.max({ unaCosa => unaCosa.peso() })
	method puedeCircularEnRuta(nivelMaximoPeligrosidad){
		return !cosas.any({ cosa => cosa.peligrosidad() > nivelMaximoPeligrosidad })
	}
}
```

Debería detectar pesoTotal como un posible `const`, al ser un property sobre `cosas` es difícil establecer un punto (hay que dejarlo). En el ejemplo de pepita, no debería sugerir cambiar la energía como referencia `var` a `const`, porque hace assignments.

## BONUS: Quick Fix asociado

Sugerir cambiar de var a const en el quick fix (agregar tests).

**Comment by lspigariol** [comment]
bien,
pero ojo que cosas es property, no se puede saber si no varia.

**Comment by fdodino** [comment]
Sí, lo modifiqué después.

**Comment by nicovio** [comment]
¿Puede ser que este ticket se pisa con #1864?

**Comment by fdodino** [comment]
Sí, no lo podía encontrar... Cerremos el otro, buen trabajo detectivesco!!

**Comment by nicovio** [comment]
Se resolvió en #1870. Cierro.
