### ISSUE TITLE
Al tener un wlk y wtest con el mismo nombre se trula los import

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1815]
En este caso (tengo un .wlk con el objeto `wollok` y un .wtest **con el mismo nombre**):
![image](https://user-images.githubusercontent.com/4098184/65471846-29fcfa00-de47-11e9-8190-a0d7dff35411.png)

Me linkea el objeto `wollok` y hasta me autocompleta los mensajes SIN EL IMPORT. 
Pero al correrlo tira
```
ERROR: Couldn't resolve reference to wollok
```

**Comment by fdodino** [comment]
Sí, esto lo habíamos detectado en un issue perdido por ahí. Voy a ver si lo encuentro para referenciarlo.

**Comment by fdodino** [comment]
Usando el ejemplo introPepita para testear un cambio en el test runner me tiró un NPE durísimo en la consola cuando lo corro. Me gustaría en principio como _workaround_ forzar a que no puedas tener el mismo nombre de archivo para un wtest o un wlk, qué les parece @npasserini @PalumboN @nscarcella ? (sí @nscarcella , te estoy empezando a arrobar para ver cómo lo trabajás en wollok-ts). A la larga estaba la opción de unificar todo en archivos .wlk y ya, eso podría funcionar.

**Comment by nscarcella** [comment]
Sí... Los tests y describes son Entities igual que las clases y objects, y si su FQN resulta ser igual no pasarían las validaciones y podrían provocar errores en runtime. Las opciones que se me ocurren para atacar eso son:
- sólo dejarlo así y avisar de forma clara que tenés que ponerle un nombre diferente al describe/test
- prependiarle alguito al nombre de un describe o test al calcular su fqn, cosa de que un test "testea algo" en un archivo "archivo" sea "archivo.T!testea algo".
- Escapear las comillas en el nombre de los tests: "archivo.\"testea algo\""
- Alguna otra gilada del estilo.

Lo de forzar a tener nombres distintos de archivos para los tests funcionaría en el IDE, pero otra herramientas podrían encontrarse con esto más adelante. Si eventualmente eliminamos la extensión wtest estaríamos forzandolos a usar nombres distintos, pero tiene el mismo problema.

**Comment by fdodino** [comment]
> "Si eventualmente eliminamos la extensión wtest estaríamos forzandolos a usar nombres distintos, pero tiene el mismo problema."
Esto no lo entendí, yo entiendo que se resuelve el problema independientemente del IDE porque fuerza a tener nombres distintos (no probé tener un archivo `pepita.spec.wtest` a ver qué pasa).

Al principio me resistía a la solución de prependearle al archivo de test un prefijo, pero veo que

- es una solución rápida y fácil de implementar
- solo rompe un test (porque está exponiendo el `fqn` hacia afuera, tendría que agregar un equivalente al `toString` de fqn para ver cómo se muestra)
- uno podría decir: si creo un wko / clase en un archivo de test no lo puedo reutilizar desde otro. Claro, eso ya pasa, no se puede, así que no le veo inconveniente.

**Comment by fdodino** [comment]
Mmm... cuando le agregué el prefijo al programa se me rompieron 15 tests, y no querría que al definir un program pepita.wpgm se me rompiera igual. Así que voy a seguir investigando opciones...
