### ISSUE TITLE
En la documentación, faltan los parámetros que se pueden usar al instanciar una clase

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1817]
Quise construir una instancia de Position (quiero usar Position en un ejercicio por fuera del game), y para ver cómo hacer, tuve que mirar el código de game.  
Creo que falta que en la doc diga que para construir una Position, como posibles parámetros nombrados del constructor están `x` e `y`.

**Comment by npasserini** [comment]
Interesante punto.

**Comment by lspigariol** [comment]
Sí. La guia completa del lenguaje no habla de atributos.
En la sección de conceptos es mas entendible, porque hace un recorte donde se explica lo mas importante (en el caso de position en game, la idea era no hablar de clases).

Hay otros casos similares: En Exception también hay que incializar el message y no está explicado. Idem en Pair.

Respecto de usar Position fuera de game, ver #1612
