### ISSUE TITLE
Diagrama dinámico, códigos visuales

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1835]
Buenas!

Amaría que el diagrama dinámico tenga las siguientes features:

- Todos los objetos que sean redondos. (No como las colecciones que son cuadradas). Esto reforzaría la diferencia conceptual con el diagrama estático.
- Los objetos creados por el usuario estuvieran diferenciados visualmente de los que me da Wollok, más que sólo por el color. (¿Quizás hacer los de Wollok más chiquitos? El tamaño de list me simpatiza)
- Los wko estuvieran diferenciados de las instancias. (¿Quizás hacer que los wko tengan borde más grueso?)

Las propuestas están hechas en base a no depender de los colores, pensando un poco en accesibilidad. Se puede reforzar estas mismas distinciones con colores. 

De todas formas, el código de colores actual no lo entiendo, perdón :S ¿por qué la position y los números tienen distinto color? ¿y por qué el color de list es diferente a estos otros?

![Selección_999(246)](https://user-images.githubusercontent.com/5421992/66285192-e3c18500-e8a1-11e9-80d4-001e90ebfd7d.png)

Abrazo!

**Comment by npasserini** [comment]
Me interesa este planteo de Alf, juntémonos un día y hagamos una propuesta.

No me gusta la idea distintos tamaños, podría dar la idea de que unos son
más importantes o más objetos que otros.

Si bien entiendo el objetivo de accesibilidad, creo que sobrecargar el
diagrama con dos indicaciones en lugar de una va a hacer las cosas más
confusas para todes. En todo caso lo consideraría como un switch, poder
apagar el código de colores o cambiarlo por otra codificación, superponer
ambas no me convence.

Creo que lo limitaría a diferenciar autodefinidos / instancias / propios de
la wre
Me pregunto si los propios de wre podrían tunearse más, así como los
números tienen una descripción especial, las positions también.

No me queda claro por qué las flechas que salen de colecciones son
especiales.

**Comment by asanzo** [comment]
Las flechas distintas me parecen bien. Podemos pensar una alternativa, pero el estado interno "posta" de la lista no estaría bien representarlo, creo, entonces hay que convencerse con algo que muestre que algún tipo de relación entre la lista y cada elemento. En ppio me parece bien así. 

Me pasó que me preguntaran en clase y salió la discusión interesante de que usamos las listas sin tener ni idea cómo están hechas adentro. ¿Tendrán un array? ¿Listas enlazadas como en algoritmos? etc.

**Comment by npasserini** [comment]
Ay, no me compro eso. El estado interno de las listas es el que se ve en el
diagrama, no hay más que eso.
Decir que un array es una forma de estado interno más válida que list o set
es darle al paradigma estructurado (o incluso peor) una preponderancia por
sobre los objetos que es innecesaria, es pretender pensar la memoria como
una tira continua, nada de eso existe en Wollok. No hay por qué traducir
list o set a construcciones más primitivas, ellos son primitivas themselves.

¿Cómo funciona un set por adentro? Cuando le agregás un elemento, después
lo tiene, si se lo sacás no lo tiene más. Cuando lo recorrés tiene los que
agregaste. No hay más que eso.
Sí, son reglas ad hoc ad hoc. Pero también las necesita un array, entonces
¿por qué agregar las reglas ad hoc de array en lugar de agregar las reglas
ad hoc de set?

**Comment by asanzo** [comment]
Bueno, si me vas a correr por izquierda te voy a terminar dando la razón. :grin:

**Comment by fdodino** [comment]
+1 a que haya una especificación: se pueden hacer muchas cosas, pero tenemos que llegar a un consenso para no hacer cambios que después involucren nuevos issues

**Comment by fdodino** [comment]
[Link a la especificación](https://docs.google.com/document/d/1XaQ1rzMoRWyGudNJI73slwDi-a_3SgEk4OygQdFWkXk/edit#)

**Comment by fdodino** [comment]
Cierro porque ya fue mergeado para la próxima versión Wollok Ingalls
