### ISSUE TITLE
Eliminar la dependencia con XPect

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1839]
Bueno, llegó el momento de decir adiós a Xpect, que no parece revivir desde la versión 0.2.0 y que nos impide subir la versión de Xtend, Eclipse y Java...

Hay algunos tests que no usan Xpect, y tienen el formato

```xtend
	@Test
	def void testNameWithOnlyNumbers() {
		val files = "1234a" -> '''
			class Tren {}
		'''

		val model = parse(files, resourceSet)
		model.assertError(model.eClass, WollokDslValidator.INVALID_NAME_FOR_FILE)
	}
```

Habría que revisar ValidationTestHelper.validate y armar algún helper para facilitar el reemplazo de los 400 tests, algunos son del type system y otros del validador.

@npasserini , dejo esto porque el año que viene quiero subir la versión de Eclipse para resolver el tema de Wollok Game con Mac (además de la consola REPL), y porque ya que estamos haciendo épicas, me puedo anotar con ésto.

**Comment by npasserini** [comment]
Si vamos a reemplazar xpect yo quiero que hagamos una herramienta similar,
con anotaciones asociadas al código.
Salirse de ese formato hace todo muuuucho más nefasto de testear.

Igualmente, lo de game en mac no me parece un gran argumento, con Silver
estamos laburando para eliminar la dependencia con libgdx tanto en linux
como mac.

**Comment by fdodino** [comment]
Buenísimo si están encarando la migración, igualmente a mí sí me parece un argumento de peso no poder migrar las versiones de Eclipse, ni la versión de JDK (que debe ser 1.8), Xtend > 2.12 mucho no cambió ni creo que lo haga, pero eso nos limita un montón (las configuraciones de mirroring especiales que tenemos que hacer en el build de maven para que no tire NPE por ejemplo). En algún momento vamos a caer en versiones no soportadas de Eclipse. 

Yo en la balanza privilegio éso. Igual, si se puede darle una vuelta, creo que podemos jugar un poco a tratar de replicar con menos complejidad los tests de xpect.

**Comment by fdodino** [comment]
Luego de salvar su vida milagrosamente Xpect cerramos el issue.
