### ISSUE TITLE
Proyecto roto causa ERROR:null al correr los tests

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1841]
Hoy corrigiendo me saltó un proyecto que hacía romper todo el entorno Wollok: los tests, apareció el Dirty State del Editor, era ingobernable. Refactorizándolo quedó pipí cucú, pero no pude ver qué tenía. Subo para que lo analicemos.

git@github.com:wollok/issue-1841.git
https://github.com/wollok/issue-1841.git

**Comment by fdodino** [comment]
El problema está en el fixture, que está reventando, y eso produce que los tests no se inicialicen correctamente.

**Comment by npasserini** [comment]
Che, pero si el fixture revienta el IDE debería informarlo razonablemente,
no?

**Comment by fdodino** [comment]
Sí, eso es lo que arreglé

**Comment by npasserini** [comment]
👍😎
