### ISSUE TITLE
Poder obtener todos los onTick's

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1852]
Así como existe el método `game.allVisuals()` para obtener todos los objetos que se están dibujando en el juego, estaría bueno tener un `game.allTicks()` que devuelva los nombres de todos los _onTick's_ que se encuentran en el juego.

Pedido por @francofresno

**Comment by PalumboN** [comment]
@francofresno estamos pensando cambiar la interfaz de Tick con esto: https://github.com/uqbar-project/wollok-language/issues/58

Para qué querías obtener todos los onTicks del juego? Esta nueva propuesta de manejar vos los objetos Tick's te serviría para lo que estabas queriendo hacer?

**Comment by francofresno** [comment]
> @francofresno estamos pensando cambiar la interfaz de Tick con esto: [uqbar-project/wollok-language#58](https://github.com/uqbar-project/wollok-language/issues/58)
> 
> Para qué querías obtener todos los onTicks del juego? Esta nueva propuesta de manejar vos los objetos Tick's te serviría para lo que estabas queriendo hacer?

Estaba desarrollando un juego de estrategia por turnos donde las unidades tenían "ticks" para simular un movimiento de iddle en la casilla donde se encontraban quietas. Cuando una unidad consumía un movimiento, esta dejaba de tener su tick. Al finalizar el turno necesitaba remover el tick de todas las unidades que aún tenían un tick, es decir, las que no habían sido movidas. Por eso, me hubiese sido muy sencillo contar con un método para obtener todos los ticks cargados y así removerlos. El workaround que le encontré fue guardar cada tick generado en una lista y luego remover los restantes.

Relacionándolo con el issue que linkeaste, yo generaba ticks con nombres únicos (el tipo de unidad + un número único). Al finalizar el turno podía seleccionar mi lista de unidades y remover los ticks usando este nombre único que tenía cada unidad pero siempre terminaba recibiendo una exception dado que las unidades que se habían movido ya no tenían ticks e intentaba remover ticks que ya no existían.

Espero que te sea de ayuda y si no entendí bien la pregunta o necesitás algo mas, acá estoy 👍

**Comment by PalumboN** [comment]
@francofresno ahh ook perfecto. Eso parece una dinámica específica del juego. La idea actual va hacia tener mayor control de los onTick y hacer más fácil esa gestión de onTicks que mencionás :+1: 

Cierro issue!
