### ISSUE TITLE
Wollok needs a way to inform the user that a method is deprecated

### ISSUE THREAD

**Issue by 51lv3str1** [uqbar-project/wollok#1857]
It could be through an annotation in wollok or something similar. It is necessary since there are several methods in Wollok-Games that are being deprecated, but not being informed to the user.

**Comment by fdodino** [comment]
@PalumboN @lspigariol @nscarcella , lo pongo en needs discussion para que nos pongamos de acuerdo en si lo movemos a wollok-language y cómo lo implementamos. En el roadmap 2020 es el último punto.

**Comment by fdodino** [comment]
Repetido con #1843... cierro éste.
