### ISSUE TITLE
Allow to reference objects/classes in the same file but different package by its full name

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#186]
```
package aves {
    object pepita {
        method volar() { "vuelo vuelo" }
    }   
}
package entrenadores {
    object mostaza {
        method entrenar() {
            aves.pepita.volar()        // DOES NOT WORK
        }
    }   
}
```

**Comment by fdodino** [comment]
Tested today and still does not work. But I think it is not so critical comparing with other issues of "import system".

**Comment by npasserini** [comment]
I would like to say I am not sure about this feature. Which is the use case? Why do we need this?

I know its a usual Java feature, but I think it tends to break modularisation, because it forces all classes to have a FQN, so every class is indeed in a unique global namespace.

I would like to propose another use case. I have two files foo.wlk and foo.wtest. I would like to be able to put them in the same folder and then write `import foo.*` inside foo.wtest, without caring about the whole path to the folder containing both files. Today I can't.

In this way, the two files can be moved unaltered, provided that they are moved together. On the contrary, if you always refer to a file by its FQN, moving it always requires to modify all its referrers. 

Maybe the two mechanism can live side by side, but I would like to avoid being forced to "always" use the FQN.

I remember once talking about some kind of lookup mechanism, so if I try to `import blah.foo` I should look first for a folder blah with a file foo in the same folder as the importing file, then in the parent folder, and so on to the root of the project (or some basic defined classpath).

**Comment by fdodino** [comment]
Mmm... este issue me deja muchas dudas @npasserini , sobre todo respecto a la última frase porque actualmente estamos haciendo que los archivos .wlk y .wtest tengan una especie de FQN diferente, además de que como dijiste arriba solemos modularizar los elementos que son agrupables en el mismo archivo, sin diferenciarlos por package. Me inclino bastante por cerrar el ticket.

**Comment by npasserini** [comment]
Ni idea. Creo que hay varias propuestas para cambiar nuestro sistema de
imports. A lo mejor se podría armar un único epic que agrupe estos y un doc
donde discutirlos.
Igualmente, yo creo que salvo bugs, los imports hoy no están en mi
prioridad, me parece que el esquema que tenemos funciona bastante bien.

**Comment by fdodino** [comment]
Dale, por lo pronto cierro este issue y si hay una propuesta de mejorar los imports lo vemos ya directamente en el roadmap. Mi idea es evitar los stale issues, o issues que tienen mucho tiempo y puede que tengan ideas que terminamos resolviendo de otra manera o que queremos atacar de otra forma (y quiero evitar que alguno de los chic@s nuev@s que entraron a Wollok se ponga con una épica que no sea necesaria)
