### ISSUE TITLE
La versión real no es la que se muestra en Acerca De

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1860]
Si aprieto "Detalles de la Instalación" es donde muestra la verdadera versión de Wollok instalada:

![Selección_999(249)](https://user-images.githubusercontent.com/5421992/67814048-d99a3d00-fa81-11e9-8a92-4a01015bd1e8.png)

Entiendo que esto sucede porque hay que modificar manualmente este archivo, y no se hizo para el último release:
https://github.com/uqbar-project/wollok/blob/0bb3de37c63f26f72107e781dd9d06b700f8f318/org.uqbar.project.wollok.updatesite/wollok-product.product#L10

¿Qué les parece sacar "Version 1.8.5" y reemplazarlo por "For version press Details"?

**Comment by fdodino** [comment]
Ah, me sacaste la duda que me agarró hace 1 día.
Es raro porque yo corrí el proceso y tendría que haberse actualizado.
Dejame que intente otra cosa, que es poner un script automágico que se ejecute cuando hagamos git tag...

**Comment by fdodino** [comment]
Bueno, Javi ya hizo ese script y se llama `changeVersions.sh`, en el raíz del proyecto, solo que con los cambios que hubo últimamente en la forma de trabajar de Maven hay que cambiarlo para que funcione adecuadamente, pero tenía previsto actualizar todos los archivos a la vez.

**Comment by fdodino** [comment]
Corrí el script de queruza para la 1.9.2 y ya anduvo
