### ISSUE TITLE
Ejecución de los tests en una subcarpeta

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1869]
Si entiendo bien, desde el Wollok XTend sólo puedo elegir entre ejecutar un archivo de test, o todos los tests en un proyecto. No hay nada en el medio, lo que es molesto si un proyecto tiene muuuuchos tests, como es el caso de wollok-language.  
Dos cosas que se pueden agregar:
- si me paro en una subcarpeta, que haya una opción para ejecutar todos los tests en esa subcarpeta
- si elijo varios archivos .wtest, que haya una opción para ejecutar los tests de los archivos elegidos.

**Comment by fdodino** [comment]
![testsDeUnaSubcarpeta](https://user-images.githubusercontent.com/4549002/84711493-e39f7c00-af3c-11ea-93c5-dc2c08ee73ad.gif)

Si seleccionás una subcarpeta te ejecuta todos los archivos de tests de esa subcarpeta. Lo único que tiene de malo es que aparece la leyenda "Run all Wollok tests in this project", lo que es confuso, voy a corregir la leyenda.

No tenemos por el momento posibilidad de seleccionar múltiples archivos, voy a investigar qué tan fácil es lograrlo.

**Comment by fdodino** [comment]
Ya pude lograr que selecciones n archivos y te ejecute los tests que están adentro de esos archivos.
