### ISSUE TITLE
QuickFix: transformar variable global en constante 

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1872]
Cuando se intenta declarar una variable global tira error: `Global variables are not allowed`. Estaría bueno que venga acompañado de un quick fix para transformar a constante.

**Comment by alete89** [comment]
Ya tenemos ese quickfix en un PR, es cuestión de ligarlo con este error.

**Comment by fdodino** [comment]
Ah, @PalumboN vos querés algo como

![globalVarToConst](https://user-images.githubusercontent.com/4549002/89846441-a1b73e80-db57-11ea-9b75-a45261dae4eb.gif)

:smile: 

Gracias a @alete89 esto es pan comido...

**Comment by PalumboN** [comment]
Jajajaj sí de lujo!
