### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [uqbar-project/wollok#1887]
Hello Wollok team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Wollok project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by PalumboN** [comment]
Hi Tamás,

Yes, we would very much like to be listed in Xtext website! :100: 

Here the requested information:
```
<tr>
	<td><a href="https://www.wollok.org/">Wollok</a></td>
	<td>Wollok is  a programming language and an IDE specially designed for teaching initial OOP courses. Students can program from the beginning incrementally adding every OO concept.</td>
	<td>LGPLv3</td>
	<td>Language, Education</td>
	<td><a href="http://www.uqbar.org/">Uqbar</a></td>
</tr>
```

Thank you very much!

**Comment by miklossy** [comment]
Thank you @PalumboN !

**Comment by miklossy** [comment]
The `Wollok` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
