### ISSUE TITLE
Unable to run programs in released v1.1

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#189]
![image](https://cloud.githubusercontent.com/assets/4633913/9186114/577ad17a-3f98-11e5-88e9-6cffa3cb00c5.png)

**Comment by javierfernandes** [comment]
I think this is because you are trying to run a project that was created with a previous wollok version. < 1.1

We could try to aumomate adding the dependency but should be blocker

**Comment by npasserini** [comment]
I tested it in a new project and it still fails
