### ISSUE TITLE
chequeo "Cannot return an assignment"  con += / -= 

### ISSUE THREAD

**Issue by clombardi** [uqbar-project/wollok#1894]
Esta definición
```
object paqueteDeLadrillos{
	var cantidad = 0
	method cantidadDeLadrillos(cant){
		return cantidad = cantidad + cant
	}
}
```
da error en el return, pone "cannot return an assignment". Eso está **perfecto**.

Peeeeero si lo cambio por `return cantidad =+ cant`, no da el error. Ufa.

**Comment by lspigariol** [comment]
ojo que no es lo mismo  += que =+

**Comment by clombardi** [comment]
quise decir `+=`

**Comment by PalumboN** [comment]
Deberíamos, además, agregar un warning para los casos `+=` y `=+` :P

**Comment by fdodino** [comment]
El tema es que si uno escribe

```wollok
a =+ 2
```

el parser lo interpreta como

```wollok
a = +2  // a = 2
```

así que subo un fix para el issue original.
