### ISSUE TITLE
Null pointer exception: Tests con diagrama dinámico + objetos definidos en wtest

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1903]
Probando un poco la nueva versión de Wollok (2.0.0) me topé con este error:
![image](https://user-images.githubusercontent.com/715971/89573837-9aafc980-d801-11ea-9fa5-03d98e4ed404.png)

Al parecer pasa cuando se define un wko en el .wtest y se corre el test con el diagrama dinámico activado. 
![image](https://user-images.githubusercontent.com/715971/89574186-20337980-d802-11ea-8425-e7a35b0ad04d.png)

El test corre y también se termina mostrando en el diagrama
![image](https://user-images.githubusercontent.com/715971/89574233-317c8600-d802-11ea-96a4-02506005e5e2.png)

... pero en el medio consistentemente salta ese Null pointer exception.

Ese error no salta si se declara a pepe como un objeto anónimo dentro del test:
![image](https://user-images.githubusercontent.com/715971/89574541-b4054580-d802-11ea-9a29-3eaa7ae1e5ae.png)
![image](https://user-images.githubusercontent.com/715971/89574552-ba93bd00-d802-11ea-8d50-c0b8a3079c81.png)

**Comment by fdodino** [comment]
Ok, muy buena la prueba @mmatos . El primer tema fue fácil de resolver: al tratar de averiguar si pepe es una referencia constante o variable, no hay variable y tira Null Pointer Exception. Eso fue fácil de resolver.

El tema fue por qué había un null, y es porque se supone que no debería estar mostrando una flecha de pepe a pepe:

![image](https://user-images.githubusercontent.com/4549002/89733853-b8ae4180-da2e-11ea-93eb-27fd95d5a4fa.png)

Eso se da porque nosotros estamos filtrando ahora las referencias a los wko, peeeeero justo también hubo un arreglo para los archivos de tests para que no colisionen los imports de archivos wlk y archivos wtest (es un tema de scoping de referencias, porque si definías wko o clases en un archivo de test te andaba en el editor pero se rompía al ejecutar los tests: #1815). En resumen, estuvo bueno que lo pudieras probar con tiempo. Gracias!

**Comment by mmatos** [comment]
Wiii ayudé 😁
