### ISSUE TITLE
El diagrama dinámico no se renderiza para tests dentro de un describe

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1904]
Con la versión 2.0.0 noté que pasa esto:

El diagrama dinámico anda bien con tests que están a nivel raíz:
![image](https://user-images.githubusercontent.com/715971/89576185-50c8e280-d805-11ea-90c7-514bca5101b3.png)

Pero si los meto en un describe, no se renderiza el diagrama:
![image](https://user-images.githubusercontent.com/715971/89576131-3858c800-d805-11ea-9a45-4a1bd67b54f2.png)

**Comment by fdodino** [comment]
Hola @maiu! 

Ahí estuve arreglando eso y de paso me di cuenta de que había que agregar el shortcut desde la solapa Wollok Tests. Unifiqué los iconitos y quedó así:

![fixDescribe1905](https://user-images.githubusercontent.com/4549002/89719300-44778d80-d99d-11ea-91f8-69ddf8c23245.gif)

(de paso probé qué pasaba si sacás el only, te deja el juego de variables del último test. En cambio si corrés los tests sueltos sin describe, te quedan todas las variables.)
