### ISSUE TITLE
Error al actualizar (Update 08/2020)

### ISSUE THREAD

**Issue by SebasCafiero** [uqbar-project/wollok#1913]
Buenas, quise probar de actualizar el wollok que tenía del 2019 y cuando le doy a check for updates me salta el error "no remedy found". Ya revisé las variables de entorno y pareciera estar todo bien respecto al java 1.8.
No estoy seguro si es un error propio del wollok o si hay un problema con mi instalación particular.
Les adjunto la foto con el error que saltó en detalle. 

![image](https://user-images.githubusercontent.com/49283074/89966848-6e8fb080-dc26-11ea-8223-635cac7d42a8.png)

Podría quitar este wollok y directamente instalarlo de nuevo desde la página, pero por las dudas les comento esta situación.
Saludos!

**Comment by fdodino** [comment]
Hola @SebasCafiero , 
       la versión de Wollok 2.0 no es compatible con la 1.9, por eso sacamos una versión _major_. Tenés que descargarte la nueva versión desde cero, muchas gracias!
Fernando
