### ISSUE TITLE
Cuando la consola REPL está desactivada, no debería activarse el listener de cambios

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1928]
Me pasa tratando de minimizar la consola para armar los gifs del sitio web:

![image](https://user-images.githubusercontent.com/4549002/91175184-cc0c0e80-e6b6-11ea-8613-685848dea9c5.png)

**Comment by PalumboN** [comment]
Esto creo que también pasa cuando se usa el plugin de git.
