### ISSUE TITLE
Tema oscuro: Algunos colores no se ven correctamente y no hay ninguna opción para cambiarlos

### ISSUE THREAD

**Issue by RaniAgus** [uqbar-project/wollok#1934]
Buenas! Acabo de instalar Wollok y, al cambiar a tema oscuro, vi que algunos colores no se adaptan al fondo oscuro:
![Untitled](https://user-images.githubusercontent.com/39303639/91765759-e0b53e80-ebaf-11ea-904a-bf1072191ce0.png)

El problema, sobre todo, es con el azul, el rojo de la consola y el texto del diagrama dinámico. 

Pude cambiar algunos colores entrando a `Window > Preferences > Wollok > Syntax Coloring`, pero no encontré en ningún apartado la opción de cambiar los colores de la consola interactiva, ni del texto del diagrama dinámico.

Saludos, y gracias de antemano!

**Comment by fdodino** [comment]
Bueno, si bien podés configurar el coloreado de sintaxis de Wollok, cuando lo cerrás se pierde todo.
Por ejemplo hice esta configuración, hay que usar Appearance > Theme : Tema de colores y tipografías (Paleta reducida).

![image](https://user-images.githubusercontent.com/4549002/92297089-ed1ffb00-ef11-11ea-8595-b936c94c6366.png)

Una picardía que se pierda después.
Estoy intentando detectar cuál es la configuración del Theme pero siempre me devuelve la default, seguiré investigando.

**Comment by RaniAgus** [comment]
@fdodino Yo los cambié entrando a `Window > Preferences > Wollok > Syntax Coloring` y me funciona perfectamente, incluso se mantiene al reiniciar. Pareciera como que Wollok tiene una forma particular de hacer el coloreado de sintaxis, como si se superpusiera encima del que tiene Eclipse por defecto.

Intenté entrar a `Appearance > Theme` y cambiar el tema de ahí, pero no tiene ningún efecto.

**Comment by fdodino** [comment]
Sip, tiene un highlight custom, supongo que falta cablearle los cambios definidos en Window > Preferences. Ya estuve mejorando un poco el look & feel:

![image](https://user-images.githubusercontent.com/4549002/92317991-e611ef00-efdc-11ea-88f7-5cb2bf75560b.png)

Igual necesitaré varios días para mejorar íconos, y varias cosas más.
