### ISSUE TITLE
Sintaxis funcionalosa + bloques = warning

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1938]
Me gustaría tener un warning para estos casos:
```Wollok
object o {
  method blah() = { ... }
}
```
(Es un método que retorna un código)

Para evitar posibles errores y aclaraciones de este estilo:
![image](https://user-images.githubusercontent.com/4098184/92557599-eca1a000-f242-11ea-859b-089d116155da.png)

Algunas condiciones extras que se podría tener:
- Solamente cuando el bloque no recibe parámetros
- Que el bloque tenga un return (o cause efecto (? )

**Comment by fdodino** [comment]
Confirmo que me acaban de preguntar por ese tema, porque además la experiencia de usuario es confusa.
