### ISSUE TITLE
Que fallen los tests sin assert

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1939]
Actualmente ya tenemos un warning cuando no se le manda ningún mensaje al objeto assert dentro de un test.

Me gustaría que además el test fallara (amarillo) diciendo que no se assertó nada.

![image](https://user-images.githubusercontent.com/4098184/92557930-cdefd900-f243-11ea-8dcf-bcbb1bcd832f.png)

------------------

EDIT:
- Depende de que podamos tener doesNotThrowException https://github.com/uqbar-project/wollok-language/issues/82
- Depende de que podamos detectar los assert en los methods del describe https://github.com/uqbar-project/wollok/issues/1943

**Comment by mmatos** [comment]
Acabo de crear un issue que podría ser relevante a la hora de considerar este que me parece más interesante: https://github.com/uqbar-project/wollok/issues/1943

**Comment by PalumboN** [comment]
@asanzo el otro día mostró en clase un uso de testing donde en este caso se espera que el test pase (comportamiento actual, el de la imagen) que me hizo dudar de mi propuesta.

**Comment by asanzo** [comment]
Estoy de acuerdo con @mmatos de que ese chequeo debería considerar los métodos de los tests, pero como dice @PalumboN me parece que lo que necesitamos es un`assert.everythingWentFine()`. Paso a explicar un ejemplo similar al que vimos en clase:

Me explico: vos esperás hacer 4 tests con un método `cuenta1.transferir(1000,cuenta2)`
- "Al transferir desde una cuenta sin guita explota"
- "Al transferir desde una cuenta la cuenta origen queda con menos guita"
- "al transferir hacia una cuenta la cuenta destino queda con más guita". 
- **"Al transferir desde una cuenta con guita no debería explotar"** <- este test es distinto de los 3 anteriores, y si bien está cubierto en los dos anteriores, es didácticamente interesante poderlo hacer. Y estaría bueno tener un assert que me deje ser declarativo al respecto. ¿Quizás un `assert.doesNotThrowException({cuenta1.transferir(1000,cuenta2)})`?

Como dice el rasta, creo que para poder implementar el "que fallen los tests sin assert" necesitamos considerar casos como este.

**Comment by matifreyre** [comment]
Yo eso lo hago con un catch y un assert.fail("sarasa").
OK, podría haber algo que no requiera catch, aunque no sé qué tan necesario
sea.

**Comment by mmatos** [comment]
Es necesario si mostrás self.error("..") y todavía no hablaste de try/catch.

+1 a tener un assertion como el que propone Alf (similar al `expect { }.not_to raise_error` de RSpec)

**Comment by matifreyre** [comment]
Ah, claro... es que nosotros damos todo junto :-D ... En ese caso,
`assert.succeed()` o `assert.success()` serían mis candidatos.

**Comment by asanzo** [comment]
Yo no doy try catch más que como bonus así que no es una solución viable :P

**Comment by asanzo** [comment]
Volviendo a ver esto, me gusta un poco menos la propuesta de @matifreyre .

Me gusta más esto:

```Wollok
test "Al transferir desde una cuenta con guita no debería explotar" {
     assert.doesNotThrowError({cuentaConGuita.transferirA(cuentaSinGuita, 1000)})
}
```

que esto:

```Wollok
test "Al transferir desde una cuenta con guita no debería explotar" {
     cuentaConGuita.transferirA(cuentaSinGuita, 1000)
     assert.success()
}
```

El primero me parece más declarativo, y tiene una sintaxis parecida a la familia `assert.throwsError`, mientras que el segundo requiere hacer el paso de entender que success en realidad está ahí porque si llega ahí es porque no explotó....

**Comment by fdodino** [comment]
A mí me resulta simpático `doesNotThrowError`, se puede implementar en Wollok mismo, en cuyo caso lo podemos mover a wollok-language y sería un PR fantástico para hacer, guiño guiño...

@asanzo @mmatos @matifreyre @PalumboN , si me dan el ok lo paso a wollok-language...

**Comment by PalumboN** [comment]
+1000 al `doesNotThrowError` 

Pero lo llamaría `notThrowsException` porque `consistencia con los métodos que ya tenemos` > `consistencia con el inglés` :eyes:

**Comment by npasserini** [comment]
Por favor no pongamos cosas mal escritas en inglés. `doesNotThrowException`debería ser good enough.

**Comment by asanzo** [comment]
1) ¿Qué les va más?
```Wollok
// Opción A
cuenta1.transferir(1000,cuenta2)
assert.doesNotThrowException()
```

```Wollok
// Opción B
assert.doesNotThrowException({cuenta1.transferir(1000,cuenta2)})
```

2) Segunda pregunta: ¿Entonces agregamos también la propuesta de rasta que el test de amarillo?

**Comment by tesonep** [comment]
B

**Comment by fdodino** [comment]
Opción B y sí. +1 a crear el `doesNotThrowException` en un issue de wollok-language y apuntarlo desde acá

**Comment by asanzo** [comment]
Charlamos en la meet de hoy que queda la opción B, y se implementa en este issue: https://github.com/uqbar-project/wollok-language/issues/82

Este issue queda para lo que originalmente propuso @PalumboN (que el test runner dé amarillo al correr un test sin asserts), ahí edité el comment ppal agregando las dependencias que habría que resolver antes que este.

@fdodino decime si quedaron los issues suficientemente claros como querías, y también porfa péguenle una revisada a las dependencias quienes estuvimos discutiendo acá (especialmente @mmatos que no estuvo en la meet de hoy)
