### ISSUE TITLE
Validación del uso de assertions no detecta si el assert está dentro de un método del describe

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1943]
Tengo un caso de testeo complejo que tira warning cuando idealmente no debería.

Declaré métodos dentro del describe que internamente le mandan mensajes al WKO assert:
![image](https://user-images.githubusercontent.com/715971/94343872-9e85ee00-fff1-11ea-9fd7-7374ec503d57.png)

Y luego uso esos métodos en tests que están dentro de ese mismo describe, pero me salta el warning de que no se está mandando ningún mensaje a assert:
![image](https://user-images.githubusercontent.com/715971/94343862-929a2c00-fff1-11ea-94fb-9480aee569f3.png)

![image](https://user-images.githubusercontent.com/715971/94343875-a80f5600-fff1-11ea-94a4-226516dc69b5.png)

No sé si es viable evitar ese warning, después de todo sólo puede asegurarse si el uso de assert está dentro del método definido dentro del mismo describe, cualquier otra cosa que no sea un mensaje a self obviamente queda descartada.

Desde ya es un detalle, cualquiera que extraiga el assert a un método del describe se supone que sabrá que puede ignorar el warning, pero lo comento para ver qué opinan.

**Comment by fdodino** [comment]
@npasserini @tesonep @nscarcella @asanzo @PalumboN no se si me olvido de algune, me gusta la idea pero quería pelotearlo un poco más antes de liberar la propuesta (en alguna reunión próxima quizás)

**Comment by asanzo** [comment]
Si https://github.com/uqbar-project/wollok/issues/1939 está resuelto, entonces, para este caso me parece razonable lo que dice la jefa de que debería no tirar el warning.

**Comment by PalumboN** [comment]
+1 a buscar el assert recursivamente en las llamadas a métodos del describe :+1:
