### ISSUE TITLE
Botones de play

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1945]
Actualmente los botones para correr la consola con y sin archivo asociado están muy juntos y varias veces lxs estudiantes se confunden y piensan que su código no anda cuando en realidad no está cargado:
![image](https://user-images.githubusercontent.com/4098184/94392006-7c918600-012d-11eb-96fc-22370786a558.png)

¿Se podría mover la opción de correr la consola sin archivo a la solapa de la consola, y dejar arriba las opciones que involucren archivos?

**Comment by fdodino** [comment]
Bueno, justo ayer vi que además el botón ése cuando reflotemos el debugger se confunde con el botón de Resume (F8). Por mí +1 a no tenerlo cerca del menú, y ponerlo en la consola, eso es fácil.

Además en la consola vos podés ver qué archivo está asociado, se puede poner un cartelito que diga: "Ningún archivo asociado" en el nombre del archivo.

**Comment by fdodino** [comment]
@PalumboN , si me das una mano al menos podemos ponerle un ícono que trate de representar "Ejecutar en la consola sin archivo asociado". En algún momento puse como un bash pero mucho no convenció.

**Comment by PalumboN** [comment]
Cuando decís "puse como un bash" te referís a algo como esto?
![image](https://user-images.githubusercontent.com/4098184/113172959-51dcd300-921f-11eb-8f07-8def57dbfc20.png)
Por qué no te convence? A mí me agrada.

Sino no se me ocurre qué poner que no sea un botón de play xD. Podríamos buscar otro que no sea ni el de ejecutar el archivo ni el del debugger.

Sino podemos ir por algo que indique que va a correr pero _sin archivo asociado_. Por ejemplo:
![image](https://user-images.githubusercontent.com/4098184/113173523-da5b7380-921f-11eb-9e7c-8bd98d1349f8.png)

**Comment by fdodino** [comment]
En general no les había convencido pero podemos volver a un ícono que trate de ser menos confuso. El segundo ícono era algo que yo buscaba pero hay que tener en cuenta que los íconos en eclipse no tienen mucha definición (creo que se bancan hasta 18x18 ó 20x20 y después sonaste). Busco algunos yo y elegimos.

**Comment by fdodino** [comment]
@PalumboN , qué te parece éste:

![image](https://user-images.githubusercontent.com/4549002/113417550-03077880-939a-11eb-9f29-0cf9213b9285.png)

**Comment by PalumboN** [comment]
+100

**Comment by fdodino** [comment]
Joya!! y una cosa que me pareció que puede ayudar es mostrar un mensaje cuando arrancás la consola Repl

![image](https://user-images.githubusercontent.com/4549002/113435731-cba8c400-93b9-11eb-8803-f325d53ca1c5.png)

(es más fácil que lo que te propuse inicialmente y es un cartel de advertencia más)
