### ISSUE TITLE
El diagrama dinámico no muestra instancias en los tests con describe

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1954]
Este código :
```Wollok
class Swallow {
	var energy = 100
}
only test "testX" {
	var littleJosephine = new Swallow()
}
```
Escupe este diagrama:
![Selección_999(574)](https://user-images.githubusercontent.com/5421992/95686077-1fd4a780-0bd2-11eb-936e-b6ea565a7a84.png)

Pero esté código:

```Wollok
class Swallow {
	var energy = 100
}

describe "f" {
	only test "testX" {
		var littleJosephine = new Swallow()
	}	
}
```

No escupe ningún diagrama:
![Selección_999(533)](https://user-images.githubusercontent.com/5421992/95686066-0b90aa80-0bd2-11eb-8caa-4ceeb5557498.png)

Sólo pasa con las instancias de las clases, porque con los wko parece funcionar correctamente

**Comment by fdodino** [comment]
Ah, @asanzo, qué bien que descubriste el patrón. Ahora creo que encontré el origen del problema:

![image](https://user-images.githubusercontent.com/4549002/99794041-56bea700-2b08-11eb-8693-78063f734258.png)

fijate que si inicializás a la golondrina en el test lo detecta bien. Fue un error que introduje al tratar de determinar si pusieron el flag `only` a los tests, y la primera expresión es la que trata de determinar si está dentro de un `only test`. Pero resulta que la primera expresión que se evalúa para `Swallow` es la inicialización de la variable energía. Entonces la expresión `100` no está dentro de un `only test` sino dentro de una clase. Por eso no está guardando la info de los objetos. Good catch!

**Comment by fdodino** [comment]
Mucho mejor así: :smile: @asanzo

![image](https://user-images.githubusercontent.com/4549002/99795108-01839500-2b0a-11eb-8757-be882b31fbbf.png)

**Comment by asanzo** [comment]
Qué buena onda!!!!
