### ISSUE TITLE
Error durante "XtextReconcilerJob"

### ISSUE THREAD

**Issue by jlsuh** [uqbar-project/wollok#1955]
Muy buenas,
quería compartir un error durante la realización de un modelo-parcial.

Estuve abstrayendo la idea en la clase `CriterioElemento` de que cada comensal pueda recibir un elemento, y que el comensal que emite dicho elemento, pueda desligarse del mismo. Al momento de definir el super(), con sus parámetros pertinentes, me sale el siguiente recuadro en pantalla:
![image](https://user-images.githubusercontent.com/38252227/96070537-cd67e500-0e76-11eb-819b-640b68fb1e6e.png)

Posterior a ello, cuando quería volver a abrir el archivo, quedaba de la siguiente manera:
![image](https://user-images.githubusercontent.com/38252227/96070652-00aa7400-0e77-11eb-889b-46ec99607f51.png)

El siguiente fragmento representa lo último que estuve haciendo previo al repentino infortunio:
![image](https://user-images.githubusercontent.com/38252227/96070832-50893b00-0e77-11eb-834b-eeae06080344.png)

Adjunto también el archivo en el que estuve trabajando.
[elAsadito.zip](https://github.com/uqbar-project/wollok/files/5382149/elAsadito.zip)

Saludos, y muchas gracias como siempre :)

**Comment by fdodino** [comment]
Bueno el tema es que al tratar de mostrar un mensaje de error piola Wollok falla irremisiblemente:


```xtend
	def static dispatch feature(WSuperInvocation call) { call.method.name }
```

con un `?` se arregla. Sale PR!
