### ISSUE TITLE
Refactor > Rename no modifica los nombres en los imports

### ISSUE THREAD

**Issue by RaniAgus** [uqbar-project/wollok#1959]
Buenas! Tengo un problema con Wollok IDE: yo uso muy seguido el refactor para renombrar los archivos en src. El problema es que cuando los renombro no me cambia los imports dentro de cada archivo como sí hace Eclipse con los # define en C

![image](https://user-images.githubusercontent.com/39303639/97599729-0f506980-19e7-11eb-8023-36b445c936e2.png)
![image](https://user-images.githubusercontent.com/39303639/97599846-3018bf00-19e7-11eb-93fc-64773600becf.png)

**Comment by fdodino** [comment]
![renaming](https://user-images.githubusercontent.com/4549002/101297483-05046500-3808-11eb-8847-4b784240d482.gif)

PR abierto.
