### ISSUE TITLE
No se marca como error el uso de una variable de un bloque en el scope de afuera

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1971]
Esto no se está marcando como un error en el IDE

![image](https://user-images.githubusercontent.com/715971/99093322-1663a400-25b1-11eb-9faa-d03bab363d35.png)

Sí falla al intentar ejecutarlo en el REPL y los tests correctamente
```
>>> carrito.productoMasCaro()
ERROR: Couldn't resolve reference to productoMasCaro
```

**Comment by fdodino** [comment]
Agh, @mmatos, me llevó casi 3 horas descular dónde estaba el problema, y lo más gracioso @npasserini @PalumboN es que cuando metí el fix saltaron dos errores, que son justamente tests que están mal:

```wollok
	method descargarCamionEn(unLugar) { destino.remove(destinos.detect{destino => destino.getLugar() == unLugar}) }
```

acá hay un typo, debería ser `destinos` en lugar de `destino.remove...`

Y 

```wollok
	method comer(alimento) {
		alimento.sum { x =>
			// XPECT errors --> "Cannot assign a variable to itself. It does not have any effect" at "energia"
			energia = energia 
		}
		
		// XPECT errors --> "Cannot assign a variable to itself. It does not have any effect" at "y"
		const y = y 
		var z = 24
		z = y
		const w = y
		
		alimento.hacerAlgo(x,y,z,w)
```

acá `x` está en el Closure. Increíble pero hace 4 años que el test está así y nunca me saltó.

Como dice un amigo: "Good catch, Maiu!"

**Comment by PalumboN** [comment]
Jajajaja yo conocía el error, creo que saltó en una demo en UTN (memoria dodinezca), pero me hice el dolobu estos 4 años :P

GROSES TODES :)
