### ISSUE TITLE
Renombrar 'variable de instancia' por 'atributo'?

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1974]
En varios [mensajes de error](https://github.com/uqbar-project/wollok/blob/bdc8c816b30373d6be956e28c9bf3133fadbf9bb/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties) aparece el concepto de `variable (o método) de instancia` lo que confunde un poco a mis estudiantes.

Podríamos llamarlos `atributos` (o simplemente métodos)? O debo incorporar ese vocabulario?? (Seguramente después de ver instanciación, porque antes no tiene sentido).

**Comment by lspigariol** [comment]
+1

**Comment by fdodino** [comment]
Je, variable de instancia es un término smalltalkero. Es una re-paja pero se puede cambiar a atributo.
Lo que sí, podemos cerrar el  #1764 que es similar... y fue abierto por el @PalumboN de hace un tiempo 😄
