### ISSUE TITLE
Editor should detect when we try to import an unexistent object.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#200]

**Comment by javierfernandes** [comment]
Related #206

**Comment by javierfernandes** [comment]
It already detects wrong file names, but still doesn't check for the obejct / class. Since I didn't want to load all the files for checking.

**Comment by javierfernandes** [comment]
It now checks all parts of the import: file, package, class/object.

<img width="224" alt="screen shot 2015-12-31 at 15 28 28" src="https://cloud.githubusercontent.com/assets/4428120/12067156/af8dfd1e-afd3-11e5-9539-1e790d6e38f7.png">
