### ISSUE TITLE
Unable to set breakpoints from perspective "Wollok"

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#201]
If you change to Debug perspective it works.

**Comment by javierfernandes** [comment]
I can set them fine with the shortcut (CTRL+SHIFT+B)

Although there's no option in the context menu for adding breakpoints when hit right-click de ruler.
I believe there's a bug for that already opened

**Comment by fdodino** [comment]
After a few releases, there were many changes: Javi already reported setting breakpoints is not available any more and several issues were added. Closing this.
