### ISSUE TITLE
NTH: Operadores ternarios

### ISSUE THREAD

**Issue by mbeorlegui** [uqbar-project/wollok#2014]
Muchas veces la pantalla queda viciada por un `if` - `else` con condiciones simples, sobretodo en el IDE de Mumuki.

Quizas para evitar esto se podrían implementar operadores ternarios como los que utilizan muchos Lenguajes de Programación.
Por la sintaxis similar, quizas sea amigable algo como en C#
```csharp
var a = 0;
var b = 1;
var r = a == b ? self.AccionTrue() : self.AccionFalse();
```

**Comment by PalumboN** [comment]
Hola @mbeorlegui 

No entendí si te referís a **tener** un "operador ternario" o simplemente a **aspectos sintácticos**:

### Sobre el operador

El `if` de Wollok ya sirve como expresión, así que eso ya se puede hacer:

```Wollok
const a = 0
const b = 1
const r = if (a == b) self.AccionTrue() else self.AccionFalse()
```

### Sobre la sintaxis

La sintaxis de Wollok está pensada por docentes de programación para la enseñanza, o sea que los usuarios de Wollok es gente novata que puede que esté dando sus primeros pasos en la programación (en general, no solo en objetos, que es para lo que está pensada toda la herramienta).
Quizá para vos que ya sabés que los chirimbolos `? :` significan `if else` resulta _amigable_, pero para alguien que está aprendiendo pueden ser confusos. Por eso elegimos generalmente **llamar a las cosas por su nombre**, para que la sintaxis se acerque al concepto que hay detrás.

De todas formas, seguimos teniendo estas discusiones cada tanto. Si te interesa estar presente en los momentos que definimos cosas de la herramienta (como el lenguaje) y querés aportar tu granito de arena te sugiero meterte al Discord de Uqbar para que estemos en contacto: podes encontrar un link en el sitio https://www.uqbar.org/ 

Muchas gracias por colaborar abriendo este issue!

**Comment by mbeorlegui** [comment]
No sabía que se podía usar de esa manera el `if else`, sin dudas es mejor eso que comentas que lo que puse yo para los que está destinado wollok.

Las gracias son a ustedes, tiene mucho laburo todo esto y sirvió un montón en la cursada!
Saludos.
