### ISSUE TITLE
Duda del uso de Wollok en Ubuntu

### ISSUE THREAD

**Issue by JoseMPaz** [uqbar-project/wollok#2024]
Buenas tardes, descargue el kit java 1.8 en un .tar.gz, descomprimi y modifique el archivo .configure para que levante java y javac, de este modo al colocar java -version, me dice 
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (build 1.8.0_382-8u382-ga-1~22.04.1-b05)
OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)
Seguido a esto baje el .zip de wollok, el cual tiene el ejecutable, y al darle ./wollok se ejecuta.
Mi duda es que al intentar visualizar en el ejm de titanic o la granja no visualizo el barco o la granja pero si los objetos. es decir no me aparece la ventana emergente como en el video de este profesor: https://www.youtube.com/watch?v=0YCzVQL5RHY  (minuto 37)
no me permite visualizar la biblioteca wollok game

**Comment by PalumboN** [comment]
Hola @JoseMPaz 

No te salta ningún error en la consola de Wollok?

**Comment by JoseMPaz** [comment]
Buenos dias, el profesor me dio este link
https://devicetests.com/fix-assistive-technology-error-java-gnome y logre
solucionarlo con la 1er opcion, desactivando el Assistive Technologies y
con eso funciono, gracias.

**Comment by PalumboN** [comment]
Genial @JoseMPaz !

Ahí tiré un PR para agregarlo en el sitio, por si alguien más tiene tu problema. https://github.com/uqbar-project/wollok-site/pull/66

Muchas gracias. Cierro este issue
