### ISSUE TITLE
Compatibilidad con macOS basado en Apple Silicon y Wollok Game en maquinas virtuales ARM

### ISSUE THREAD

**Issue by ghost** [uqbar-project/wollok#2025]
Hola!

Estoy utilizando una macbook pro con el chip M1 Pro.
Intenté correr la version de Wollok para macOS basado en arquitectura Intel habiendo previamente instalado el software [Rosetta](https://support.apple.com/es-es/HT211861) pero aun asi no logro hacerlo funcionar ([tambien habiendo instalado java para macOS ARM](https://techtutelage.net/?p=321)). Al querer iniciar Wollok, en primera instancia sale el error [Wollok está dañado / Wollok is damaged](https://www.wollok.org/instalacion/#:~:text=Mac%3A-,Wollok,-est%C3%A1%20da%C3%B1ado%20/%20Wollok), luego de aplicar el comando recomndado por la guia de instalación, el software simula querer iniciar y a los pocos segundos se cierra automaticamente.

Pude hacer funcionar Wollok en una VM de Windows 10 ARM con el software VMWare Fusion.
En cuanto a Wollok Game, el software no funciona al ser ejecutado, mostrando el siguiente error.
![image](https://github.com/uqbar-project/wollok/assets/94919997/e4c15664-0887-48d5-b619-159aa0dc5dc2)

¿hay alguna solución posible a alguno de estos inconvenientes?

muchas gracias!

**Comment by ghost** [comment]
Hola!

Pude solucionar este problema de la siguiente forma.

Instalé la versión de JDK para macOS x64. Luego me encontré con estos errores y los resolví como dice la guia de instalación:

![image](https://github.com/uqbar-project/wollok/assets/94919997/d91eb473-1d8e-4623-bc13-292ce73f868e)

![image](https://github.com/uqbar-project/wollok/assets/94919997/412a5e90-c649-4816-9d2a-a221ae914c0c)

![image](https://github.com/uqbar-project/wollok/assets/94919997/9d89c46e-3484-4844-a18f-7245c98f52e1)

![image](https://github.com/uqbar-project/wollok/assets/94919997/f5f6c94d-b69a-4028-9e48-07ba8df092ee)

Luego de arreglar todo eso, Wollok y Wollok game ya funcionan. 

Saludos!

**Comment by PalumboN** [comment]
Gracias por el update @kenzogrosvald !
