### ISSUE TITLE
Page: Update site link won't work

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#207]
In http://wollok.uqbar.org/entorno-de-programacin says the update site is http://update.uqbar.org/wollok, but that's not true: I had to add /master at the end to make it work

**Comment by matifreyre** [comment]
This one can be closed, right?

**Comment by npasserini** [comment]
In a few days we will be realeasing a new version, that could be a perfect
moment to test the update site. What do you say?

**Comment by matifreyre** [comment]
That page doesn't exist anymore, and the current equivalent one (http://wollok.uqbar.org/instalacion/) is OK.
