### ISSUE TITLE
[dynamic diagram] visually identify user objects (named objects or instance of user defined classes)

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#221]
We currently have two colors:
- numbers
- any other object

The "any other objects" is a broad category. 
I would like to differentiate those objects that belong to the current user's project from other objects like Pairs, Lists, Sets, and any other wollok libraries classes.

Probably using a new color for this will be enough

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/60405283-95efff00-9b85-11e9-8c03-5901c03f71ea.png)

Proposed categories:

- collection
- null: white
- string: light brown
- boolean: light violet
- custom definitions: grayed blue
- numbers: green
- any other Wollok object: default class color

**Comment by fdodino** [comment]
Second version: simplyfing colors in order to ease recognition of user defined objects

![image](https://user-images.githubusercontent.com/4549002/60405554-46123780-9b87-11e9-82a0-44de9312687a.png)

**Comment by npasserini** [comment]
Genial!

Sólo me da dudas por qué la fecha no tiene el mismo color que los demás
objetos básicos.

**Comment by fdodino** [comment]
Todavía estás a tiempo, yo puse los objetos boolean, string y números, podemos extenderlos a fechas. Fijate si hay algún otro que te parezca que debería verse en verde también, es bastante fácil de incluir ahora que publiqué el fqn de los tipos de cada objeto.

**Comment by lspigariol** [comment]
esta buena la idea!!!
me gusta mas la segunda, la de todos los objetos básicos del mismo color.

pares?
rangos?

**Comment by npasserini** [comment]
Yo diferenciaría las colecciones del resto de los objetos básicos. Imagino
que range entra ahí.

Y después podrían tener un color especial game y su familia, aunque hay
algunos detalles para pensar:
- eventualmente positions tal vez deberían ser objetos más genéricos que
game entonces tal vez no aplica.
- no sé si no es mejor que game directamente no aparezca ... y lo mismo
podría pensarse para keys? ¿hay algún objeto de game que queremos ver en el
diagrama?

Esto último lo pienso principalmente porque son objetos bien conocidos y
entonces te aparecen siempre descolgados. En el caso que por algún motivo
que no me imagino alguien se quiera guardar una key como atributo ahí no me
parece mal que aparezca, pero como wko sólo hace ruido.

**Comment by fdodino** [comment]
A mí me gusta la idea de mostrar 2 vistas diferentes: la representación de un objeto en el diagrama vs. la representación visual en Wollok Game. 

De todas maneras, creo que a la altura de hacer el juego el alumno ya puede prescindir del diagrama... en el camino didáctico Wollok Game aparece más bien al final, cómo lo ven ustedes?

**Comment by npasserini** [comment]
> A mí me gusta la idea de mostrar 2 vistas diferentes: la representación de
> un objeto en el diagrama vs. la representación visual en Wollok Game.
>
100% de acuerdo!

Creo que  no me expresé bien. Los objetos visuales creados por el
estudiante obvio que tienen que aparecer en el diagrama, sólo me refería a
los objetos del framework, que por ser wkos aparecen en el diagrama cuando
los usás.

Es fino igual lo que estoy diciendo, pero bueno, lo quería comentar: no
hacen falta y me parece que le meten un toquecito de ruido.

> De todas maneras, creo que a la altura de hacer el juego el alumno ya
> puede prescindir del diagrama... en el camino didáctico Wollok Game aparece
> más bien al final, cómo lo ven ustedes?
>
> —
>
Acá no estoy tan de acuerdo, creo que puede estar bueno relajar esta regla.
Cuento algunas perspectivas que venimos trabajando:

1) Los últimos dos cuatrimestres armamos un juego en base a pepita y lo
mostramos muy temprano y los dejamos a los pibes jugar con pepita + game.
En particular lo usamos para introducir bloques antes que colecciones,
funciona muy bien y creo que es la mejor manera de introducir bloques de
todas las que yo probé y vi.

Este cuatrimestre además lo retomamos después de clases, como ejemplo. Y si
bien no es indispensable, fue un ejemplo muy bonito mostrando las 3 cosas a
la vez: repl + diagrama + game operando al mismo tiempo.

Todas estas son cosas que pienso repetir y de hecho el plan es darle más
lugar a un "pepita game" que tenemos que terminar de enchetizar antes de
que empiece el próximo cuatri. La idea es que este ejemplo nos acompañe
toda la cursada incorporando nuevos temas.

2) La segunda perspectiva es que ayer en la retro del curso nos preguntaban
por el debugger, que por el momento no está entre nuestras prioridades. Y
lo que charlaba con Nahuel es que más allá de que me gustaría tener un
debugger, también pienso que sería un error que pensemos que la única forma
de buscar errores en el código de un programa sea poniendo breakpoints y
ejecutando línea por línea. Esa estrategia puede no escalar en proyectos
grandes y muy posiblemente no sea la mejor si tengo que debuggear un game.

Ergo, necesitamos otras herramientas además del debugger y una que ayer
pensamos con Nahuel es usar más lo de levantar partes del juego desde un
REPL. Imagino que si tenés muchos objetos puede funcionar mejor las
consultas directamente con código en el repl pero me tienta también ver
cómo podemos aprovechar el diagrama para inspeccionar nuestro grafo de
objetos.

En fin... creo que el diagrama y game son tal vez dos de las herramientas
más poderosas que tiene wollok y creo que está bueno pensar las estrategias
que permitan usarlas juntas.

**Comment by fdodino** [comment]
Copado!!

Me gustaría que charlemos sobre ese camino didáctico. Yo mostraba al principio pepita y después lo dejaba para el final, me gustaría ver qué vuelta de tuerca se le puede dar.

**Comment by lspigariol** [comment]
coincido en que esta bueno hacer convivir diagrama de objetos y WGame,
usandolo desde la consola.

game no aporta mucha para el diagrama, pero el atributo position de los
visuales estaría bueno.

yo tambien en el ultimo tiempo estoy tendiendo a usar mas Wgame y desde mas
temprano. Es un tema para seguir viendo y analizando.  Para mi es mucho mas
prioritario que el debugger

no sé si hay que ubicar a Wgame en "el" camino didactico, pero sí que se
pueda incluir en cualquier camino didáctico.
- el año pasado lo usamos en unsam para introducir bloques antes de
colecciones, con el keyPress
- este año en frd no llegue a concretarlo porque no arme un buen ejemplo,
pero habia pensado para la primer clase, para mostrar la idea de mensaje
con y sin efecto, antes de ver métodos.
- tambien lo use como tp para practicar polimorfismo (y como habilidad de
leer/modificar codigo hecho por otro) con el ejemplo del tateti.
- y por ultimo, similar a unsam, como tp integrador "avanzado" de
crear/inventar un juego.
lo que me reclamaron los estudiantes es mas ayuda, material de consulta,
etc.

**Comment by PalumboN** [comment]
> lo que me reclamaron los estudiantes es mas ayuda, material de consulta, etc.

Algo que acabamos de agregar [al sitio de la doc de WG](https://www.wollok.org/documentacion/conceptos/) es una doc avanzada que hizo un estudiante de UNQ este cuatri: https://github.com/leodelgadodev/Documentacion-wollokGame

**Comment by lspigariol** [comment]
la documentacion del estudiante esta buena, la voy a recomendar

la "oficial" esta un poco desactualizada, hay algunos cambios del ultimo
tiempo que no estan reflejados y hace que los ejemplos no funcionen.

si me explican como hacer, puedo actualizar la info, con otros ejemplos,
o subo issues con cada item a modificar?

aparte, en varios ejemplos se usan constructores, puede ser la ocasion de
sacarlos

**Comment by npasserini** [comment]
El mié., 3 de jul. de 2019 a la(s) 09:38, Lucas Spigariol (
notifications@github.com) escribió:

> la "oficial" esta un poco desactualizada, hay algunos cambios del ultimo
> tiempo que no estan reflejados y hace que los ejemplos no funcionen.
>
> si me explican como hacer, puedo actualizar la info, con otros ejemplos,
> o subo issues con cada item a modificar?
>

Eso estaría buenísimo!
De hecho mi idea es publicar esto que hizo Leo en el grupo de docentes, aún
no lo hice porque estaba esperando a sumarlo a él a ese grupo, pero eso ya
ocurrió.


game no aporta mucha para el diagrama, pero el atributo position de los
> visuales estaría bueno.


Claro, exactamente. Me quedé pensando y creo que afinando el lápiz, el
problema no es específico de wgame sino que es algo general a cualquier wko
que esté en el core de wollok => en el momento que los usás aparecen en el
diagrama y no aportan. Las keys creo que no son problemas porque
técnicamente no son wkos; en cambio sí podría pasar con assert. Es medio
sutil porque no pasa muy seguido, pero sería un lindo chiche que no
aparezcan en el diagrama wkos del core.

>
