### ISSUE TITLE
Check over MessageNotUnderstood implementation

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#23]
It has some implementations that might be needed for other "wollok runtime" exceptions.
But the comment states it might not longer be necessary...

class MessageNotUnderstood extends WollokRuntimeException {
	// Esto es previo a tener la infraestructura de debugging
	// probablemente seria bueno unificar el manejo de errores con eso
	var Stack<WFeatureCall> wollokStack = new Stack
	
	new(String message) {
		super(message)
	}
	
	def pushStack(WFeatureCall call) { wollokStack.push(call) }
	
	override getMessage() '''«super.getMessage()»
		«FOR m : wollokStack»
		«(m as WExpression).method?.declaringContext?.contextName».«(m as WExpression).method?.name»():«NodeModelUtils.findActualNodeFor(m).textRegionWithLineInformation.lineNumber»
		«ENDFOR»
	'''
	
	def getInternalMessage(){
		super.message
	}
}

**Comment by javierfernandes** [comment]
Closing this since in v1.3.0 we have completely changed the way message not understood is implemented as part of migrating interpreter built-in code to wollok code :)
