### ISSUE TITLE
[objects-diagram] Implement a better automatic layout for nodes

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#237]
I believe it's currently using a Zest directed graph layout, but it kind of sucks.
We need to have a better one.

It should try to identify the important nodes (user defined objects) and arrange their references objects (an numeric instance var for example), close to it and around it.

Here is a manually arranged example:

<img width="251" alt="screen shot 2015-09-17 at 23 22 58" src="https://cloud.githubusercontent.com/assets/4428120/9950692/7d436d36-5d93-11e5-967c-d47477b3729a.png">

Then it needs to be clever enough to arrange related clusters of objects next to each other in the best way.

**Comment by fdodino** [comment]
Solved in 1.7 version.
