### ISSUE TITLE
Null management on binary operations

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#24]
The multiply operation has some null management logic which is not present in other operations, why is that?

	@BinaryOperation('*')  
	def Object multiplyOperation(Object a, Object b) { 
		if (a == null || b == null) null
		else multiply(a, b)
	}

Should add this null-management-logic to every operation of the interpreter?

**Comment by javierfernandes** [comment]
This was because xtend failed if one of the parameter of the multiple dispatch method.
I tried to update all the operations which made sense (like 1 + null = 1), maybe I missed some others.
Or maybe I thought it had no sense for others (ex:  n /  null ??)

**Comment by npasserini** [comment]
But is it right ... n + null = n

Feels like Javascript

**Comment by javierfernandes** [comment]
hehe !
Well, then at least the error message should be improved with "cannot add 2 + null"
A common problem is for example forgetting to initialise an instance variable le Pepita.energy
Then try to add something to it.

**Comment by javierfernandes** [comment]
This will change with #433
