### ISSUE TITLE
[class-diagram] Be able to delete a class code from the diagram

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#245]
Right-click will open a context menu. Then "delete" action there

**Comment by fdodino** [comment]
+1!

**Comment by fdodino** [comment]
Well, you can only delete a class from code view. But now you can hide a class from a static diagram:

![image](https://cloud.githubusercontent.com/assets/4549002/26743435/255662fc-47b8-11e7-9905-43bf9b09f7d3.png)

So, "Guerrero" class still exists, while not appearing in this static diagram.
