### ISSUE TITLE
Check if WollokInterpreter interfaces should be merged

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#25]
Check if XWollokInterpreter and IWollokInterpreter could be merged in one single interface.

**Comment by fdodino** [comment]
@npasserini , XWollokInterpreter doesn't seem to exist anymore.
Now we have IWollokInterpreter (interface) and WollokInterpreter / WollokREPLInterpreter as implementations.
Can we close this issue?

**Comment by npasserini** [comment]
This question is for @javierfernandes

**Comment by javierfernandes** [comment]
Not sure what IWollokInterpreter was.

I think that XWollokInterpreter has been abstracted to something even
decoupled from wollok.
It is all the infraestructure to create an interpreter with a debugger,
that can be used for any language (at least it was the intention). And it
is in a separated bundle called "xinterpreter" (that's where the x come
from.. and that comes from X-text)

So, I wouldn't merge wollok specific things int XInterpreter, I think
