### ISSUE TITLE
Class diagram should also show named objects

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#254]
It currently only shows classes.
That's probably because we think in terms of UML which is also thought in terms of "traditional OOP" (meaning class based, non object-centered).

Now, shouldn't we also be showing named objects ? since they are important objects which are part of the program ?

**Comment by javierfernandes** [comment]
@npasserini @tesonep  what do you think ?

**Comment by npasserini** [comment]
Right.

**Comment by tesonep** [comment]
Yes, It's great to me to have both together.

I think named objects is a great tool of our programming language, and the
students are using it very well. A lot of nice patterns appear with the use
of named objects.
Not showing in the class diagram is a foulness.

On Thu, Sep 24, 2015 at 11:50 PM, Nico Passerini <notifications@github.com>
wrote:

> Right.
>
> On Thu, Sep 24, 2015 at 6:56 PM, javierfernandes <notifications@github.com
> >
> wrote:
>
> > @npasserini <https://github.com/npasserini> @tesonep
> > <https://github.com/tesonep> what do you think ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/uqbar-project/wollok/issues/254#issuecomment-143061004>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uqbar-project/wollok/issues/254#issuecomment-143108540>
> .
>



-- 
Pablo Tesone.
tesonep@gmail.com

**Comment by javierfernandes** [comment]
Done
It doesn't show the relations between objects and classes (just for the case where a named object extends a class) I will create a separated issue for that. I don't think it would be difficult to implement.

Here is how it looks:

<img width="388" alt="screen shot 2015-09-30 at 10 59 54" src="https://cloud.githubusercontent.com/assets/4428120/10195177/b4d4c85c-6762-11e5-8423-736d8b590a6d.png">
