### ISSUE TITLE
WKO cannot inherit from a class which has a non-default constructor

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#268]

**Comment by javierfernandes** [comment]
First working examples:

<img width="286" alt="screen shot 2015-10-21 at 23 41 00" src="https://cloud.githubusercontent.com/assets/4428120/10655676/52da2a4c-784d-11e5-9c17-36bc33a1adb0.png">

And referencing another WKO as parameter value

```xtend
class Dog {
				val owner
				new(param) {
					owner = param
				}	
				method owner() = owner
			}
			object lassie extends Dog(jorge) {
			}
			
			object jorge {
				method name() = "Jorge"
			}
			
			program p {
				assert.equals(jorge, lassie.owner())
			}
```

I still need to:
* add new validator's checks to make sure you are calling a valid super constructor
* add a new check (that should be there already) when an object extends a class which doesn't have a default no-args constructor. An error should arise there telling that you MUST explicitly call one
* add a quickfix for that.
* tests some other weird potential cases. Currently the parameters values could be any WExpression. That mean that you could write there "if" statements, and any other kind of complex value (like calling a an objects method. We must think if that's necessary, or more important if it introduces bugs. I don't mind have new crazy usages, just that they shouldn't be buggy :P

**Comment by javierfernandes** [comment]
@npasserini  FYI

**Comment by javierfernandes** [comment]
This actually works out-of-the-box

```xtend
class Dog {
	val owner
	new(param) {
		owner = param
	}	
	method owner() = owner
}
object lassie extends Dog(jorge.name()) {
}
			
object jorge {
	method name() = "Jorge"
}
			
program p {
	assert.equals("Jorge", lassie.owner())
}
```

**Comment by npasserini** [comment]
Great!

**Comment by javierfernandes** [comment]
Related issues for the pending work:

#351 
#352
#353
