### ISSUE TITLE
[check] Detect unused parameters in constructors

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#280]
Warning I guess.

Example

```
class A {
    new(a,b)
}
```

**Comment by fdodino** [comment]
Also in methods, there wasn't a warning message.

**Comment by fdodino** [comment]
Hm... several errors in tests appeared, so I'm not sure now.
If a parameter is not used in a constructor, ok, we should warn it.
But, if you want to keep polymorphism, and you don't use a parameter inside a method, I think we cannot say this is a "bad smell" until we have a type system that allows us to confirm there  is only one implementation of this message.
What do you think @npasserini ?
