### ISSUE TITLE
Length methods of strings returns a java integer instead of a wollok integer

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#283]
If you write `"hola".length()` in the repl you get 4 But if hoy try tu use the result in a bigger expression you get an error `"hola".length() - 1`.

This is because it returns a `java.lang.Integer` instead of 
`org.uqbar.project.wollok.interpreter.nativeobj.WollokInteger`

**Comment by javierfernandes** [comment]
Fixed in hotfixes branch. To be merged to master
