### ISSUE TITLE
Improve collections toString

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#291]
Both sets & lists should have a better toString

Currently it shows the underlying Java class, which is not useful.
It should show the contents of the collection, probably the same result as doing col.join(",").
Or even better add enclose that in "[]" or "{}" depending on the type of collection.

**Comment by javierfernandes** [comment]
Done !

```
val a = #{23, 2, 2}
assert.equals("#{2, 23}", a.toString())
```

and it actually sends the wollok message "toString" to each element

```
object myObject {
			method toString() = "My Object"
		}
		program p {
			val a = #[23, 2, 1, myObject]
			assert.equals("#[23, 2, 1, My Object]", a.toString())
		}
```
