### ISSUE TITLE
Run REPL without an associated file.

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#3]

**Comment by npasserini** [comment]
Duplicates issue #10

**Comment by javierfernandes** [comment]
Hey, shouldn't this be reopened ?
They are both marked as duplicates of each others #3 and #10 but none of them have associated commits. I think none of them have been solved

**Comment by npasserini** [comment]
Done.

**Comment by flbulgarelli** [comment]
Duplicate of #465

**Comment by flbulgarelli** [comment]
Anyway, was this issue solved?

**Comment by tesonep** [comment]
Yes, it is in the branch of development for 1.5
