### ISSUE TITLE
New Diagrams

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#315]
Provide some new diagrams to complement the "structure" and the "runtime diagram".

Some ideas here:
- *_Static Flow diagram: *_ to show a current method's body (?). Kind of a low level diagram like

<img src="https://me102.files.wordpress.com/2006/04/program%20flow%20chart.jpg"/>
- **Dynamic Sequence Diagram**: hooked into the debugging session. Interactively create the objects and show messages being sent between objects.
- **Dynamic Activity Diagram**: also hooked to the debugger, show a static diagram like the following, but decorated with colors to show where the flow is going

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Activity_conducting.svg/880px-Activity_conducting.svg.png" />

**Comment by fdodino** [comment]
Really nice idea, but 

- static diagram is barely used
- debugger would be a more useful tool

Considering lot of efforts will be put in wollok-ts, I'm closing this issue.
