### ISSUE TITLE
New Kind of "Projectional" Editor

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#316]
The idea is to try to create a new editor similar to the one that [MPS](https://www.jetbrains.com/mps/) has.
They are called "projectional editors" because the user sees text, but he doesn't directly write text. Instead there are "objects" and blocks there. And he can only move around between some placeholders and change some values.
Kind of a mix between a block editor (like Scratch or [Blockly](https://blockly-demo.appspot.com/static/demos/index.html)) and a text editor.

Here a simple screenshot:

<img src="https://confluence.jetbrains.com/download/attachments/49459198/Editor18.png?version=1&modificationDate=1357841176000&api=v2"/>

**Comment by fdodino** [comment]
Cool!

**Comment by fdodino** [comment]
Since it has to do with new ideas, I think it's ok to close it.
