### ISSUE TITLE
Blocks editor

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#317]
Prototype a block editor similar to Scratch and a couple of other current tools for teaching programming.

What would need to be designed and thought here is how that should be tailored or implemented for an OOP language like wollok.
Because all block implementations are for imperative procedural languages that don't include objects.

I think that we can base the implementation on [Google's opensource Blockly](https://developers.google.com/blockly/) library which is pure javascript and already can be extended for different languages.
This can also be ported to a web version easily.

Here is a just 30 minutes prototype screenshot

![unnamed](https://cloud.githubusercontent.com/assets/4428120/10500575/9b51beaa-72af-11e5-9cb4-6eb16a3694da.png)

**Comment by javierfernandes** [comment]
A long-term idea or branch of this work would be to create an XText generator (can be pluggable) that will generate the blockly javascript code automatically based on the xtext grammar.
Because in blockly you need to define something similar for each model element, just that it is a graphical description, but the concepts are the same

**Comment by fdodino** [comment]
There's already a [Wollok Blockly](https://github.com/uqbar-project/wollok-blockly) repo, so closing this issue.
