### ISSUE TITLE
Integrate autocomplete (code assist) into REPL

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#321]
Investigate whether we can reuse the code complete that we have in the editor, but for the REPL so that it can autocomplete variables and messages.
This will be really useful to avoid typos and writing a lot in the console.

**Comment by fdodino** [comment]
I would be great, yeah, :) but  I think this is not so important, mainly because we foster students to use unit testing as soon as possible.

**Comment by fdodino** [comment]
Since it could potentiially be easier in different tools (like VSC and LSP), and it's very hard to add autocomplete capabilities to Xtext environment, and since we need to focus in this new tools, I'm closing this ticket until something new comes up
