### ISSUE TITLE
Content Assist heuristic for parameters with the same name in diff methods (same class/object)

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#334]
In the absence of a type system, we would like to think of different heuristics to assist the programmer while coding.

Here is one that for sure cannot be 100% accurate, but could help

```xtend
object pepita {
        var energia = 100
	var ubicacion = 0

	method volarA(lugar) {
		energia -= ubicacion - lugar.ubicacion()
		ubicacion = lugar.ubicacion()
	} 
	
	method puedeIrA(lugar) {
		lugar. << ASSIST HERE >>
	}
}
```

Here a WKO has two methods having a parameter with the same name "lugar". This probably means that we expect that parameters to be polymorphic. There's some "concept" behind that name.
So in the second I would like to have proposals including the messages I've sent to the parameter of the other methods. In this case it will propose me "ubicacion()".

It would be nice to present this proposals with some kind of style or note telling the user that this is just a "guess" and that it might not be a correct message.

**Comment by javierfernandes** [comment]
@npasserini @tesonep what do you think of this ?

**Comment by javierfernandes** [comment]
Sample here for parameter "unCoso" for which there's also another method with a similar parameter.

<img width="302" alt="screen shot 2015-10-21 at 22 54 48" src="https://cloud.githubusercontent.com/assets/4428120/10655080/cde88752-7847-11e5-8ffe-724c1578b41b.png">

**Comment by npasserini** [comment]
Excelent!
