### ISSUE TITLE
[static-diagram] Show classes referenced by the current classes/objects being shown on the editor

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#345]
Currently the editor only shows the classes/objects declared on the current open file (in the editor).
I would like it also to show those classes/objects internally referenced by the code.
For example

``` xtend
class A extends X {    // x declared in another file

    method createFoo() = new Foo("blah")  // Foo also from another file
}

class B extends A {  
   method doSomething() {
       birdman.fly()           // birdman is a WKO defined in another file
   }
}
```

This must show:
- A and B defined in the current file
- Also X, Foo and birdman from other files.

Maybe they should be shown with a different style to differentiate them.

**Comment by fdodino** [comment]
@javierfernandes  Can we close this issue, and open a new one for Static Diagram with a DSL? So that students should be responsible for communicating 
- which relations
- which variables
- which methods are important.

**Comment by npasserini** [comment]
Why a DSL?
You are introducing a new language to be learned, it will distract your
students.

I have two alternate proposals:
1) Use wollok game to create a diagram builder... the challenge is how to
do it without metaprogramming, :-)
2) Allow the student to create and customize diagrams from the UI, without
DSLs.

**Comment by fdodino** [comment]
Hmm... I buy it because certain relations would be the same as Wollok.
I like 2) just because I haven't seen Wollok Game yet.
I'll continue in #844
