### ISSUE TITLE
[repl] Create a REPL preferences page for enabling/disabling syntax coloring

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#347]
Syntax coloring parses the repl content on every change. So it could be heavy.
We need a way to disabled it in case it performs badly. 
This will also give us flexibility.

There are two kinds of syntax coloring:
- one based on the ANSI output from the REPL itself. To disabled that we need to launch the repl passing some arg (there's another issue to implement that mechanism on the repl itself)
- one based on parsing the file (this one should be easier)

**Comment by fdodino** [comment]
I think this is useful for people with black themes also. Related to #1630
