### ISSUE TITLE
Runtime state control mechanism (for timemachine)

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#349]
This one is crazy.

If we have full control of the state and flow of the program in runtime, then we could do some crazy stuff like a "timemachine" program execution. Kind of a debugger session where you can, not only go forward in time by resuming execution, but also go back and re-play.

There's a similar concept in React with what I believe is a chrome plugin for development where you can see all the actions queued in a toolbar like photoshop "history", and then you can undo things.

Also related with this we could think of a better way to handle errors.
Stacktraces only contain static data. It would be really nice to have something more "complete" and "intelligent". A browsable stack trace including state at the different stack elements.
This could allow to explore back an execution and its state.

Many of this thinks would be kind of impossible to implement in a productive system. Specially in the presence of I/O. But for Wollok and a learning environment we could get rid of those special situations.

**Comment by fdodino** [comment]
There is a current wollok-ts implementation, since we are focusing on different tools, I'll close this issue. If someone else wishes to implement it, we can take it back to life.
