### ISSUE TITLE
Not all tests are running from maven

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#355]
If I run all the tests from eclipse (selection the project) then it recognizes 457 tests

<img width="498" alt="screen shot 2015-10-23 at 12 25 10" src="https://cloud.githubusercontent.com/assets/4428120/10697230/402e2404-7981-11e5-9dcb-457b9ff1c516.png">

But the maven build recognizes runs 415 (217+114)

```
Tests run: 271, Failures: 0, Errors: 0, Skipped: 4
Tests run: 114, Failures: 0, Errors: 0, Skipped: 0
```

Maybe it is because we are excluding some ?

**Comment by fdodino** [comment]
I'll put in the `Discuss` column, since we still need to debate about sanity tests.

**Comment by fdodino** [comment]
Stale issue, closing it.
