### ISSUE TITLE
Locigal operators || and && should be short-circuited 

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#358]
Example:

    class Una {
    	method prueba(unaClase){
    		if (false && unaClase.unMetodo()){
    			console.writeln("Success")
    		}		
    	}
    }   
    
    class Otra {
    	
    }

In the REPL:

    >>> var pepe = new Una()
    a Una[]
    >>> var otroPepe = new Otra()
    a Otra[]
    >>> pepe.prueba(otroPepe)
     Error in line (line:1): pepe.prueba(otroPepe) ...

The right hand side operant should not be evaluated if the left hand side is false.
The same happens on:

    if (true || unaClase.unMetodo()){

**Comment by javierfernandes** [comment]
Right, we are evaluating the two arguments ahead of op execution

```xtend
			binary.feature.asBinaryOperation.apply(binary.leftOperand.eval, binary.rightOperand.eval)
```

We need to make all binary operations use the second parameter as a lazy arg.
All other operations will just evaluate the value, but && and || will only evaluate the second if needed

**Comment by javierfernandes** [comment]
Fixed !

**Comment by npasserini** [comment]
Thanks!

Could we make this a quick fix and avoid waiting to the next minor version?
