### ISSUE TITLE
TypeSystem Label provider extension should only work if type system is enabled

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#363]
The same as the Type System extension to the validator/checker.

Currently the label provider is always executing, but it must also check the preference.
Maybe we can even add a new property to the "type system" section.

**Comment by javierfernandes** [comment]
See
* XSemanticsWollokTypeSystemLabelExtension
* XSemanticsWollokValidationExtension

**Comment by npasserini** [comment]
@fdodino Do you remember why is this issue labeled as "discuss".  We might consider it non-critical, but I do not see the discussion.

**Comment by fdodino** [comment]
Hahaha, I added this label maybe because a typo.
Removing it.
