### ISSUE TITLE
Find a way to post-process AST to hook wollok.lang.Object into all classes and objects

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#365]
Classes and objects without parent always inherit from wollok.lang.Object.

I would like to implement that in a single place. Probably that should be after parsing, and before validating.

Currently I'm doing that both in  the interpreter but also from the checker. Otherwise the checker fails !
I kind of hacked it in **WollokModelExtensions.resolveWKO()**

**Comment by fdodino** [comment]
Another stale issue, I'll close the issue until refactoring is clear enough to be developed
