### ISSUE TITLE
Error using min method on collections

### ISSUE THREAD

**Issue by dfortini** [uqbar-project/wollok#37]
when doing:
return golonrinas.min[p | p.energia()]

where energia is an integer

I get this error:
java.lang.ClassCastException: org.uqbar.project.wollok.interpreter.nativeobj.WollokInteger cannot be cast to java.lang.Comparable

**Comment by tesonep** [comment]
The problem is that WollokInteger, the wrapper of the integers is not a comparable of java. So the internal implementation of min is not working.

During the solving of this issue is needed to add tests for the methods of collections, to avoid the regression of this error.
