### ISSUE TITLE
Add button to re-launch last test from the tests view

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#373]
<img width="332" alt="screen shot 2015-11-03 at 17 13 37" src="https://cloud.githubusercontent.com/assets/4428120/10920345/543f8fde-824e-11e5-8dc0-8773eead833a.png">

Would be nice to have a button there to relaunch

**Comment by fdodino** [comment]
Implemented in release 1.4 by Pablo Tesone.
