### ISSUE TITLE
[check] method not returning value on every possible flow

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#385]
Example:

```xtend
	method capacidadDisponible(camion) {
		if (camion.tieneLugar()) {
			return camion.getCargaMaxima() - camion.getCargaActual()
		}
	}
```

This must not compile, since it only returns a value on the positive side of the if.

**Comment by npasserini** [comment]
Excelent!

**Comment by javierfernandes** [comment]
Fixed !

<img width="303" alt="screen shot 2015-11-13 at 12 28 00" src="https://cloud.githubusercontent.com/assets/4428120/11149583/6f43767c-8a02-11e5-95ba-0def4e7cab53.png">
