### ISSUE TITLE
IDE should produce a warning before executing a project with errors.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#394]

**Comment by fdodino** [comment]
It is done for tests, I'm not sure for a program, but it is easy to achieve if you see Test Launcher.

**Comment by fdodino** [comment]
See WollokTestLaunchShortcut in org.uqbar.project.wollok.ui.tests.shortcut, method launch()

**Comment by npasserini** [comment]
On saturday, this annoyed me a little. I think it might be ok to produce a
warning, but I didn't like that it forbid me to run any test, I think it
could be nicer to be a bit more flexible.

2017-04-21 14:44 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
But otherwise you get no error message and no output (if you try to run tests in a .wtest file dhat does not compile). Ok, maybe the best approach could be to run tests that are ok, but i think it is not simple to achieve.

**Comment by npasserini** [comment]
Maybe I wasn't clear. I do not want "no error message and no output".
What I would love is the eclipse (for Java/XTend/...) regular behaviour:
receive the warning message, but allow me decide to run anyway.
I am not sure here if you just do not like the idea or you think is better
to forbid execution on any error or it is just that the "warning + run
anyway" option was just in front of me and I didn't see it.

Anyway, I do not like the "no output" in any case. If a test can not be run
because it can not be parsed, it should appear in the test report. If no
test was found, that should also be reported.
I guess all of this can be really difficult, but just the warning message
could do it for now and we can planify the improved reporting for the next
iteration.

2017-04-27 15:13 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
"I am not sure here if you just do not like the idea or you think is better
to forbid execution on any error or it is just that the "warning + run
anyway" option was just in front of me and I didn't see it."
None of them.
:smile: 

I like the idea.
But since recovering from a parse / link / whatever error seemed a hard task, I preferred to avoid such a bad behavior.
Ok, let's just warn user and make an improvement later.

**Comment by npasserini** [comment]
:+1:


2017-04-28 6:59 GMT-03:00 Fernando Dodino <notifications@github.com>:
