### ISSUE TITLE
Static diagram should keep node positions (layout) when refreshing

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#397]
Now it automatically refreshes the content while typing. But it changes the node positions.
So if you manually layed-out it will lost the node positions

**Comment by javierfernandes** [comment]
@fdodino was working on a new layout for the diagram.
This issue could be related to that (invalidated probably).

Fer feel free to delay this to v1.6 if you think we will not make it for 1.5
I'm trying to clean up the milestone being reallistic

**Comment by fdodino** [comment]
Ok, I have 3 releases in mind:
- For 1.5 (monday perhaps) I'll push several enhancements
- For 1.5.1 I'll continue working on enhancements if I don't get them all (such as avoid redrawing all figures every time you write a letter)
- For 1.6 we should work  on a customized static diagram view, with a DSL that every student should define for each project

**Comment by javierfernandes** [comment]
:)

**Comment by fdodino** [comment]
I didn't read the original issue. 

:)

I think this will be in version 1.5.1

**Comment by fdodino** [comment]
Added a toolbar, so you can move a class / object , and IDE remembers every position of each element you move. You can also clear fixed positions from toolbar.

**Comment by npasserini** [comment]
Genial!

2017-05-19 20:26 GMT-03:00 Fernando Dodino <notifications@github.com>:
