### ISSUE TITLE
Auto-Format distinct invocation messages in distinct lines

### ISSUE THREAD

**Issue by sancuba** [uqbar-project/wollok#404]
Cuando escribo esto:
objeto.mensaje1()
objeto.mensaje2()
objeto.mensaje3()

y luego aplico formato automatico presionando Ctr+Shift + F me lo deja asi:
objeto.mensaje1() objeto.mensaje2() objeto.mensaje3()

**Comment by fdodino** [comment]
Hay varios issues relacionados con el componente formatter. Lo pasamos por el momento a NiceToHave.

**Comment by fdodino** [comment]
Ya hay un test que pasa ok en el branch formatter-issues. En proceso.
