### ISSUE TITLE
Bad if usage does not contemplate negated condition

### ISSUE THREAD

**Issue by Lucas-Quintana** [uqbar-project/wollok#407]
When writing:
`if (poder > 50) return true`
`else return false`
You get the same error message and solution than
`if (poder > 50) return false`
`else return true`

**Comment by javierfernandes** [comment]
Good catch !

Fixed now in "dev" branch (will be released with v1.3.0)

If the "if" returns the negated condition then the message is different as in the next screenshot

<img width="575" alt="screen shot 2015-11-19 at 12 28 57" src="https://cloud.githubusercontent.com/assets/4428120/11274777/358922fe-8eb9-11e5-952e-dce43ac5abfb.png">
