### ISSUE TITLE
wlk filename: dashes (-) mess with import declarations

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#411]
I have:
file-1.wlk (has code)
other.wlk (has an import)

In other.wlk I write "import file-1.wlk" and it marks the hyphen with an "ERROR EOF expected".

I elliminate the hipyen, and everything goes smoothly.

**Comment by tesonep** [comment]
This problem is because the name of a file with a hyphen in the middle is not a valid identifier, my proposal is adding a validation of the name of the file? Does it is good enough?

**Comment by Juancete** [comment]
And when you make a wlk file with spaces like "my file.wlk" you get the following error when launck with REPL:

**ERROR [main] (WollokChecker.java:89) - Repl can only be used with .wlk files.**

Same if you make a wlk file with dots in the middle like "my.file.wlk". You can run with REPL but if you send a message to an object you get the following error:

**ERROR: Cannot resolve import my.file.* (line: -1)**

**Comment by tesonep** [comment]
To me there two things to do here. 

1) add a new validator to check the name of the file. Giving error in the first element, more or less the same that happens when you have the package wrong in xtend. It should check: 
     - that the filename, without the extension, is a valid identifier (no spaces, no dots, no hyphens) 

2) Modify the wizards to validate the entered filename with the same logic.

**Comment by fdodino** [comment]
2) is done in a branch

**Comment by tesonep** [comment]
It is not only in a branch, it is in the productive version.
