### ISSUE TITLE
Use Haskell/Prolog lists syntax

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#415]
Most OO modern languages - JS, Python, Ruby, Swift, Groovy - use plain brackets to create literal collections, only XTend has the `#[]` syntax. The more symbols you need to represent a thing, the more ackward to the student looks. 

Also Haskell and Prolog have the same syntax for non head-tail lists. In order to keep compatibility with those languages, as in #409 in am proposing there to use that syntax.

**Comment by flbulgarelli** [comment]
I understand the complexity of this change since it somewhat collides with block's syntax. But we should give a try.

**Comment by npasserini** [comment]
I think we could do it for lists if we change block syntax. We could use
something like Javascript new closure syntax: (args) => {code}.. ideally
with both () and {} being optional. Not sure.

**Comment by flbulgarelli** [comment]
I like that proposal. 

I actually feel a little ackward the brackets syntax for closures. When you have worked for 6 months with Haskell and Prolog, then seing `[ 4 ]` looks like the list with just the element `4`, instead of a block that returns `4`.

The main issue is to replaces brackets with braces, which has quite sense since we are already using the braces to syntactially group collaborations - sentences.  Then any syntax for parameters could work: 

* `(x, y) => {}`
* `{ x, y ->  }`
* `{ (x, y) -> }`

and so on. 

We should consider the request of adding literal dictionaries here. Maybe we want to reserve some arrow syntax for key-value pairs, like in Scala or Ruby

**Comment by npasserini** [comment]
I think that set/dictionary literals will have to stick to the #{} notation

```
val mySet = #{1,2,3}
val myDict = #{a -> 1, b -> 2}
```

It is not so nice, but (unlike lists) this literals are optional, so you
could use new Set/new Dict/Map instead.

**Comment by flbulgarelli** [comment]
Fixed.
