### ISSUE TITLE
REPL won't let you type anything besides an enter at startup

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#421]
We saw this at the wollok-day.
Not sure if it only happens on windows, or on every s.o.

**Comment by npasserini** [comment]
Happens on linux.

**Comment by javierfernandes** [comment]
Works fine in mac.
I cannot reproduce it :(

**Comment by matifreyre** [comment]
Still happens in Windows. Has there been any advance with this?

**Comment by Juancete** [comment]
Done!
