### ISSUE TITLE
Allow a single catch block with undefined explicit type 

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#424]
For example:

```xtend
try {
   pepita.fly()
}
catch e {
    pepita.eat()
}
```

In this case e is inferred to be *wollok.lang.Exception* type.

This allow us to introduce error handling without taking about types.

Maybe this can also be used for default cases

```xtend
try {
   pepita.fly()
}
catch e: PepitaNoTieneEnergiaException 
    pepita.eat()
catch e {     // means any other exception
    console.println("Se rompio todo")
    throw e
}
```

**Comment by javierfernandes** [comment]
@npasserini  what do you think ?

**Comment by npasserini** [comment]
Works for me. I am not a fun of Java-like exception handling, yet I do not
have a better proposal. This could be an improvement, pospone type-based
catching.

Other ideas I would like to discuss are:
- Deprecating "exceptions" and allowing to throw any object.
- Using more advanced pattern matching in catches.
- Introduce symbols and use them as the simplest example of pattern
matching.

Examples
```xtend
class Golondrina { method volar(cuanto) if (!this.puedoVolar(cuanto) {
throw NoPuedoVolar(cuanto) }
class Golondrina { method volar(cuanto) if (!this.puedoVolar(cuanto) {
throw "no puedo volar " + cuanto }
class Golondrina { method volar(cuanto) if (!this.puedoVolar(cuanto) {
throw :NO_PUEDO_VOLAR_TANTO }
```

In the last example we could require the declaration of the error (like an
object or a new construction) or not (like scala or pharo symbols).

Y los catches correspodientes:
```xtend
try { ... } catch e : NoPuedoVolar // just like now but with any object
try { ... } catch NoPuedoVolar(cuanto) // destructure and bind 'cuanto'
variable
try { ... } catch "no puedo volar" // simple string matching
try { ... } catch :NO_PUEDO_VOLAR_TANTO // as a symbol
```


None of these completely works for me, they require a little more thought.
So +1 to your proposal, at least until I can figure something else.

**Comment by javierfernandes** [comment]
Implemented !

**Comment by npasserini** [comment]
What did you implement exactly!

**Comment by javierfernandes** [comment]
The original idea. The type is optional. Also a check for unreachable
catches. So you can only have one without type. No type means
wollok.lang.Exception. It is all documented in the release notes
