### ISSUE TITLE
Replace null by nothing

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#425]
This is more a question that an actual request: should we use `null` or `nil`?

Again C++ languages use `null`, while `nil` comes from Smalltalk-influenced languages. 

Here I don 't have a strong position for the Smalltakish name, but I think that `nil` is a backward compatible term with our bibliography. 

And, it is just a matter of taste, but using `nil` maker our wollok look less Javish :smile:

**Comment by fdodino** [comment]
After discussing with Wollok development team, we decided to rename null to **nothing**

**Comment by fdodino** [comment]
Después de haber trabajado en el issue #1366 (PR #1691) cada vez me convenzo más de no invertir tiempo en hacer este cambio por lo complicado de dejar andando todo ok y el poco efecto que tendría en los alumnos relacionar el concepto "nothing" con `null` o `nil` que ya conocen de otros lenguajes. Es decir, alto costo para tan poco beneficio, donde además el null de Wollok se mezcla con el null propio de la JDK en la implementación interna. Lo muevo a la columna Won't Do, creo que la oportunidad de reflotarlo está para la versión WollokJS.
