### ISSUE TITLE
Check if your VM is compatible with your Eclipse product

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#426]
It has happened that Eclipse does not start because it is a 64bit version and it can not run in a 32bit vm, producing an obscure error. 

It would be nice to check this before and produce a more understandable error, maybe even including instructions to fix the problem.

**Comment by javierfernandes** [comment]
I think we could ship the JRE within the product itself

<img width="360" alt="screen shot 2015-12-07 at 09 12 21" src="https://cloud.githubusercontent.com/assets/4428120/11626607/cd5cdfd2-9cc2-11e5-8b75-118bfce9acad.png">

It will increase the package size though

**Comment by npasserini** [comment]
I am not sure if it is a good idea... because JRE has to be installed I
think and in some machines you do not have necessary rights. Don't you
think?

**Comment by javierfernandes** [comment]
I believe that, when it is bundled then it's a "portable" version. No need
to install it.
I need to check.

**Comment by npasserini** [comment]
Why is this a discussion?
I'll move it to "nice to have".

**Comment by fdodino** [comment]
After Oxygen, 32bits installation are no longer support. I'm closing this issue since it will require an extra effort for the student to download an old 32 bit version of Wollok and then use the appropiate 32bit JRE.
