### ISSUE TITLE
Wollok.org typo

### ISSUE THREAD

**Issue by aitrusgit** [uqbar-project/wollok#428]
Hay un typo bastante confuso en el overview de wollok ( http://www.wollok.org/learn/modulo2-objetos )

````
object pepita {
 ... 

 method volar(metros) {
 energia = energia = 4 * metros
 }
}
````

deberia ser

````
object pepita {
 ... 

 method volar(metros) {
 energia = energia - 4 * metros
 }
}
````

**Comment by javierfernandes** [comment]
I think I don't have access to change that.

**Comment by npasserini** [comment]
Claudio if you have a google-sites user I can give you access so you can
fix it yourself.

**Comment by aitrusgit** [comment]
I should have,  claudiof@gmail.com

**Comment by npasserini** [comment]
Done, you have rights to fix it.
Javi please check again, you should have full access rights to the site.

**Comment by javierfernandes** [comment]
Cool I have now

**Comment by matifreyre** [comment]
Closing this.
That page doesn't exist anymore. I didn't find such a typo in the new language reference, the examples or the doc.
Please re-open if needed.
