### ISSUE TITLE
Model MessageNotUnderstood exception in wollok itself

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#429]
We need to model it as a regular wollok Exception

**Comment by npasserini** [comment]
Why?

**Comment by javierfernandes** [comment]
Ok, maybe it was not 100% necessary :P  But it will simplify the interpreter to have it modeled as another regular wollok exception, and reuse the same code that shows an exception.
I guess it is "elegant" in the sense that the interpreter should be easier.

I'm not doing it to have a dynamic programming model. I'll prefer to have a simpler type system and not dynamic facilities.
I guess that we can limit this method to avoid dynamic objects and therefore make the type system easier.

**Comment by javierfernandes** [comment]
Sample outputs:

```
wollok.lang.MessageNotUnderstoodException: a AsustadorNato[nivelMotivacion=100, edad=25, puntosTerrorInnatos=200] does not understand cantina()
	at wollok.lang.Object.messageNotUnderstood(name,parameters) [/wollok.wlk:151]
	at  [/workspace.wpgm:23]
```

<img width="489" alt="screen shot 2015-11-17 at 00 22 29" src="https://cloud.githubusercontent.com/assets/4428120/11216423/db350466-8d29-11e5-8fdb-7b12ff68ba8c.png">
<img width="486" alt="screen shot 2015-11-17 at 00 33 01" src="https://cloud.githubusercontent.com/assets/4428120/11216422/db310b2c-8d29-11e5-931a-cd501c78a4a3.png">
