### ISSUE TITLE
Add Ranges as collections.

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#43]
The message 1.to(10), generates a new WList[1,2,3,4,5,6,7,8,9,10]

The message 1.toByStep(3,0.5) generates WList[1, 1.5, 2, 2.5, 3]

**Comment by tesonep** [comment]
Ready to be integrated into master

**Comment by JuanchiRios** [comment]
This should be working in Wollok Diderot? Because if i do
`1.to(20)`
i get 
```
wollok.lang.MessageNotUnderstoodException: 1 does not understand to(p0)
	at wollok.lang.Object.messageNotUnderstood
```

@tesonep @javierfernandes
