### ISSUE TITLE
Can't override a method that returns a value with a method that just throws an error

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#435]
A message "Must return a value since overridden method returns a value" is shown in these cases, but the overridden method could be a generalization that might not apply to a specific subclass and therefore this should be allowed.

Example:
```wollok
class Persona {
  method quiereSubirA(unMicro) {
    return false
  }
}
class Indeciso inherits Persona {
  override method quiereSubirA(unMicro){  // ERROR
    throw new AunNoMeDecidoException()
  }
}
```

**Comment by javierfernandes** [comment]
Fixed in "dev" branch.
Can be updated via update site url (using the dev one).
Will be part of the 1.3.0 release Dec 14th (potential release date)
