### ISSUE TITLE
Autocomplete should show where the method comes from

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#437]
For example in Java/xtend eclipse shows as text decoration in gray where the method comes from

<img width="336" alt="screen shot 2015-11-18 at 09 48 42" src="https://cloud.githubusercontent.com/assets/4428120/11241462/c627645a-8dd9-11e5-9c24-724f840fccc4.png">

**Comment by Juancete** [comment]
@javierfernandes do you like something like this ? 
![autocomplete](https://cloud.githubusercontent.com/assets/1617224/25927766/9b032e6e-35ce-11e7-9587-54f26d796f8d.png)

**Comment by npasserini** [comment]
Nice!

2017-05-10 22:19 GMT-03:00 Juancete <notifications@github.com>:

**Comment by javierfernandes** [comment]
Cool.
I guesd that in english it should be "from class B"

Also in terms of usability it would be nice that if the class is in the
same package as the one you are writting the client code then just use the
simple name. But if it is in a different package/namespace then use the
fullname. It couls be useful in cases like
- the class is in another file
- same file but you have a complex model with many packages
- idem but even more useful you have two classes B in different packages
(to identify wich one is)

These are just nice to have enhancements :)

**Comment by Juancete** [comment]
That's right!!! it's "from class B". Sorry for my english. I write like an animal.

i worked with this and i get something like: 
![resolved](https://cloud.githubusercontent.com/assets/1617224/26038246/4b2aef4e-38da-11e7-9623-04df024e83d6.png)

Also, it works wit objects
![objects](https://cloud.githubusercontent.com/assets/1617224/26038248/583e48b6-38da-11e7-83fc-c920356dad5a.png)

And mixins
![mixin](https://cloud.githubusercontent.com/assets/1617224/26038251/6202a356-38da-11e7-8fdb-a0cde58b2686.png)

Is this what you expected @javierfernandes ?

**Comment by javierfernandes** [comment]
Yes, exactly !
That's great.

Now, this is a extremely obsessive comment, but, from a ux point of view, I
wonder if it is not better to avoid using the common FQN syntax and always
show the class simple name and then have the package as a context further
down the line with parenthesis, here let me show:

```
pruebaPropia - from class R
pruebaExterna - from class A (archivoExterno.conUnPaquete)
pruebaHeredada - from class B (example.afuera)
```

I'm not sure. This crossed my mind because I was not able to see the actual
class name in the screenshots because the tooltip was to narrow, and it
seems like you need to scroll all the way to the right to see the class :S

PS: I liked the "pedo" variable :)

**Comment by Juancete** [comment]
Yes, I think you're right. Is a better solution. 
![fixed](https://cloud.githubusercontent.com/assets/1617224/26039125/fa52df06-38ec-11e7-8ce6-3022f0eb42cf.png)
PS: Fuck!!! My mistake.... I renamed it :smile:

**Comment by npasserini** [comment]
Genial, y ya que estamos tan sutiles, ¿qué pasa si volamos class?
Entiendo que podría no ser una clase si no un mixin, pero es un caso raro,
así que cuando es clase podría no decir nada.

2017-05-14 21:34 GMT-03:00 Juancete <notifications@github.com>:

**Comment by Juancete** [comment]
@npasserini en el post previo se ve que discrimina entre objeto, clase y mixin alternado el texto que muestra :smile:

**Comment by npasserini** [comment]
Sí, no lo dudo, mi pregunta es si no podemos hacer que cuando sea de una
clase (que debería ser 99% de los casos) no ponga nada.
Y hasta donde entiendo "objeto" no puede ser una opción, salvo self.

2017-05-14 22:48 GMT-03:00 Juancete <notifications@github.com>:

**Comment by Juancete** [comment]
Objeto entiendo que es cuando luego de crear un WKO y al utilizar dicho objeto en otro lugar obtengo un autocompletar. Por ejemplo si tengo un WKO denominado a y tiene definido un metodoA(), si dentro de un test hago a. y trato de obtener los mensajes que puede entender, ahí se completa el "From objet a".

¿Puede ser o lo malinterpreto yo?

**Comment by npasserini** [comment]
Tenés razón, hay casos donde va object.

Igualmente, dado que los objetos serían con minúscula y las clases con
mayúscula uno podría prescindir de esas palabras. No sé, ¿qué opinan los
demás?

2017-05-14 23:27 GMT-03:00 Juancete <notifications@github.com>:

**Comment by javierfernandes** [comment]
Mmm.. es un tema. Entiendo que lo querés ocultar para que no aparezca la
palabra "clase" a quien todavía trabaja sólo con objetos y no con clases.
Pero sacarlo directamente también le quita utilidad luego, cuando sí estas
laburando con todo el lenguaje (objetos/clases/mixins).

No se cómo quedaría y si se puede (qué tan fácil es), pero tal vez podría
solucionarse usando el iconito de clase/objeto/mixin justo antes del nombre
de la clase/objeto.
O sea, habría 2 iconos, el primero dice si es un método o variable u
objeto.. blah.. como hasta ahora,

`icono - nombreElement - [From] iconoContexto nombre [(fqn)]`

Otra opción más molesta es que el ícono del elemento (método digamos) tenga
variantes según de donde viene, entonces, que sea el (m) pero de diferentes
colores (??)

Podríamos también ver cómo hacen los otros IDEs o el eclipse para
Scala/Java, ya no recuerdo ahora

2017-05-14 23:29 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by npasserini** [comment]
2017-05-15 8:40 GMT-03:00 Javier Fernandes <notifications@github.com>:

> Mmm.. es un tema. Entiendo que lo querés ocultar para que no aparezca la
> palabra "clase" a quien todavía trabaja sólo con objetos y no con clases.
> Pero sacarlo directamente también le quita utilidad luego, cuando sí estas
> laburando con todo el lenguaje (objetos/clases/mixins).
>
>
Ja, no había pensado en eso, pero también puede ser.
Lo mío era más sutil: sólo que me parece que (casi) siempre dice clase y
que lo hace más verboso al pedo, desde un punto de vista de UX no es
información, es ruido que hace más difícil encontrar lo que sí me interesa.


> No se cómo quedaría y si se puede (qué tan fácil es), pero tal vez podría
> solucionarse usando el iconito de clase/objeto/mixin justo antes del nombre
> de la clase/objeto.
> O sea, habría 2 iconos, el primero dice si es un método o variable u
> objeto.. blah.. como hasta ahora,
>
> `icono - nombreElement - [From] iconoContexto nombre [(fqn)]`
>

Intersante, no sé qué tan fácil es.

Hay otra dimensión para pensar, porque antes de que Juan me lo hiciera ver,
yo me estaba imaginando onda contro+o, o sea estoy viendo los métodos del
objeto/clase en el que estoy codeando.
En cambio veo que esto permite también ver los mensajes que le puedo mandar
a un objeto que estoy usando (que ya no es lo que estoy codeando).

En el primer caso, la situación pide (o podría pedir) que vos discrimines
por qué mi objeto tiene esos mensajes que yo no codeé, de dónde salieron.
En la segunda, me parece más dudoso, si vos querés mandar un mensaje no te
importaría tanto si lo implementa el objeto x o su superclase. En todo caso
uno podría hacer algo espercial para los métodos que vienen de object.

Creo que sería bueno decidir esto antes de continuar con lo anterior.

**Comment by javierfernandes** [comment]
Sí, el mecanismo del autocomplete es el mismo.
Sería muy bueno poder tener info contextual, como decís. Si estoy
mandandome mensajes a this, entonces me sirve ver de donde viene, si estoy
"codeando" dentro del objeto digamos.

Si estoy por fuera no, o capaz sí, mejor tenerlo como opcional.
El eclipse en Java tenía un doble CTRL+O, o sea, la 2da vez que apretabas
CTRL+O te agregaba más métodos (los sobrescritos (?)).
Capaz acá podría ser lo mismo, o tener un shortcut más. Por defecto desde
afuera no muestra de donde viene, pero un segundo CTRL+barra agregar la
info de contexto



2017-05-15 12:12 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by Juancete** [comment]
Me gusta la idea que se tenga en cuenta el contexto. Creo que no sería difícil. El tema del doble CTRL+O habría que investigarlo... tal vez se pueda hacer que cambie el comportamiento. Si sale entonces quedaría algo como:

* **Self y CTRL+O** => muestro origen tal como está.
* **objeto y CTRL+O** =>  solo muestra la firma del método. 
* **objeto, CTRL+O y CTRL+O** => muestra el origen de cada método

¿No? Referente a poner una imagen en medio del StyledText del popup no parece ser muy sencillo, pero entiendo que se podría hacer.

**Comment by npasserini** [comment]
A ver, esto lleva un montón de brainstorming e ideas que no sabemos qué tan
difícil es implementarlas. Así que, Juan, fijate vos dónde cortarla, hacé
algo simple y mergealo y en todo caso dejemos hagamos otro issue para
pensar opciones más complejas tranquilos.

Al margen de eso, me gusta la idea del doble ctrl+0, pero creo que hay que
es diferente a lo que estamos haciendo ahora. Corregime Juan, pero creo que
el eclipse labura como dice Javi:

   - ctrl+o muestra los métodos que corresponden a la clase/objeto dónde
   estoy parado. No importa exactamente la selección, no es un autocomplete,
   es una forma de navecación por el archivo.
   - ctrl+barra autocompleta mensajes entre otras cosas.

Lo que Juan dice en el último mail mezcla las dos cosas, no estoy seguro de
que sea una buena idea, yo mantendría el comportamiento del eclipse.
En ambos casos, presionar de nuevo la misma combinación cambia el
comportamiento:

   - ctrl+o muestra métodos heredados (creo)
   - ctrl+barra cambia las sugerencias, cicla sobre diferentes propuestas.

Eso lo podemos tunear en wollok, pero mantendría la idea de que ctrl+o sea
para navegar y ctrl+barra sea para autocompletar.
Resumiendo una propuesta podría ser:
A) Siempre ctrl+barra permite autocompletar. En el caso que lo que sigue
sea un envío de mensaje y hay más de una opción muestra los mensajes que
puedo mandar.
A1)
Si el texto anterior es "super." debería mostrarme los mensajes a partir de
mi super clase.
Entre self y cualquier otra cosa no veo diferencias en principio.
A2) Por default no mostraría el origen de los mensajes.
A3) Por default deberíamos filtrar mensajes de muy bajo nivel en algunas
clases de Wollok que idealmente no deberían mostrarse.
Tal vez para arrancar podríamos filtrar todo object y fumar los demás, a
futuro me gustaría pensar algo más inteligente.
A4) ctrl+barra adicionales podrían cambiar lo que se muestra, por ejemplo:
- el segundo no agrega opciones pero muestra el origen de los mensajes
- un tercero mostraría los mensajes que fueron filtrados en a4

Esto es lo que más dudas me da, tal vez no deberíamos hacer nada de eso y
en cambio tener una opción de configuración.

-------------------
B) ctrl+o debería permite navegar entre los métodos de la definición actual
B1) No tiene sentido pensar en self/super/otro, no importa el texto exacto
debajo del cursor, lo que mira es la definición de objeto/clase/mixin en la
que estoy parado.
B2) Por defecto muestra los métodos de la propia definición, ctrl+o
adicionales agregarían
- superclases o mixins "propios"
- superclases o mixins de librerías y/o core wollok.
- un ctrl+o extra lo volvería al original.
B3) Todo método que no corresponde a la definición actual debería indicar
scope, siguiendo la propuesta de Javi varios mails más atrás.
B4) No creo que sea necesario indicar que el origen es una clase, porque es
la opción por antonomasia, sólo pondría un indicador cuando es un mixin.
Acá entiendo que no puede ser un objeto, porque los propios no tienen
indicación de origen y los heredados no pueden ser de un objeto.


2017-05-15 14:16 GMT-03:00 Juancete <notifications@github.com>:

**Comment by Juancete** [comment]
Ok. Ahora muestra de donde proviene el método si es llamado desde "self". En otros casos no.
