### ISSUE TITLE
Autocomplete should show the wollokdoc documentation of each method

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#438]
In java/xtend besides the autocomplete box on its right it shows another box with the current selected autocomplete documentation. This helps a lot the user to know what that method does, without having to navigate to it.

Here it shows a little bit on the right, as a yellow box
<img width="336" alt="screen shot 2015-11-18 at 09 48 42" src="https://cloud.githubusercontent.com/assets/4428120/11241462/c627645a-8dd9-11e5-9c24-724f840fccc4.png">

**Comment by fdodino** [comment]
Fixed recently, still trying to use ICompletionProposalExtension3 to display html info.
