### ISSUE TITLE
Autocomplete should show inherited methods

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#439]
For example here:

<img width="211" alt="screen shot 2015-11-18 at 09 53 07" src="https://cloud.githubusercontent.com/assets/4428120/11241517/33ab0ad6-8dda-11e5-8d4b-897b4b057795.png">

It should also show the wollok.lang.Object methods inherited by A.

I think that we should find a way to show them so that the user can differentiate those messages in A from those inherited. Maybe organizing the list like a tree with class "classes" as categories (groups) and also sorting it as the hierarchy branch ?

**Comment by javierfernandes** [comment]
This will make more sense once we have a better type system

**Comment by fdodino** [comment]
This issue was already solved (I don't know who did) :)
