### ISSUE TITLE
Add syntax highlighting to Mumuki editor for wollok

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#445]
On Wollok side I will create a small generic app that will generate what mumuki needs based on the xtext grammar, so that we don't need to manually maintain another file and apply changes every time we update the wollok grammar.
I already know how to generate a list of wollok keywords dynamically.

I might also publish this as a separated tool for any xtext language, to contribute to xtext community, if the output is generic enough.

**Comment by javierfernandes** [comment]
@flbulgarelli @faloi what do you need for this ?

Where can I take a look for other examples of syntax highlight for other languages ?

**Comment by flbulgarelli** [comment]
Hi! We need support for Ace editor format, and Github Flavoured markdown format

**Comment by javierfernandes** [comment]
I guess that one needs to create a new Ace editor mode

https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode

Although Ace page says Sublime hightlight can be imported into Ace.
We already have one of that

**Comment by javierfernandes** [comment]
Example custom ace mode for bash

https://github.com/flexiant/ace-mode-bash

**Comment by faloi** [comment]
> Although Ace page says Sublime hightlight can be imported into Ace.
We already have one of that

Here is the [HOW-TO](https://github.com/ajaxorg/ace/wiki/Importing-.tmtheme-and-.tmlanguage-Files-into-Ace), updated on September 2012 :worried:. Can you give it a try?

**Comment by javierfernandes** [comment]
I created a new one based on Java's mode in Ace

<img width="779" alt="screen shot 2015-11-19 at 16 49 30" src="https://cloud.githubusercontent.com/assets/4428120/11282335/90be15e8-8edd-11e5-8f60-5ea46eedec7f.png">

It still requires manual work to maintain. And I had to copy paste java mode code which has a lot of code that I don't fully understand, but it works relatively well.

I need to:
* Fix the small tool that I created in Wollok that generates a json with the grammar keywords and operatores. The regexp that it generates is not escaping all values.
* add that to git
* Create a new repo for the "wollok-ace-mode"
* See how Mumuki can use this mode (maybe I can create a PR for ace repo so that they can include wollok mode by default ?)

**Comment by faloi** [comment]
> See how Mumuki can use this mode (maybe I can create a PR for ace repo so that they can include wollok mode by default ?)

Yes, let's try that first. Modes are not pluggable, so to include it we have to fork many repositories (Ace, the gem that provides Ace on Rails, etc).

**Comment by javierfernandes** [comment]
rails :S

**Comment by javierfernandes** [comment]
Here is an example PR for drools

https://github.com/ajaxorg/ace/pull/2672

**Comment by javierfernandes** [comment]
Ok. I think that I already have it ready for creating a PR to ace.
I was able to create a test and run it successfully.

I have also contributed with code snippets which allows to have a basic autocomplete !!
Look !

<img width="735" alt="screen shot 2015-11-20 at 14 12 13" src="https://cloud.githubusercontent.com/assets/4428120/11306488/df6c1bc8-8f90-11e5-98be-3988ef2a5f6c.png">

@npasserini 
@faloi 
@flbulgarelli 

To enabled this you should include this in mumuki html

```html
<script src="/Users/jfernandes/dev/data/repo/wollok/ace-editor/wollok-ace/build/src/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="/Users/jfernandes/dev/data/repo/wollok/ace-editor/wollok-ace/build/src/ext-language_tools.js" type="text/javascript" charset="utf-8"></script>

<script>
    var editor = ace.edit("editor");
    //editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/wollok");
    editor.setOptions({
        enableBasicAutocompletion: true
    });
</script>
```

(disregard my local path, the second js

**Comment by javierfernandes** [comment]
PR created https://github.com/ajaxorg/ace/pull/2776

**Comment by flbulgarelli** [comment]
Awesome

**Comment by javierfernandes** [comment]
PR closed !

https://github.com/ajaxorg/ace/pull/2776

**Comment by flbulgarelli** [comment]
Awesome!
