### ISSUE TITLE
XText DSL for code complete

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#446]
Currently to add code complete proposals in xtext you need to use a complex API and if you also want it have it i18nized there would be a lot of bureaucracy .

For example

``` xtend
    addTemplate(WLibraryElementRule, templateContext, acceptor, WollokTemplateProposalProvider_createPackage_name, WollokTemplateProposalProvider_createPackage_description, "org.uqbar.project.wollok.createpackage", context,
'''package ${packageName} {

}''')
```

There's a name, description, and id. Name and descriptions are Messages. keys that are i18nized.
This all is for creating a new rule element a Package.
You also need to register the template based on the generated rule element class (WLibraryElementRule) in this case.

Notice that this can be generalized as a template for creating a rule element.

In wollok we have improved this a little bit by using some xtend features like extension methods and operator overloading.

``` xtend
<< WPackage >>
'''package ${packageName} {

}'''
```

This is still embedded in xtend code.

It would be nice to have it as an external DSL built with xtext itself.

Another approach (maybe complementary) is to have this templates automatically generated based on the grammar.
Notice here the way the WPackage grammar is described:

```
WPackage:
    'package' name=QualifiedName '{'
        elements+=(WClass | WNamedObject)*
    '}'
;
```

If we could read those tokens and replace the dynamic parts by variables, for example

```
package ${name} {
     // TODO: elements
}
```

It would be really cool !

**Comment by fdodino** [comment]
Closing this issue since it's difficult to customize an autocomplete behavior and we are focusing on different issues.
