### ISSUE TITLE
Generalize the debugger infrastructure into a XText Debugger Framework

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#447]
Our debugger implements a lot of behaviour (and therefore code) that could be reused for any other XText interpreted language.
For example the remote communication between the Eclipse UI and the interpreter (RMI).
Also the state machine for stepping, in, out, resume and breakpoints handling.

It all could be generalized. It's actually already in terms of EObjects.
We just need to extract it and introduce some extension points for filtering content (transparent elements), and stuff like that.

I think that this can be contributed into XText with worflow generator step

**Comment by fdodino** [comment]
Nice epic to do, but since we are moving to different tools like wollok-ts it's ok to close this issue.
