### ISSUE TITLE
Investigate how to disable language features in XText

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#450]
The best would be to somehow annotate grammar rules.
But as there is no Xtext out-of-the-box mechanism I think that we need to intercept many points to disabled different aspects of the language.
For example disabling the "if" expression means
- **content provider:** won't show it
- **validator:** writing an if will generate an error
- **syntax highlight:** won't highlight the if expression
- **runtime (interpreter):** will fail with a particular message
- **linker:** for example for the "it" keyword, or automatically generated accessors.

This could become more complex if a language feature involves more than just a single grammar rule.
At the end maybe we could think of a statically typed DSL to defined languages configurations.

Some example use cases:
- disable **if expression**
- disable **properties** (auto getter / setters)
- disable **short-syntax mode**: could be something like: optional parenthesis for constructors and method calls (with no args);  the "it" operator plus and "with" operator; short syntax for function's apply.

**Comment by javierfernandes** [comment]
This gets even more complex if you think that a wollok program can be written with certain lang settings (no if, etc) but it uses a wollok library (like our SDK) which uses advanced features like mixins, and stuff.

**Comment by javierfernandes** [comment]
And idea here..

Manually specify on each file which features you want
```scala
language with mixins, modernSyntax, implicits


class Dog mixed with Mammal and FourLegged and Domestic {
}

mixin Mammal { ... }
```

Or defining a version with a new DSL
 
``scala
language version advanced {
    features: mixins, modernSyntax, implicits
}
```

And then using it

```scala
wollok version advanced

... // code
```

The version could be defined for the whole project

**Comment by fdodino** [comment]
I'd really love this idea, but we are focusing in 2 different implementations, and trying to migrate from one version to another. Closing this issue.
