### ISSUE TITLE
Run wrepl.sh without an input file

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#465]
Could wollok be able to run an interpreter without using an input file?

**Comment by npasserini** [comment]
I do not see why not.

**Comment by fdodino** [comment]
@npasserini , I think this is a Nice to have issue. I didn't use wrepl.sh, should a student do it?

**Comment by tesonep** [comment]
This is already working. 
A student should be using the Wollok IDE, however the tools support to be used from the command line, for example if they use Sublime.
