### ISSUE TITLE
Bundle i18n extra bundles to the distro

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#475]
Currently wollok is i18nized, so if your OS is in spanish for example, wollok validation messages and other UI elements will show in spanish. But, we are not bundling the eclipse fragments for spanish, so the eclipse itself will still be in english.

We need to find a way to either generate different distros for spanish and english or to bundle the spanish fragments.

**Comment by javierfernandes** [comment]
Fixed !!
The distro now is shipping spanish fragments of eclipse.
So not only the wollok part but eclipse itself is in spanish (pretty ugly in my personal opinion, but well)

<img width="830" alt="screen shot 2015-12-11 at 15 46 55" src="https://cloud.githubusercontent.com/assets/4428120/11752663/97583106-a01f-11e5-8008-6a82b7bf8c14.png">
<img width="375" alt="screen shot 2015-12-11 at 15 47 10" src="https://cloud.githubusercontent.com/assets/4428120/11752662/97575a6a-a01f-11e5-9e02-473f68061ec9.png">

**Comment by npasserini** [comment]
Grosso!
