### ISSUE TITLE
Filter unwanted wizards

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#476]
The wollok IDE (product) currently has a lot of options in the wizards because of other plugins.

We need a way to remove all that to avoid confusing the beginners.
For advanced programmers, there's always the chance to install wollok plugins into his own eclipse

**Comment by javierfernandes** [comment]
Done. It now looks like this:

<img width="326" alt="screen shot 2015-12-13 at 14 21 44" src="https://cloud.githubusercontent.com/assets/4428120/11768427/56fad8ce-a1ab-11e5-97ae-347880c5a8d8.png">

**Comment by npasserini** [comment]
Amazing.
