### ISSUE TITLE
Think of a way to avoid instantiating Position class

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#478]
Currently to use wollok game you need to instantiate the Position class.

```xtend
new Position(3, 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```
We want to avoid showing classes in the first part of the OOP learning-path.
So we should think of a way to avoid it.
It could be with a new feature in wollok language itself like extension methods or literals.

Example using a literal

```xtend
(3 : 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```

Although I don't like to couple the language syntax with wollok game.
Another option more object-based without any feature

```xtend
game.at(3, 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```

**Comment by npasserini** [comment]
I think about an intermediate possibility.

On one hand I like to be able to create positions using literals, such as
3@3.
Also I think that for game characters it is nicer to be coupled to a
position than to the whole game or board i.e
this.setPosition(3@3)
is nicer than
this.setPosition(game.at(3,3))

Also I like that positions know their contents and their neighbours,
without requiring to talk about game/board.

So I would propose:

someCharacter.setPosition(3@3) // => this code can be placed anywhere in
the game domain
game/board.add(someCharacter) // => this kind of code has a tighter
coupling with the game an we should be more careful about it.

But I am not sure, maybe this requires more thinking.

**Comment by npasserini** [comment]
Why is this closed? Is this solved? Is discarded?

**Comment by PalumboN** [comment]
I create at(x, y) method in game object because it is enough for what I need.

I like have a literal for this too. But we don't agree wich (you proposed @, but I didn't know if there was quorum). We can open other issue for that!

**Comment by npasserini** [comment]
Ok, thanks. When I opened the issue the history is clear, but gmail had set
me a trap, because I do not see the whole history here.
Maybe, it would be nice that we put always a comment when closing an issue,
even a very simple one just like "solved" or "discarded", so it is easier
to follow.

**Comment by PalumboN** [comment]
> Maybe, it would be nice that we put always a comment when closing an issue,
even a very simple one just like "solved" or "discarded", so it is easier
to follow.

Like :+1:
