### ISSUE TITLE
Autocomplete should propose constructor parameters

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#482]
Example

``` xtend
class Ghost {
    var posicion
    var color

    new(_posicion, _color) {
        color = _color
      ...
}
```

Here it should autocomplete

``` xtend

new Ghost....
```

**Comment by fdodino** [comment]
Moving to "Nice to have" column since 1) we are deprecating constructors in Wollok, 2) is difficult to complete smart when having multiple constructors , 3) there is no clue about which values could be a good choice.

**Comment by fdodino** [comment]
Closing issue, constructors will be deleted soon.
