### ISSUE TITLE
Move "wollok-example" project to its own github repo

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#486]
We want it to be easily imported into a wollok IDE to have something working to start on.
Kind of snippets

**Comment by fdodino** [comment]
Wollok examples moved to http://github.com/wollok/...
Maybe we can add a dynamic page to link this examples so people can download them

**Comment by fdodino** [comment]
Added a html page in welcome page pointing to examples in wollok site. Closing this issue.
