### ISSUE TITLE
Organize and split "wollok-examples" project into small projects

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#487]
Currently is has a lot of files and different examples, like guides and execersices.
They all should have their own repositories. For example:

``` uqbar-project/wollok-excersice-monstersinc```

So eventually we could expose this content directly to the IDE with the "teamwork" line of work (@lgassman)
```

**Comment by fdodino** [comment]
They are now in https://github.com/wollok/...
They were split and published here: http://www.wollok.org/ejemplos/
In #486 I proposed they could be an IDE page (or maybe included in a Welcome page).
But I don't see the difference between this issue and #486, @javierfernandes ... is there anything else we should add?

**Comment by npasserini** [comment]
@fdodino isn't this already done?

**Comment by fdodino** [comment]
I wasn't sure about the second paragraph: 

> So eventually we could expose this content directly to the IDE with the "teamwork" line of work 

Welcome page is already linking sample page in Wollok site, so let's close it.
