### ISSUE TITLE
Somehow show the complete wollok exception to understand what happened in the game

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#490]
I'm coding a new game and I did something wrong.
So the character shows a bubble with the error, but is not enough.
I cannot see the complete error, so I cannot fix it :(

A workaround or the simplest solution would be to also log the stack trace in the console.

Also the bubble never disappears automatically :(

**Comment by PalumboN** [comment]
We can show the message in the bubble and log the stack trace in the console. Put all stack in the bubble can be annoying.

> Also the bubble never disappears automatically :(
This is because the messages are putting in a queue and each is shown for 3 seconds.

**Comment by javierfernandes** [comment]
Showing it in the console seems enough
