### ISSUE TITLE
Character movements strategies: keep character on the screen

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#494]
To have a declarative way to change the way the character moves in the board.
For example keep it on the screen won't let you move far to the west/left once you reached the border. And the same for all other directions

**Comment by PalumboN** [comment]
I think that this is a **camera** strategy, instead of movement strategy. Because I want continue working with the position objects like always and at rendering time calculate the real position on the board depending the camera. Maybe _libgdx_ has something for this feature.

**Comment by fdodino** [comment]
@PalumboN , do you want this issue to be in Backlog or in Nice to have column?

**Comment by PalumboN** [comment]
Mmmmm.. I want it, but Wollok-Game has others features / bug fixes to be implemented before. I prefer solve that before.

**Comment by fdodino** [comment]
Hi @PalumboN !
It seems easy if we touch Position class

```xtend
abstract class Position {
       ...
	def incX(int spaces) { 
		x = x + spaces
		if (x < 0) x = 0
		if (x >= Gameboard.instance.width) x = Gameboard.instance.width - 1
	}

	def incY(int spaces) { 
		y = y + spaces
		if (y < 0) y = 0
		if (y >= Gameboard.instance.height) y = Gameboard.instance.height - 1
	}
```

Tested and it works!

**Comment by fdodino** [comment]
Step by step. #1318... for tomorrow
