### ISSUE TITLE
Allow nested WKObjects

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#495]
For example:

``` scala
object keyboard {
    object a extends Key
    object b extends Key
    ...
    object z extends Key
}
```

Then one can do

``` scala
val a = keyboard.a
```

Or maybe import it

``` scala
import wollok.io.keyboard.a
```

Then

``` scala
   val aKey = a
```

**Comment by javierfernandes** [comment]
This might be delayed by first trying nested packages which will provide a way to organize objects withour violating encapsulation or introducing a new object accessing syntax

**Comment by fdodino** [comment]
Since it is a stale issue, I'm closing it until anyone is interested.
