### ISSUE TITLE
State of WKOs is carried on to subsequent tests in the same test file

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#505]
Tests should be independent from each other, but a side-effect in a method of a WKO in a test of a given file affects subsequent tests in the same file.

![image](https://cloud.githubusercontent.com/assets/10454118/11944785/568f9546-a827-11e5-8a48-feeca2f3d09f.png)

![image](https://cloud.githubusercontent.com/assets/10454118/11944816/a2453964-a827-11e5-8438-61132fcedd03.png)

**Comment by javierfernandes** [comment]
Nice issue report :+1: 

I think this should be priority for v1.3.1

**Comment by javierfernandes** [comment]
Fixed !
This now works
```xtend

object globalin {
	var a = 10
	method a(nuevo) { a = nuevo }
	method a() = a
}

test "Changing a to 20" {
	assert.equals(10, globalin.a()) 
	globalin.a(20) 
	assert.equals(20, globalin.a())
}

test "Changing a to 10" {
    // starts with 10 again !
	assert.equals(10, globalin.a())
	globalin.a(30)
	assert.equals(30, globalin.a())
}

test "Changing a to 10" {
    // starts with 10 again !
	assert.equals(10, globalin.a())
}
```

Lets keep an eye on this, since I fixed with with a single line of code :P I'm not sure it is contemplating all scenarios.
Basically what it does is to clear the global objects registry before any test execution.

@npasserini
