### ISSUE TITLE
Wollok.exe icon in the Win-64 package is the standard from eclipse

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#506]
The executable file used to have a custom icon. Now that icon is gone and the standard eclipse icon is displayed instead.

![image](https://cloud.githubusercontent.com/assets/10454118/11944999/99b7d066-a829-11e5-9dd3-b3511490f247.png)

**Comment by javierfernandes** [comment]
Can you please recheck this once we release 1.5 ?
I changed the icons with the new isologo, but I'm not sure about the end result

**Comment by matifreyre** [comment]
Still the eclipse icon :disappointed:
