### ISSUE TITLE
Double-clicking on a test raises a Java null pointer exception

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#507]
When double-clicking **on a test that resulted in error**, instead of the expected navigation to the corresponding test, a Java exception is raised.

![image](https://cloud.githubusercontent.com/assets/10454118/11945050/3f4b5ac0-a82a-11e5-94af-d8e7155a73dd.png)

**Comment by npasserini** [comment]
I propose a temporal solution. 
This could be improved after solving #597
