### ISSUE TITLE
charAt method return null

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#508]
The String's method _chatAt(Int)_ returns always `null`. This is because the [native implementation](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.lib/src/wollok/lang/WString.xtend#L20) is without code.

We was talking about if we really need a new type Char or not; and if we must delete this method or not. For me, it can return a String with one letter, like a shortcut for `substring(n, n+1)`.

**Comment by npasserini** [comment]
I think that the discussion here is to haver characters as a type or not.
If not, I would remove this method.

**Comment by PalumboN** [comment]
Solved
