### ISSUE TITLE
Null/Nil should be an object

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#521]
That way not only the metaphor will be more consistent, but also it allows us to easily implement messages like the elvis operator without changing the language

**Comment by javierfernandes** [comment]
This will allow us to delete the WollokBasicBinaryOperations and probably the unary class. Meaning special treatment for null on operands.

**Comment by fdodino** [comment]
See comment in #425

**Comment by fdodino** [comment]
Well, I strongly believe that null being an object will carry a lot of development and will not add so many benefits. At least for now, I prefer closing the issue until a something else comes up.
