### ISSUE TITLE
Enumerable/Iterable mixin/protocol

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#523]
We need to put in a single place logic common to iterable things: collections and dictionaries. It should provide the following definitions: 
- map
- filter
- etc

And require a forEach, flatMap or fold method.

Depends on #322

**Comment by fdodino** [comment]
We thought also @npasserini to have native methods instead of Wollok methods regarding performance. I'd like to debate this in 2019 (let's see if we have time to tackle it)

**Comment by fdodino** [comment]
It's not related to IDE but current implementation has native approach for sets and lists, so I'm closing this issue.
