### ISSUE TITLE
Change "new" keyword to "constructor" for constructors declarations

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#527]
Currently, constructors are declarared using the new keyword.

This is confusing, since we are using the same token for very different use cases. And it does not match the name we use for it: constructor. 

Also, since clases are not objects, the intuition of being a method and thus shares the selector mesaage is broken.

JS does it better: it has a constructor keyword. 

My proposal is to rename the **new** token to **constructor**. 

@npasserini this is what we discussed

**Comment by npasserini** [comment]
I like this. @javierfernandes ?

**Comment by flbulgarelli** [comment]
Fixed

**Comment by npasserini** [comment]
I think that in the future we should wait to have more opinions before
changing the language.

**Comment by flbulgarelli** [comment]
@npasserini Sure, but how? A more defined process?

**Comment by Juancete** [comment]
need to update the language reference with this update (?)

**Comment by npasserini** [comment]
Juan, I do not understand, are you asking permission to do it?
In that case, go for it.

Otherwise please explain.

**Comment by Juancete** [comment]
I'm asking permission and approval XD. I can do the modification.

**Comment by npasserini** [comment]
Done.
