### ISSUE TITLE
Writing aVar++ in the REPL makes it crash

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#530]
When typing the last '+' it slows down everything and then produces an error:
![captura de pantalla de 2015-12-26 13 59 29](https://cloud.githubusercontent.com/assets/10291211/12007206/eeb1bebc-abd8-11e5-8b8f-e20fe935371b.png)

**Comment by javierfernandes** [comment]
In mac I'm not currently getting the error window but I can see a stack trace for Unhanlded parameter type WReferenciableImpl in WMethodContainerExtensions.isWritableVarRef() multimethod.
