### ISSUE TITLE
Strange things happens in the editor when you copy and paste the same method in an object

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#531]
when you have a method duplicated in the same object, and you want to rename (manually) one of them the editor goes crazy and shows the text a pair of lines below, it generally normalizes when saving the file.

![captura de pantalla de 2015-12-26 14 23 38](https://cloud.githubusercontent.com/assets/10291211/12007306/d69b5726-abdc-11e5-961a-5e205791ee61.png)

![captura de pantalla de 2015-12-26 14 24 02](https://cloud.githubusercontent.com/assets/10291211/12007308/dd5195c6-abdc-11e5-83fc-203a9ef701b8.png)

**Comment by matifreyre** [comment]
This kind of things also happen sometimes when you split a sentence in two lines, like:
![image](https://cloud.githubusercontent.com/assets/10454118/12820273/1fa4af4c-cb3d-11e5-8dd6-8638d4f2f3a0.png)

After just pressing "enter" to split the line, it gets like:
![image](https://cloud.githubusercontent.com/assets/10454118/12820307/44b54030-cb3d-11e5-9346-04794420b1db.png)

You can see it inserts a blank line before. Now, if I press ctrl + z to undo the change:
![image](https://cloud.githubusercontent.com/assets/10454118/12820352/717d0382-cb3d-11e5-8edb-47f22c51fbad.png)

It completes the original line back, but doesn't remove the second one!

You can scroll up or down until it's not visible and back to this rows and you'll see it corrected, so it seems a visual problem only (but it's really annoying). Even if you move the cursor up and down with the arrows (after messing it up as explained before) it does similar weird things.

**Comment by javierfernandes** [comment]
I think this is related (somehow) with the static diagram.
I never seen this happened with the static diagram view closed

**Comment by matifreyre** [comment]
It still happens to me even after I close the static diagram view. Is there anywhere a downloadable packaged version with the latest updates? I'd like to try some environment that I haven't had any chance to mess up anyhow.

**Comment by fdodino** [comment]
Related to #531
I'm closing also this issue, please reopen it if you experience strange behaviors again.

**Comment by flbulgarelli** [comment]
> Related to #531

@fdodino it is related to itself?

**Comment by fdodino** [comment]
Yes, because as Pancho Ibáñez said: "Everything is related with everything"
:)

#343 

And there was also another issue related with this, I can't find it.
