### ISSUE TITLE
Warn about message sent for which there aren't any method declaration in the whole project

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#534]
I ran into this common mistake that made me waste a lot of time

``` scala
        mixin FlyingShortcuts {
            method fly100Meters() {
                this.fly(100)
            }
        }

program t {
            val b = new BirdWithFlyingShortCuts()
            b.fly100meters()
            assert.equals(100, b.energy())
        }
```

Then got "message not understood", because of a type.
I was calling it as "fly100meters" when the actual name is "fly100Meters" (with a capital M).

That sucks !

While we don't have a type system, we could create some sort of heuristic based on information of all the current project content.
As wollok projects are not much big in size.

The idea is to:
- Create an eclipse builder.
- It will handle a kind of "index" or "db" per opened project
- Everytime something changes it will update its database
- The data is basically all the methods in the project
- Then a validator will check every message send, and if there is not at least one class defining a compatible method, it will report a warning.

**Comment by matifreyre** [comment]
You may want to use this for auto- completion too (cases not currently
covered can propose all existing messages, like Smalltalk). I don't know if
it's possible, just an idea.

**Comment by javierfernandes** [comment]
Yes, that's right.
What we need to provide in that case is a way to clearly identify visually which proposals are being "potential" message, and which ones are "checked messages".

Wollok's current approach for completion is the opposite to Pharo. It just gives you the options for which it is completely sure are valid messages.

__There's only one case where this is not true, while completing proposals for parameters. If you have another method with a parameter declared with the same name, then it proposes the same messages you sent in the other method. There's a github issue somewhere that explains this__

Anyway I think it is important to cleary differentiate this two kinds of proposals.
But for sure smart-autocompleting will reduce typing.

Also maybe we should only lookup in this registry based on some sort of filtering.
For example, only once you have typed at least 2 or characters we will propose only those that match.
Otherwise it suspect that it will propose too much options which will render it useless.

**Comment by fdodino** [comment]
Well, although it is not the desired solution, I added recently in "DNU fixes" PR the ability to detect case-sensitive message problems.

**Comment by fdodino** [comment]
Added TS-based autocomplete, so I think we can close this issue.
