### ISSUE TITLE
Show mixins in static diagram

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#540]

**Comment by javierfernandes** [comment]
The diagram layout sucks, and the code is terrible, since it is really hacked-up and has duplication.
All the diagrams need a really good refactoring, but well, mixins are now shown

<img width="401" alt="screen shot 2016-01-03 at 20 57 48" src="https://cloud.githubusercontent.com/assets/4428120/12105557/a910ff0e-b334-11e5-9658-55570ab8318e.png">

**Comment by npasserini** [comment]
Great
