### ISSUE TITLE
Design an icon for Mixins in label providers

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#541]
Autocomplete, outline, etc.

<img width="265" alt="screen shot 2015-12-28 at 01 43 42" src="https://cloud.githubusercontent.com/assets/4428120/12014119/88299db8-ad04-11e5-8eab-eb42d74809b9.png">

It is currently being shown with the default icon

**Comment by javierfernandes** [comment]
New icon. This is how it looks


![uploads/88ea33dc-6993-4416-94b2-0f2dfdd5e49d/Screen Shot 2015-12-30 at 14.28.26.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F88ea33dc-6993-4416-94b2-0f2dfdd5e49d%2FScreen+Shot+2015-12-30+at+14.28.26.png)

**Comment by PalumboN** [comment]
Like!
