### ISSUE TITLE
System.exit(0) breaks WollokGame

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#543]
Since it ends the whole process killing libgdx background thread.

Wollok game start() method should block the thread. And maybe continue it once libgdx notifies that the window has been closed.

**Comment by Juancete** [comment]
LwjglApplication start a new thread in a variable called mainLoopThread. We need just join the main thread to wait until the libgdx application ends.

**Comment by javierfernandes** [comment]
Yeah ! Cool!
