### ISSUE TITLE
Add isBetween message to numbers

### ISSUE THREAD

**Issue by JuanchiRios** [uqbar-project/wollok#548]
Do you guys agree? It´s a silly one but i think it can help.

**Comment by PalumboN** [comment]
:+1:

**Comment by javierfernandes** [comment]
:+1:

Eventually this will be part of a mixins :P

**Comment by flbulgarelli** [comment]
:+1:

**Comment by JuanchiRios** [comment]
Hey i have some trouble testing this method.
I defined it in Number
	method isBetween(limitA,limitB) = {
			val vmax = limitA.max(limitB)
			val vmin = limitA.min(limitB)
			(this >= vmin && this <= vmax)
		}
if the first part of the condition it's false => no problem but if it's true wollok throw this assertion error: java.lang.AssertionError: wollok.kang.Exception: Error evaluating line classpath:/wollok.wlk:[433]: this <=vmax

and then if i move the conditions like this: (this <= vmax && this >= vmin)
the tests which gave me OK throw the assertion error and the tests with assertion error go green

I try with parenthesis, and instead of && and i thought it could be the way wollok evaluate expressions but a i have no idea how it´s done. Now i am running out of ideas, any ideas?

**Comment by javierfernandes** [comment]
Yes. I have seen something like rhis before.
I think it is related with shortcircuit boolean operations impl.
I'll try to reproduce it

**Comment by JuanchiRios** [comment]
yep it's kind of weird because if i change the 'this' hardcoding a real values in the tests it s goes green. Cam you tell me again that way of printing that you taught me the other day and then i forget. it was for printing variables and forget about concat them

**Comment by javierfernandes** [comment]
It is an xtend feature. Currently wollok doesn't have it.
It is called string interpolation or "rich strings"

```
val string = '''Hello «someone.name()» ! '''
```

**Comment by fdodino** [comment]
Fixed in PR wdate. Now in dev branch. Method named "between".
