### ISSUE TITLE
Must not allow you to define a class with the same name in the same package/file !

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#549]
It currently lets you do this 

``` xtend

class A {
}

class A {
}
```

weird ! I thought we were checking this already

**Comment by javierfernandes** [comment]
Maybe this can be generalized for any WNamed instance. 
There must no be any sibling semantic modelo also WNamed and with the same name

**Comment by npasserini** [comment]
@javierfernandes  Works for me.
