### ISSUE TITLE
Error in "Create instance/local variable" refactors

### ISSUE THREAD

**Issue by matiasfmartino** [uqbar-project/wollok#553]
Sometimes works, but most of the time it throws that error.

It happens both in classes and objects. 

![image](https://cloud.githubusercontent.com/assets/8515210/12052857/f4548d4c-aef1-11e5-8657-281b6e246755.png)

**Comment by javierfernandes** [comment]
So it creates the var successfully but shows that error screen, right ?

**Comment by matiasfmartino** [comment]
Yep, that's right.

**Comment by fdodino** [comment]
I've been testing and this popup error does not longer appear. But... still we have to check whether we are in a method without a body, because trying to create a local variable results in a NPE:
