### ISSUE TITLE
Postfix and plus-equals operators aren't recognised as assignations

### ISSUE THREAD

**Issue by matiasfmartino** [uqbar-project/wollok#554]
Using the plus-plus operator shows the warning

![image](https://cloud.githubusercontent.com/assets/8515210/12053732/94c9fa70-aefa-11e5-9523-1fb0fca9231b.png)

but replacing it with the equivalent expression doesn't

![image](https://cloud.githubusercontent.com/assets/8515210/12053758/e0c68a60-aefa-11e5-8cca-1a0e62e97862.png)

This happens with all the other variants as well (-- ,=/, =*, etc).

**Comment by matiasfmartino** [comment]
![image](https://cloud.githubusercontent.com/assets/8515210/12054020/c2d5fc9a-aefd-11e5-9f62-5377c413e6ff.png)

**Comment by javierfernandes** [comment]
Yes, there's already an issue already for this second problem #529

**Comment by javierfernandes** [comment]
Fixed in dev (1.3.1 or probably will be renamed to 1.4 since we are adding some changes that are not "hotfixes")

**Comment by javierfernandes** [comment]
Also fixed for multiassignoperators in binaryOperations (+=, *=, -=, etc)
