### ISSUE TITLE
Adding enums?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#558]
_I am not really convinced of this issue, but..._

Looking at #552, I am wondering that having enums would:
- remove some bolilerplate code
- clearer reveal intention

Here is my proposal:

```
enum Keys [inherits ... includes ....]{
  NUM_1 {   
   method getKeyCodes() = [8, 145]
  }
  NUM_2 {   
   method getKeyCodes() = [9, 146]
  }
  NUM_3 {   
   method getKeyCodes() = [10, 147]
  }
}
```

That way, we avoid the pattern `object $enumValue inherits $enum`

**Comment by flbulgarelli** [comment]
@PalumboN

**Comment by javierfernandes** [comment]
This can be written 

```xtend
object X inherits Key(6)
object Y inherits Key(7)
object Z inherits Key(8)
```

If we add nested objects we will have something similar to enums

```xtend
object Keys   {
    object X inherits Key(6)
    object Y inherits Key(7)
    object Z inherits Key(8)
}
```

**Comment by PalumboN** [comment]
Javi's solution is nice.

But, in fact, I think it really is:
```xtend
object X inherits Key(6) { }
object Y inherits Key(7) { }
object Z inherits Key(8) { }
```
right?

**Comment by flbulgarelli** [comment]
Can you inherit from a parameterized class? I didn't know that. Is this already in master?

**Comment by javierfernandes** [comment]
Yes, since 1.3

You are right currently forces you to write braces.
But i'm getting tired of it.
I'm thinking on making them optionals.
Specially in 1.4 with the precense of mixins.
Maybe we can detect the weird cases statically where you are not mixing
anything and not calling a super with parameters and create a warning. Sin
it doesn make much sense (?)

**Comment by flbulgarelli** [comment]
Ok, braces can be optional. 

But don't you think you are still repeating logic here?

```
object Keys   {
    object X inherits Key(6)
    object Y inherits Key(7)
    object Z inherits Key(8)
}
```

Just wondering, another option could be the following: 

```
enum Keys   {
    X = Key(6)
    Y = Key(7)
    Z = Key(8)
}
```

Again, I am not particullary convinced it is a great idea, but I can not ignore that we are repeating something otherwise.

**Comment by javierfernandes** [comment]
Yes. It is true. I'm just thinking about two things:
1) Trying to balance adding a new concept/lang element with its benefit.
2) i always felt enums impls in other languages were weird. Eventually ypu
want to start modelling on them and it is not enough. You end up moving
back to regular classes.

Maybe if we give it a turnaround and connect this concept (well known
limited instances) wirth value objects modelling in the language it would
make more sense (?)
And that ended up being the 3)  ;)

**Comment by flbulgarelli** [comment]
Linking with Value Objects? How?

It feels strange to me. Actually when I teach about persistence and object stereotypes in an advanced object design course - DDS for those who know it - it adhere to [Evans classification](http://martinfowler.com/bliki/EvansClassification.html) (described in DDD):
  * Entities: objects with reference semantic, which have an important identity and a varying state. Like `pepita`. 
  * Value Objects: objects with value semantic, which have no import identity and immutable state - they are interchangable and shareable . Common case: a position or point
 * Services: objects with not interesting state nor identity. Common case: an stateless strategy. 
 
But I add a fourth category: symbolic objects. Those are objects that don't have any state, but their identity is important. These are classical Symbols in Smalltalk/Scala/Ruby or Enums in Java. 

In the last three cases, since they have no (mutable) state, whey can or must be shared, so they can be enumerated. 

That is why I think that enums are not always connected to value objects.

But  ok to 1. I don't have a great speech. Perhaps we can push this on hold unless someone else wants to say something

**Comment by npasserini** [comment]
I am not sure about this, and since it is not disruptive, I think we should
wait until other parts of the grammar stabilize to see what is best.

I'll try to point out some details:

Firts, this is kind of weird in our metaphore in which we forbid to
interact with an object other than through messages:

object Keys   {
>     object X inherits Key(6)
>     object Y inherits Key(7)
>     object Z inherits Key(8)
> }
>
>
What would be the way to access X?
I am not sure about allowing Keys.X, I think students could confuse it with
a variable access.

Maybe something like Keys::X could be more "correct"... but still doesn't
look too nice.

Maybe adding enums is a path to a solution, but I agree with jfernandes'
objections:

> Yes. It is true. I'm just thinking about two things:
> 1) Trying to balance adding a new concept/lang element with its benefit.
> 2) i always felt enums impls in other languages were weird. Eventually ypu
> want to start modelling on them and it is not enough. You end up moving
> back to regular classes.


Also, I think that there is another soluton which is to use a package

package keys   {
>     object X inherits Key(6)
>     object Y inherits Key(7)
>     object Z inherits Key(8)
> }
>
>
I am not sure if this is currently working, but I think it would be
compatible with the specification we once defined for packages (and never
implemented completely).

**Comment by npasserini** [comment]
I am not sure about how we came to value objects...

On Thu, Dec 31, 2015 at 12:43 AM, Franco Leonardo Bulgarelli <
notifications@github.com> wrote:

> But I add a fourth category: symbolic objects. Those are objects that
> don't have any state, but their identity is important. These are classical
> Symbols in Smalltalk/Scala/Ruby or Enums in Java.
>
>
but this sounds more like an implementation issue to me. I would like to
care about the visible behavior of an object.
So if you have a = Key(6) and b = Key(7) they should behave differently and
if I write twice c = Key(6) and d = Key(6) they should behave the same, I
shouldn't care if they are the same object or not.

Eventually c == d should be true, which you could consider (a discouraged)
part of the behavior of these objects.

Most of the time, checks for object identity (or equality, makes no
difference to my point) are in fact missed polymorphism opportunities. So I
am not sure about adding more tools for a student which then I will have to
keep the students from using them wrong.

**Comment by flbulgarelli** [comment]
> So I am not sure about adding more tools for a student which then I will have to
keep the students from using them wrong.

Ok, you have a point. At least in an initial/intermediate OO course such difference has not too much sense.

**Comment by javierfernandes** [comment]
Yes. I think we can use packages. And it would be more suitable to this
case.

**Comment by fdodino** [comment]
Stale issues. Closing it.
