### ISSUE TITLE
Add .times to integer

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#566]
That is a simpler case of range iteration:

```groovy
3.times {
   someone.doSomething()
}
```

We could name it `times`, or `timesDo` or `timesRepeat` . I like the first one.

**Comment by matifreyre** [comment]
Shouldn't it receive a closure as its argument?

**Comment by javierfernandes** [comment]
@matifreyre that's actually a closure.
Just that, as I noticed :)  the new closure's syntax could be confused with blocks (sets of statements/expression).

This can be read as:

```scala
3.times ( {  someone.doSomething()   } )
```
Maybe that's more explicit.

**Comment by matifreyre** [comment]
You mean the parenthesis are optional even when you do have
parameters? Indeed it looks like a block. If that's the case, it seems very
confusing to me. I'd rather not have that option, or at least limit it to
no-parameter methods.

**Comment by npasserini** [comment]
The parenthesis are optional only for a message with a unique parameter
which is a closure.

**Comment by npasserini** [comment]
:+1: to this, even when we I have serious doubts about the now syntax
closure.

**Comment by flbulgarelli** [comment]
Hey @matifreyre @npasserini I have started another thread about optional parenthesis #564 Could we discuss them there?

**Comment by matifreyre** [comment]
Sure thing. 
I also agree with the "times" addition for integers.
