### ISSUE TITLE
Add assert.throwsException

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#567]
Add a method for checking that a no arg closure, when evaluated, actually throws an exception <del>of an specific type.</del>

**Comment by flbulgarelli** [comment]
Hmm, I am thinking we have a problem here. Since classes are not objects, we can not simply pass the class to do type checking. Oops.

**Comment by javierfernandes** [comment]
We were trying to avoid metaprogramming because of future type system complexities (and other static checks)

**Comment by flbulgarelli** [comment]
Seems legit.

**Comment by flbulgarelli** [comment]
Fixed
