### ISSUE TITLE
[refactor] Migrate from JUnit "embedding" wollok code tests  (interpreter runtime tests) to pure wollok files

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#576]
Currently we have a lot of runtime tests implemented as junit methods which only have a wollok program / test.
It runs the interpreter expecting no errors.
The good part is that it is JUnit, so really easy to any "junit" developer. Also, it easily integrates with the eclipse UI, etc.

The bad part is, basically that having the wollok code embeded in the java/xtend class makes it more difficult to manipulate by a metaprogram.

If we are going to build a tool to expose wollok tests via web, then we would need them to be in regular wollok files, and isolated from java/xtend code.
Even if we are not talking about modifying them, just showing the content.

I see 2 options here:
- Follow what @tesonep did for executing the wollok examples in **WollokExamplesTests**, but for new files in **wollok.test** project (this new files will come up from migrating the current tests's bodies)
- Use XPect for this: it won't check anything statically, but just run the interpreter expecting no errors. XPect is for checking "anything" and extensible.

**Comment by npasserini** [comment]
Pienso que esto se parece mucho a lo que hicieron con @nscarcella en los sanity tests. ¿Les parece si lo redefinimos simplemente como usar los sanity tests?

**Comment by fdodino** [comment]
Hola @npasserini! Voy a cerrar este issue y generemos uno nuevo especificando el refactor para empezar a usar sanity tests y deprecar los viejos como hablamos ayer.
