### ISSUE TITLE
Split "interpreter" implementation from wollok main project/plugin

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#577]
The interpreter can be moved down to a new plugin **org.uqbar.project.wollok.interpreter** that depends on the main package, and is being seen by all other plugins.
This will start to take out code from the main project which is more coupled with xtext and its building tools.

**Comment by fdodino** [comment]
@npasserini Don't we have a xinterpreter project already? Can we close this issue?

**Comment by npasserini** [comment]
Puede ser. @Javier Fernandes <javier.fernandes@gmail.com> tendrá algo para
decir al respecto, ¿cuál era la idea?

**Comment by javierfernandes** [comment]
hmm.. trying to recall what this was about.
Ok, so, I believe that the idea is like this

* xinterpreter: already exists as pointed out. It is a generic model for interpreters on top of xtext. It models all the interfaces and data structure an interpreter should handle. And as it models execution context, stack, etc.. it is the basis to implement the debugger. Notice that this is (AFAIK) completely unaware of any wollok specifics.
* wollok: the main package currently **implements** an interpreter, by implementing the xinterpreter API. But this project/module also has many other things (like validations, and many other things that I don't recall right now, but it is basically the way xtext structures your code from start. Pretty raw).

My suggestion here was in the line of trying to split that ".wollok" project into several different modules, extracting individual concerns.
In particular this was to extract the wollok xinterpreter implementation into a smaller package.
I supposed that it doesn't have any short-term functional benefit. It was all about trying to split wollok into smaller packages like in other modern fwks (npm packages, ruby gems, etc).

**Comment by npasserini** [comment]
Gracias Javi!

**Comment by javierfernandes** [comment]
👍

**Comment by fdodino** [comment]
Ok, closing it.
