### ISSUE TITLE
Change validation message adding "ClassX cannot be instantiated .. "

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#579]
This is for

```
Must implement inherited abstract methods: M1.doIt()" at "C"
```

Also replace 

```
M1.doIt()
```

 with 

```
doIt() (required by M1)
```

**Comment by fdodino** [comment]
Ok, I added 4 different kind of errors:

- for a class inheriting from a superclass or mixed with some mixins
- for a wko inheriting from a superclass or mixed with some mixins
- for a bad defined class (which does not inherit from any superclass, but it defines an abstract method)
- and also for a bad define wko (which does not inherit from any superclass, but it defines an abstract method)

**Comment by npasserini** [comment]
Hey, wkos should not allow for abstract methods!

2017-06-30 9:11 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
I didn't follow you.
I was talking about two different kind of errors,.and thus Messages
1) when you define an abstract method in a wko
2) when you inherit from an abstract class and you don't implement their abstract methods

I've done this already

**Comment by npasserini** [comment]
I mean, WKOs are different than classes. A class might have abstract
methods, and then is abstract. A WKO can *never *have abstract methods.

So, if you have a class with abstract methods, you could only raise an
error on instantiation, but if you have a WKO, you can mark the abstract
method as an error immediately. I mean, not the object but the method
itself. (I do not know if you already did so, sorry.)

Also, in the same line, I would make the message more specific. I
understand current message is:

"Wrong definition of object badWko. You must implement all methods:
badWko.abstractMethod()" at "badWko"

And instead could be something like (in method position)

"Abstract method not allowed here inside object definition, you must
provide an implementation." at "method abstractMethod()"


2017-06-30 13:43 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
It is ok if you want to change the message, I'll see how to change wko to method.

**Comment by fdodino** [comment]
Ok, @npasserini 

I think I've finally got the point. When wko does not inherit from anything, behavior is

```xtend
				abstractMethods.forEach [ abstractMethod |
					report('''«WollokDslValidator_WKO_WITHOUT_INHERITANCE_MUST_IMPLEMENT_ALL_METHODS»''',
						abstractMethod, WNAMED__NAME)
				]
```

So, source of error is abstractMethod and not wko.

Messages are:

```
WollokDslValidator_WKO_MUST_IMPLEMENT_ABSTRACT_METHODS = You must implement all abstract methods inherited
WollokDslValidator_WKO_WITHOUT_INHERITANCE_MUST_IMPLEMENT_ALL_METHODS = Abstract method not allowed inside object definition, you must provide an implementation
```

**Comment by npasserini** [comment]
:-)

Yet, I think that "You must implement all *inherited *abstract methods" is
better english than "You must implement all abstract methods inherited".

2017-06-30 20:22 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Hahaha, are right you !
![image](https://user-images.githubusercontent.com/4549002/27831278-5b89cee4-60a0-11e7-8527-a32756d59cec.png)
