### ISSUE TITLE
Customize "outline" content for tests

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#581]
It is currently showing all sentences/expressions of the test body.

<img width="276" alt="screen shot 2016-01-10 at 10 36 57" src="https://cloud.githubusercontent.com/assets/4428120/12221739/4c60aa56-b786-11e5-8285-237516b8ce26.png">

The easiest change would be to just truncate that and not render any child.

Another interesting change would be to show asserts as elements there.
For example

``` bash
mytestfile
      |-- test blah blah
      |            |-- assert energy > 0
      |            `-- assert true lalala
      `-- test lololo
```

**Comment by fdodino** [comment]
> The easiest change would be to just truncate that and not render any child.
Agree. I'll cut the tree for fixture and tests.

**Comment by npasserini** [comment]
+1
