### ISSUE TITLE
REPL inserts an m in the command while writing that needs to be erased manually

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#598]
This appears when I just enter a letter k (just an example, happens with any text) into the console
>>> [km

The [ is harmless and doesn't affect the execution (I'm using it in Windows, not sure if that is related).
The m is considered as text from the user input for the evaluation, making it fail, so the user needs to delete it.

**Comment by javierfernandes** [comment]
Fixed in 1.4.1
