### ISSUE TITLE
[scm] Create github releases

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#616]
In github there's the concept of a release, which is related to tags
https://help.github.com/articles/creating-releases/

We are not using them.
Using it means getting inline with other opensource projects..
Also the "releases" tab will appear in the gh page, and we could use some gh-pages scripts etc..

There's a way to make this releases automatically through API
https://developer.github.com/v3/repos/releases/#create-a-release

We should create a script and hook it into travis release process.

**Comment by fdodino** [comment]
We created #1863 , so closing this ticket.
