### ISSUE TITLE
[REPL] Weird behaviour when typing "new" keyword

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#633]
Steps to reproduce it:
1) Write 
const someVar = ne.
Everything is normal.
2) Type "w", it doesn't show in REPL console.
3) Then type a space, then a letter (suppose a C), you get finally 
"const someVar = new C"
If you try to go backwards, you get an error.

**Comment by Juancete** [comment]
This issue was reported on  #631. Mr. Fernandes found a solution for it, pushed a solution and merged to the dev-1.4 branch.

**Comment by javierfernandes** [comment]
Fixed in #631
