### ISSUE TITLE
[REPL] Error when typing Home/End keywords

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#634]
Steps to reproduce it
0) Define a variable / constant named shrek.
const shrek = new Heroe() // but you could use 4, "Pepe", anything that you want
1) Type a word, like "shrek"
2) Press "Home" key.  You loose the cursor, the only way to get out is pressing Enter key, then you get this error:
>>> shrek ERROR: Couldn't resolve reference to Referenciable 'shrek'. (line: 1)

**Comment by Juancete** [comment]
Done!
