### ISSUE TITLE
Copy/Clone Support for Object

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#657]
It would be nice to have a copy() or clone() method in Object.

**Comment by matifreyre** [comment]
There is already a copy() method for collections, so I would go with that one.

**Comment by npasserini** [comment]
Let's discuss this.

**Comment by fdodino** [comment]
Stale issue. Closing it.

**Comment by fdodino** [comment]
And moreover, I didn't need it  at all.
