### ISSUE TITLE
Navigation with arrows up/down changes the text visually

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#659]
Sometimes it repeats the line at the top in the current line, sometimes it plays with the identation. It's very very very annoying. It is also not deterministic, and I can't figure out why sometimes it happens and sometimes it doesn't.

(Windows 10)

**Comment by javierfernandes** [comment]
Since now some time I suspect that this has to do with the static diagram view.
I detected that it doesn't happen if that view is closed (double check closing it first then restarting eclipse, make sure you start without the static diagram view)

**Comment by asanzo** [comment]
Here @matifreyre says: "If that's the case, let's have a quick fix: Let the initial Wollok don't have the Static Diagram open, so by default it appears closed". 

I agree with this, it's important for releasing Wollok with a stable initial configuration.

BTW, the "ghost duplicated line" problem also appears sometimes when starting to write a parameter.

**Comment by fdodino** [comment]
Finally Javi solved this. Closing this issue.
