### ISSUE TITLE
REPL Console - Horizontal Navigation Bar covers last line

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#660]
When the amount of lines in the console is greater than the console height, it starts to scroll down. That's great.

The problem is that the last line gets covered by the bottom scroll bar. You have to wait a bit for it to disappear. It's very annoying.

(Windows 10)

**Comment by fdodino** [comment]
Is this still happening to you @asanzo ?
Couldn't reproduce it or I think I didn't catch the way to reproduce ti.

**Comment by mmatos** [comment]
@asanzo is this still happening to you? I tried it in Windows 7 and couldn't reproduce it.

**Comment by tesonep** [comment]
@asanzo could you check it? I could not reproduce, maybe it is a problem with windows 10 new GUI.

**Comment by asanzo** [comment]
I was finally able to sit in a Windows 10 machine and re-test this.
I  can't reproduce it now . The lowest scrollbar is fixed apparently, so it now does not do what I described before..

Let's close this, and thanks for leaving it open till now :).
