### ISSUE TITLE
Enhancement: Overriding with just super line should raise warning

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#661]
Hi!

It would be great to have a warning raised when something like this appears:

```
override method comer(cant) {
     super(cant)
}
```

Saying "It's a conceptual mistake to redefine a method that's like the superclass' method, Fix: remove method"

**Comment by javierfernandes** [comment]
Nice !

This is the kind of ideas that I was expecting long ago :P
I think you are the first one to come up with a new validation rule to enforce a concept. You are "groso" Alf, know it !

**Comment by asanzo** [comment]
Heheheh Copyright @lspigariol

**Comment by asanzo** [comment]
Let's not forget the case with return as well:

```wollok
override method estasCurada(){
        return super()
    }
```

**Comment by fdodino** [comment]
Hi @asanzo , I would prefer to raise an error instead of a warning.
It is configurable by user, but default can be warn-error.
What do you think?

**Comment by asanzo** [comment]
In Paradigmas we strictly correct it as an error, as wrong use of inheritance. I certainly wouldn't mind it to be an error. Let the tool help the teacher a bit :)

Go for it.

**Comment by fdodino** [comment]
Ok! Thanks!

It was a bit hard to detect whether you are using only super the right way:

```xtend
mixin Energy {
	var energy = 100
	method reduceEnergy(amount) { energy -= amount }
	method energy() = energy
}
		
class Bird mixed with Energy {
	override method reduceEnergy(amount) { 
		super(1)  // that's correct
	}
}

class A {
	method toBeOverriden(a) {}
}

class MethodsCalledOnWellKnowObjects inherits A {
	override method toBeOverriden(a) {
		// XPECT errors --> "This message call produces no value" at "eat"
		super(pepita.eat(10))  // another right use of super, sending an expression
	}

```

vs. 

```
	// XPECT errors --> "It's a conceptual mistake to redefine a method that's like the superclass' method" at "jugar"
	override method jugar(tiempo) {
		super(tiempo)
	}
```

But finally I could check super call with same method parameters
