### ISSUE TITLE
Concatenate collections

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#662]
I didn't find a method with **no effect** which returns a new collection concatenating other two:

For example:

```
[1,2,3].concat([a,b,c])
```

that returns:

```
[1,2,3,a,b,c]
```

`++` operator would do the trick as well, or polymorphic `+` too.

**Comment by fdodino** [comment]
done in branch wdate. Yeah, I know it's a bad name.

**Comment by javierfernandes** [comment]
:P
