### ISSUE TITLE
Error: Cannot modify values

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#664]
```
object o {
   const hola = 5
   method prueba(){
         hola = 6
   }
}
```

That throws an error "cannot modify values" on line `hola=6`.

It should say "canot modify constants".

**Comment by fdodino** [comment]
solved in branch wdate

**Comment by javierfernandes** [comment]
We are talking about a static error right ?
This should be catched by the static checker (besides it must explode in
runtime, in case you bypassed the validator)
