### ISSUE TITLE
Spanish environment?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#674]
Currently the Wollok Eclipse is English based. Is it possible to add spanish translations to UI?

**Comment by javierfernandes** [comment]
It is also in spanish.
I think that it starts based on you host locale.
If you want to force it, there is an eclipse init paramenter called "nl".

./eclipse -nl es

Or something like that.
https://eclipse.org/articles/Article-Speak-The-Local-Language/article.html

Probably can be also added to the eclipse.ini file

**Comment by flbulgarelli** [comment]
Nice, it worked!

**Comment by matifreyre** [comment]
Can we close this one?

**Comment by flbulgarelli** [comment]
Yes
