### ISSUE TITLE
Help Menu: about Wollok menu item is shown as a red box

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#675]
I guess this is just a place holder and the actual Wollok Icon is missing, right?

**Comment by fdodino** [comment]
Yes, you are right.
Yesterday I found the warning in IDE.

**Comment by fdodino** [comment]
Changed image in wollok.product.product but after a few tries, still seeing red box instead of icon.
I'll left this issue and continue with others.

**Comment by fdodino** [comment]
http://andrius.velykis.lt/2012/10/creating-icons-for-eclipse-rcp-launcher/

**Comment by fdodino** [comment]
tab 'Branding" of wollok-product.product had an "About Dialog" configuration, renamed org.uqbar.project.ui... to icons/wollok-logo-about.fw.png, without leading "/"

**Comment by fdodino** [comment]
Finally got it!
http://www.eclipse.org/eclipse/platform-ua/proposals/shared-intro/shared-intro.htm
windowImages property of plugin.xml in org.uqbar.project.wollok.product was tied to "product:" but you must use project relative path.
