### ISSUE TITLE
Weird warnings on new empty proyect

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#676]
When you create a new empty project, you get the following warnings in the Problems view: 

```
Description Resource    Path    Location    Type
Bundle 'de.itemis.xtext.antlr' cannot be resolved   MANIFEST.MF /mi-proyecto/META-INF   line 14 Plug-in Problem
Bundle 'org.eclipse.emf.mwe2.launch' cannot be resolved MANIFEST.MF /mi-proyecto/META-INF   line 15 Plug-in Problem
```

This is kinda disturbing :stuck_out_tongue:

**Comment by matifreyre** [comment]
Currently, I'm only getting the first warning. Still disturbing, though.

**Comment by matifreyre** [comment]
Both warnings today in a new product :dizzy_face:

**Comment by flbulgarelli** [comment]
> Both warnings today in a new product :dizzy_face:

Buu :sob:

**Comment by fdodino** [comment]
I deleted both references in MANIFEST.MF everything works fine although.
Have you tried to do that? 
So I think maybe we just don't need this optional bundles...

**Comment by matifreyre** [comment]
This is still happening in Freire (I'll never get used to spell it with a "i").

**Comment by fdodino** [comment]
Yes @matifreyre , in the demo same warnings appeared.
I didn't remember I closed this issue (maybe I didn't but it  was waffle or github)

**Comment by matifreyre** [comment]
This is still open, the one you closed is a duplicate.

**Comment by fdodino** [comment]
:+1:

**Comment by fdodino** [comment]
It still happens, but since it is not easy to fix, I'll move to `Won't do (IDE related)` column .

**Comment by fdodino** [comment]
Found it!

`AbstractPluginProjectCreator`

```java
	protected List<String> getRequiredBundles() {
		return Lists.newArrayList(
			"com.ibm.icu",
			"org.eclipse.xtext", 
			"org.eclipse.xtext.generator",
			"org.eclipse.xtend",
			"org.eclipse.xtend.typesystem.emf",
			"org.eclipse.xpand", 
			"de.itemis.xtext.antlr;resolution:=optional",
			"org.eclipse.emf.mwe2.launch;resolution:=optional");
	}
```

we should override this method in `WollokProjectCreator` (which in turn trusts `AbstractWollokProjectCreator` autogenerated file). Maybe we should filter last two bundles.
