### ISSUE TITLE
Hide confusing Java/General options

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#678]
When navigating the Wollok Eclipse UI, you will sometimes find references to Java: 
- the Junit window
- the Java new project options
- the general new project options when you create a new project. 

The latter is the worst in my opinion, since for a **novice** user, it is not obvious if you should create you new project as `general` or `wollok`. 

Could we wipe such options?

**Comment by fdodino** [comment]
+1

**Comment by fdodino** [comment]
Verified against Wollok 1.6.7. Closing
