### ISSUE TITLE
Static diagram is broken

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#681]
* When you add a new class, it is not shown.
* When you add a new object, it replaces the previous one
* a black straight line is rendered over the class box, always. 

For example, this is what was produced after the following code: 

```wollok
/**
 * This is an example wollok hello world
 */
object ex {
	
	method sayHi(){
		
		console.println('Hello Wollok!')
	}
	
	method sayBaz() {
		
	}
	
	
}


object goo {
	
}

class Foo {
	
}

class Bar inherits Foo {
	method zaraza() {
		
	}	
}
```

![wollok](https://cloud.githubusercontent.com/assets/677436/15873677/256644e0-2cd6-11e6-912d-65c8a79510fc.png)

If the static diagram is not working, disabling it may be a better solution

**Comment by fdodino** [comment]
For release 1.5 we will hide static diagram for Wollok perspective.
Future work will involve enhancements for this diagram.

**Comment by javierfernandes** [comment]
Just for the record.
The black line are the lines all rendered one on top of the other, because
all boxes are placed in the same space.
The problem is basically the automatic layout algorithm.

If you go and start dragging the boxes and manually layout them, you will
use that it is not so bad :P

**Comment by fdodino** [comment]
Ok, @javierfernandes , remind me where is that automatic layout algorithm and I'll try to fix it in a near future (no promise) :)

**Comment by fdodino** [comment]
I found an interesting paper
http://d-nb.info/96977866X/34

Also
http://kb.yworks.com/article/314/
http://docs.yworks.com/yfiles/doc/developers-guide/incremental_hierarchical_layouter.html

Problem is 

```java
	def addClass(WClass c) {
		println("Adding... " + c.name)
		addClass(new ClassModel(c) => [
			location = new Point(100, 100)
		])
	}
```

And also, I see every time you change editor class diagram is redrawn.

**Comment by fdodino** [comment]
Mmm... I see several refreshing problems with the connectors.

**Comment by javierfernandes** [comment]
Yes. It is basiically hacked.

In theory it should remember locations from previous nodes. That worked
some time ago

**Comment by fdodino** [comment]
![classdiagram_fix](https://cloud.githubusercontent.com/assets/4549002/17001095/f54ed42e-4e9b-11e6-8d53-02ac44d1283c.png)

Added a very simple algorithm. Attached a sample.

Still I have proposals & questions: @flbulgarelli @javierfernandes @npasserini @tesonep @matifreyre 

* Should we add a connector between named objects and Object class? I would like to avoid that line.
* How can we draw an association line?
* Can we draw an association between classes and objects?

**Comment by javierfernandes** [comment]
Coool !!!



We cannot draw association arrows between Class <-> Class without a type
system.

We can draw

   - Class -> WKO
   - WKO -> WKO
   - WKO -> Class (inheritance)

Eventually I was also thinking on having some heuristics like, if all
classes
in the current diagram inherit from  a class (like Object), then don't draw
that one.

Another ones could be to draw this classes in a folded, smaller way, like
just a box
without the methods.

Think that this is not "drawings" but a full MVC there, so you can alwasy
click on it
and that will take you to the object in the code.
Or we can even show a tooltip with the content. Etc.

**Comment by fdodino** [comment]
>Think that this is not "drawings" but a full MVC there, so you can alwasy
>click on it
>and that will take you to the object in the code.
Awesome!! Didn't notice that!

I like that. We can "strategize" the way a Shape appears.
I changed previous image, so objects don't connect with Object but Object subclasses do.

**Comment by fdodino** [comment]
Created a branch https://github.com/uqbar-project/wollok/tree/static-diagram-fix-%23681
