### ISSUE TITLE
Distinguish between errors and failures

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#686]
When running tests, the test runner does not distinguish assertion errors from failures - unexpected exceptions. 

It would be nice that the runner use different colors for them: yellow/red - as SUnit - or blue/red most xUnit Eclipse's runners.

**Comment by fdodino** [comment]
I put an orange/red for failure/error issues.

**Comment by fdodino** [comment]
This is done and released since Dec 2016 1.5.3
