### ISSUE TITLE
Strange formatting rule for variable assignments

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#687]
See the following code: 

``` wollok
class Foo {
    var x
    var y

    constructor(anX, anY) {
        x = anX
                y = anY
    }
}
```

If you format it, you get: 

``` wollok
class Foo {
    var x
    var y

    constructor(anX, anY) {
        x = anX y = anY
    }
}
```

Which is a little confusing - ok, newlines and semicolons are not truly necessary to parse the tree, but having all them in the same line is not really clear.

**Comment by fdodino** [comment]
Passing test on branch formatter-issues
