### ISSUE TITLE
Empty block message

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#688]
Although is nice to ensure that there are no empty tests nor programs, the error message you get is quite  confusing: `required (...)+ loop did not match anything at input '}'`

It should be something like `program must not be empty`.

**Comment by fdodino** [comment]
Changed Wollok grammar to use * instead of + in Xtext definition and added new validators for  program, test and fixture.

**Comment by fdodino** [comment]
![issue688.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e187893687d5f1d7abf301b44fff9e2c4533317346f67e23d2e52db9402d590e5d1afa440e5f44aefc8e79afe72e6c981e5ab38532022d8c6853beb2901eb80bbb258b4a82b0b88b4dc8ef3521f5c6.png)
