### ISSUE TITLE
Message autocomplete does not work on literal lists

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#689]
Autocomplete works here: 

``` wollok
program abc {
    var x = []
    x.**here**
}
```

But not here: 

``` wollok
program abc {
    [].**here**
}
```

**Comment by fdodino** [comment]
It works for first example, but not for second one.
I'll consider severity medium in Nice to have column, @npasserini , so when Backlog column is finished someone knows which of NTHave issues are more important than another ones.
