### ISSUE TITLE
No-args sum, max and min versions 

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#691]
It would be nice to expose `sum`, `max` and `min` messages in numeric collections, similar to their existing counterparts but that don't require a block. For example:  `[20, 30, 4].sum() //answers 54`

**Comment by matifreyre** [comment]
Easy enough... let me try to do this one.

**Comment by matifreyre** [comment]
@flbulgarelli please have a look at branch dev-issue-#691 and tell me if it looks as you expected.

**Comment by matifreyre** [comment]
Methods added in #718.

**Comment by fdodino** [comment]
@matifreyre is this ready? Can we close this issue?

**Comment by fdodino** [comment]
Sorry, didn't see it was already closed!!

**Comment by matifreyre** [comment]
You can re-open and close it again if you want!
