### ISSUE TITLE
Add a way to simply raise an exception message

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#694]
When teaching about exceptions, I want to avoid talking about exception classes and exception objects head-first, at least until the bubbling mechanism has being understood. 

I'd like to have a language feature, or simply a method in `object` that allows you to raise an `Exception` given a message, similar to what `assert.fail` does. For example: 

```wollok
raise("not enough energy!")
```

**Comment by javierfernandes** [comment]
Yes, there is a method in Object class for that.

https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok.lib/src/wollok.wlk

method error(message) {
throw new Exception(message)
}

**Comment by flbulgarelli** [comment]
Nice. Cosing

**Comment by flbulgarelli** [comment]
Hm, wait. 

It is not behaving exactly as expected. I will open a different ticket for it
