### ISSUE TITLE
try-catch formatting issues

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#696]
I formatted a simple program with a try-cath, and this is what I got: 

``` wollok
program abc {
    console.println(4)
    try
        {
            5 + 5
        }
            catch e : Exception
            {
                console.println(e)
            }
        }
```

**Comment by fdodino** [comment]
:+1:

**Comment by fdodino** [comment]
Before anything, we should agree our desired formatting.
I'd like to use

```scala
program abc {
	console.println(4)
	try {
		5 + 5
	} catch e : Exception {
		console.println(e)
	}
}
```

What do you think @flbulgarelli @tesonep @javierfernandes @npasserini ?

**Comment by tesonep** [comment]
For me it is OK.

**Comment by npasserini** [comment]
Why not like this?

> program abc {
>     console.println(4)
>     try {
>         5 + 5*    }  *
>
> *        catch e : Exception {*
>
>         console.println(e)
>     }
> }
>
>

**Comment by matifreyre** [comment]
Not sure about this last option @npasserini ...
I like to open blocks in the same line I'm writing (both proposals do this), increase the indentation one level for everything within, and close it in a new line at the same offset that the opening line started. Pretty much what Fer proposed.

I understand that *catch* is part of the *try* sentence and should be equally indented.

In other words, I see it like this:

```
try {...} catch {...}
```

If you want to span either block's content into multiple lines, write that content with a +1 indentation level and get back to the *try* indentation level when closing the block.

In your option, the *try* block is closed at the end of its content line (5 + 5) while the *catch* block is closed in a new line with a lower indentation level than where it was opened. I don't really understand it.

**Comment by npasserini** [comment]
On Mon, Aug 22, 2016 at 4:11 PM, Matías Freyre <notifications@github.com>
wrote:

> In your option, the *try* block is closed at the end of its content line
> (5 + 5) while the *catch* block is closed in a new line with a lower
> indentation level than where it was opened. I don't really understand it.
>
> Maybe we are not seeing the same , I intended that each closing } goes in
a new line. All multi-line block has a } which is alone in its own line.

**Comment by fdodino** [comment]
I didn´t follow you @npasserini , could you please put your suggestion between markdown code?
:smile:

**Comment by npasserini** [comment]
```scala
program abc {
	console.println(4)
	try {
		5 + 5
	} 
        catch e : Exception {
		console.println(e)
	}
}
```

**Comment by fdodino** [comment]
I still prefer my suggestion, but I don't mind using yours. 
What do everybody else think? Have we an agreement?

**Comment by matifreyre** [comment]
For a sinlge catch, I like more @fdodino's proposal, because it looks like catch is a continuation of the try block.

For multiple catch clauses I can agree with @npasserini. The second catch, using Fer's choice would look like associated with the previous catch block instead of the try block.

Anyway, I don't think that initial students will need several catch blocks at the same level too often, so I still like a little bit more Fer's choice.

**Comment by fdodino** [comment]
I'd like to solve, but can't find where to start.
Any suggestion? Thanks!!

**Comment by javierfernandes** [comment]
En 2.10 (?) hay una API nueva de formatter. Es uno de los improvements
más grandes de xtext.. creo.

Acá estaba leyendo un poco
http://es.slideshare.net/meysholdt/xtexts-new-formatter-api

Entiendo que es algo parecido a lo que hicimos nosotros sobre la API vieja
para hacerla más amigable (tampoco es que hicimos mucho).

El formatter es "jodido".
No siempre hacer lo que uno quiere, y hay que andar medio a prueba y error.
Básicamente, tenés que referirte a la sección de código, en base gramática.
Para eso se usa el Wollok*GrammarAccess o algo así.
Ese tiene métodos generados a partir de la gramática, para acceder a cada
"token".

Entonces le decís algo onda

antesDe(WClass_leftCurlyBraces).espacios(1,1,1)

nótese que el "leftCurlyBrances" lo generó solo en base a la gramática

WClass:
   name=ID  '{'
   ... etc

Ponele.

La forma de definir los espacios es con: mínimo, máximo y preferido.
Así el formatter no es tan "rígido".

Muchas veces cuesta saber como se llama los métodos del GrammarAccess
según el simbolo o token de la gramática. Para eso, conviene ver el javadoc.
Porque xtext al generar el método te pone en el javadoc la linea de la
gramática
que generó eso.

La clase que hay que tocar es

https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting/WollokDslFormatter.xtend

Tenemos dispatch methods según el elemento de la gramática (similar a
laburar con los EObjects)

def dispatch formatting(FormattingConfig it, extension
WMethodDeclarationElements e) {

El segundo parámetro da el dispatch.
Ese ejemplo es para la declaración de un método.
Para un package

def dispatch formatting(FormattingConfig it, extension WPackageElements e) {

Nótese que tienen el keyword "extension" esto permite mandarle mensajes sin
necesidad de escribir "e.mensaje", sino simplemente "mensaje".
Son extension methods.
Así luego podés acceder a los elementos de esa regla fácil:

Onda

setLinewrap(1, 2, 2).after(*leftCurlyBracketKeyword_2*)

Eso es equivalante a

setLinewrap(1, 2, 2).after(*e.getLeftCurlyBracketKeyword_2()*)

Por último, hay un tests de formateo en junit

https://github.com/uqbar-project/wollok/blob/496fe4748ca96d3849c741788b6b58eb0de3b726/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/formatter/WollokFormatterTestCase.xtend

(está mal el package, no es de XPEct)

Para testear cosas como


@Test
def void testSimpleProgramWithVariablesAndMessageSend() throws Exception {
assertFormatting('''program p { const a = 10 const b = 20 self.println(a +
b) }''',
'''
program p {
const a = 10
const b = 20
self.println(a + b)
}''')
}

Porque es medio delicado, cuando cambiás algo podés arreglar cierto caso de
formateo, pero romper otro.

Bueno, creo que eso es todo.

Saludin

**Comment by fdodino** [comment]
¡Gracias Javi!

**Comment by fdodino** [comment]
Igual no puedo romper mucho más que el try/catch, porque está acá lo que hay que tocar
	def dispatch formatting(FormattingConfig it, extension WTryElements i) {
		setLinewrap(1, 1, 2).before(group)
		setLinewrap(1, 1, 1).after(tryKeyword_0)
		setLinewrap(1, 1, 1).after(catchBlocksAssignment_2)
		
		setIndentationIncrement.around(expressionAssignment_1)
	}

Eso sí, el ejemplo de Franco me da distinto, porque depende de cómo escribiste la línea.

**Comment by fdodino** [comment]
Ouch!!
Ahora me doy cuenta.
Tengo un tema con los { }, porque no los genera el Grammar:

```scala
	public class WTryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.uqbar.project.wollok.WollokDsl.WTry");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpressionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpressionWBlockOrExpressionParserRuleCall_1_0 = (RuleCall)cExpressionAssignment_1.eContents().get(0);
		private final Assignment cCatchBlocksAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCatchBlocksWCatchParserRuleCall_2_0 = (RuleCall)cCatchBlocksAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cThenAlwaysKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAlwaysExpressionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAlwaysExpressionWBlockOrExpressionParserRuleCall_3_1_0 = (RuleCall)cAlwaysExpressionAssignment_3_1.eContents().get(0);
		
		//WTry:
		//	'try'
		//	expression=WBlockOrExpression
		//	catchBlocks+=WCatch* (=> 'then always' alwaysExpression=WBlockOrExpression)?;
		@Override public ParserRule getRule() { return rule; }

		//'try' expression=WBlockOrExpression catchBlocks+=WCatch* (=> 'then always' alwaysExpression=WBlockOrExpression)?
		public Group getGroup() { return cGroup; }

		//'try'
		public Keyword getTryKeyword_0() { return cTryKeyword_0; }

		//expression=WBlockOrExpression
		public Assignment getExpressionAssignment_1() { return cExpressionAssignment_1; }

		//WBlockOrExpression
		public RuleCall getExpressionWBlockOrExpressionParserRuleCall_1_0() { return cExpressionWBlockOrExpressionParserRuleCall_1_0; }

		//catchBlocks+=WCatch*
		public Assignment getCatchBlocksAssignment_2() { return cCatchBlocksAssignment_2; }

		//WCatch
		public RuleCall getCatchBlocksWCatchParserRuleCall_2_0() { return cCatchBlocksWCatchParserRuleCall_2_0; }

		//(=> 'then always' alwaysExpression=WBlockOrExpression)?
		public Group getGroup_3() { return cGroup_3; }

		//=> 'then always'
		public Keyword getThenAlwaysKeyword_3_0() { return cThenAlwaysKeyword_3_0; }

		//alwaysExpression=WBlockOrExpression
		public Assignment getAlwaysExpressionAssignment_3_1() { return cAlwaysExpressionAssignment_3_1; }

		//WBlockOrExpression
		public RuleCall getAlwaysExpressionWBlockOrExpressionParserRuleCall_3_1_0() { return cAlwaysExpressionWBlockOrExpressionParserRuleCall_3_1_0; }
	}
```

¿Dónde se genera la gramática?

**Comment by fdodino** [comment]
WollokDsl.ecore?

Lástima, mañana empiezo la calesita de dar clases. Pero mientras tanto dejo la pregunta:
¿debería cambiar la gramática? ¿qué pasa si querés usar una sola línea para el try/catch/then always?

**Comment by javierfernandes** [comment]
Fer, eso es porque las llaves no son parte de la regla del
Try/Catch/Always, sino de las expresiones que contienen.
El try dice "acá va una expresión.
Y entonces eso puede ser una de las tantas expresiones (sin llaves), o la
"expression con llaves" (no recuerdo el nombre ahora, pero la podés buscar
en *WollokDsl.xtext*)

El .xtext es la papa de todo.
El ecore se genera sólo, igual que ese grammaraccess y todas esas clases.
Todo en base al .xtext

Saludin

**Comment by javierfernandes** [comment]
Ah.. es esta regla

WBlockExpression returns WExpression:
{WBlockExpression}
'{'
(expressions+=WExpressionOrVarDeclaration ';'?)*
'}';

El nombre "Block" no viene de bloque tipo "closure" sino de un conjunto de
expresiones.
En fin.

Ahora, lo jodido, que nunca hice es, cómo definis el formateo de un
WBlockExpression, de forma distinta, en caso en que esté dentro del WTry o
WCatch.
Hay que jugar un poco para eso. No tengo ningún ejemplo. Nunca lo hice.



2016-08-23 18:08 GMT-03:00 Javier Fernandes <javier.fernandes@gmail.com>:

**Comment by fdodino** [comment]
Ok, gracias!!
Si puedo en estos días chusmeo algo, si no lo voy a ir viendo la semana que viene.

**Comment by fdodino** [comment]
Bueno, después de un largo tiempo con la nueva versión del Formatter de Xtext ya tengo andando estos ejemplos:

```javascript
		program abc {
			console.println(4)
			try {
				5 + 5
			} catch e : UserException {
				console.println(e)
			} catch e2 : Exception {
				console.println("Bad error")
				console.println("Do nothing")
			} then always {
				console.println("finally")
			}
		}

		program abc {
			console.println(4)
			try
				5 + 5
			catch e : Exception
				console.println(e)
		}
```

Es decir, maneja try / catch con WBlockExpression y expresiones simples.

**Comment by npasserini** [comment]
Arrrmoso.

2017-10-24 21:40 GMT-03:00 Fernando Dodino <notifications@github.com>:
