### ISSUE TITLE
Easy way to navigate to wollok.wlk?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#700]
Since method navigation does work only on a few cases - well known objects, mostly - it is not easy to navigate to, for example, collection methods. 

If I select `Open Resouce`, and type `wollok`, this file is not listed. And It is not listed as a project library neither. 

Is there an easy way of navigating to `wollok.wlk` as a normal student?

**Comment by matifreyre** [comment]
The only way I found was by adding import wollok.* so that you can
ctrl+click on it.

It's easy enough, but completely counterintuitive. There should be a more
intuitive one.

**Comment by tesonep** [comment]
Now from an object or a class you can get to the definition by F3.

**Comment by flbulgarelli** [comment]
Nice!

But the problem here is different: I'd like to be able to navigate to the wollok file without having to click or select an element of the program that is defined there. 
 
I would like to be able to directly go to library files - for example with the resource view, or from a library element like in Java's package view

**Comment by javierfernandes** [comment]
I'm not sure but maybe the "search element" window include the libraries content (CTRL+SHIFT+F3 or CMD +SHIFT+F3 in mac).

**Comment by fdodino** [comment]
Yes, it does.
It is documented in [Happy shortcuts of Wollok IDE](https://docs.google.com/document/d/1A6JB4EretksCyMDvOj4NzfiEzX8yfboDTZnER7x_xJI/edit?usp=sharing)
So I'm closing this issue.
