### ISSUE TITLE
Formatting forEach + if is weird

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#702]
The described construct is formatted in a quite strange way: 

``` wollok
object foo {
    method bar() {
        [ 3, 4, 50, 100 ].forEach({ it => if (it > 4) {
            console.println(4)
        } else {
            console.println(it)
        } })
    }
}
```

I expect something like this:

``` wollok
object foo {
    method bar() {
        [ 3, 4, 50, 100 ].forEach({ it => 
                    if (it > 4) {
            console.println(4)
            } else {
            console.println(it)
            } })
    }
}
```

Or like this: 

``` wollok
object foo {
    method bar() {
        [ 3, 4, 50, 100 ].forEach({ it => 
                    if (it > 4) {
            console.println(4)
            } else {
            console.println(it)
            } 
              })
    }
}
```

In any case, I expect that the formatting honors the indent and gives the `if` within the block an extra nesting level.

**Comment by matifreyre** [comment]
Well... I'd expect none of the above options but something more like:

```
object foo {
    method bar() {
        [ 3, 4, 50, 100 ].forEach({ it => if (it > 4) {
                console.println(4)
            } else {
                console.println(it)
            }
        })
    }
}
```
Close a curly brace at the same indentation level it was opened and add one level to everything in-between. 
I'm considering anything wrote after a "{" in the same line as already having an extra level, as if it were like this:

```
object foo {
    method bar() {
        [ 3, 4, 50, 100 ].forEach({ 
            it => if (it > 4) {
                console.println(4)
            } else {
                console.println(it)
            }
        })
    }
}
```

**Comment by flbulgarelli** [comment]
I don't like your proposals, but it honors indents. So it is better than current :wink:

**Comment by fdodino** [comment]
:+1:  to Mati's proposal.

**Comment by fdodino** [comment]
Related to #696 try/catch formatting issue

**Comment by fdodino** [comment]
Well , folks, I'm working in closure + if expressions, and I arrived to this solution:

```javascript
		object foo {
			method bar() {
				[ 3, 4, 50, 100 ].forEach({
					it =>
						if (it > 4) {
							console.println(4)
						} else {
							console.println(it)
						}
				})
			}
		}
```

This formatting has a passing test. I think you can't have in same line 

```java
it => if (it > 4) {
```

because then you loose indentation of "then" expression respect to "if" sentence.
I mean, it is technically feasible, but it leads to another problems when you have an isolated if expression outside a closure.

You can take a look  in branch "formatter-issues"
@npasserini @tesonep

**Comment by fdodino** [comment]
Enhanced formatting

```javascript
		object foo {
		
			method bar() {
				[ 3, 4, 50, 100 ].forEach({ it =>
					if (it > 4) {
						console.println(4)
					} else {
						console.println(it)
					}
				})
			}
		
		}

		object foo {
		
			method attack(target) {
				var attackers = self.standingMembers()
				if (attackers.isEmpty()) throw new CannotAttackException("No attackers available")
				attackers.forEach({ aMember => aMember.attack(target) })
			}
		
		}

		class Cantante {
		
			const albumes = new Set()
		
			method mejorarAlbumes() {
				albumes.forEach({ album =>
					album.agregarCancion(new Cancion())
					album.sumarCosto(100)
				})
			}
		
		}

```

That is: 
1) having a Closure with just one expression forms an inline expression (just one line)
2) having a Closure with one expression, but inside a complex expression has the format above shown
3) having a Closure with several lines, forms an indented expression

**Comment by fdodino** [comment]
Same as if expressions
