### ISSUE TITLE
Typo on missing override error

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#704]
If you try to write a method that overrides a superclass method, but you don't mark it as override, you get an error and a quick fix :+1: 

Buuut, there is little typo there: `Method must be marked as override**s**, since it overrides a superclass
   method`

It should be just `override`, because, err, well, that is the keyword you need to put :stuck_out_tongue:

**Comment by flbulgarelli** [comment]
In spanish the message is fine :smile:

**Comment by Juancete** [comment]
Done!
