### ISSUE TITLE
Equals or == ?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#705]
Exploring the autocomplete suggestions, I see that it offers you both `equal` and `==`. Since I know the implementation, I know that they are synonyms 

But it is quite confusing for the newcomer if you see these two options, plus the`===`. It is not obvious which one you should use. What is more, you could redefine equals instead of `==`, getting strange problems, so they are not truly synonyms. 

Which is the recommended way of comparing objects by equality? Could we just have one way and discard the other, reducing code divergence and potential errors?

**Comment by matifreyre** [comment]
I like to have both options, but I see the point in having only one of them. 
What about ```&&``` / ```and``` and ```||``` / ```or```? Would you rather have only one option there too?

**Comment by iluetich** [comment]
I think it's rarely considered "good" to have methods / logic that behaves identically. In the example that @matifreyre provides, Ruby gives both options: `&&` and `and`.

However, this operators are not _equal_. See [&& versus and operator](http://stackoverflow.com/questions/1426826/difference-between-and-and-in-ruby) and [|| versus or operator](http://stackoverflow.com/questions/2083112/difference-between-or-and-in-ruby). For additional documentation, [here](http://phrogz.net/programmingruby/language.html#table_18.4).

Is there any particular need for having `equals` method **and** `==` operator?

**Comment by fdodino** [comment]
@javierfernandes had an explanation: == is an operand, equals is a message. 
I don't mind having both ways, but I'd like to have a better javadoc to avoid confusions.

**Comment by flbulgarelli** [comment]
> What about && / and and || / or? Would you rather have only one option there too?

My opinion there is the same: we should only have one way . But it is not a so big problem since you are not going probably to override `&&` or `||` methods

**Comment by flbulgarelli** [comment]
> @javierfernandes had an explanation: == is an operand, equals is a message. 

This is not actually true. Both are messages, whose methods are defined in object. And you can actually override them. Actually many operands are messages, for example `+`, and this is good! Actually there should not be special operands, everything should be a message unless there is a really good motivation to not do so.

**Comment by flbulgarelli** [comment]
> I don't mind having both ways, but I'd like to have a better javadoc to avoid confusions.

I don't think having a better _wollokdoc_ ( :stuck_out_tongue: ) is the solution to the problem - if your design is not  clear, documentation is not the solution. Look at the following scenario: I want to define a `Point` class and I want to implement equality. Can you guess which of the following implementations are correct and which not? 

```
class Punto {
	const x
	const y
	constructor(unX, unY) {
		x = unX
		y = unY
	}
	method x() = x
	method y() = y
	override method equals(otro) = otro.x() == x && otro.y() == y
}
```

```
class Punto {
	const x
	const y

	constructor(unX, unY) {
		x = unX
		y = unY
	}
	
	method x() = x
	method y() = y

	override method equals(otro) = otro.x().equals(x) && otro.y().equals(y)

}
```


```
class Punto {
	const x
	const y
	constructor(unX, unY) {
		x = unX
		y = unY
	}
	method x() = x
	method y() = y
	override method ==(otro) = otro.x() == x && otro.y() == y
}
```

```
class Punto {
	const x
	const y

	constructor(unX, unY) {
		x = unX
		y = unY
	}
	
	method x() = x
	method y() = y

	override method ==(otro) = otro.x().equals(x) && otro.y().equals(y)

}
```


_please ignore the fact that I am not checking they are instances of the same class_

Actually only the latter works properly. And this is not obvious; 

* `equals` implementation actually delegates in `==`. So you can implement `==` and expect everything works. But not the opposite
* that means that the "always working" method is "equals",either because you implemented it or because you implemented `==`. So you should always send `equals` and not `==`. 

Some years ago I had the same design problem in a productive system and the same kind of bugs. I don't remember now if we just marked the "synonym" method as `final` in Java, or we just dropped it. I think the second option is better.

**Comment by flbulgarelli** [comment]
@matifreyre regarding your question about ` and` vs `&&`, I see an extra problem: `&&`  is an operator, and operators are messages. So that fits nicely a wollok rule that is similar to smalltalk's, ruby's, haskell's and so on: _operators are infix, keywords are prefix, but in any case they are normal computations_. 

But then we have `and`: it is a keyword message, but it doesn't look like all the other messages - using the dot syntax -: `x.and(y)`. I found that inconsistent. That is not a big issue, but it can still made better.

**Comment by fdodino** [comment]
After several releases, now you can see in Object class from lang.wlk

```scala
	/**
	 * o1.equals(o2) is a synonym for o1 == o2
	 */
	method equals(other) = self == other
```

So, closing it.
