### ISSUE TITLE
Missing core methods in string

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#707]
There are two important methods string class is lacking: 

* `isEmpty`
* `contains`/`includes`

**Comment by fdodino** [comment]
Agree! @flbulgarelli , today I was thinking the same. It bothers me there is an indexOf method.
I handle this.

**Comment by fdodino** [comment]
It was also lacking <, >, <=, >=

Coding it in wdate branch.

**Comment by fdodino** [comment]
Also: equalsIgnoreCase(), split() and charAt(index) was offered but  not implemented!

**Comment by flbulgarelli** [comment]
@fdodino awesome that you have all those issues implemented. I think it is time to merge them in master instead of adding them to another unrelated branch. Could you pull request them now, before it continues growing and diverging from master?

**Comment by fdodino** [comment]
Sorry, it is impossible for me to follow all issues, pull request and mails.
