### ISSUE TITLE
Add missing non-core, but rather helpful string methods

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#708]
There are some useful methods that are missing in string class: 

* `reverse`
* `replace`
* `capitalize`

I have used them many times on programming exercises. 

PS: We need to add them here because chars are not part of the language.

**Comment by JuanchiRios** [comment]
i prefer toUpperCase() and toLowerCase() instead of capitalize() and uncapitalize()

**Comment by flbulgarelli** [comment]
@JuanchiRios they are different things. 

`toUpperCasse` and `toLoweCase` are already there. `capitalize`and `uncapitalize` should just change the first letter :wink:

**Comment by fdodino** [comment]
@flbulgarelli 
Should it work like this?

alfa romeo => Alfa Romeo
AUDI => Audi
bmw => Bmw
ONETWO THREE FOUR => Onetwo Three Four

**Comment by flbulgarelli** [comment]
@fdodino  Yup!

**Comment by fdodino** [comment]
Ok, hands on!

**Comment by fdodino** [comment]
After talking with @flbulgarelli , we decided not to implement uncapitalize
