### ISSUE TITLE
Create Scoping tests with XPect

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#71]
https://github.com/meysholdt/Xpect/blob/master/org.eclipse.xtext.example.domainmodel.xpect.tests/src/org/eclipse/xtext/example/domainmodel/xpect/tests/scoping/test1.dmodel.xt

**Comment by fdodino** [comment]
After all these years, I believe we should decouple our dependency with Xpect. Closing issue.

**Comment by PalumboN** [comment]
Ojo Fer, más allá del XPect acá se propone testear el scope que tiene un elemento del lenguaje (igual puede que no queramos eso, solo aviso! :P)

**Comment by fdodino** [comment]
Je, sí, pero tenemos test de wollok-language para eso ya...
