### ISSUE TITLE
Source and refactor menus disappear

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#713]
If you click on the project view, you can see both source and refactor menus in menu bar - which most of their options disabled, which is confusing.  

Buuuut, it you then click on the code editor, those menus are gone! 

Not a heavy issue - no functionality is lost - but it is very annoying.

**Comment by fdodino** [comment]
I realized Source menu is related to Java. We should disable it. @npasserini

**Comment by fdodino** [comment]
Verified against Wollok 1.6.7. Closing
