### ISSUE TITLE
Moving files across folders doesn't update references

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#714]
If you create a subfolder an move a file to it, imports are not updated. 

Anyway, I couldn't manage to import files in subfolders. Which is its syntax?  I tried by using `subfolder.file.object`, using paths as strings, and even declaring packages inside the file in the subfolder, with no luck.

I am not particularly anxious for having multi-directory projects, but since Eclipse offered the option to do that, I tried it :grimacing:

**Comment by Nefreo** [comment]
This would be userful for separation of `src` and `test` files.

**Comment by fdodino** [comment]
Agree

**Comment by fdodino** [comment]
Well, after a few years now we have a QuickFix automatic import which is particularly for me a _good enough_ solution. Since we are focusing in different tools, it's time to close this issue
