### ISSUE TITLE
Error after quick fix: create variable

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#715]
After using a quick fix `create instance variable`, I get the following error: 

``` wollok
object pepita {

    method volar() {
        energia -= 10
    }
}
```

![wollokquickfix](https://cloud.githubusercontent.com/assets/677436/15907843/2b1b582a-2d95-11e6-8c61-e7f920cce6f6.png)

The  refactor works, however.

**Comment by Juancete** [comment]
is this a bug of Xtext 2.9.x?

[check this out](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472467)

**Comment by Juancete** [comment]
@javierfernandes  @npasserini  Could you see the link in my previous post?

**Comment by fdodino** [comment]
I think it discourages the student to use refactor menus, so I put Medium severity.

**Comment by fdodino** [comment]
Is still happening this? I made some tests and I think it's fixed.
