### ISSUE TITLE
Debugger is not launching

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#717]
I think I have read that @fdodino could launch the debugger by manually configuring it, so it is actually _possible_ to run it, right? If so, how?

However, are there any plans to activate it by default? It is will be a nightmare if debugger doesn't start automatically.

**Comment by fdodino** [comment]
@flbulgarelli you have to high timeout value. @javierfernandes will be working on it this days.

**Comment by javierfernandes** [comment]
This should be now fixed in Wollok 1.5

Besides the timeout there was an issue in the communication between the remote process
See #837
