### ISSUE TITLE
Cuaderno de apuntes?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#720]
The Spanish version of the Wollok Eclipse has in Help a menu options that is named "Cuaderno de apuntes". 

![cuadernodeapuntes](https://cloud.githubusercontent.com/assets/677436/15914649/0b7771f6-2db9-11e6-9366-177a54296b6b.png)

As a student, I'd expect something really different there. I think such tool is meaningless to wollok. Could we just remove it?

**Comment by fdodino** [comment]
Verifyied agains Wollok 1.6.7 - Closing it
