### ISSUE TITLE
Wollok allows to override a concrete method with an abstract method

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#722]
Wollok is accepting the following program, but it shoudn't:

```
class Foo {
	method foo() { console.println('foo') }
}

class Baz inherits Foo {
	override method foo()
}
```

Also, in runtime, if you do `new Baz().foo()`, it evaluates the superclass version.

**Comment by javierfernandes** [comment]
Done !
Check PR and close please

**Comment by flbulgarelli** [comment]
Done :smile:
