### ISSUE TITLE
Add union, difference and intersection methods to collections

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#726]
They are useful in many examples and exercises

**Comment by matifreyre** [comment]
The resulting collection being of the same class as the receiving one, right?

**Comment by matifreyre** [comment]
I was thinking... should these really be for collections in general or just for sets? I don't see how they could be applied to lists. I think they are set operations exclusively.
I mean, what would you expect as the result for something like ```[1, 2, 1].difference(#{1})```, for example? Should it be ```[1, 2]```, ```[2, 1]``` or ```[2]```?

**Comment by flbulgarelli** [comment]
> The resulting collection being of the same class as the receiving one, right?

@matifreyre I think that would be nice

**Comment by flbulgarelli** [comment]
> I mean, what would you expect as the result for something like [1, 2, 1].difference(#{1}), for example? Should it be [1, 2], [2, 1] or [2]? 

@matifreyre not sure. I think that adding to set is good enough, but could you check how it behaves in smalltalk and haskell?

**Comment by matifreyre** [comment]
They have different approaches:

- The most similar function for lists is [```\\```](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-List.html). Textual from Haskell doc: "In the result of xs \\ ys, the first occurrence of each element of ys in turn (if any) has been removed from xs". So, if the first list has at least 2 more occurrences of a given element than the second, the resulting list will also have this element repeated.

- Pharo Smalltalk (4.0) ```#Collection>>difference:``` creates an intermediate Set to build the collection (```self asSet```) and removes those elements existing on the parameter collection, and then returns a collection of the same species as the receiver. As it is using a Set, it's removing all duplicates from the receiver.

I like the Smalltalk approach more. What do you think?

**Comment by fdodino** [comment]
:+1: the St approach

**Comment by npasserini** [comment]
I do not agree.

I think it is weird to do:
{ 1. 1. 1. 1 } difference: { 2 } "#(1)"

If you want to remove duplicates just do asSet().
If lists implement difference, they should behave as lists, it should
return a list and it should not remove duplicates.

I see several options that could be more consistent:
1) Consider difference as a set operation and do not implement it for lists.
2) The haskell way:

method difference(another) {
  const result = self.copy()
  another.forEach { elem => result.remove(elem) }  will remove the first
occurrence of elem
  return result
}

So
[ 1, 1, 1, 1].difference([2]) ==> [ 1, 1, 1, 1]
[ 1, 1, 1, 1].difference(#{2}) ==> [ 1, 1, 1, 1]

and
[1, 2, 1].difference(#{1}) ==> [2,1]

2') Demand that the argument is also a list, but I think it might not be
necessary.

**Comment by matifreyre** [comment]
Well... my initial answer is that I do see all 3 of these methods as Set
operations only. Even the 3 names come from math's set vocabulary. E.g. you
don't "unite" lists, you concatenate them, or you merge them somehow if you
want, but union is a Set operation.
I think you can operate other collections this way if you assume they are
going to be treated as sets, otherwise get yourself a more appropiate name.
Yes, we can extrapolate, many other languages do that, but we are forced to
make assumptions on how they should behave, like someone did for Haskell
and someone else did, differently, for Smalltalk.

**Comment by npasserini** [comment]
On Wed, Jun 15, 2016 at 2:31 PM, Matías Freyre <notifications@github.com>
wrote:

> Well... my initial answer is that I do see all 3 of these methods as Set
> operations only. Even the 3 names come from math's set vocabulary. E.g. you
> don't "unite" lists, you concatenate them, or you merge them somehow if you
> want, but union is a Set operation.
>

Ok for me.


> I think you can operate other collections this way if you assume they are
> going to be treated as sets,
>
> I think that if you want lists to be treated as sets, then you should us
asSet(), I can't think of a scenario in which my previous example
([1,1,1,1].difference([2]) ==> [1]) is desirable.

**Comment by matifreyre** [comment]
@flbulgarelli... do you agree to implement these for Set only? I think your original idea was to do it for all collections.
@fdodino, any thoughts about this?

**Comment by flbulgarelli** [comment]
> @flbulgarelli... do you agree to implement these for Set only? I think your original idea was to do it for all collections

Yes, but ok, let's do it for set's only by now.
