### ISSUE TITLE
add "wrpel" command to WDK

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#73]
For headless execution of the RPL.

There are already 2 commands: winterpreter, wchecker.

We need to add a "wrpel"

**Comment by tesonep** [comment]
What is your idea about this? 
How is a headless repl?? 
If you can run the interpreter you only need to use -r parameter

**Comment by javierfernandes** [comment]
Ah, cool, then just to create a "wrepl" script that will do "winterpreter -r"  :P
