### ISSUE TITLE
Range doesn't have any, all, fold methods of Collection

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#730]
It would be very useful to use them, like in prime() definition of Wollok Integers.
Otherwise I have to code

```java
		method prime() {
			if (self == 1) return false
			var isPrime = true
			(2..self - 1).forEach({ i =>
				// Horrible definition, but return doesn't exit from loop
				// and I need fold, any methods in Range
				if(self % i == 0) isPrime = false 
			})
			return isPrime
		}
```

**Comment by flbulgarelli** [comment]
I was wondering this is a similar issue yo what happens on strings. 

Se could implement it using nixins to avoid logic repetition .

I reported an issue about adding an enunerable protocol some months ago.

However, un both cases a asList method could solve most of the usescases, right?

**Comment by fdodino** [comment]
Implemented a toList() method in Range, I sent a mail a few hours ago...

**Comment by flbulgarelli** [comment]
Hi @fdodino 

I was noticing that we don't have a good convention for conversion methods. Some of them are `toXYZ` (like `toString`) and others are  `asXYZ` like `asSet`.

We should define a convention and stick to it.

**Comment by npasserini** [comment]
Strings are a bit more complicated, because the will force us to introduce
characters as a data type.

I think that Strings have inherently different operations than collections,
I don't see why we would do a map or filter... it seems weird and it
complicates a very common object that I would prefer to keep simple.

+1 to the mixin idea.

**Comment by fdodino** [comment]
I'm closing this issue.
Please @flbulgarelli add a new issue to complete the task by defining a mixin between collections and ranges.
