### ISSUE TITLE
Inconsistent conversion methods names

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#735]
I was noticing that we don't have a good convention for conversion methods. Some of them are `toXYZ` (like `toString`) and others are  `asXYZ` like `asSet`.

We should define a convention and stick to it for new methods, and rename existing ones. 

_there are more `to` methods than `as` methods. So I think moving to `to` is easier_

**Comment by matifreyre** [comment]
While I don't dislike the Smalltalk-like ```as``` convention, I think I
like the ```to``` convention more, it sounds more natural to me.

I can change collections. I'm working on them for other issues in branch
dev-collections-api.

**Comment by fdodino** [comment]
Agree. But before changing anything I would close this discussion with all participants.

**Comment by matifreyre** [comment]
@npasserini @tesonep @javierfernandes any thoughts on this?

**Comment by tesonep** [comment]
To me any of the two it's ok. As Franco said, it will be better to use to*

**Comment by npasserini** [comment]
I do not have a preference between toX and asY, but I am not sure if all
those messages have the same meaning.

For example, when I have unaCol.asSet() this means a type conversion it is
a transformation between two domain objects.
On the other hand whatever.toString() is not the same. It is not a
transformation between domain objects, toString has not a domain meaning.
We could argue if toString *could *not have a domain meaning or even
*should* not have a domain meaning, but I am pretty sure that it is a bad
idea to force both to be the same.

For example an URL object could have a toString that produces "URL(
www.google.com)" but its asString should be "www.google.com". The names
could change, the point is that for debugging purposes it is nice to have a
toString method that gives more information and also a conversion method
that can convert an url object to a string.

Pharo has indeed three methods:
printString:  (~ lo que en Java es toString)
"Answer a String whose characters are a description of the receiver.
If you want to print without a character limit, use fullPrintString."

asString
"Convert the receiver into a String"

displayString
"While printString is about to give a detailled information about an
object, displayString is a message that should return a short string-based
representation to be used by list and related UI frameworks. By default,
simply return printString."
"asString should not be implemented in Object, and kept for conversion
between strings, symbols, text and characters."


Otro ejemplo de Pharo
$a asString
'a'

$a printString
'$a'

($a es un Character)


Yendo un paso más allá y siguiendo la semántica propuesta, es lógico que
cualquier objeto de dominio tenga un printString/toString, porque sirve
para debuggear, mientras que sería incorrecto implementar asString en
cualquier objeto que no tenga dentro de su comportamiento de negocio la
lógica de "convertirse a un string". Mismo una colección no se "convierte"
en string (salvo ponele una colección de caracteres) en cambio hay otra
operación más compleja, como join().

**Comment by flbulgarelli** [comment]
When I wrote this issue there were more inconsistencies between `as` and `to` methods. 

Now looking at  https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.lib/src/wollok.wlk it looks like we have just `to[Smart]String` and to `as<Collection>`. It is not that bad. Perhaps we could leave everything as-is now:  as for collections and to for strings. 

However, although I understand there are slightly different semantics for those methods, I still disagree it is a good idea to have that two close conventions, because: 

* it is easy to not pick the right name when righting a method
* it is easy to not to remember the method

It harms the language usability. For example, in [ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html), there are two methods `to_json` and `as_json`, and they have quite different semantics and it is quite clear when you should use one of them. However, after years of working with rails developers, I see still a lot of silly bugs because of using the wrong method. Actually most of those developers stopped doing the mistake after learning a mnemonic rule that I originally coined for myself.

**Comment by fdodino** [comment]
Stale issue. Closing it until we have a new roadmap for this.
