### ISSUE TITLE
Validation: Boolean expressions compared against booleans

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#736]
Add a new validation to the language to check the expressions like:
```
casa.esComplicado() == true
```

It can be present in different contexts like conditions in the if or the return:

```
if(casa.esComplicado() == true){
   ....
}
```

```
method xxx(){
     return casa.esComplicado() == false
}
```

In all cases it would have to generate an error. Take in consideration this can be configured as the other "semantics validations".

**Comment by javierfernandes** [comment]
Implemented.
Check PR and close please.

I made a generic error message.
Than can be enhanced later with particular messages for "true" and "false" (false to use the not operand". And also include a generated message based on the ast text to provide with the solution.
Also a quick fix.
But well, it is enough for today for me :P
