### ISSUE TITLE
Refactor test to simplify program evaluation in a test

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#737]
I was thinking, maybe we can provide a method similar to "interpretPropagatingErrors" to avoid the bolierplate of the "program" and just write the assertion for this cases, right ?
Something like

```java
def void integersBetweenTrue() {
    '''assert.that(3.between(1,5)'''.test
}
```

Test would do

```java
def test(String testCode) {
    ''''program a {
           <<testCode>>
    '''.interpretPropagatingErrors
}
```

Just a toy (un chiche :) )

**Comment by javierfernandes** [comment]
:thumbs_up:

**Comment by npasserini** [comment]
+1

**Comment by fdodino** [comment]
I'm creating a new branch. test method is easy, but refactor is not :)
