### ISSUE TITLE
Model an Interval object for real (double, float) numbers

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#738]
It should have start, end, and step.
It should offer this methods:
- contains(e)
- random()

It is not enumerable since they are infinite numbers.
You can not implement a forEach method.

**Comment by npasserini** [comment]
Why step?
I see an interval as a continous set of (real) numbers.

**Comment by tesonep** [comment]
It should be in the Math namespace, once the package is fixed.

**Comment by fdodino** [comment]
Ok, no step since it doesn't make sense if not enumerable.
Didn't understand what "Math namespace" is.

**Comment by tesonep** [comment]
I was just saying to put it in the wollok.math package, or something like that, nothing really important.
