### ISSUE TITLE
Corregir la versión de Xtext en el Readme

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#74]
Ahora dice: 
Download eclipse's XText distribution v2.7.3 (Full Eclipse)

**Comment by javierfernandes** [comment]
y qué tiene ?
Yo estaba laburando con esa ?
De hecho me tuve que pelear un poco porque la actual de xtext es 2.8, pero nosotros teníamos todo en 2.7.

Y en el branch mavenizado también usamos 2.7.3

**Comment by tesonep** [comment]
Al final no actualizamos nada, así que esto quedo viejo.

**Comment by npasserini** [comment]
Sí, matalo. Yo puse eso porque pensé que habíamos migrado a 2.8 pero al
final no.
