### ISSUE TITLE
Validation: Using local variables only for assignment and then return

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#746]
For example this should be avoided:

```
method costos(persona, cant_hambiente, cant_pisos) {
	 var costo = empleados.sum({per=>persona.presupuesto(cant_hambiente,cant_pisos)})
	 return costo
}
method presupuestoMaximo(){
	var presupuesto_maximo = 0.20  * ahorros
	return  presupuesto_maximo
}
```

For this to be good it should have a metric to establish if the use is to improve readability. Maybe we can test if the right part of the assignation is more than sending only a message (It can be one or two, I don't know).

**Comment by javierfernandes** [comment]
Done in v1.5
