### ISSUE TITLE
Input to the server should be a json

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#756]
Including 
- a program to be run
- type of program (wlk/wpgm/wtest)

Maybe there are more parameters.
If there were only these two we could have just different endpoints.
Does it make sense to run just a wlk? => maybe we could just validate it.

Should we consider the possibility of sending more than one "file" to the server? 
(Maybe later)

**Comment by javierfernandes** [comment]
I think this can also be closed @npasserini

**Comment by flbulgarelli** [comment]
It has [been merged](https://github.com/uqbar-project/wollok/pull/824) and it is working at http://server.wollok.org:8080.
