### ISSUE TITLE
Anonymous objects are not printable

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#765]
It would be nice to make objects defined in repl implement `toString`. Otherwise you see this error:

```
>>> [mobject {  var x = 3   }
[31mwollok.lang.MessageNotUnderstoodException: anonymousObject does not understand message toString()
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
        ....
```

**Comment by matifreyre** [comment]
We can close this one, right?

**Comment by PalumboN** [comment]
https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/ObjectTest.xtend#L37

Yes!
