### ISSUE TITLE
Validation: Non boolean operands on boolean expressions or if

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#774]
This are typically typing errors.
There are some grammar elements which require a boolean expression like OR and AND are binary operators which eventually need that both of their operands (left and right side) be a boolean or boolean producing expressions.

Without a type system and type inference we cannot statically check this, but we can check some basic cases like the followings:
(this applies to the condition part of the if, but also to and, or and not operations)

```xtend
/* XPECT_SETUP org.uqbar.project.wollok.tests.xpect.WollokXPectTest END_SETUP */

object pepita {
}

object p {
	method run() {
		// XPECT errors --> "Non boolean expression" at "null"
		if (null)
			throw new Exception("asd")
		
		// XPECT errors --> "Non boolean expression" at "2"
		if (2)
			throw new Exception("asd")
		
		// XPECT errors --> "Non boolean expression" at "2+2"
		if (2+2)
			throw new Exception("asd")
		
		// XPECT errors --> "Non boolean expression" at "2"	
		a = 2 && p != null
		
		// XPECT errors --> "Non boolean expression" at "2"	
		a = 2 || p != null
		
		// XPECT errors --> "Non boolean expression" at "p"	
		a = pepita || p != null
		
		// XPECT errors --> "Non boolean expression" at "new List()"	
		a = new List() || p != null
		
		
		// more cases with method call require a type system with inference
	}
}
```

**Comment by javierfernandes** [comment]
Another one that is already validated in runtime by 61aefa8

```scala
var expresionNula
if (expresionNula)
```

**Comment by npasserini** [comment]
There are some issues that we might allow as warnings. For example I
sometimes modify my code from

if (some condition) { blah }

temporarily to

if (true || some condition) { blah }
just for debugging purposes.. what do you think?

**Comment by javierfernandes** [comment]
Yes could be a warning.

**Comment by matifreyre** [comment]
Will it be configurable?
I'd like those as errors for students by default, but also that we can
change them for warnings for these cases.

**Comment by npasserini** [comment]
Every validation should be configurable but in a global base, I do not know
if that is what you mean.

**Comment by matifreyre** [comment]
Yes, that's it

**Comment by javierfernandes** [comment]
Yes. They are global or per project.

What we dont have yet is an export import of theconf to a file or something

**Comment by javierfernandes** [comment]
I've splitted this issue into two, this one and #803 

This one is for non-boolean values both in if condition and in boolean expressions.

I know that the and/or can be overloaded (overriden) by customs classes and without a type system they can change the semantic of this operations and therefore render this validator useless or non-appropriated, but I think that those should be the less cases.

I'm thinking on introducing a code annotation to bypass checks in such a cases. Like many other tools have

```xtend
// > ignore (RedundantBooleanValue)
method myMethod() {
     return true || self.whatever()
}
```
This comment-level metadata could be as part of method comment, or a class-level.
If possible could also be the comment just on top of the offending line.

I'll write a different issue for this.
