### ISSUE TITLE
ACE (web editor) plugin for wollok code is outdated

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#781]
All latest changes to the language grammar and syntax didn't update the wollok plugin for ACE

So the web editor is now outdated.
This will affect mumuki and the "showcase"

Sample for the "const" keyword
<img width="678" alt="screen shot 2016-06-29 at 15 11 24" src="https://cloud.githubusercontent.com/assets/4428120/16463388/fba72470-3e0b-11e6-96d9-dd6be4852023.png">

Changes that I remember:
- val - > const
- new -> constructor
- closures
- this -> self

New features:
- mixin
- mixed with

<img width="363" alt="screen shot 2016-06-29 at 15 15 38" src="https://cloud.githubusercontent.com/assets/4428120/16463479/664dfca4-3e0c-11e6-8d4c-a0174fcc9f2b.png">

**Comment by flbulgarelli** [comment]
@dggluz this is an issue you could take

**Comment by dggluz** [comment]
Yeah, I can take it. 

Is there any place where I can find the updated language's reference?

**Comment by PalumboN** [comment]
> Is there any place where I can find the updated language's 

In the site: http://www.wollok.org/en/lang-ref/

**Comment by dggluz** [comment]
Thanks! @PalumboN

**Comment by fdodino** [comment]
Hi @dggluz, any news? I'm not a PM, I'm just asking because I'm cleaning Wollok's house :)

**Comment by flbulgarelli** [comment]
In the end we are not going to implement this

**Comment by fdodino** [comment]
Closing it.
