### ISSUE TITLE
Prefer exceptions over special values on standard library

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#784]
Checking [this PR](https://github.com/uqbar-project/wollok/pull/782/files), I found that the following methods return special and weird values in scenarios that should fail:

* `String.indexOf` returns -1
* `String.lastIndexOf` returns -1

**Comment by matifreyre** [comment]
The wrapped native String returns those values. We can just catch them in WString and throw an exception instead, right? Any voices against that?
