### ISSUE TITLE
"documentation" keywords?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#791]
While documenting code, we usually write thinks like the following: 
- the method is private: it is not intended to be used by outsiders 
- the method is not intended to be overriden
- .... something else?

Perhaps we should reify such annotations and convert them into keywords. I mean they should not alter the language semantics, but help in detecting problems and produce warnings

**Comment by flbulgarelli** [comment]
Actually the most important part of this issues is the semantics of `private`-like keywords instead of telling which keywords we should have.

**Comment by flbulgarelli** [comment]
See https://github.com/uqbar-project/wollok/pull/772

**Comment by fdodino** [comment]
Stale issue. Closing it.
