### ISSUE TITLE
Make eclipse junit plugin correctly show comparisson errors when tests fail

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#822]
We have a lot of tests in junit like this:

``` xtend
    @Test
    def void whileInClosure() {
        '''
        program p {
            var i = 0
            { i++ }.while { i < 10 } 
            assert.equals(10, i) 
        }'''.interpretPropagatingErrors
    }
```

When the program fails because of a wollok "assertion" it shows this:

<img width="367" alt="screen shot 2016-07-14 at 09 59 20" src="https://cloud.githubusercontent.com/assets/4428120/16840225/e7b1d0a6-49a9-11e6-9c89-dfd6a1d20bc9.png">

For eclipse this is like any other exception.
If we somehow catch that exceptions and convert into the same exception class junit Assert.assertEquals() throw we would benefit from the comparisson view (specially for strings)

Like this
<img width="844" alt="screen shot 2016-07-14 at 10 03 10" src="https://cloud.githubusercontent.com/assets/4428120/16840298/38d91d90-49aa-11e6-90f1-175813e9a463.png">

**Comment by flbulgarelli** [comment]
@javierfernandes  I remember you just need to throw this exception http://junit.sourceforge.net/javadoc/org/junit/ComparisonFailure.html

**Comment by javierfernandes** [comment]
Yes, we need to catch some specific wollok exceptions (which is wrapped in
a java exception like
   AssertionException) and convert them.
