### ISSUE TITLE
Model Class class and be able to refer them by names

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#825]
This could open a whole new world of metaprogramming and reflection API.
But I don't want to think about that right now.
Specially because the language is still changing.

So the only small steps needed here are:
- grammar element for reference to types
- model the object they are resolved to (Class / Type, whatever). The only needed thing here is maybe the name, or just identity, or "isInstance". We only need this right now to compare an object agains a given type

assert.throwsExceptionWithType(MyExceptionClass, { ... some code ... })

**Comment by npasserini** [comment]
Je, I knew that the moment we allow for class objects, we will have
instanceof. Please not.

If we allow classes as values... let's make them just for the purpose they
are born: test expectation.
What to they need for that matter, nothing... all can be native.

**Comment by fdodino** [comment]
Closing until there's a consensus about it.
