### ISSUE TITLE
Stack trace test failing on Windows due to EOL representation

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#828]
There's a test for the stack trace that's failing in dev because of the EOL at ExceptionPropagationInNativeTestCase.nativeMethodCallsWollokClosureThrowingASimpleException

wollok.lang.Exception: Expected [wollok.lang.Exception: SoundGarden
        at  [natives.wpgm]
        at natives.Repeater.ntimes(n,closure) [natives.wpgm]
        at  [natives.wpgm]
] but found [wollok.lang.Exception: SoundGarden
        at  [natives.wpgm]
        at natives.Repeater.ntimes(n,closure) [natives.wpgm]
        at  [natives.wpgm]
]

I'm working under Windows, and when I debug the WString.equals I see this:

![image](https://cloud.githubusercontent.com/assets/10454118/16895167/d4aee8e6-4b42-11e6-9023-16a53a384e32.png)

**Comment by matifreyre** [comment]
Related to #828

**Comment by matifreyre** [comment]
@fdodino 's proposal was:

> ```xtend
> class StringPrinter {
>     var buffer = ""
>     method println(obj) {
>         buffer += obj.toString() + "\n"
>     }
>     method getBuffer() = buffer
> }   
> ```
> 
> I'd like to use lineSeparator as a constant, in Wollok, to simplify testing situation like before.

**Comment by matifreyre** [comment]
I can confirm that changing that ```\n``` for ```\r\n``` makes that test succeed under Windows (and Maven build complete without errors). Maybe just a native call to get the system's EOL representation will do.

**Comment by matifreyre** [comment]
I'm thinking in adding a console.newline() method. What do you think @fdodino?

**Comment by fdodino** [comment]
Perfect @matifreyre .
newline() would be a native method implemented in Java as System.getProperty("line.separator")?
And then we should replace all hardcoded  "\n" in Wollok methods to console.newline()
Also Java methods "\n" should be replaced with System.getProperty("line.separator")

**Comment by matifreyre** [comment]
I like the System.lineSeparator() method slightly more, but in the end it should be the same.

**Comment by fdodino** [comment]
:+1:  System.lineSeparator

**Comment by javierfernandes** [comment]
I wonder if all \n in a wollok string should be automatically converted
into a lineSeparator (?)

**Comment by matifreyre** [comment]
I'm trying not to apply any automatic rule here...

@javierfernandes can you tell me if this "\n" has to be changed? It's in class AbstractWollokTypeSystemTestCase:

```xtend
	def static String escapeNodeTextToCompare(String nodeText) {
		if (nodeText.startsWith("\n"))
			nodeText.substring(1).escapeNodeTextToCompare
		else if (nodeText.startsWith("\t"))
			nodeText.substring(1).escapeNodeTextToCompare
		else
			nodeText
	}
```

**Comment by javierfernandes** [comment]
I think so.
It tries to remove newlines and tabs to compare just code "content"
