### ISSUE TITLE
Add Windows environment to Travis build

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#829]
Several tests were failing in Windows platforms, so it would be nice to test every build on Travis against a Windows environment.

**Comment by javierfernandes** [comment]
Not sure if it is possible :(

https://docs.travis-ci.com/user/multi-os/

There they just mention OSX and linux.

**Comment by fdodino** [comment]
Yes, you are right:
http://stackoverflow.com/questions/19818336/travis-ci-test-package-for-linux-osx-windows

There are technical issues explained here:
https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Awindows+
