### ISSUE TITLE
Enhacements for Static Diagram

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#844]
I suggest a couple of enhancements for Static Diagram.
- Fix #619 Could NOT find diagram node for parent class
- Configuration: Autorefresh on/off with a refresh button. So we can avoid refreshing every key you type. If autorefresh is on, it would work like now. If autorwefresh is off, every new  class, mixing, WKO is added based on a layout and user should arrange position as desired.
  - Avoid recreating class diagram. Thus, we can keep position of existing nodes when typing (#397)
  - #245 Be able to delete a class code from the diagram (requires not recreating view, only adding a class)
  - Also, be able to delete variables and methods.
  - Save into a .wcd? static diagram, so I can be opened later.
- Show icon for overriding methods #257
- Verify #471 is done (Add a zoom pane to static diagram). It has been coded, but i can't see in dev branch.
- Enhance connection routers to a clever way: allow left-right, left-bottom, left-top, right-bottom, right-top connections depending on nodes position
- i18n internationalization for messages and dialog windows
- Configuration for showing: instance variables (default false) and methods (default true). This should be adapt size (height) of nodes, lets say 30-70-100 for class name, instance variable names and methods.
- Configuration: filter accessors (default true)
- Configuration: use all height possible and all width possible to show members (variables and methods) of a node

I must learn a way of generating a Static Diagram Configuration, and store it in a project (that's what I called wcd). As Pablo told me, we could store a .wcd for every .wlk in a project. We could store serialized objects. Every time we need to refresh, new classes would be added, except for those already been deleted.

Changes I don't subscribe:
- #264, adding packages to Static Diagram is not so necessary for initial OO courses

I'll start working soon.

**Comment by lspigariol** [comment]
user class show inherits arrows to Object class. but WKO dont do the same.

really, i dont like show Object class in diagram (only user defined classes and object)

**Comment by fdodino** [comment]
I agree, but we should have associations relantionship in static diagram, otherwise there would be a lot of unrelated classes.

**Comment by fdodino** [comment]
@lspigariol  Ya arreglé que no se visualice Object en el diagrama, ni la flecha de herencia de las clases generales que heredan de Object.
Está en un branch en proceso.

**Comment by lspigariol** [comment]
Genial!
