### ISSUE TITLE
About Wollok is showing version 1.4.3

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#849]
When you select Help > About Wollok
You get version 1.4.3
It should be 1.5.0 (or  the last one)

**Comment by javierfernandes** [comment]
I couldn't reproduce that (maybe it was regenerated on the last release).
What I found is that the image was missing and that the copyright was 2014 :S

Fixing that now look like this

<img width="680" alt="screen shot 2016-08-04 at 18 39 36" src="https://cloud.githubusercontent.com/assets/4428120/17419273/06f4c840-5a73-11e6-99f6-539826147663.png">

**Comment by javierfernandes** [comment]
Just that the 1.6.0 will be 1.5.1
