### ISSUE TITLE
Fake Issue for Page in Wiki Wollok 1.5.0 Epicuro New Features

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#850]
![image](https://cloud.githubusercontent.com/assets/4549002/17155290/cff20804-535a-11e6-85da-2dfad3f9a7e3.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17155608/2dff4762-535c-11e6-92e7-733bf93d880d.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17162413/36a110a0-538c-11e6-9939-0cd22683bd34.png)

![image](https://cloud.githubusercontent.com/assets/4549002/17162432/80088f5c-538c-11e6-95a9-f2f7b830b0c0.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17170349/fe20ee22-53c1-11e6-87e1-2517003a5490.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17170474/95fa1048-53c2-11e6-82dc-625b31c2b8eb.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17170623/5d5d3cbe-53c3-11e6-8086-c47df70caf3d.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17172042/b5bd609a-53c9-11e6-8c8b-e37c519652f8.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17172301/c8e34dbe-53ca-11e6-8211-994bb0042f8c.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/17172426/71f868b2-53cb-11e6-8c05-30167eeecc32.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24624776/43ccf3e0-1883-11e7-958d-b2b7e01ffc85.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24624879/93b26bce-1883-11e7-9d95-7a1283b313d4.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24624961/d31a3224-1883-11e7-9be7-3e742b4e5ae8.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24625034/1fa7e960-1884-11e7-93f7-44703d895ff2.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24625277/e39387bc-1884-11e7-8645-19f96354381e.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24625307/f9431f32-1884-11e7-9c81-bec5cfbd8926.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24625352/2494e198-1885-11e7-8e74-d45a503feb12.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24625778/76ccf10c-1886-11e7-8cfe-24ea228a1789.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24626124/a49457ba-1886-11e7-932b-21c7ee7a4fa9.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24626202/e232d222-1886-11e7-902b-f60732001e48.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24626250/0a6e4ece-1887-11e7-8b7d-45e410b89ee0.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24660291/87b35a20-1925-11e7-853f-724901841440.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24667208/086f096c-1939-11e7-9163-86a79e2b4096.png)

**Comment by fdodino** [comment]
![image](https://cloud.githubusercontent.com/assets/4549002/24683448/74e38d20-1975-11e7-9d1e-a386a37cf89e.png)

**Comment by Juancete** [comment]
![plugin-wizard](https://user-images.githubusercontent.com/1617224/27833967-5f890d1a-60ab-11e7-8230-167ab1bad584.png)
![wollok-product product](https://user-images.githubusercontent.com/1617224/27833968-5fad9edc-60ab-11e7-9fce-ca13eb7aec3e.png)
![targetplatform target](https://user-images.githubusercontent.com/1617224/27833969-5fd3adfc-60ab-11e7-8e21-497a51453bc8.png)

**Comment by Juancete** [comment]
![wollok-product product](https://user-images.githubusercontent.com/1617224/27834333-f0133490-60ac-11e7-8d04-005ec8c7337c.png)
![plugin-wizard](https://user-images.githubusercontent.com/1617224/27834334-f0425f68-60ac-11e7-8a00-87617c1d9d18.png)
![targetplatform target](https://user-images.githubusercontent.com/1617224/27834335-f060e1f4-60ac-11e7-87bc-c0978c5626e8.png)

**Comment by Juancete** [comment]
![connect-512](https://user-images.githubusercontent.com/1617224/27834783-ab414f62-60ae-11e7-9a7a-586df04b298c.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/33188821-cda49cc0-d07b-11e7-9dd0-20271967ba74.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/33188939-e8bd08ac-d07c-11e7-9c3c-058bf8ceaeb1.png)

**Comment by fdodino** [comment]
![wollokdocgenerator](https://user-images.githubusercontent.com/4549002/33192450-732d69f4-d0a1-11e7-9f4e-e0ef43e904e0.png)

**Comment by fdodino** [comment]
![wollokdocgenerator 1](https://user-images.githubusercontent.com/4549002/33193069-cf2adbbc-d0a4-11e7-87a4-96c1f77ef6d1.png)

**Comment by fdodino** [comment]
![wolloktypesystem_initialization](https://user-images.githubusercontent.com/4549002/37427295-bb629c00-27a7-11e8-96e3-da4ff483aec6.png)

**Comment by fdodino** [comment]
![wolloktypesystem_initialization 1](https://user-images.githubusercontent.com/4549002/37430061-dea9ddce-27af-11e8-9716-1136f0f39ab6.png)

**Comment by fdodino** [comment]
![wolloktypesystem_analysis](https://user-images.githubusercontent.com/4549002/37430243-524a2ea0-27b0-11e8-84a1-8bcd37d4bc07.png)

**Comment by fdodino** [comment]
![wolloktypesystem_typeinfo](https://user-images.githubusercontent.com/4549002/37432427-0dcd6ede-27b7-11e8-84ea-bf4405bb67fc.png)

**Comment by fdodino** [comment]
![wolloksupertypesandsubtypes](https://user-images.githubusercontent.com/4549002/37484521-8833f836-2867-11e8-891e-bc9e5bdccbe5.png)

**Comment by fdodino** [comment]
![wolloktypesystem_ast](https://user-images.githubusercontent.com/4549002/37545985-a5113918-2949-11e8-82c5-f258e61854b4.png)

**Comment by fdodino** [comment]
![wolloktypesystem_inferencestrategies](https://user-images.githubusercontent.com/4549002/37547722-2972c606-2952-11e8-95e4-04e7256d6d25.png)

**Comment by fdodino** [comment]
![wolloktypesystem_inferencestrategies 1](https://user-images.githubusercontent.com/4549002/37547999-bc7bc74e-2953-11e8-93b0-30055683025c.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/44292887-d4c2e200-a25d-11e8-97a7-82f9e5b18b19.png)

**Comment by npasserini** [comment]
![error wollok al hacer push](https://user-images.githubusercontent.com/4633913/46709738-68d87680-cc1b-11e8-8132-41c71d25285f.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/54160568-ac374b00-442e-11e9-9541-552a5e7edbc9.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/59193276-8ddf0980-8b5b-11e9-83e5-fe76f3a039b2.png)

**Comment by fdodino** [comment]
![wollokDevDiscouragedAccess](https://user-images.githubusercontent.com/4549002/59193775-33df4380-8b5d-11e9-9d3e-c40b3e373073.png)

**Comment by fdodino** [comment]
![wollokDevDiscouragedAccess](https://user-images.githubusercontent.com/4549002/59196158-4b6dfa80-8b64-11e9-8dd4-146ab2d0a135.png)

**Comment by fdodino** [comment]
![Tests](https://user-images.githubusercontent.com/4549002/64067821-39e93b80-cc05-11e9-8ceb-a19a7831f73a.gif)

**Comment by fdodino** [comment]
![Wollok_Testing_Launch](https://user-images.githubusercontent.com/4549002/64067884-d90e3300-cc05-11e9-82ec-f3e6da8e9df7.png)

![image](https://user-images.githubusercontent.com/4549002/64069800-5cd91700-cc28-11e9-8719-c6f03460af94.png)

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/64069963-619fca00-cc2c-11e9-921f-41f58819ea5d.png)

**Comment by fdodino** [comment]
![WollokPluginConfiguration](https://user-images.githubusercontent.com/4549002/69489837-6f48a280-0e5d-11ea-8914-037a78baf322.png)

**Comment by fdodino** [comment]
![Wollok Development Architecture](https://user-images.githubusercontent.com/4549002/69925567-a3404b00-148f-11ea-964b-518fefb0b4f8.png)

**Comment by fdodino** [comment]
![wollokTest2Times](https://user-images.githubusercontent.com/4549002/70363346-c63f7600-1866-11ea-8504-dcc0f4bccca6.gif)

**Comment by fdodino** [comment]
![runningWollokEnv](https://user-images.githubusercontent.com/4549002/70363476-4c5bbc80-1867-11ea-8744-178a266cd5fe.gif)

**Comment by fdodino** [comment]
![showFailuresOnly](https://user-images.githubusercontent.com/4549002/70369039-fa7c5c00-1891-11ea-84cc-b73c83c76731.jpg)

**Comment by fdodino** [comment]
![Wollok Development Architecture](https://user-images.githubusercontent.com/4549002/70379283-972e1080-1909-11ea-85b7-fceae26d37cf.png)

**Comment by fdodino** [comment]
![Maven, Tycho   P2 Architecture for Wollok](https://user-images.githubusercontent.com/4549002/70382168-e0945500-1935-11ea-89fd-0d4eff5466ef.png)
