### ISSUE TITLE
Possible duplicate "Run REPL without a file" button

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#851]
In Student IDE, you see 2 buttons for this feature

![image](https://cloud.githubusercontent.com/assets/4549002/17161299/b0a05352-5382-11e6-8e98-0d3243de627a.png)

**Comment by tesonep** [comment]
I think it is happen when run from the IDE. Running the product I could not reproduce it.

**Comment by fdodino** [comment]
Yes, that's right.
Running the product doesn't happen.
I think we can close this issue.

**Comment by tesonep** [comment]
We solved (?)
