### ISSUE TITLE
Fix "QuickFix create method" for self 

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#854]
If you code

```java
method costoTotal(ambiente) = self.costoPintura(ambiente) ...
```
and you don't have costoPintura defined, it would be nice to add QuickFix create method...

**Comment by fdodino** [comment]
It works for WKO... maybe it was just a matter of this/self replacement

**Comment by javierfernandes** [comment]
Yes. This was impñemented already

**Comment by fdodino** [comment]
@tesonep Grosso!!!
