### ISSUE TITLE
Unpredictable duplicate lines in editor again

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#855]
I couldn't reproduce it.
I think it happened when I pressed an Enter key inside a comment.
Maybe some evil listener is causing this.
I was able to solve it with Ctrl + A and working again. No longer the problem appeared.

**Comment by npasserini** [comment]
This has more thant 6 months, does it still happen?

**Comment by fdodino** [comment]
Maybe we can close this issue until it happens again, I could not reproduce it and students didn't report any problem.
