### ISSUE TITLE
Add methods for truncate and round a Double

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#862]
When we works with positions distances in Wollok Game we have a lot of decimals:
```XTend
>>> pepita.distance(new Position(2,2))
1.4142135623730951
```

Should be cool can cut or round to a few (or none) decimals.

**Comment by npasserini** [comment]
You want to truncate the double or just to format it more nicely?

**Comment by PalumboN** [comment]
Truncate the double, so I can use it to update the pepita's energy (for ex) without a lot of decimals. 

Or you are thinking in format all double representation?

**Comment by fdodino** [comment]
```scala
	/**
	 * Answers the next integer greater than self
	 * 13.224.roundUp() ==> 14
	 * 15.942.roundUp() ==> 16
	 */
	method roundUp() = self.roundUp(0)
	
	/**
	 * Rounds up self up to a certain amount of decimals
	 * 1.223445.roundUp(3) ==> 1.224
	 * 14.6165.roundUp(3) ==> 14.617
	 */
	method roundUp(_decimals) native
	
	/**
	 * Truncates self up to a certain amount of decimals
	 * 1.223445.truncate(3) ==> 1.223
	 * 14.6165.truncate(3) ==> 14.616
	 */
	method truncate(_decimals) native
```

**Comment by npasserini** [comment]
I think that we need also examples with negative numbers.

**Comment by fdodino** [comment]
Ok, I will add some tests also.
And I'll change tests cases so we use .test() instead of interpretPropagatingErrors
