### ISSUE TITLE
Change default example when creating a new project

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#869]
When you create a new Wollok Project it creates an `example.wlk` with

``` XTend
/**
 * This is an example wollok hello world
 */
object ex {
    method sayHi(){
        console.println('Hello Wollok!')
    }
}
```

I don't like that, because:
- _ex_ is not expressive 
- I don't want a first program with `console.println`, because it not represent the paradigm's ideas for me.

I prefer an object with an attribute, a "question" method and an "action" method. Like:

``` XTend
object pepita {
    var energia = 100

    method energia() = energia

    method volar(kms) {
        energia -= kms + 10
    }
}
```

**Comment by npasserini** [comment]
+1

**Comment by lspigariol** [comment]
+1  
but in the first example,  dont like use = for return and -= for assign and send message at the some time.

tener ejemplo es útil para los primeros proyectos, después es molesto.
Incluso cuando se importa un proyecto usando el asistente, lo agrega de prepo.
¿por que no poner por defecto un proyecto (o varios) con ejemplos sencillos (o de complejidad creciente) pero que cuando se crea uno nuevo aparezca vacío?

**Comment by javierfernandes** [comment]
Eclipse has a way to introduce examples and help.
Many plugins support this so for example besides the options in the wizard
to create a new object / program, there could be a folder "Wollok Examples"
with a list like "Pepita", "Pepe's salary" (?) etc. When selected that will
import this example project into the workspace.

I agree that it could be annoying if you need to delete all this code every
time

2016-08-01 9:26 GMT-03:00 lspigariol <notifications@github.com>:

**Comment by lgassman** [comment]
In my opinion, it is enough to change _console.println('Hello Wollok!')_ for _return 'Hello Wollok!'_

**Comment by npasserini** [comment]
I would just forget about println and also hello world.
If you look at the old wollok site, there was a carefully thought and well
documented pepita-based introductory path which does not need any of theese.
I think that didn't make it to the new site, but the old one might be
accessible.

**Comment by fdodino** [comment]
@npasserini @PalumboN creo que este issue es sencillo, hoy devuelve un string "I am Wolloktastic!" que para mí no es tan intrusivo como un ejemplo completo que la cuarta vez que creás un objeto es incómodo para borrar.
Lo dejo en discussion.

**Comment by lspigariol** [comment]
Tal vez sea interesante que haya codigo de ejemplo en proyectos que ya
vengan en el workspace al instalar wollok, mas que al crear nuevo proyecto.

**Comment by npasserini** [comment]
Eso parece más complejo de implementar.

**Comment by fdodino** [comment]
Cierro el issue, creo que para hacer lo que pide Lucas necesitamos pensar en una vuelta de tuerca y ya que vamos a modificar nuestra arquitectura y no basarla tanto en Eclipse no me parece que convenga invertir tiempo (además los alumnos no tienen mayores problemas para insertarse en el IDE)
