### ISSUE TITLE
Outline view for classes still show constants as "val"

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#870]
This code:

```
class Camion {
	const minimoBienCargado = 0.75
	const cosos = []
	var capacidadMaxima
	var estado = disponible
```

is displayed like:
![image](https://cloud.githubusercontent.com/assets/10454118/17272353/afc3670e-566a-11e6-85fb-eda9715220b2.png)

**Comment by javierfernandes** [comment]
Ideally the code should use the grammar access to get the keyword instead of hardcoding (and repeating the keyword in xtend/java)

**Comment by javierfernandes** [comment]
<img width="306" alt="screen shot 2016-08-02 at 19 41 59" src="https://cloud.githubusercontent.com/assets/4428120/17351286/a78e5f44-5903-11e6-9062-9d1cc35333b9.png">

Fixing it. Waiting to be merged

**Comment by fdodino** [comment]
I see it fixed in branch debugger-fixes :smile:

**Comment by javierfernandes** [comment]
The icon sucks.
It probably should be better as an arrow from a circle.
Representing a reference from an object (instance variable) to some other (or null/nothing)
