### ISSUE TITLE
Tests outline icon is aligned too far to the right

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#874]
It gets to close to the text without any spacing 
<img width="120" alt="screen shot 2016-07-31 at 21 14 48" src="https://cloud.githubusercontent.com/assets/4428120/17280330/ebf93fe2-5763-11e6-9245-777a44ec0afb.png">

**Comment by fdodino** [comment]
Icon is org.uqbar.project.wollok.ui/icons/wollok-icon-test_16.png
