### ISSUE TITLE
Error is not sufficiently descriptive when trying ==== in the REPL

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#877]

**Comment by javierfernandes** [comment]
What's the current error like ?

I suspect this is a tokenizer/parser-level error message. Difficult to customize :S

**Comment by fdodino** [comment]
Error is 

```
>>> 4 ==== 4
ERROR: no viable alternative at input '=' (line: 1)
```

I'm not sure, but I would put it in the "Nice to have column" unless I find it is easy to enhance error message. What do you think @npasserini ?

**Comment by npasserini** [comment]
Yes, nice to have.

Maybe it would be nice to add a label to all this kind of errors "we would
like to customize the parser error"

2017-03-11 11:03 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Added a "parser message" label

**Comment by fdodino** [comment]
![image](https://user-images.githubusercontent.com/4549002/30559870-799d8614-9c8c-11e7-988c-53cfa40900f4.png)

**Comment by npasserini** [comment]
Why don't we use here the same messages as in the rest of DNUs?

2017-09-18 16:16 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Because parser intercepts the message. So we have just a token, and several nodes to manipulate.

**Comment by npasserini** [comment]
Do you agree that it could be "nice to have" the same message in this case?
In that case let's add a new ticket.


2017-09-19 7:51 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Hm, if we are planning a mayor enhancement we should also detect other parser errors too with similar symbols. But it is ok to think such functionality

**Comment by lspigariol** [comment]
Me parece mejor un mensaje DNU, pero siendo un siendo un mensaje que no
existe (y que no podria existir) se puede acotar algo despues.

tal objeto no entiende el mensaje. ==== es un nombre de método no permitido



2017-09-19 10:59 GMT-03:00 Fernando Dodino <notifications@github.com>:
