### ISSUE TITLE
WREPL.sh should be available for Windows also

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#880]

**Comment by Charlyzzz** [comment]
Yesterday I finally could make it work! (through Cygwin thought). 
It shouldn't be a hussle to port it entirely.

![untitled](https://cloud.githubusercontent.com/assets/7073356/17306549/fc05940a-5806-11e6-9387-da7a24381c7b.jpg)

**Comment by javierfernandes** [comment]
Nice background ;)

Yeah, we just need to google a little bit to create a .bat

**Comment by Charlyzzz** [comment]
```batch
@ECHO OFF

SETLOCAL EnableExtensions

FOR /R %cd%\..\lib %%f IN (*.jar) do call :AddToClasspath %%f
REM FOO BAR BAZ
GOTO :EOF

:AddToClasspath
ECHO %CLASSPATH%
SET CLASSPATH=%1;%CLASSPATH%
GOTO :EOF
```

CLASSPATH variable eventually grows too long, causing an interruption. Is it possible to have all jar files at the same level? (in order to use -cp lib/*)

**Comment by npasserini** [comment]
@charlyzzz any news on this?

**Comment by fdodino** [comment]
I'll close this issue since we can use git bash/cygwin to run any bash script, like wollok-cli.
