### ISSUE TITLE
[debugger][ui] step by step execution stops in a reference to a wko highlighting the whole object

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#881]
I think I solved this before.
The debugger has a set of multiple dispatch methods to evaluate if certain AST elements should be "transparent" for step by step execution or not.
This should be one. 
In the AST there are many intermediate objects that are not really important for step by step execution, just synthetic constructions for modularizing the grammar.
Those should
<img width="656" alt="screen shot 2016-08-01 at 22 06 51" src="https://cloud.githubusercontent.com/assets/4428120/17313717/91b1c686-5834-11e6-90f8-e532aae25826.png">
 be transparent.

**Comment by javierfernandes** [comment]
Fixed ! To be merged

**Comment by fdodino** [comment]
See it fixed in branch debugger-fixes :smile:
