### ISSUE TITLE
[outline] Outline doesn't show instance variables anymore

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#884]
Related to #870 

<img width="334" alt="screen shot 2016-08-02 at 18 53 14" src="https://cloud.githubusercontent.com/assets/4428120/17346741/847529d2-58e2-11e6-8f30-b12f466c4281.png">

That tree should be including instance variables but it is not !

**Comment by javierfernandes** [comment]
Fixed.
Waiting to be merged
<img width="306" alt="screen shot 2016-08-02 at 19 41 59" src="https://cloud.githubusercontent.com/assets/4428120/17351399/8643b4b4-5904-11e6-96f2-65d57b9df061.png">

**Comment by fdodino** [comment]
See it fixed in branch debugger-fixes :smile:
