### ISSUE TITLE
Add preferences to configure the way wollok filters eclipse "things"

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#893]
Currently we filter wizards and other stuff, but this is "hardcoded" in the code.

See 

``` WollokViewerFilter```

It would be really cool to have this patterns configurable in a preference so that you can enabled / disabled them or add new rules.
This would be helpful to try things out.
We can actually have an autocomplete that does some kind of "reflection" on the eclipse platform querying different things that you can use as filters later.

@Juancete what do you think ?
```

**Comment by javierfernandes** [comment]
@Juancete

**Comment by Juancete** [comment]
Yes, i think. I'm not sure how to do that, but i can learn :smile:

**Comment by fdodino** [comment]
Well, I deleted a lot of Java stuff in menues and shortcuts, so I believe this ticket is ready to be closed.
