### ISSUE TITLE
Change default WKO image to new icon

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#898]
![screenshot from 2016-08-04 04 18 57](https://cloud.githubusercontent.com/assets/4098184/17394481/b854cdb6-59ff-11e6-92d7-e18e3f5cca0a.png)

**Comment by PalumboN** [comment]
Closed in dev-1.5 #915

**Comment by PalumboN** [comment]
@npasserini Are you talking about this old icon or the new icon in the PR: #915?

**Comment by npasserini** [comment]
You're right, the new Icon looks great. Sorry.
