### ISSUE TITLE
Can change image size

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#901]
Should be nice can change the WKO image dynamically. For example, we could do `pepita.come()` and the image increase its size.

Maybe we should have an _Image_ class (like _Position_) with the path (or only the file name) and some "scaling factor".

**Comment by javierfernandes** [comment]
I thought about this or something related some time ago. We always
envisioned an mvc ui for wollok. And to have a good mvc observability
should be at the core of the language. So. It is far from being inplemented
but i remember that internally i implemented a listener feature for all
wollok objects. You can be notified about fields being changed. I think
this is still not exposed to wollok code. But we need to consider that.

Al thought if wollok game follows the "loop" approach for rendering you
could implement this feature rigjt now without listeners.

**Comment by PalumboN** [comment]
WOwowo I missed your comment. That is very useful. Do you remember some method or class where I can start to investigate?

**Comment by npasserini** [comment]
+1

**Comment by javierfernandes** [comment]
I believe that the WollokObject classs has a fields listener.
Kind of needs to be exposed to the wollok world.

**Comment by npasserini** [comment]
I think that we agree on this being a good idea, but it still lacks some definitions, so I move it to discussion.

**Comment by fdodino** [comment]
Moving to `Won't do` but in fact it has to do with future version of Wollok Game (perhaps in TS)

**Comment by fdodino** [comment]
What about this @PalumboN ? We have something but I don't know if I should close the issue and start a new one...

**Comment by PalumboN** [comment]
Jajajaj te veo manija de cerrar issues y no me animo a ir en contra de eso :P

Se podría armar otro con una propuesta más formal y que abarque más cosas (como rotaciones, animaciones, transparencia).
@51lv3str1 estuvo trabajando con eso en su implementación de game.

**Comment by fdodino** [comment]
Jajaja, lo que yo quiero es depurar un toque los issues, porque hay muchos viejos que fueron reformulándose y no tiene sentido mantenerlos como están. Y de paso tratar de ser más específicos, menos abarcativos (más granulares, onda rotación => 1 issue, animación => 1 issue, aclarando qué se espera, cómo se consideraría aceptado el issue, en los que tenga sentido poner casos de prueba, o cómo usarlos), para ayudar a que el que quiera ponerse tenga suficiente información o se sienta guiado por el issue.
