### ISSUE TITLE
REPL explodes when Wollok Game is running

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#903]
When REPL is running and a game windows is open `game.start()` sometimes sending a message to an object that is printing in the game do Wollok crash and kill the game.

> > > pepita.vola(20)
> > >      WVM Error in line  (1): pepita.vola(20):
> > >           WVM Error in line  (16): {
> > >         if (self.podesVolar()) {
> > >             energia = energia - 8 \* kms
> > >             posicion.moveUp(1)  
> > >         }
> > >     }:
> > >                WVM Error in line  (17): if (self.podesVolar()) {
> > >             energia = energia - 8 \* kms
> > >             posicion.moveUp(1)  
> > >         }:
> > >                     WVM Error in line  (17): {
> > >             energia = energia - 8 \* kms
> > >             posicion.moveUp(1)  
> > >         }:
> > >                          WVM Error in line  (19): posicion.moveUp(1):
> > >                               WVM Error in line  (224): { y += num }:
> > >                                    WVM Error in line  (224): y += num:
> > > org.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving 1 + org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$$Lambda$114/977772506@65514add
> > >     at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.lambda$1(WollokDeclarativeNativeBasicOperations.java:74)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.performOpAndUpdateRef(WollokInterpreterEvaluator.java:714)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:644)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:166)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:138)
> > >     at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
> > >     at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:140)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:615)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:168)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.eval(AbstractWollokCallable.java:131)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.lambda$0(AbstractWollokCallable.java:87)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:190)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:99)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:119)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:767)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:208)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:138)
> > >     at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
> > >     at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:140)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:615)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:168)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:249)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:176)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:138)
> > >     at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
> > >     at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:140)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:615)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:168)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.eval(AbstractWollokCallable.java:131)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.lambda$0(AbstractWollokCallable.java:87)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:190)
> > >     at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:99)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:119)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:767)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:208)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:138)
> > >     at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
> > >     at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:140)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:182)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:212)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:69)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:210)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:146)
> > >     at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:162)
> > >     at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:87)
> > >     at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:50)
> > >     at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
> > >     at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:34)
> > > Caused by: org.uqbar.project.wollok.interpreter.WollokInterpret
> > > erException: Error evaluating line classpath:/wollok/lib.wlk:[226]: num
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:242)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:133)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$17(WollokInterpreterEvaluator.java:688)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:190)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$13(WollokInterpreterEvaluator.java:690)
> > >     at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.sumOperation(WollokDeclarativeNativeBasicOperations.java:116)
> > >     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > >     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > >     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > >     at java.lang.reflect.Method.invoke(Method.java:498)
> > >     at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.lambda$1(WollokDeclarativeNativeBasicOperations.java:57)
> > >     ... 74 more
> > > Caused by: org.uqbar.project.wollok.interpreter.context.UnresolvableReference: Cannot resolve reference num
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.resolve(WollokInterpreter.java:279)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokNativeLobby.resolve(WollokNativeLobby.java:62)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokNativeLobby.resolve(WollokNativeLobby.java:1)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.resolve(WollokObject.java:276)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.resolve(WollokObject.java:1)
> > >     at org.uqbar.project.wollok.interpreter.context.CompositeEvaluationContext.resolve(CompositeEvaluationContext.java:62)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.resolve(WollokObject.java:276)
> > >     at org.uqbar.project.wollok.interpreter.core.WollokObject.resolve(WollokObject.java:1)
> > >     at org.uqbar.project.wollok.interpreter.context.CompositeEvaluationContext.resolve(CompositeEvaluationContext.java:62)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:212)
> > >     at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:202)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
> > >     at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:230)
> > >     ... 84 more

**Comment by javierfernandes** [comment]
Could be null treatment ?

**Comment by PalumboN** [comment]
I don't think. I don't have nulls in this program. I think that it's a problem because an attribute of the position need be evaluated by the REPL and Wollok Game at the same time, and this cause problems (I don't know how).

**Comment by PalumboN** [comment]
The exception is thrown by Eclipse. It collides with Wollok-Game thread on evaluating

```
!MESSAGE org.eclipse.swt.SWTException: Invalid thread access
!STACK 0
org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:86)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.inject(ContextInjectionFactory.java:73)
	at org.eclipse.ui.internal.Workbench.createWorkbenchWindow(Workbench.java:1486)
	at org.eclipse.ui.internal.Workbench.openWorkbenchWindow(Workbench.java:2635)
	at org.eclipse.ui.internal.Workbench.openWorkbenchWindow(Workbench.java:2627)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:3134)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:3073)
	at org.uqbar.project.wollok.ui.launch.shortcut.WollokLaunchDelegate.lambda$3(WollokLaunchDelegate.java:221)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.ui.launch.shortcut.WollokLaunchDelegate.openDebugPerspective(WollokLaunchDelegate.java:226)
	at org.uqbar.project.wollok.ui.launch.shortcut.WollokLaunchDelegate.handleEvents(WollokLaunchDelegate.java:210)
	at org.uqbar.project.wollok.ui.launch.shortcut.WollokLaunchDelegate$1.handleDebugEvents(WollokLaunchDelegate.java:186)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1161)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1197)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:441)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:420)
	at org.eclipse.swt.widgets.ToolItem.getParent(ToolItem.java:415)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:780)
	at org.eclipse.jface.action.ActionContributionItem$1.propertyChange(ActionContributionItem.java:114)
	at org.eclipse.jface.action.ExternalActionManager$CommandCallback.bindingManagerChanged(ExternalActionManager.java:287)
	at org.eclipse.jface.bindings.BindingManager.fireBindingManagerChanged(BindingManager.java:901)
	at org.eclipse.jface.bindings.BindingManager.setActiveBindings(BindingManager.java:2178)
	at org.eclipse.jface.bindings.BindingManager.recomputeBindings(BindingManager.java:1743)
	at org.eclipse.jface.bindings.BindingManager.contextManagerChanged(BindingManager.java:690)
	at org.eclipse.core.commands.contexts.ContextManager.fireContextManagerChanged(ContextManager.java:162)
	at org.eclipse.core.commands.contexts.ContextManager.setActiveContextIds(ContextManager.java:293)
	at org.eclipse.e4.ui.internal.services.ContextContextService.getActiveContextIds(ContextContextService.java:161)
	at org.eclipse.ui.internal.WorkbenchWindow.setup(WorkbenchWindow.java:631)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 19 more
```

**Comment by fdodino** [comment]
Hi @PalumboN , can we close this issue?

**Comment by PalumboN** [comment]
Yes! It was fixed for your demo, no?

**Comment by fdodino** [comment]
Jajaj "No?" Yeah!!
