### ISSUE TITLE
Customize wollok product welcome page

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#906]
We are currently using the default "universal" welcome page.
It would be cool to customize in the following way:
- A "Wollok" header
- Wollok colors (theme)
- Link to wollok "homepage"
- Link to "Language Reference"
- Tutorial to import wollok examples (maybe @fdodino examples ? from the wollok-examples repository)
- Shortcuts to wizards: "New Project"

**Comment by javierfernandes** [comment]
Here is a tutorial

https://dzone.com/articles/short-tutorial-introwelcome

**Comment by javierfernandes** [comment]
I think this is the official doc

http://www.eclipse.org/eclipse/platform-ua/proposals/shared-intro/shared-intro.htm

**Comment by fdodino** [comment]
I think is not so important, but it affects the way students introduce to Wollok.

**Comment by fdodino** [comment]
As I posted in a mail: 
Bueno, estuve peleando un poco con la Welcome Page.
Primero había que cambiarle el universalIntro por una definición custom. Lo que pasa es que lo que te permite toquetear es un introContent.xml bastante básico.
Entonces vi que se podía generar una página html, y armamos con Darío (Grinberg) esto:
http://www.wollok.org/welcome/root.html
Listo, pensé. 
Lo puse en introContent.xml ... y no anduvo, porque no era XHTML.
Entonces lo validé acá: https://validator.w3.org/
Y aun así me tiraba error de SAX al parsear el content. Entonces usé este otro validador:
https://www.freeformatter.com/xml-validator-xsd.html
Pero tiraba un NullPointerException al tratar de generar el content.
Entonces jugué un poquito más con el introContent.xml pero llegué a la conclusión de que lo mejor era usar como página de bienvenida una url web y al pingo, es fácil de customizar, tenés herramientas por afuera del eclipse y no dependés de un parser limitado para mostrarlo en la ventana. Lo malo: necesita Internet, pero es un chiche, a lo sumo la mayoría lo verá y un porcentaje menor le dará error de navegación y lo cerrará.

Lo único que quiero ver es si lo podemos internacionalizar, para que me direccione a una página welcome/root_en.html o root_es.html. Por lo demás, lo considero aceptable como para salir a "producción".
