### ISSUE TITLE
Get rid of java wizard and implement our own "New Package"

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#909]
Currently Java wizards are still there just because they provide a way to create packages.
But this could be confusing for the user

<img width="278" alt="screen shot 2016-08-05 at 16 10 01" src="https://cloud.githubusercontent.com/assets/4428120/17447844/3fefb452-5b27-11e6-885b-ab3a548bb9c0.png">

We should have the package wizard under Wollok menu

**Comment by fdodino** [comment]
@npasserini , I'll put this  issue into Nice to have column, because packages doesn't work right now. We should allow first to have Wollok files in different directories.

**Comment by fdodino** [comment]
Closing it.
