### ISSUE TITLE
Using map over a set should return a list

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#916]
It's not useful to get a set as a result of a map, it's more logical to get a list to ensure duplicates are included. To me this is invalid (the collection returned by juegos() is a set of 2 objects):

> > > biblioteca.juegos().map({juego => juego.tiempoRestante()})
> > > # {30.0, 50}
> > > 
> > > timbaElLeon.jugar(20)
> > > biblioteca.juegos().map({juego => juego.tiempoRestante()})
> > > # {30}

**Comment by PalumboN** [comment]
Agree https://github.com/uqbar-project/wollok/pull/918

**Comment by npasserini** [comment]
JJajajaa, this is a long term discussion in Smalltalk / Pharo.

**Comment by fdodino** [comment]
Why not a new maplist method?

**Comment by npasserini** [comment]
I didn' want to add another method to the list protocol, which is already
big from my point of view and for an educative language. I am afraid adding
more methods increases the possibility of confussion and gets overwhelming.
Also it is a thing that can be very easily achieved.

Whatever decission you make you can get the opposite behavior by

aSet.asList().map(bleh)
or
aSet.map(bleh).asSet().


But, well... you are the second person proposing that, after Fernandes, so
maybe I am wrong.

**Comment by lspigariol** [comment]
if you use set for receptor, return another set is consistent: is the results set.

**Comment by tesonep** [comment]
I am closing it, because it is fixed in the PR #918
