### ISSUE TITLE
A project folder seems a bit polluted

### ISSUE THREAD

**Issue by Charlyzzz** [uqbar-project/wollok#917]
Thinking of an introduction for students in the VCS world, we realised a simple proyect with 2 useful files (in the eyes of the student) consists of this paraphernalia:

![untitled](https://cloud.githubusercontent.com/assets/7073356/17540964/59551f00-5e91-11e6-9bbb-9aed4de47c96.png)

I know that most of these files are Eclipse related, but what really grind my gears are the extra files inside the src folder. The absence of a one-on-one relation between what a newcomer desings and what he sees is kind of a big deal (at least for me).

Is it possible to trade some configurability in exchange for cleanness?

**Comment by javierfernandes** [comment]
I dont think we will ever have a 1 to 1 relation there. Wollok projects ti
be able to be opened by eclipse are eclipse plugins. We cannot get rid of
.project .classpath or .serttings.

Theb there are 2 extra items in src.
Wollok.root was inteoduced recently as a way to mark the projects src
folder for the module system. Since in runtime wollok doesnt rely on
eclipse workbench api. Unless qe couple with .classpath i dont see a way

The las file is the log conf file. Not really sure on how to configure
log4j by default without a file.

**Comment by Charlyzzz** [comment]
After some research I've found [this](https://logging.apache.org/log4j/2.0/faq.html#config_from_code) in log4j FAQ.

**Comment by npasserini** [comment]
Is all of this visible for the student?
Maybe if we can not get rid of it, at least it could be hidden.
First, do not show it in the default wollok perspectives and views.
Then, .* files are by default hidden in linux, how does it work in windows?
Can we hide them also there?
If possible, then let's make hidden files those which are not yet hidden.

On Wed, Aug 10, 2016 at 8:06 PM, Erwin Debusschere <notifications@github.com

**Comment by javierfernandes** [comment]
It is all hidden in the wollok perspective and view.

**Comment by fdodino** [comment]
@Charlyzzz I think you are trying to use Wollok from outside the IDE.
As @javierfernandes said, in Wollok perspective all of these files are hidden, so students have a clean view of their project.
Having a SVN integration, there is no need to add complexity to the student to go outside the IDE.
But if you desire to use git, you can just explain to them:"Well, just add those files to git repo".

**Comment by fdodino** [comment]
Update:
Now I understand @Charlyzzz that these files are also viewed in Project Explorer:
![image](https://cloud.githubusercontent.com/assets/4549002/17656713/875a5428-6293-11e6-9d37-c2279e368645.png)
So you're right.

I agree a student should not see them in this perspective. Outside IDE I still believe it is not a Wollok problem.

**Comment by javierfernandes** [comment]
He wait. What did you do to avoid filtering ?Im seeing the content filter
fine.

The original screenshot was from outside eclipse.

**Comment by fdodino** [comment]
Sorry, I think it was a Wollok perspective in wollok environment (not the final product) and bad target platform.
Don't take for serious by last comment.

**Comment by fdodino** [comment]
Closing this issue, waiting until we develop our own git plugin in Wollok IDE
