### ISSUE TITLE
Try if we can bundle the JVM as part of the product

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#922]
http://eclipseo.blogspot.com.ar/2014/11/bundle-jre-along-with-your-product.html

**Comment by tesonep** [comment]
The question is if it is enough with the JRE, or we should pack a JDK??

**Comment by javierfernandes** [comment]
hehe.. yeah.. not really sure. We need to try out a generated product
running with JAVA_HOME pointing to a JRE to see if it works fine.
