### ISSUE TITLE
Cover all the QuickFixes operations with tests

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#931]

**Comment by javierfernandes** [comment]
+1 :)

**Comment by fdodino** [comment]
Already done!

**Comment by npasserini** [comment]
Denserio?!

2017-04-30 3:53 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
No sé si ya están todos pero lo estarán en breve en el branch donde estoy
laburando.

Ojo que también cambié la convención de getters y setters que fue la que
definimos el año pasado.

**Comment by fdodino** [comment]
Well, I've done almost every quick fix. Unfortunately I was stuck trying to reproduce behavior of LINKING_DIAGNOSIS, so "Create local variable", "Create instance variable", "Add parameter to method", "Create class" have no tests. All other quickfixes do.

**Comment by fdodino** [comment]
I'll create a "Nice to have" new approach for these quickfixes.

**Comment by npasserini** [comment]
:+1+

2017-05-09 20:41 GMT-03:00 Fernando Dodino <notifications@github.com>:
