### ISSUE TITLE
Throw an exception without "new"

### ISSUE THREAD

**Issue by lgassman** [uqbar-project/wollok#932]
when an object is unable to fulfill its responsibility when it receives a message, it must throw an Exception/Error.  This is an independent concept of "Class". But the Exception/Error support  in wollok is using Classes: _throw new Exception("message error")__  (I am ok?)

I think that is nice to have a way to throw an Exception before to teach Classes. (Only the throw, no manage it)

In smalltalk I can use "self error:". but I dont like error: as an instance message of self. Alternatively you can think asError() as instance method of String. (Ex: "messageError".throwError()). It doesn't like me. Another option is an instance method of boolean Class (Ex: (a < b).assert("Problem because a >= b"))
I think is nice not use a message because you want to interrupt the message sending

I think that a reserved word is necesary. Using "error" could have backwards compatibily problem, but is the best word. Using "throw" is less intuitive, but friend of Class style. 

```
object pepita {
     var energy
      method fly(kms) {
             var usedEnergy = 10 - kms
              if( energy < usedEnergy){
                     error "pepita has not energy to fly " +  kms +" kms"
              }
              energy -= usedEnergy
      }
}




```

**Comment by PalumboN** [comment]
We have an `error` object for that: https://github.com/uqbar-project/wollok/blob/master/org.uqbar.project.wollok.lib/src/wollok/lib.wlk#L254

You can do `error.throwWithMessage("pepita has not energy to fly " + kms +" kms")`.

**Comment by flbulgarelli** [comment]
@PalumboN Nice, but isn't it a bit verbose?  It was because `throw` was already a reserved word, right?

I thought it was going to be named `error.raise` or something like that.

**Comment by matifreyre** [comment]
```throw``` is a reserved word, that's right. As you, I proposed ```raise``` too, but I believe they used ```throwWithMessage``` to keep the "throw" terminology consistent. Wasn't that the case @tesonep?

**Comment by PalumboN** [comment]
Agree!

**Comment by javierfernandes** [comment]
I don't remember raise being a reserved word.
Althought it could confuse if you first tell raise and later throw (?). Not
sure.

error.createWithMessage(" ... ")  ?

wollok.error(" ... ") ?

**Comment by tesonep** [comment]
We keep it for the throw

**Comment by lgassman** [comment]
The error object is fine for me. I still think that a reserved word is better because highlights the interruption of message chain, but it''s a subtle thing.

**Comment by npasserini** [comment]
I think that the two requirements leo posted:
1) throw an exception without using "new".
2) have a reserved word

... both could be solved if we decide to research an old proposal of mine:
allowing any object to be "thrown".
I think that we should pay attention to this issue, this could be one of
the major improvements for Wollok 1.6 (or 2.0).

**Comment by fdodino** [comment]
Closing it since there is already a card for throwing an exception without using `new`
