### ISSUE TITLE
WollokChecker Error on REPL when initializing a WKO (attribute with error?)

### ISSUE THREAD

**Issue by nicombrana** [uqbar-project/wollok#938]
Whenever an attribute is being initialized by sending a message to another object, the error that is being described is WollokChecker.

![wollokchecker](https://cloud.githubusercontent.com/assets/1686306/17904038/16b671e0-6944-11e6-9114-f7046e6f675b.jpg)

**Comment by javierfernandes** [comment]
Does "springfield" object also references exBosque in one of its instance variables initialization ?

I tried this 

```xtend
object springfield {
	method riquezaDelSuelo() = 23
}
object exBosque
{
	var capacidadEnToneladas = 1
	var riquezaDelSuelo = springfield.riquezaDelSuelo()
	method produccionEnergetica() { return 0.5 + (capacidadEnToneladas * riquezaDelSuelo) }
	method esContaminante() = true
}
```

And moving springfield into another file
springfield.wlk
```xtend
object springfield {
	method riquezaDelSuelo() = 23
}
```

simpsons.wlk
```xtend
import springfield.springfield

object exBosque
{
	var capacidadEnToneladas = 1
	var riquezaDelSuelo = springfield.riquezaDelSuelo()
	method produccionEnergetica() { return 0.5 + (capacidadEnToneladas * riquezaDelSuelo) }
	method esContaminante() = true
}
```

And both REPL sessions worked fine:

```java
Wollok interactive console (type "quit" to quit):
>>> exBosque
exBosque[riquezaDelSuelo=23, capacidadEnToneladas=1]
>>> 
```

But I saw this  same error in #868 

(my test was in a dirty branch, so, probably I should test it in a clean branch)

**Comment by npasserini** [comment]
This is related to #868, which has been fixed. 
@nicombrana Could you check if this works for you or provide specific code to reproduce the problem?
