### ISSUE TITLE
Provide a preference to choose type system implementation

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#944]
We currently have some typesystem prototypes.
I would like to have a way to configure which one to use.

Each type system should implement an extension point.

The core wollok will be able to load them all but only use one at a time if any.

**Comment by flbulgarelli** [comment]
@javierfernandes does this mean that you can enable/disable static type checks? Or that you can plug different type checkers in? Or  both?

**Comment by javierfernandes** [comment]
Static checks can be enabled/disabled already individually in a preference.

Also the "type checker" based on the type system can be enabled/disabled
already in the type system preferences.

Now this property is to choose which typesystem implementatiin to use

**Comment by flbulgarelli** [comment]
Thanks

**Comment by javierfernandes** [comment]
Implemented in "type-system" branch.

<img width="630" alt="screen shot 2016-08-27 at 20 37 00" src="https://cloud.githubusercontent.com/assets/4428120/18038056/bfae4868-6d68-11e6-9caa-3473524f15ce.png">

Will be merged into 1.6 along with other changes.
