### ISSUE TITLE
Project name allows spaces but generates error

### ISSUE THREAD

**Issue by JessSaavedra** [uqbar-project/wollok#945]
![wollokerror](https://cloud.githubusercontent.com/assets/7197057/18030746/94f60676-6c99-11e6-97ca-c242f257f037.png)

**Comment by lspigariol** [comment]
neither in files names.
the rules are same of all identifier, but is not checked or warning.

**Comment by fdodino** [comment]
Ok, if you define "obj ects.wlk" file you cannot run it in a REPL console:
ERROR [main] (WollokChecker.java:89) - Repl can only be used with .wlk files.
