### ISSUE TITLE
Imports not working for different packages

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#946]
When importing objects from a different package, they are not resolved:

![image](https://cloud.githubusercontent.com/assets/10454118/18030745/8b26bd8e-6c99-11e6-8ba8-2ff612bbefd7.png)

At the same time, "autocomplete" sees their content (it doesn't include the package name, though):

![image](https://cloud.githubusercontent.com/assets/10454118/18030753/d185c090-6c99-11e6-9885-fcb0107e8c00.png)

**Comment by fdodino** [comment]
There ' s also a problem when you use a folder to group several .wlk files, you get a

ERROR [main] (WollokChecker.java:89) - 
java.lang.NullPointerException
    at org.uqbar.project.wollok.launch.WollokChecker.parse(WollokChecker.java:111)
    at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:82)
    at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:34)

**Comment by npasserini** [comment]
Really we solved this! This is great news!
