### ISSUE TITLE
[type-system] Make inference tests parametrized to run with all type systems impls

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#950]
Currently all tests inherit from an abstract class which instantiates a single Type System and tries that one.

I would like to have the test defined once, and run for each type system implementation.

Also for this, the XSemantics impl must be refactored to make it polymorphic with the others

**Comment by javierfernandes** [comment]
<img width="569" alt="screen shot 2016-08-28 at 23 47 52" src="https://cloud.githubusercontent.com/assets/4428120/18039487/e00473b0-6d79-11e6-9f7b-222fb40efaef.png">

**Comment by npasserini** [comment]
I think this is done, right?
