### ISSUE TITLE
[type-system] Infer constructor parameter types

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#952]
Currently this is not being inferred:

``` scala
class Golondrina inherits Object {
    var energia = 100
    var edad = 18

        // XPECT type "Integer" at "en"
        // XPECT type "Integer" at "ed"
    constructor(en, ed) {
        energia = en
        edad = ed
    }
}
```

constructor's "en" and "ed" should be inferred to be Int (as assigned to "energia" and "edad" which are inferred to be Int).

This rule should be pretty similar to the one for method parameters

**Comment by PalumboN** [comment]
Done in 1.6.4
