### ISSUE TITLE
Clicking in game prints weird things in console

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#955]
```
Click en 73,9 con boton0
Hay 0 elementos
```

We should remove them. And would be nice to have some listener for the click (custom or default configuration).

**Comment by javierfernandes** [comment]
I remember that Pilas had this kinds of modes for debugging that showed
data like the cursor and all pbjects positions, dimensions etc. It wad an
overlay on top of the game. Maybe thatvwould be cool

**Comment by PalumboN** [comment]
Now, if you put the cursor over some object (without click) you see the non-WG-attributes (like "energia", but not "posicion"). Maybe on click you can see these other WG-attributes?
