### ISSUE TITLE
[validator] Add help to validator's preferences page

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#957]
We have a mechanism to make all static checks (validations) configurable, per workspace / per project.

The preference pages is automatically generated based on annotations on the checks methods (like an extension to xtext API).

The label of each option is generated based on the method's name.

<img width="645" alt="screen shot 2016-08-29 at 10 54 36" src="https://cloud.githubusercontent.com/assets/4428120/18053719/46f4a57e-6dd7-11e6-8048-872817489578.png">

Example: 

``` scala
    @Check
    @DefaultSeverity(ERROR)
    def cannotInstantiateAbstractClasses(WConstructorCall it) {
        }
```

Now, many times just the name is not enough to understand what this check does.
So it would be good to also provide a "help" description.
It could be a "?" button right to the combo. If you press it then a panel will appear showing the description.
The description should be i18nized !
So, maybe we don't even need to add an annotation. It could be a convention on the i18n key

``` properties
CHECK_cannotInstantiateAbstractClasses_description = You are trying to instantiate a class which is abstract. I.e.: new Animal().
```

As part of this refactor we could also i18n the text which is now there, since it is currently generated based on the method name, and therefor will always be in english.

So it could be

``` properties
CHECK_cannotInstantiateAbstractClasses_label = Cannot Instantiate an Abstract Class
CHECK_cannotInstantiateAbstractClasses_description = You are trying to instantiate a class which is abstract. I.e.: new Animal().
```

It would be even better to also include a code example ! :P

**Comment by fdodino** [comment]
I believe we have different priorities and change of severity for issues is a _good enough_ solution, so closing this ticket.
