### ISSUE TITLE
Don't allow to define classes with same name as core classes

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#966]
For example "Object" !

**Comment by fdodino** [comment]
Should we have also a list of reserved words? Like "if", "else", "try", etc.

**Comment by npasserini** [comment]
I think the parser already checks this, but maybe it is necessary to ensure
that the error message is descriptive.


2017-04-21 14:49 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by Guusy** [comment]
fixes in #1682
