### ISSUE TITLE
No puedo configurar las preferencias.

### ISSUE THREAD

**Issue by franja506** [uqbar-project/wollok#967]
Buenas, el problema surge cuando intento configurar las preferencias de Wollok. El sistema operativo que utilizo es ubuntu mate 16.04 lts 64 bits. Básicamente, no me deja configurar nada, o sea, queda tildada en la primera pantalla que me presenta hasta que salga de configuraciones. Esto me sucede tanto en las preferencias de ventana, propiedades del proyecto,configuraciones de ejecución y configuraciones de depuración. Desde ya, estoy a su disposición para cualquier consulta que quieran hacerme,mi mail es franja506@gmail.com.
Atte.,

Francisco Javier González Cáceres

PD: Adjunto el detalle de instalación
[detalles de instalacion.txt](https://github.com/uqbar-project/wollok/files/453653/detalles.de.instalacion.txt)

**Comment by fdodino** [comment]
Hola Francisco,
        gracias por enviarnos el inconveniente, que detectamos se daba por una configuración de GTK. Esto lo agregamos en http://www.wollok.org/instalacion/#error-al-crear-un-proyecto-wollok-en-ubuntu.
Además, en el próximo release forzaremos esta configuración para los equipos Linux, de manera de no tener este inconveniente.
Cerramos el issue.
Saludos y suerte
Fernando
