### ISSUE TITLE
Add short description to wollok wizards

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#97]
Currently our wizards don't show any description at the top of the window.

Compare attachments (disregard the %name, it's just part of i18nization)
![screen shot 2015-05-23 at 10 56 34](https://cloud.githubusercontent.com/assets/4428120/7784398/b6d664f0-013a-11e5-8caa-9068b9bfd54b.png)

![screen shot 2015-05-23 at 10 56 46](https://cloud.githubusercontent.com/assets/4428120/7784392/9ad3e610-013a-11e5-8aba-2e050cd66d05.png)

**Comment by fdodino** [comment]
+1, Useful for newcomers

**Comment by juanbono** [comment]
Hi! What do you think about these descriptions?

_plugin.properties_
```
wollokProjectDescription = Create a new Wollok Project
wollokObjectsAndClassesDescription = Create Wollok Objects and Classes
wollokTestDescription = Create a new Wollok Test
wollokDescribeDescription = Create a new Wollok Describe Test
wollokProgramDescription = Create a Wollok Program
```

_plugin_es.properties_
```
wollokProjectDescription = Crea un nuevo Proyecto Wollok
wollokObjectsAndClassesDescription = Crea un nuevo Objeto o Clase Wollok
wollokTestDescription = Crea un Test de Wollok
wollokDescribeDescription = Crea una nueva Descripción de tests de Wollok
wollokProgramDescription = Crea un nuevo Programa Wollok
```

**Comment by fdodino** [comment]
Sounds good, the only exception is I would not use uppercase for common sustantives in spanish (Crea un nuevo programa Wollok, or Crea una descripción de tests de Wollok)

**Comment by juanbono** [comment]
> Sounds good, the only exception is I would not use uppercase for common sustantives in spanish (Crea un nuevo programa Wollok, or Crea una descripción de tests de Wollok)

Ok, I'll change that
