### ISSUE TITLE
List equality problems

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#979]
This is wrong in both cases:

```xtext
>>> [1,2] == [1,2,3]
wollok.lang.Exception: Index: 2, Size: 2
	at wollok.lang.List.==(other) [/lang.wlk:855]
	at  [/__synthetic0.wpgm:3]
>>> [1,2,3] == [1,2]
true
```

**Comment by flbulgarelli** [comment]
I thought this issue  had been solved . Maybe it hasnt been released yet

**Comment by asanzo** [comment]
Sounded familiar, but couldn't find it in the open/closed issues list, so I reported it.

**Comment by PalumboN** [comment]
Yeah https://github.com/uqbar-project/wollok/pull/883
