### ISSUE TITLE
Exportar proyecto

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [uqbar-project/wollok#980]
Cuando le doy para exportar un proyecto wollok y lo exporto como wollok game, le indico ruta y nombre del comprimido que genera(.zip), le doy a finalizar y no solo no se cierra la ventana para  indicar que se finalizo sino que en la ruta indicada genera el .zip pero de un peso de 0bytes.

Quiza falte alguna validacion en el medio que indique que no se puede crear el wollok game de un proyecto, o que lo exporte como es debido.

Pd: De todas maneras pude exportar el archivo como archivo de archivado.

**Comment by PalumboN** [comment]
Hola @CarolinaPonceRodriguez, efectivamente esa funcionalidad quedó deprecada hace tiempo. Habría que repensarlo o quitarlo directamente (teniendo en cuenta que existe una forma de exportación genérica).
Muchas gracias!

**Comment by npasserini** [comment]
@PalumboN ¿podemos tomar una decisión con este issue?

**Comment by PalumboN** [comment]
Sí, hay que sacarlo

**Comment by npasserini** [comment]
Lo paso al backlog entonces, sacar esa funcionalidad deprecada no debería ser un gran problema, ¿no?

**Comment by PalumboN** [comment]
No, sale fácil.
