### ISSUE TITLE
Parsing error if constructor is declared after a method declaration

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#982]
The following code works just fine:

```
 class MaestroAgua {
    var habilidad
    constructor(unaHabilidad){
        habilidad = unaHabilidad
    }
    method poder(){
        return habilidad* 100
    }
    method esGroso(){
        return habilidad > 5
    }
} 
```

However this does not:

```
 class MaestroAgua {
    var habilidad

    method poder(){
        return habilidad* 100
    }
    method esGroso(){
        return habilidad > 5
    }
    constructor(unaHabilidad){
        habilidad = unaHabilidad
    }
 } 
```

The error displayed is: **ERROR: mismatched input 'constructor' expecting '}'**

**Comment by npasserini** [comment]
I do not think that we should allow to change the order. What we should do is to provide a better error mesage... but that is not easy?

**Comment by fdodino** [comment]
Forgot to mention this is already fixed in dev branch. Now you see "You should declare constructors before methods." This works also for describe suite tests.
