### ISSUE TITLE
Add unique method to lists

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#983]
I have already see `asSet().asList()` idiom in many students solutions. So we need a method for removing duplicates in lists, without converting them into sets. It could be as simple as: 

```
method unique() = asSet().asList()
```

It could be a method with or without effects, it is not so important for me. An effectful method could be named `removeDuplicates` or something like that.

**Comment by npasserini** [comment]
I do not like the name unique.
#removeDuplicates sounds ok for an effectful methods or #withoutDuplicates
could work for a pure one.

**Comment by flbulgarelli** [comment]
Ok, `withoutDuplicates`  sounds good for a pure method!
