### ISSUE TITLE
Warning/Error on anemic super calls

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#994]
Can we issue an error or at least a warning when super is misused?

These two methods should be marked as warning or error:

```wollok
	override method estasCurada(){
		return super()
	}
	
	override method atenuate(cant){
		super(cant)
	}
```

Message could be "It is conceptually wrong to override a method if no change is intended. Not having this method would have the same behaviour"

Quick fix: remove method.

**Comment by matifreyre** [comment]
You already reported this at #661

**Comment by asanzo** [comment]
I swear I searched first. I'm seriously blind.
